
ALTER TABLE tblICDCode
DROP CONSTRAINT PK_tblICDCode
GO
UPDATE tblICDCode SET [ICDFormat]=9 WHERE [ICDFormat] IS NULL
GO
ALTER TABLE tblICDCode
ALTER COLUMN [ICDFormat] INTEGER NOT NULL
GO
ALTER TABLE tblICDCode
ADD CONSTRAINT PK_tblICDCode PRIMARY KEY (ICDFormat, Code)
GO

UPDATE tblControl SET DBVersion='2.60'
GO
