CREATE TABLE [dbo].[ConcurSAE] (
    [ProcessedFlag]         BIT             NOT NULL,
    [BatchID]               INT             NULL,
    [BatchDate]             DATETIME        NULL,
    [EmployeeID]            VARCHAR (15)    NULL,
    [LastName]              VARCHAR (32)    NULL,
    [FirstName]             VARCHAR (32)    NULL,
    [MiddleInitial]         VARCHAR (1)     NULL,
    [EmployeeExpenseGroup]  VARCHAR (6)     NULL,
    [EmployeeFacility]      INT             NULL,
    [EmployeeLocation]      INT             NULL,
    [EmployeeDept]          INT             NULL,
    [ReportID]              VARCHAR (32)    NOT NULL,
    [ReportKey]             INT             NULL,
    [ReportCurrency]        VARCHAR (3)     NULL,
    [ReportCountry]         VARCHAR (64)    NULL,
    [ReportSubmitDate]      DATETIME        NULL,
    [ProcessingPaymentDate] DATETIME        NULL,
    [ReportName]            VARCHAR (40)    NULL,
    [ReportTotalAmount]     MONEY           NULL,
    [ReportApprovedAmount]  MONEY           NULL,
    [ReportFacility]        INT             NULL,
    [ReportLocation]        INT             NULL,
    [ReportDept]            INT             NULL,
    [ReportExpenseGroup]    VARCHAR (6)     NULL,
    [ReportKeyID]           VARCHAR (48)    NULL,
    [EntryTransType]        VARCHAR (3)     NULL,
    [EntryExpenseName]      VARCHAR (64)    NULL,
    [EntryDate]             DATETIME        NULL,
    [EntryCurrency]         VARCHAR (3)     NULL,
    [EntryExchangeRate]     DECIMAL (10, 6) NULL,
    [EntryRateType]         VARCHAR (1)     NULL,
    [EntryPersonal]         VARCHAR (1)     NULL,
    [EntryDescription]      VARCHAR (64)    NULL,
    [EntryVendor]           VARCHAR (64)    NULL,
    [EntryVendorDesc]       VARCHAR (64)    NULL,
    [EntryProjectCode]      VARCHAR (48)    NULL,
    [EntryCountry]          VARCHAR (48)    NULL,
    [EntryTransAmtEntered]  MONEY           NULL,
    [EntryTransAmtConvert]  MONEY           NULL,
    [EntryTransAmtApproved] MONEY           NULL,
    [EntryPaymentCode]      VARCHAR (4)     NULL,
    [EntryCountry2]         VARCHAR (2)     NULL,
    [EntryCountrySub]       VARCHAR (6)     NULL,
    [EntryNaturalAcct]      INT             NULL,
    [DRCRFlag]              VARCHAR (2)     NULL,
    [EntryJournalAmt]       MONEY           NULL,
    [EntryJournalKey]       INT             NOT NULL,
    [EntryAllocFacility]    INT             NULL,
    [EntryAllocLocation]    INT             NULL,
    [EntryAllocDept]        INT             NULL,
    [EntryAllocProjectCode] VARCHAR (48)    NULL,
    [EntryAllocPercent]     DECIMAL (6, 4)  NULL,
    [PrimaryKey]            INT             IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [ITProjectCode]         VARCHAR (32)    NULL,
    [HSTAmt]                MONEY           NULL,
    [QSTAmt]                MONEY           NULL,
    CONSTRAINT [PK_ConcurSAE] PRIMARY KEY CLUSTERED ([PrimaryKey] ASC)
);

