CREATE TABLE [dbo].[EWClientImport] (
    [PrimaryKey]             INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [ImportStatus]           VARCHAR (25)  NULL,
    [DateAdded]              DATETIME      CONSTRAINT [DF_EWClientImport_DateAdded] DEFAULT (getdate()) NOT NULL,
    [Filename]               VARCHAR (70)  NULL,
    [EWClientID]             INT           NULL,
    [IsNew]                  BIT           CONSTRAINT [DF_EWClientImport_IsNew] DEFAULT ((0)) NOT NULL,
    [WCFSynced]              BIT           CONSTRAINT [DF_EWClientImport_WCFSynced] DEFAULT ((0)) NOT NULL,
    [ActivationSent]         BIT           CONSTRAINT [DF_EWClientImport_ActivationSent] DEFAULT ((0)) NOT NULL,
    [Notes]                  VARCHAR (300) NULL,
    [OfficeID]               VARCHAR (20)  NULL,
    [EWCompanyIntName]       VARCHAR (70)  NULL,
    [EWCompanyID]            INT           NULL,
    [FullName]               VARCHAR (50)  NULL,
    [LastName]               VARCHAR (50)  NULL,
    [FirstName]              VARCHAR (50)  NULL,
    [MI]                     VARCHAR (1)   NULL,
    [Title]                  VARCHAR (50)  NULL,
    [Email]                  VARCHAR (70)  NULL,
    [Phone1]                 VARCHAR (15)  NULL,
    [Fax]                    VARCHAR (15)  NULL,
    [MailingFull]            VARCHAR (70)  NULL,
    [MailingAddress1]        VARCHAR (50)  NULL,
    [MailingCity]            VARCHAR (50)  NULL,
    [MailingState]           VARCHAR (2)   NULL,
    [MailingZip]             VARCHAR (10)  NULL,
    [SourceDBID]             INT           NULL,
    [SourceClientCode]       INT           NULL,
    [AlwaysCreateNew]        BIT           CONSTRAINT [DF_EWClientImport_AlwaysCreateNew] DEFAULT ((0)) NOT NULL,
    [Prefix]                 VARCHAR (10)  NULL,
    [Suffix]                 VARCHAR (50)  NULL,
    [Status]                 VARCHAR (10)  NULL,
    [TypeCode]               INT           NULL,
    [ClientDateAdded]        DATETIME      NULL,
    [ClientUserIDAdded]      VARCHAR (15)  NULL,
    [ClientDateEdited]       DATETIME      NULL,
    [ClientUserIDEdited]     VARCHAR (15)  NULL,
    [Phone1Ext]              VARCHAR (15)  NULL,
    [Phone2]                 VARCHAR (15)  NULL,
    [Phone2Ext]              VARCHAR (15)  NULL,
    [MailingAddress2]        VARCHAR (50)  NULL,
    [BillAddr1]              VARCHAR (50)  NULL,
    [BillAddr2]              VARCHAR (50)  NULL,
    [BillCity]               VARCHAR (50)  NULL,
    [BillState]              VARCHAR (2)   NULL,
    [BillZip]                VARCHAR (10)  NULL,
    [BillAttn]               VARCHAR (70)  NULL,
    [SetupWeb]               BIT           CONSTRAINT [DF_EWClientImport_SetupWeb] DEFAULT ((1)) NOT NULL,
    [UserID]                 VARCHAR (100) NULL,
    [Password]               VARCHAR (200) NULL,
    [ProviderSearch]         BIT           NULL,
    [AutoPublishNewCases]    BIT           NULL,
    [StatusID]               INT           NULL,
    [LastLoginDate]          DATETIME      NULL,
    [FailedLoginAttempts]    INT           NULL,
    [LockoutDate]            DATETIME      NULL,
    [LastPasswordChangeDate] DATETIME      NULL,
    [DisplayClient]          BIT           NULL,
    CONSTRAINT [PK_EWClientImport] PRIMARY KEY CLUSTERED ([PrimaryKey] ASC)
);

