CREATE TABLE [dbo].[EWCompany] (
    [EWCompanyID]                INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [ExtName]                    VARCHAR (70) NULL,
    [IntName]                    VARCHAR (70) NULL,
    [Addr1]                      VARCHAR (50) NULL,
    [Addr2]                      VARCHAR (50) NULL,
    [City]                       VARCHAR (50) NULL,
    [State]                      VARCHAR (2)  NULL,
    [Zip]                        VARCHAR (10) NULL,
    [Country]                    VARCHAR (50) NULL,
    [Phone]                      VARCHAR (15) NULL,
    [Status]                     VARCHAR (10) NULL,
    [CreditHold]                 BIT          CONSTRAINT [DF_EWCompany_CreditHold] DEFAULT ((0)) NOT NULL,
    [EWFacilityID]               INT          NULL,
    [InvRemitEWFacilityID]       INT          NULL,
    [EWCompanyTypeID]            INT          NULL,
    [SecurityProfileID]          INT          NULL,
    [BulkBillingID]              INT          NULL,
    [ParentCompanyID]            INT          NULL,
    [DateAdded]                  DATETIME     NULL,
    [UserIDAdded]                VARCHAR (20) NULL,
    [DateEdited]                 DATETIME     NULL,
    [UserIDEdited]               VARCHAR (20) NULL,
    [GeneralFileUploadFolderID]  INT          NULL,
    [MMITracking]                BIT          NULL,
    [TaxExempt]                  BIT          NULL,
    [IsUnknown]                  BIT          CONSTRAINT [DF_EWCompany_IsUnknown] DEFAULT ((0)) NOT NULL,
    [UseNotification]            BIT          NULL,
    [AllowCoverLetterGeneration] BIT          NULL,
    [NPProviderSearch]           BIT          CONSTRAINT [DF_EWCompany_NPProviderSearch] DEFAULT ((0)) NOT NULL,
    [DataHandling]               INT          NULL, 
    CONSTRAINT [PK_EWCompany] PRIMARY KEY CLUSTERED ([EWCompanyID] ASC)
);

