CREATE TABLE [dbo].[EWDoctor] (
    [EWDoctorID]             INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [SourceDBID]             INT          NULL,
    [SourceDoctorCode]       INT          NULL,
    [LastName]               VARCHAR (50) NULL,
    [FirstName]              VARCHAR (50) NULL,
    [MiddleInitial]          VARCHAR (2)  NULL,
    [Credentials]            VARCHAR (50) NULL,
    [SSNTaxID]               VARCHAR (50) NULL,
    [LicenseNbr]             VARCHAR (50) NULL,
    [UPIN]                   VARCHAR (50) NULL,
    [Status]                 VARCHAR (10) NULL,
    [DateAdded]              DATETIME     NULL,
    [DateEdited]             DATETIME     NULL,
    [UserIDAdded]            VARCHAR (15) NULL,
    [UserIDEdited]           VARCHAR (15) NULL,
    [Prefix]                 VARCHAR (10) NULL,
    [Addr1]                  VARCHAR (50) NULL,
    [Addr2]                  VARCHAR (50) NULL,
    [City]                   VARCHAR (50) NULL,
    [State]                  VARCHAR (2)  NULL,
    [Zip]                    VARCHAR (15) NULL,
    [Phone]                  VARCHAR (15) NULL,
    [PhoneExt]               VARCHAR (15) NULL,
    [CellPhone]              VARCHAR (15) NULL,
    [Pager]                  VARCHAR (15) NULL,
    [FaxNbr]                 VARCHAR (15) NULL,
    [EmailAddr]              VARCHAR (70) NULL,
    [Qualifications]         TEXT         NULL,
    [County]                 VARCHAR (50) NULL,
    [WCNbr]                  VARCHAR (50) NULL,
    [RemitAttn]              VARCHAR (70) NULL,
    [RemitAddr1]             VARCHAR (70) NULL,
    [RemitAddr2]             VARCHAR (70) NULL,
    [RemitCity]              VARCHAR (70) NULL,
    [RemitState]             VARCHAR (10) NULL,
    [RemitZip]               VARCHAR (10) NULL,
    [CreateVouchers]         BIT          NULL,
    [OPType]                 VARCHAR (5)  NULL,
    [CompanyName]            VARCHAR (70) NULL,
    [PrintOnCheckAs]         VARCHAR (70) NULL,
    [UnRegNbr]               VARCHAR (50) NULL,
    [NPINbr]                 VARCHAR (20) NULL,
    [HCAIProviderRegistryID] VARCHAR (50) NULL,
    [EWDoctor]               BIT          NULL,
    [DateLastUsed]           DATETIME     NULL,
    [CredentialingStatus]    VARCHAR (20) NULL,
    [CredentialingSource]    VARCHAR (15) NULL,
    [CredentialingUpdated]   DATETIME     NULL,
    [CredentialingNotes]     VARCHAR (50) NULL,
    [WAProviderStateID]      VARCHAR (20) NULL,
    [WAProviderNationalID]   VARCHAR (20) NULL,
    [DOB]                    DATETIME     NULL,
    [APKey]                  VARCHAR (50) NULL,
    [Country]                VARCHAR (50) NULL,
    [PracticingDoctor]       INT          NULL,
    [CalcTaxOnVouchers]      BIT          NULL,
    [SSN]                    VARCHAR (15) NULL,
    [GPIDMethod]             INT          NULL,
    [NPPublishOnWeb]         BIT          CONSTRAINT [DF_EWDoctor_NPPublishOnWeb] DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_EWDoctor] PRIMARY KEY CLUSTERED ([EWDoctorID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_EWDoctor_LastNameFirstNameMiddleInitial]
    ON [dbo].[EWDoctor]([LastName] ASC, [FirstName] ASC, [MiddleInitial] ASC) WITH (FILLFACTOR = 90);

