CREATE TABLE [dbo].[EWFacility] (
    [EWFacilityID]              INT           NOT NULL,
    [FacilityName]              VARCHAR (40)  NULL,
    [LegalName]                 VARCHAR (40)  NULL,
    [SeqNo]                     INT           NULL,
    [DBID]                      INT           NULL,
    [ShortName]                 VARCHAR (20)  NULL,
    [Accting]                   VARCHAR (5)   NULL,
    [GPFacility]                VARCHAR (3)   NULL,
    [Address]                   VARCHAR (50)  NULL,
    [City]                      VARCHAR (20)  NULL,
    [State]                     VARCHAR (3)   NULL,
    [Zip]                       VARCHAR (10)  NULL,
    [Phone]                     VARCHAR (25)  NULL,
    [Fax]                       VARCHAR (25)  NULL,
    [Region]                    VARCHAR (15)  NULL,
    [FedTaxID]                  VARCHAR (20)  NULL,
    [DateAquired]               DATETIME      NULL,
    [DateIMECentric]            DATETIME      NULL,
    [DateGP]                    DATETIME      NULL,
    [Active]                    BIT           NULL,
    [Logo]                      VARCHAR (256)  NULL,
    [ContactOps]                VARCHAR (30)  NULL,
    [ContactAcct]               VARCHAR (30)  NULL,
    [InvRemitEWFacilityID]      INT           NULL,
    [AcctingPhone]              VARCHAR (25)  NULL,
    [AcctingFax]                VARCHAR (25)  NULL,
    [RemitAddress]              VARCHAR (50)  NULL,
    [RemitCity]                 VARCHAR (20)  NULL,
    [RemitState]                VARCHAR (3)   NULL,
    [RemitZip]                  VARCHAR (10)  NULL,
    [Website]                   VARCHAR (40)  NULL,
    [DRDataFeed]                INT           NULL,
    [DRHistory]                 INT           NULL,
    [CountryCode]               VARCHAR (2)   NULL,
    [ParentEWFacilityID]        INT           NULL,
    [MigratingClaimNotifyEmail] VARCHAR (140) NULL,
    [ReferralGroup]             INT           NULL,
    [DateDR]                    DATETIME      NULL,
    [EWServiceTypeID]           INT           NULL,
    [AltDBID]                   INT           NULL,
    [ReportDBID]                INT           NULL,
    CONSTRAINT [PK_EWFacility] PRIMARY KEY CLUSTERED ([EWFacilityID] ASC) WITH (FILLFACTOR = 90)
);

