CREATE TABLE [dbo].[GPTempVendorVoucher] (
    [PrimaryKey]       INT          IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [SourceID]         INT          NULL,
    [FormatVersion]    INT          NOT NULL,
    [ProcessedFlag]    BIT          NOT NULL,
    [ExportDate]       DATETIME     NOT NULL,
    [DocumentNo]       VARCHAR (15) NOT NULL,
    [DocumentDate]     DATETIME     NOT NULL,
    [ServiceDate]      DATETIME     NOT NULL,
    [Comment]          VARCHAR (30) NULL,
    [GPGLAccount]      VARCHAR (16) NOT NULL,
    [GPFacilityID]     VARCHAR (3)  NOT NULL,
    [GPNaturalAccount] VARCHAR (5)  NOT NULL,
    [ClaimNo]          VARCHAR (50) NULL,
    [CaseNo]           VARCHAR (15) NULL,
    [BatchNo]          VARCHAR (15) NOT NULL,
    [TotalAmount]      MONEY        NOT NULL,
    [PayeeName]        VARCHAR (64) NULL,
    [Address1]         VARCHAR (50) NULL,
    [Address2]         VARCHAR (50) NULL,
    [Address3]         VARCHAR (50) NULL,
    [City]             VARCHAR (35) NULL,
    [State]            VARCHAR (2)  NULL,
    [Zip]              VARCHAR (50) NULL,
    [County]           VARCHAR (50) NULL,
    [Country]          VARCHAR (2)  NULL,
    CONSTRAINT [PK_GPTempVendorVoucher] PRIMARY KEY CLUSTERED ([PrimaryKey] ASC)
);

