CREATE TABLE [dbo].[InfoIssue] (
    [IssueID]               INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [Abstract]              VARCHAR (250) NULL,
    [Description]           VARCHAR (MAX) NULL,
    [DateAdded]             DATETIME      NULL,
    [DateEdited]            DATETIME      NULL,
    [UserAdded]             INT           NULL,
    [UserEdited]            INT           NULL,
    [RequestorID]           INT           NULL,
    [RequestorEWFacilityID] INT           NULL,
    [IssueType]             VARCHAR (20)  NULL,
    [Visibility]            VARCHAR (15)  NULL,
    [Product]               VARCHAR (30)  NULL,
    [Status]                VARCHAR (20)  NULL,
    [Priority]              VARCHAR (20)  NULL,
    [Resolution]            VARCHAR (20)  NULL,
    [OwnerID]               INT           NULL,
    [NeededBy]              DATETIME      NULL,
    [AffectsDoc]            BIT           NULL,
    [AffectsInstall]        BIT           NULL,
    [EstHours]              REAL          NULL,
    [ActualHours]           REAL          NULL,
    [RecreateNote]          VARCHAR (MAX) NULL,
    [WorkaroundNote]        VARCHAR (MAX) NULL,
    [ReleaseNote]           VARCHAR (MAX) NULL,
    [ReportedVersion]       VARCHAR (15)  NULL,
    [TargetVersion]         VARCHAR (15)  NULL,
    [Rank]                  INT           NULL,
    [AssignedToID]          INT           NULL,
    [FollowupDate]          DATETIME      NULL,
    [TrainingNeeded]        BIT           NULL,
    [RelatedIssueID]        INT           NULL,
    [ResolutionDate]        DATETIME      NULL,
    [Workflow]              INT           NULL,
    [PrevStatus]            VARCHAR (20)  NULL,
    [ResolutionReleaseID]   INT           NULL,
    [AffectsSchema]         BIT           NULL,
    [ProblemStmt]           VARCHAR (MAX) NULL,
    [DueDate]               DATETIME      NULL,
    [ReqBS]                 BIT           NULL,
    [ReqDR]                 BIT           NULL,
    [ReqQA]                 BIT           NULL,
    [TestPlanStatus]        VARCHAR (16)  NULL,
    [QAAssignedID]          INT           NULL,
    CONSTRAINT [PK_InfoIssue] PRIMARY KEY CLUSTERED ([IssueID] ASC)
);

