CREATE TABLE [dbo].[ISAuthorTemplate] (
    [AuthorTemplateID] INT           NOT NULL,
    [EWTransDeptID]    INT           NULL,
    [FU_FACILITYID]    INT           NOT NULL,
    [A_LANGUAGE]       NVARCHAR (8)  NULL,
    [A_ACCESS]         INT           NULL,
    [A_DIFFIC]         FLOAT (53)    NULL,
    [A_JOBTYPE]        INT           NULL,
    [A_KEYID]          INT           NULL,
    [A_AUDIO]          INT           NOT NULL,
    [A_PREF_TYPIST]    INT           NULL,
    [A_ALT_TYPIST]     INT           NULL,
    [A_CPRIOR]         BIT           NOT NULL,
    [A_DICTATE]        BIT           NOT NULL,
    [A_REVIEW]         BIT           NOT NULL,
    [A_CREVIEW]        BIT           NOT NULL,
    [A_CSECCODE]       BIT           NOT NULL,
    [A_CJTYPE]         BIT           NOT NULL,
    [A_CJDEPT]         BIT           NOT NULL,
    [A_PRREVIEW]       BIT           NOT NULL,
    [A_POREVIEW]       BIT           NOT NULL,
    [A_CRVWPR]         BIT           NOT NULL,
    [A_CRVWPO]         BIT           NOT NULL,
    [A_CONFIRM]        BIT           NOT NULL,
    [A_ENQUIRE]        BIT           NOT NULL,
    [A_CPROMPT]        BIT           NOT NULL,
    [A_CSTATUS]        BIT           NOT NULL,
    [A_TALLOC]         INT           NOT NULL,
    [A_JIMPORT]        INT           NOT NULL,
    [A_PRIORITY]       NVARCHAR (1)  NULL,
    [A_PROMPT]         NVARCHAR (1)  NULL,
    [A_NREWIND]        INT           NULL,
    [A_FREWIND]        INT           NULL,
    [A_VOLUME]         INT           NULL,
    [A_SPEED]          INT           NULL,
    [A_SPEECHREC]      BIT           CONSTRAINT [DF_ISAuthorTemplate_A_SPEECHREC] DEFAULT ((0)) NOT NULL,
    [A_SRPCUSER]       NVARCHAR (50) NULL,
    [A_SRPHONEUSER]    NVARCHAR (50) NULL,
    [A_SRACOUSTICADAP] BIT           CONSTRAINT [DF_ISAuthorTemplate_A_SRACOUSTICADAP] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_ISAuthorTemplate] PRIMARY KEY NONCLUSTERED ([AuthorTemplateID] ASC)
);

