CREATE TABLE [dbo].[ISIntegration] (
    [IntegrationID]           INT           NOT NULL,
    [Name]                    VARCHAR (15)  NULL,
    [Active]                  BIT           CONSTRAINT [DF_ISIntegration_Active] DEFAULT ((1)) NOT NULL,
    [Type]                    VARCHAR (10)  NULL,
    [ToGP]                    BIT           CONSTRAINT [DF_ISIntegration_ToGP] DEFAULT ((0)) NOT NULL,
    [FromGP]                  BIT           CONSTRAINT [DF_ISIntegration_FromGP] DEFAULT ((0)) NOT NULL,
    [DBID]                    INT           NULL,
    [LastDateEditedCompany]   DATETIME      NULL,
    [LastDateEditedClient]    DATETIME      NULL,
    [LastDateEditedDoctor]    DATETIME      NULL,
    [DRVersion]               INT           NULL,
    [DRInterval]              INT           NULL,
    [DRWeekend]               BIT           NULL,
    [FromGPNextBatchNo]       INT           CONSTRAINT [DF_ISIntegration_FromGPNextBatchNo] DEFAULT ((1)) NOT NULL,
    [FromGPFacilityIDs]       VARCHAR (70)  NULL,
    [CountryCode]             VARCHAR (2)   NULL,
    [GPEntityPrefix]          VARCHAR (3)   NULL,
    [UseDataFeedIDForGP]      BIT           CONSTRAINT [DF_ISIntegration_UseDataFeedIDForGP] DEFAULT ((0)) NOT NULL,
    [ManageIMECentricID]      BIT           CONSTRAINT [DF_ISIntegration_ManageIMECentricID] DEFAULT ((1)) NOT NULL,
    [NextCompanyID]           INT           NULL,
    [NextClientID]            INT           NULL,
    [NextDoctorID]            INT           NULL,
    [FolderPath]              VARCHAR (256)  NULL,
    [UseSFTP]                 BIT           NOT NULL,
    [SFTPPath]                VARCHAR (60)  NULL,
    [Email]                   VARCHAR (200) NULL,
    [OffsetHours]             INT           NULL,
    [FromGPExcludeInvNoStart] INT           NULL,
    [FromGPExcludeInvNoEnd]   INT           NULL,
    [FromGPExcludeVoNoStart]  INT           NULL,
    [FromGPExcludeVoNoEnd]    INT           NULL,
    [GPDBID]                  INT           NULL,
    [ExportMarketer]          BIT           CONSTRAINT [DF_ISIntegration_ExportMarketer] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_ISIntegration] PRIMARY KEY CLUSTERED ([IntegrationID] ASC) WITH (FILLFACTOR = 90)
);

