CREATE TABLE [dbo].[tblOffice] (
    [OfficeCode]                INT              IDENTITY (1, 1) NOT NULL,
    [Description]               VARCHAR (70)     NULL,
    [ShortDesc]                 VARCHAR (15)     NULL,
    [IMECode]                   INT              NULL,
    [Class]                     VARCHAR (30)     NULL,
    [Status]                    VARCHAR (10)     NULL,
    [DateAdded]                 DATETIME         NULL,
    [DateEdited]                DATETIME         NULL,
    [UserIDAdded]               VARCHAR (30)     NULL,
    [UserIDEdited]              VARCHAR (30)     NULL,
    [WebGUID]                   UNIQUEIDENTIFIER NULL,
    [WebSynchDate]              DATETIME         NULL,
    [bccEmailAddress]           VARCHAR (100)    NULL,
    [PublishOnWeb]              BIT              CONSTRAINT [DF_tblOffice_PublishOnWeb] DEFAULT (0) NULL,
    [USDVarchar1]               VARCHAR (50)     NULL,
    [USDVarchar2]               VARCHAR (50)     NULL,
    [EWFacilityID]              INT              NULL,
    [EWLocationID]              INT              NULL,
    [UseEDIExport]              BIT              CONSTRAINT [DF_tblOffice_UseEDIExport] DEFAULT ((0)) NULL,
    [BillingProviderNonNPINbr]  VARCHAR (20)     NULL,
    [EWTransDeptID]             INT              NULL,
    [EWTimeZoneID]              INT              NULL,
    [ReferralNotifyEmail]       VARCHAR (200)    NULL,
    [FileUploadNotifyEmail]     VARCHAR (200)    NULL,
    [ConfirmationSetupID]       INT              NULL,
    [IssueVersion]              INT              NULL,
    [NotificationEmailAddress]  VARCHAR (70)     NULL,
    [ShowFollowUpOnCaseOpen]    BIT              CONSTRAINT [DF_tblOffice_ShowFollowUpOnCaseOpen] DEFAULT ((0)) NOT NULL,
    [EnvelopeFolderID]          INT              NULL,
    [UseCaseLock]               BIT              NULL,
    [UseDPS]                    BIT              CONSTRAINT [DF_tblOffice_UseDPS] DEFAULT ((0)) NOT NULL,
    [NYWCCompanyName]           VARCHAR (50)     NULL,
    [FeeApprovalDocumentCode]   VARCHAR (15)     NULL,
    [FeeQuoteDocumentCode]      VARCHAR (15)     NULL,
    [DoctorQuoteDocumentCode]   VARCHAR (15)     NULL,
    [DPSSystemID]               INT              CONSTRAINT [DF_tblOffice_DPSSystemID] DEFAULT ((0)) NOT NULL,
    [DPSFolderID]               INT              NULL,
    [DataHandlingForDupSubCase] INT              CONSTRAINT [DF_tblOffice_DataHandlingForDupSubCase] DEFAULT ((1)) NOT NULL,
    [FSInvoiceSetting]          INT              NULL,
    [FSVoucherSetting]          INT              NULL,
    [DaySheetDocument]          VARCHAR (15)     NULL,
    [OCRSystemID]               INT              NULL,
	[RecordRetrievalDocument]   VARCHAR (15)     NULL,
	[RecRetrievalIncludeFileTypes] VARCHAR(150)  NULL,
	[RecRetrievalExcludeFileTypes] VARCHAR(150)  NULL,
	[RecRetrievalFileHandling]  INT              NULL,
	[RecRetrievalOrderStatus]   VARCHAR(150)     NULL,
	[EntitiesDoNotPublishOnWeb] VARCHAR(50)      NULL,
    CONSTRAINT [PK_tblOffice] PRIMARY KEY CLUSTERED ([OfficeCode] ASC) WITH (FILLFACTOR = 90)
);





