--Set Simple Recovery Mode
ALTER DATABASE tmpIMEC SET RECOVERY SIMPLE WITH NO_WAIT;
GO

--Shrink Log File
DBCC SHRINKFILE (N'IMETrackSQL_log' , 0, TRUNCATEONLY)
GO


--Take DB Offline
ALTER DATABASE tmpIMEC SET OFFLINE WITH ROLLBACK IMMEDIATE
GO
