--Set Simple Recovery Mode
ALTER DATABASE tmpIMEC SET RECOVERY SIMPLE WITH NO_WAIT;
GO

--Shrink Log File
DBCC SHRINKFILE (N'IMETrackSQL_log' , 0, TRUNCATEONLY)
GO

--Shrink Data File
ALTER DATABASE [IMECentricEWDrSch] ADD FILE ( NAME = N'tmpData', FILENAME = N'D:\SQLData\tmpData.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB ) TO FILEGROUP [PRIMARY]
GO
DBCC SHRINKFILE (N'IMETrackSQL_dat' , EMPTYFILE)
GO
DBCC SHRINKFILE (N'IMETrackSQL_dat' , 1)
GO
DBCC SHRINKFILE (N'tmpData' , EMPTYFILE)
GO
ALTER DATABASE [IMECentricEWDrSch]  REMOVE FILE [tmpData]
GO



--Take DB Offline
ALTER DATABASE tmpIMEC SET OFFLINE WITH ROLLBACK IMMEDIATE
GO
