
CREATE PROCEDURE [proc_WebQRRequest_Insert]
(
	@QRRequestID int = NULL output,
	@ReqService varchar(40) = NULL,
	@ReqType varchar(40) = NULL,
	@RefCompanyName varchar(30) = NULL,
	@RefCompanyAddress1 varchar(30) = NULL,
	@RefCompanyAddress2 varchar(30) = NULL,
	@RefCompanyCity varchar(30) = NULL,
	@RefCompanyProvince varchar(25) = NULL,
	@RefCompanyPostalCode varchar(15) = NULL,
	@RefPersonFirstName varchar(30) = NULL,
	@RefPersonLastName varchar(30) = NULL,
	@RefPersonOffice varchar(50) = NULL,
	@RefPersonPhone varchar(30) = NULL,
	@RefPersonFax varchar(30) = NULL,
	@RefPersonEmail varchar(255) = NULL,
	@ExamineeFileNum varchar(50) = NULL,
	@ExamineeDOI smalldatetime = NULL,
	@ExamineeDOB smalldatetime = NULL,
	@ExamineePrefix varchar(15) = NULL,
	@ExamineeFirstName varchar(30) = NULL,
	@ExamineeLastName varchar(30) = NULL,
	@ExamineeAddress1 varchar(30) = NULL,
	@ExamineeAddress2 varchar(30) = NULL,
	@ExamineeCity varchar(30) = NULL,
	@ExamineeProvince varchar(25) = NULL,
	@ExamineePostalCode varchar(15) = NULL,
	@ExamineePhone varchar(30) = NULL,
	@ExamineeFax varchar(30) = NULL,
	@ExamineeEmail varchar(255) = NULL,
	@ExamineeSSN varchar(15) = NULL,
	@ExamineeGender varchar(10) = NULL,
	@Transportation varchar(10) = NULL,
	@Interpretation varchar(10) = NULL,
	@Language varchar(50) = NULL,
	@AdditionalTransInterpNeeds varchar(2000) = NULL,
	@CorrespFirstName varchar(30) = NULL,
	@CorrespLastName varchar(30) = NULL,
	@CorrespEmail varchar(255) = NULL,
	@ReqPhysicianFirstName varchar(30) = NULL,
	@ReqPhysicianLastName varchar(30) = NULL,
	@ReqSpecialties varchar(4000) = NULL,
	@SubspecialtyExpertise varchar(4000) = NULL,
	@PhysSpecInstructions varchar(4000) = NULL,
	@PreferredTimeline varchar(4000) = NULL,
	@DiagInjDescMedBrief varchar(4000) = NULL,
	@DateAdded smalldatetime = NULL,
	@EWFacilityID int = NULL,
	@IPAddress varchar(50) = NULL
)
AS
BEGIN

	SET NOCOUNT OFF
	DECLARE @Err int

	INSERT
	INTO [tblWebQRRequest]
	(
		[ReqService],
		[ReqType],
		[RefCompanyName],
		[RefCompanyAddress1],
		[RefCompanyAddress2],
		[RefCompanyCity],
		[RefCompanyProvince],
		[RefCompanyPostalCode],
		[RefPersonFirstName],
		[RefPersonLastName],
		[RefPersonOffice],
		[RefPersonPhone],
		[RefPersonFax],
		[RefPersonEmail],
		[ExamineeFileNum],
		[ExamineeDOI],
		[ExamineeDOB],
		[ExamineePrefix],
		[ExamineeFirstName],
		[ExamineeLastName],
		[ExamineeAddress1],
		[ExamineeAddress2],
		[ExamineeCity],
		[ExamineeProvince],
		[ExamineePostalCode],
		[ExamineePhone],
		[ExamineeFax],
		[ExamineeEmail],
		[ExamineeSSN],
		[ExamineeGender],
		[Transportation],
		[Interpretation],
		[Language],
		[AdditionalTransInterpNeeds],
		[CorrespFirstName],
		[CorrespLastName],
		[CorrespEmail],
		[ReqPhysicianFirstName],
		[ReqPhysicianLastName],
		[ReqSpecialties],
		[SubspecialtyExpertise],
		[PhysSpecInstructions],
		[PreferredTimeline],
		[DiagInjDescMedBrief],
		[DateAdded],
		[EWFacilityID],
		[IPAddress]
	)
	VALUES
	(
		@ReqService,
		@ReqType,
		@RefCompanyName,
		@RefCompanyAddress1,
		@RefCompanyAddress2,
		@RefCompanyCity,
		@RefCompanyProvince,
		@RefCompanyPostalCode,
		@RefPersonFirstName,
		@RefPersonLastName,
		@RefPersonOffice,
		@RefPersonPhone,
		@RefPersonFax,
		@RefPersonEmail,
		@ExamineeFileNum,
		@ExamineeDOI,
		@ExamineeDOB,
		@ExamineePrefix,
		@ExamineeFirstName,
		@ExamineeLastName,
		@ExamineeAddress1,
		@ExamineeAddress2,
		@ExamineeCity,
		@ExamineeProvince,
		@ExamineePostalCode,
		@ExamineePhone,
		@ExamineeFax,
		@ExamineeEmail,
		@ExamineeSSN,
		@ExamineeGender,
		@Transportation,
		@Interpretation,
		@Language,
		@AdditionalTransInterpNeeds,
		@CorrespFirstName,
		@CorrespLastName,
		@CorrespEmail,
		@ReqPhysicianFirstName,
		@ReqPhysicianLastName,
		@ReqSpecialties,
		@SubspecialtyExpertise,
		@PhysSpecInstructions,
		@PreferredTimeline,
		@DiagInjDescMedBrief,
		@DateAdded,
		@EWFacilityID,
		@IPAddress	
	)

	SET @Err = @@Error

	SELECT @QRRequestID = SCOPE_IDENTITY()

	RETURN @Err
END
