CREATE VIEW vwPDFInvDetData
AS
	SELECT	
			AD1.LineNbr AS InvLineNbr1 ,
	        AD1.Date AS InvServiceDate1 ,
			B.BlankValue AS InvServiceDate1MM,
			B.BlankValue AS InvServiceDate1DD,
			B.BlankValue AS InvServiceDate1YY,
			B.BlankValue AS InvServiceDateTo1MM,
			B.BlankValue AS InvServiceDateTo1DD,
			B.BlankValue AS InvServiceDateTo1YY,
	        AD1.CPTCode AS InvCPT1,
	        AD1.Modifier AS InvModifier1,
	        AD1.Modifier2 AS InvModifier1b ,
	        AD1.Modifier3 AS InvModifier1c ,
	        AD1.Modifier4 AS InvModifier1d ,
			B.BlankValue AS InvICD1,
			B.BlankValue AS InvDiagnosisPointer1,
	        AD1.Location AS InvPlaceOfService1,
			'2' AS InvTypeOfService1,
	        AD1.SuppInfo AS SupplementalInfo1,
	        AD1.Unit AS InvUnit1,
	        AD1.ExtendedAmount AS InvDetAmt1,
	        B.BlankValue AS InvDetAmt1Dollars,
			B.BlankValue AS InvDetAmt1Cents,
			AD1.DrOpCode AS DrOpCode1,
			DR1.NPINbr AS DoctorNPINbr1,


			AD2.LineNbr AS InvLineNbr2 ,
	        AD2.Date AS InvServiceDate2 ,
			B.BlankValue AS InvServiceDate2MM,
			B.BlankValue AS InvServiceDate2DD,
			B.BlankValue AS InvServiceDate2YY,
			B.BlankValue AS InvServiceDateTo2MM,
			B.BlankValue AS InvServiceDateTo2DD,
			B.BlankValue AS InvServiceDateTo2YY,
	        AD2.CPTCode AS InvCPT2,
	        AD2.Modifier AS InvModifier2,
	        AD2.Modifier2 AS InvModifier2b ,
	        AD2.Modifier3 AS InvModifier2c ,
	        AD2.Modifier4 AS InvModifier2d ,
			B.BlankValue AS InvICD2,
			B.BlankValue AS InvDiagnosisPointer2,
	        AD2.Location AS InvPlaceOfService2,
			'2' AS InvTypeOfService2,
	        AD2.SuppInfo AS SupplementalInfo2,
	        AD2.Unit AS InvUnit2,
	        AD2.ExtendedAmount AS InvDetAmt2,
	        B.BlankValue AS InvDetAmt2Dollars,
			B.BlankValue AS InvDetAmt2Cents,
			AD2.DrOpCode AS DrOpCode2,
			DR2.NPINbr AS DoctorNPINbr2,


			AD3.LineNbr AS InvLineNbr3 ,
	        AD3.Date AS InvServiceDate3 ,
			B.BlankValue AS InvServiceDate3MM,
			B.BlankValue AS InvServiceDate3DD,
			B.BlankValue AS InvServiceDate3YY,
			B.BlankValue AS InvServiceDateTo3MM,
			B.BlankValue AS InvServiceDateTo3DD,
			B.BlankValue AS InvServiceDateTo3YY,
	        AD3.CPTCode AS InvCPT3,
	        AD3.Modifier AS InvModifier3,
	        AD3.Modifier2 AS InvModifier3b ,
	        AD3.Modifier3 AS InvModifier3c ,
	        AD3.Modifier4 AS InvModifier3d ,
			B.BlankValue AS InvICD3,
			B.BlankValue AS InvDiagnosisPointer3,
	        AD3.Location AS InvPlaceOfService3,
			'2' AS InvTypeOfService3,
	        AD3.SuppInfo AS SupplementalInfo3,
	        AD3.Unit AS InvUnit3,
	        AD3.ExtendedAmount AS InvDetAmt3,
	        B.BlankValue AS InvDetAmt3Dollars,
			B.BlankValue AS InvDetAmt3Cents,
			AD3.DrOpCode AS DrOpCode3,
			DR3.NPINbr AS DoctorNPINbr3,


			AD4.LineNbr AS InvLineNbr4 ,
	        AD4.Date AS InvServiceDate4 ,
			B.BlankValue AS InvServiceDate4MM,
			B.BlankValue AS InvServiceDate4DD,
			B.BlankValue AS InvServiceDate4YY,
			B.BlankValue AS InvServiceDateTo4MM,
			B.BlankValue AS InvServiceDateTo4DD,
			B.BlankValue AS InvServiceDateTo4YY,
	        AD4.CPTCode AS InvCPT4,
	        AD4.Modifier AS InvModifier4,
	        AD4.Modifier2 AS InvModifier4b ,
	        AD4.Modifier3 AS InvModifier4c ,
	        AD4.Modifier4 AS InvModifier4d ,
			B.BlankValue AS InvICD4,
			B.BlankValue AS InvDiagnosisPointer4,
	        AD4.Location AS InvPlaceOfService4,
			'2' AS InvTypeOfService4,
	        AD4.SuppInfo AS SupplementalInfo4,
	        AD4.Unit AS InvUnit4,
	        AD4.ExtendedAmount AS InvDetAmt4,
	        B.BlankValue AS InvDetAmt4Dollars,
			B.BlankValue AS InvDetAmt4Cents,
			AD4.DrOpCode AS DrOpCode4,
			DR4.NPINbr AS DoctorNPINbr4,


			AD5.LineNbr AS InvLineNbr5 ,
	        AD5.Date AS InvServiceDate5 ,
			B.BlankValue AS InvServiceDate5MM,
			B.BlankValue AS InvServiceDate5DD,
			B.BlankValue AS InvServiceDate5YY,
			B.BlankValue AS InvServiceDateTo5MM,
			B.BlankValue AS InvServiceDateTo5DD,
			B.BlankValue AS InvServiceDateTo5YY,
	        AD5.CPTCode AS InvCPT5,
	        AD5.Modifier AS InvModifier5,
	        AD5.Modifier2 AS InvModifier5b ,
	        AD5.Modifier3 AS InvModifier5c ,
	        AD5.Modifier4 AS InvModifier5d ,
			B.BlankValue AS InvICD5,
			B.BlankValue AS InvDiagnosisPointer5,
	        AD5.Location AS InvPlaceOfService5,
			'2' AS InvTypeOfService5,
	        AD5.SuppInfo AS SupplementalInfo5,
	        AD5.Unit AS InvUnit5,
	        AD5.ExtendedAmount AS InvDetAmt5,
	        B.BlankValue AS InvDetAmt5Dollars,
			B.BlankValue AS InvDetAmt5Cents,
			AD5.DrOpCode AS DrOpCode5,
			DR5.NPINbr AS DoctorNPINbr5,


			AD6.LineNbr AS InvLineNbr6 ,
	        AD6.Date AS InvServiceDate6 ,
			B.BlankValue AS InvServiceDate6MM,
			B.BlankValue AS InvServiceDate6DD,
			B.BlankValue AS InvServiceDate6YY,
			B.BlankValue AS InvServiceDateTo6MM,
			B.BlankValue AS InvServiceDateTo6DD,
			B.BlankValue AS InvServiceDateTo6YY,
	        AD6.CPTCode AS InvCPT6,
	        AD6.Modifier AS InvModifier6,
	        AD6.Modifier2 AS InvModifier6b ,
	        AD6.Modifier3 AS InvModifier6c ,
	        AD6.Modifier4 AS InvModifier6d ,
			B.BlankValue AS InvICD6,
			B.BlankValue AS InvDiagnosisPointer6,
	        AD6.Location AS InvPlaceOfService6,
			'2' AS InvTypeOfService6,
	        AD6.SuppInfo AS SupplementalInfo6,
	        AD6.Unit AS InvUnit6,
	        AD6.ExtendedAmount AS InvDetAmt6,
	        B.BlankValue AS InvDetAmt6Dollars,
			B.BlankValue AS InvDetAmt6Cents,
			AD6.DrOpCode AS DrOpCode6,
			DR6.NPINbr AS DoctorNPINbr6,

			B.BlankValue AS InvICDDiagnosisPointer,
			AD1.HeaderID AS InvDetHeaderID

	FROM	tblAcctDetail AS AD1
	LEFT OUTER JOIN tblAcctDetail AS AD2 ON AD2.HeaderID = AD1.HeaderID AND AD2.LineNbr=2
	LEFT OUTER JOIN tblAcctDetail AS AD3 ON AD3.HeaderID = AD1.HeaderID AND AD3.LineNbr=3
	LEFT OUTER JOIN tblAcctDetail AS AD4 ON AD4.HeaderID = AD1.HeaderID AND AD4.LineNbr=4
	LEFT OUTER JOIN tblAcctDetail AS AD5 ON AD5.HeaderID = AD1.HeaderID AND AD5.LineNbr=5
	LEFT OUTER JOIN tblAcctDetail AS AD6 ON AD6.HeaderID = AD1.HeaderID AND AD6.LineNbr=6
	LEFT OUTER JOIN tblDoctor AS DR1 ON AD1.DrOpCode=DR1.DoctorCode
	LEFT OUTER JOIN tblDoctor AS DR2 ON AD2.DrOpCode=DR2.DoctorCode
	LEFT OUTER JOIN tblDoctor AS DR3 ON AD3.DrOpCode=DR3.DoctorCode
	LEFT OUTER JOIN tblDoctor AS DR4 ON AD4.DrOpCode=DR4.DoctorCode
	LEFT OUTER JOIN tblDoctor AS DR5 ON AD5.DrOpCode=DR5.DoctorCode
	LEFT OUTER JOIN tblDoctor AS DR6 ON AD6.DrOpCode=DR6.DoctorCode
	LEFT OUTER JOIN tblBlank AS B ON 1=1
	WHERE AD1.LineNbr=1
