CREATE PROCEDURE [proc_Examinee_Update]
(
	@chartnbr int,
	@lastname varchar(50) = NULL,
	@firstname varchar(50) = NULL,
	@middleinitial varchar(5) = NULL,
	@addr1 varchar(50) = NULL,
	@addr2 varchar(50) = NULL,
	@city varchar(50) = NULL,
	@state varchar(2) = NULL,
	@zip varchar(10) = NULL,
	@phone1 varchar(15) = NULL,
	@phone2 varchar(15) = NULL,
	@SSN varchar(15) = NULL,
	@sex varchar(10) = NULL,
	@DOB datetime = NULL,
	@dateadded datetime = NULL,
	@dateedited datetime = NULL,
	@useridadded varchar(15) = NULL,
	@useridedited varchar(15) = NULL,
	@note text = NULL,
	@prefix varchar(10) = NULL,
	@fax varchar(15) = NULL,
	@email varchar(50) = NULL,
	@insured varchar(50) = NULL,
	@employer varchar(70) = NULL,
	@treatingphysician varchar(70) = NULL,
	@InsuredAddr1 varchar(70) = NULL,
	@InsuredCity varchar(70) = NULL,
	@InsuredState varchar(5) = NULL,
	@InsuredZip varchar(10) = NULL,
	@InsuredPhone varchar(15) = NULL,
	@InsuredPhoneExt varchar(10) = NULL,
	@InsuredFax varchar(15) = NULL,
	@InsuredEmail varchar(70) = NULL,
	@TreatingPhysicianAddr1 varchar(70) = NULL,
	@TreatingPhysicianCity varchar(70) = NULL,
	@TreatingPhysicianState varchar(5) = NULL,
	@TreatingPhysicianZip varchar(10) = NULL,
	@TreatingPhysicianPhone varchar(15) = NULL,
	@TreatingPhysicianPhoneExt varchar(10) = NULL,
	@TreatingPhysicianFax varchar(15) = NULL,
	@TreatingPhysicianEmail varchar(70) = NULL,
	@TreatingPhysicianDiagnosis varchar(70) = NULL,
	@EmployerAddr1 varchar(70) = NULL,
	@EmployerCity varchar(70) = NULL,
	@EmployerState varchar(5) = NULL,
	@EmployerZip varchar(10) = NULL,
	@EmployerPhone varchar(15) = NULL,
	@EmployerPhoneExt varchar(10) = NULL,
	@EmployerFax varchar(15) = NULL,
	@EmployerEmail varchar(70) = NULL,
	@policynumber varchar(70) = NULL,
	@EmployerContactFirstName varchar(50) = NULL,
	@EmployerContactLastName varchar(50) = NULL,
	@County varchar(50) = NULL,
	@MobilePhone varchar(15) = NULL,
	@WorkPhone varchar(15) = NULL
)
AS
BEGIN

	SET NOCOUNT OFF
	DECLARE @Err int

	UPDATE [tblExaminee]
	SET
		[lastname] = @lastname,
		[firstname] = @firstname,
		[middleinitial] = @middleinitial,
		[addr1] = @addr1,
		[addr2] = @addr2,
		[city] = @city,
		[state] = @state,
		[zip] = @zip,
		[phone1] = @phone1,
		[phone2] = @phone2,
		[SSN] = @SSN,
		[sex] = @sex,
		[DOB] = @DOB,
		[dateadded] = @dateadded,
		[dateedited] = @dateedited,
		[useridadded] = @useridadded,
		[useridedited] = @useridedited,
		[note] = @note,
		[prefix] = @prefix,
		[fax] = @fax,
		[email] = @email,
		[insured] = @insured,
		[employer] = @employer,
		[treatingphysician] = @treatingphysician,
		[InsuredAddr1] = @InsuredAddr1,
		[InsuredCity] = @InsuredCity,
		[InsuredState] = @InsuredState,
		[InsuredZip] = @InsuredZip,
		[InsuredPhone] = @InsuredPhone,
		[InsuredPhoneExt] = @InsuredPhoneExt,
		[InsuredFax] = @InsuredFax,
		[InsuredEmail] = @InsuredEmail,
		[TreatingPhysicianAddr1] = @TreatingPhysicianAddr1,
		[TreatingPhysicianCity] = @TreatingPhysicianCity,
		[TreatingPhysicianState] = @TreatingPhysicianState,
		[TreatingPhysicianZip] = @TreatingPhysicianZip,
		[TreatingPhysicianPhone] = @TreatingPhysicianPhone,
		[TreatingPhysicianPhoneExt] = @TreatingPhysicianPhoneExt,
		[TreatingPhysicianFax] = @TreatingPhysicianFax,
		[TreatingPhysicianEmail] = @TreatingPhysicianEmail,
		[TreatingPhysicianDiagnosis] = @TreatingPhysicianDiagnosis,
		[EmployerAddr1] = @EmployerAddr1,
		[EmployerCity] = @EmployerCity,
		[EmployerState] = @EmployerState,
		[EmployerZip] = @EmployerZip,
		[EmployerPhone] = @EmployerPhone,
		[EmployerPhoneExt] = @EmployerPhoneExt,
		[EmployerFax] = @EmployerFax,
		[EmployerEmail] = @EmployerEmail,
		[policynumber] = @policynumber,
		[EmployerContactFirstName] = @EmployerContactFirstName,
		[EmployerContactLastName] = @EmployerContactLastName,
		[County] = @County,
		[MobilePhone] = @MobilePhone,
		[WorkPhone] = @WorkPhone
	WHERE
		[chartnbr] = @chartnbr


	SET @Err = @@Error


	RETURN @Err
END
GO