

CREATE PROCEDURE [proc_tblExamineeUpdate]
(
 @chartnbr int,
 @oldchartnbr varchar(15) = NULL,
 @lastname varchar(50) = NULL,
 @firstname varchar(50) = NULL,
 @middleinitial varchar(5) = NULL,
 @addr1 varchar(50) = NULL,
 @addr2 varchar(50) = NULL,
 @city varchar(50) = NULL,
 @state varchar(2) = NULL,
 @zip varchar(10) = NULL,
 @phone1 varchar(15) = NULL,
 @phone2 varchar(15) = NULL,
 @SSN varchar(15) = NULL,
 @sex varchar(10) = NULL,
 @DOB datetime = NULL,
 @dateadded datetime = NULL,
 @dateedited datetime = NULL,
 @useridadded varchar(15) = NULL,
 @useridedited varchar(15) = NULL,
 @note text = NULL,
 @county varchar(50) = NULL,
 @prefix varchar(10) = NULL,
 @usdvarchar1 varchar(50) = NULL,
 @usdvarchar2 varchar(50) = NULL,
 @usddate1 datetime = NULL,
 @usddate2 datetime = NULL,
 @usdtext1 text = NULL,
 @usdtext2 text = NULL,
 @usdint1 int = NULL,
 @usdint2 int = NULL,
 @usdmoney1 money = NULL,
 @usdmoney2 money = NULL,
 @fax varchar(15) = NULL,
 @email varchar(50) = NULL,
 @insured varchar(50) = NULL,
 @employer varchar(70) = NULL,
 @treatingphysician varchar(70) = NULL,
 @InsuredAddr1 varchar(70) = NULL,
 @InsuredCity varchar(70) = NULL,
 @InsuredState varchar(5) = NULL,
 @InsuredZip varchar(10) = NULL,
 @InsuredSex varchar(10) = NULL,
 @InsuredRelationship varchar(20) = NULL,
 @InsuredPhone varchar(15) = NULL,
 @InsuredPhoneExt varchar(10) = NULL,
 @InsuredFax varchar(15) = NULL,
 @InsuredEmail varchar(70) = NULL,
 @ExamineeStatus varchar(30) = NULL,
 @TreatingPhysicianAddr1 varchar(70) = NULL,
 @TreatingPhysicianCity varchar(70) = NULL,
 @TreatingPhysicianState varchar(5) = NULL,
 @TreatingPhysicianZip varchar(10) = NULL,
 @TreatingPhysicianPhone varchar(15) = NULL,
 @TreatingPhysicianPhoneExt varchar(10) = NULL,
 @TreatingPhysicianFax varchar(15) = NULL,
 @TreatingPhysicianEmail varchar(70) = NULL,
 @EmployerAddr1 varchar(70) = NULL,
 @EmployerCity varchar(70) = NULL,
 @EmployerState varchar(5) = NULL,
 @EmployerZip varchar(10) = NULL,
 @EmployerPhone varchar(15) = NULL,
 @EmployerPhoneExt varchar(10) = NULL,
 @EmployerFax varchar(15) = NULL,
 @EmployerEmail varchar(70) = NULL,
 @Country varchar(50) = NULL,
 @policynumber varchar(70) = NULL,
 @EmployerContactFirstName varchar(50) = NULL,
 @EmployerContactLastName varchar(50) = NULL
)
AS
BEGIN

 SET NOCOUNT OFF
 DECLARE @Err int

 UPDATE [tblExaminee]
 SET
  [oldchartnbr] = @oldchartnbr,
  [lastname] = @lastname,
  [firstname] = @firstname,
  [middleinitial] = @middleinitial,
  [addr1] = @addr1,
  [addr2] = @addr2,
  [city] = @city,
  [state] = @state,
  [zip] = @zip,
  [phone1] = @phone1,
  [phone2] = @phone2,
  [SSN] = @SSN,
  [sex] = @sex,
  [DOB] = @DOB,
  [dateadded] = @dateadded,
  [dateedited] = @dateedited,
  [useridadded] = @useridadded,
  [useridedited] = @useridedited,
  [note] = @note,
  [county] = @county,
  [prefix] = @prefix,
  [usdvarchar1] = @usdvarchar1,
  [usdvarchar2] = @usdvarchar2,
  [usddate1] = @usddate1,
  [usddate2] = @usddate2,
  [usdtext1] = @usdtext1,
  [usdtext2] = @usdtext2,
  [usdint1] = @usdint1,
  [usdint2] = @usdint2,
  [usdmoney1] = @usdmoney1,
  [usdmoney2] = @usdmoney2,
  [fax] = @fax,
  [email] = @email,
  [insured] = @insured,
  [employer] = @employer,
  [treatingphysician] = @treatingphysician,
  [InsuredAddr1] = @InsuredAddr1,
  [InsuredCity] = @InsuredCity,
  [InsuredState] = @InsuredState,
  [InsuredZip] = @InsuredZip,
  [InsuredSex] = @InsuredSex,
  [InsuredRelationship] = @InsuredRelationship,
  [InsuredPhone] = @InsuredPhone,
  [InsuredPhoneExt] = @InsuredPhoneExt,
  [InsuredFax] = @InsuredFax,
  [InsuredEmail] = @InsuredEmail,
  [ExamineeStatus] = @ExamineeStatus,
  [TreatingPhysicianAddr1] = @TreatingPhysicianAddr1,
  [TreatingPhysicianCity] = @TreatingPhysicianCity,
  [TreatingPhysicianState] = @TreatingPhysicianState,
  [TreatingPhysicianZip] = @TreatingPhysicianZip,
  [TreatingPhysicianPhone] = @TreatingPhysicianPhone,
  [TreatingPhysicianPhoneExt] = @TreatingPhysicianPhoneExt,
  [TreatingPhysicianFax] = @TreatingPhysicianFax,
  [TreatingPhysicianEmail] = @TreatingPhysicianEmail,
  [EmployerAddr1] = @EmployerAddr1,
  [EmployerCity] = @EmployerCity,
  [EmployerState] = @EmployerState,
  [EmployerZip] = @EmployerZip,
  [EmployerPhone] = @EmployerPhone,
  [EmployerPhoneExt] = @EmployerPhoneExt,
  [EmployerFax] = @EmployerFax,
  [EmployerEmail] = @EmployerEmail,
  [Country] = @Country,
  [policynumber] = @policynumber,
  [EmployerContactFirstName] = @EmployerContactFirstName,
  [EmployerContactLastName] = @EmployerContactLastName
 WHERE
  [chartnbr] = @chartnbr


 SET @Err = @@Error


 RETURN @Err
END


