CREATE TABLE [dbo].[tblServices] (
    [ServiceCode]           INT           IDENTITY (1, 1) NOT NULL,
    [Description]           VARCHAR (50)  NULL,
    [DateAdded]             DATETIME      NULL,
    [UserIDAdded]           VARCHAR (15)  NULL,
    [DateEdited]            DATETIME      NULL,
    [UserIDEdited]          VARCHAR (15)  NULL,
    [ShortDesc]             VARCHAR (5)   NULL,
    [OfficeCode]            INT           NULL,
    [Status]                VARCHAR (15)  NULL,
    [PublishOnWeb]          BIT           NULL,
    [WebSynchDate]          DATETIME      NULL,
    [WebID]                 INT           NULL,
    [DaysToCommitDate]      INT           NULL,
    [CalcFrom]              VARCHAR (10)  NULL,
    [ServiceType]           VARCHAR (20)  NULL,
    [ShowLegalTabOnCase]    BIT           CONSTRAINT [DF_tblServices_ShowLegalTabOnCase] DEFAULT ((0)) NULL,
    [EWServiceTypeID]       INT           NULL,
    [ApptBased]             BIT           NULL,
    [CaseRecdDateOverride]  BIT           NULL,
    [AllowNonApptBasedDate] BIT           CONSTRAINT [DF_tblServices_AllowNonApptBasedDate] DEFAULT ((0)) NULL,
    [LongDesc]              VARCHAR (250) NULL,
    [DNUSetting]            INT           CONSTRAINT [DF_tblServices_DNUSetting] DEFAULT ((1)) NULL,
    [IsReExam]              BIT           CONSTRAINT [DF_tblServices_IsReExam] DEFAULT ((0)) NOT NULL,
    [ReExamServiceCode]     INT           NULL,
    [UseDrPortalCalendar]	BIT			  CONSTRAINT [DF_tblServices_UseDrPortalCalendar] DEFAULT ((0)) NOT NULL,
	[ProdCode]              INT           NULL,
    CONSTRAINT [PK_tblServices] PRIMARY KEY CLUSTERED ([ServiceCode] ASC)
);

