CREATE TABLE [dbo].[tblCasePeerBill] (
    [PeerBillID]            INT           IDENTITY (1, 1) NOT NULL,
    [CaseNbr]               INT           NOT NULL,
    [DateBillReceived]      DATETIME      NULL,
    [ServiceDate]           DATETIME      NULL,
    [BillNumber]            VARCHAR (50)  NULL,
    [BillAmount]            MONEY         NULL,
    [ReferringProviderName] VARCHAR (50)  NULL,
    [ReferringProviderTIN]  VARCHAR (11)  NULL,
    [ProviderName]          VARCHAR (50)  NULL,
    [ProviderTIN]           VARCHAR (11)  NULL,
    [ProviderSpecialtyCode] VARCHAR (50)  NULL,
    [ServiceRendered]       VARCHAR (250) NULL,
    [CPTCode]               VARCHAR (50)  NULL,
    [BillAmountApproved]    MONEY         NULL,
    [BillAmountDenied]      MONEY         NULL,
    [DateAdded]             DATETIME      NULL,
    [UserIDAdded]           VARCHAR (15)  NULL,
    [DateEdited]            DATETIME      NULL,
    [UserIDEdited]          VARCHAR (15)  NULL,
    [ProviderZip]           VARCHAR(10)   NULL, 
    [ServiceEndDate]        DATETIME      NULL, 
    CONSTRAINT [PK_tblCasePeerBill] PRIMARY KEY CLUSTERED ([PeerBillID] ASC)
);

