CREATE TABLE [dbo].[tblBusinessRuleCondition] (
    [BusinessRuleConditionID] INT          IDENTITY (1, 1) NOT NULL,
    [EntityType]              VARCHAR (2)  NULL,
    [EntityID]                INT          NULL,
    [BillingEntity]           INT          CONSTRAINT [DF_tblBusinessRuleCondition_BillingEntity] DEFAULT ((0)) NOT NULL,
    [ProcessOrder]            INT          NULL,
    [BusinessRuleID]          INT          NOT NULL,
    [DateAdded]               DATETIME     NULL,
    [UserIDAdded]             VARCHAR (20) NULL,
    [DateEdited]              DATETIME     NULL,
    [UserIDEdited]            VARCHAR (20) NULL,
    [OfficeCode]              INT          NULL,
    [EWBusLineID]             INT          NULL,
    [EWServiceTypeID]         INT          NULL,
    [Jurisdiction]            VARCHAR (5)  NULL,
    [Param1]                  VARCHAR (50) NULL,
    [Param2]                  VARCHAR (50) NULL,
    [Param3]                  VARCHAR (50) NULL,
    [Param4]                  VARCHAR (50) NULL,
    [Param5]                  VARCHAR (50) NULL,
    [Skip]                    Bit          CONSTRAINT [DF_tblBusinessRuleCondition_Skip] DEFAULT ((0)) NULL,
    [Param6]                  VARCHAR(MAX) NULL, 
    CONSTRAINT [PK_tblBusinessRuleCondition] PRIMARY KEY CLUSTERED ([BusinessRuleConditionID] ASC)
);

