CREATE TABLE [dbo].[tblFeeDetail] (
    [FeeCode]              INT             NOT NULL,
    [ProdCode]             INT             NOT NULL,
    [Fee]                  MONEY           NULL,
    [LateCancelFee]        MONEY           NULL,
    [NoShowFee]            MONEY           NULL,
    [DateAdded]            DATETIME        NULL,
    [UserIDAdded]          VARCHAR (20)    NULL,
    [DateEdited]           DATETIME        NULL,
    [UserIDEdited]         VARCHAR (20)    NULL,
    [DrFee]                MONEY           NULL,
    [DrLateCancelFee]      MONEY           NULL,
    [DrNoShowFee]          MONEY           NULL,
    [CancelDays]           INT             NULL,
    [CancelDays2]          INT             NULL,
    [LateCancelFee2]       MONEY           NULL,
    [CancelDays3]          INT             NULL,
    [LateCancelFee3]       MONEY           NULL,
    [DrLateCancelFee2]     MONEY           NULL,
    [DrLateCancelFee3]     MONEY           NULL,
    [RecordInchesIncluded] DECIMAL (18, 2) CONSTRAINT [DF_tblFeeDetail_RecordInchesIncluded] DEFAULT ((0)) NULL,
    [feeplus]              MONEY           NULL,
    [MinFee]               MONEY           NULL,
    [Rounding]             INT             NULL,
    [RoundOn]              BIT             NULL,
    [Divisor]              DECIMAL (18)    NULL,
    [RevenueAcct]          VARCHAR (50)    NULL,
    [ExpenseAcct]          VARCHAR (50)    NULL,
    [Dept]                 VARCHAR (50)    NULL,
    CONSTRAINT [PK_tblfeedetail] PRIMARY KEY CLUSTERED ([FeeCode] ASC, [ProdCode] ASC)
);

