CREATE TABLE [dbo].[tblIMEData] (
    [CompanyName]                   VARCHAR (70)  NOT NULL,
    [EmailAddress]                  VARCHAR (70)  NULL,
    [DirDocument]                   VARCHAR (256)  NULL,
    [NoShowLtrDocument]             VARCHAR (15)  NULL,
    [UserIDAdded]                   VARCHAR (20)  NULL,
    [DateAdded]                     DATETIME      NULL,
    [UserIDEdited]                  VARCHAR (20)  NULL,
    [DateEdited]                    DATETIME      NULL,
    [DistanceUofM]                  VARCHAR (5)   NULL,
    [DaysToCancel]                  INT           NULL,
    [OrderCCDropdown]               VARCHAR (20)  NULL,
    [VerbalDocument]                VARCHAR (50)  NULL,
    [VerbalQueue]                   INT           NULL,
    [SortCaseHistoryDesc]           VARCHAR (10)  NULL,
    [INFeeCode]                     INT           NULL,
    [VOFeeCode]                     INT           NULL,
    [INDocumentCode]                VARCHAR (15)  NULL,
    [VODocumentCode]                VARCHAR (15)  NULL,
    [InvoiceDesc]                   INT           NULL,
    [StdTerms]                      VARCHAR (30)  NULL,
    [InvoiceCopies]                 INT           NULL,
    [DirImport]                     VARCHAR (256)  NULL,
    [VoucherCopies]                 INT           NULL,
    [SourceDirectory]               VARCHAR (256)  NULL,
    [Country]                       VARCHAR (50)  NULL,
    [IMECode]                       INT           IDENTITY (1, 1) NOT NULL,
    [QAfterNoShow]                  INT           NULL,
    [UsePanelExam]                  BIT           NULL,
    [ShowOntarioAutoFields]         BIT           NULL,
    [DirAcctDocument]               VARCHAR (256) NULL,
    [DefaultAddressLabel]           INT           NULL,
    [DefaultCaseLabel]              INT           NULL,
    [InvoiceNoShows]                BIT           NULL,
    [InvoiceLateCancels]            BIT           NULL,
    [VoucherNoShows]                BIT           NULL,
    [VoucherLateCancels]            BIT           NULL,
    [ShowEWFacilityOnInvVo]         BIT           CONSTRAINT [DF_tblIMEData_ShowEWFacilityOnInvVo] DEFAULT ((0)) NOT NULL,
    [ShowProductDescOnClaimForm]    BIT           CONSTRAINT [DF_tblIMEData_ShowProductDescOnClaimForm] DEFAULT ((0)) NOT NULL,
    [ShowClientAsReferringProvider] BIT           CONSTRAINT [DF_tblIMEData_ShowClientAsReferringProvider] DEFAULT ((0)) NOT NULL,
    [MonetaryUnit]                  INT           NULL,
    [DirTranscription]              VARCHAR (256)  NULL,
    [QAfterLateCancel]              INT           NULL,
    [TaxCalcMethod]                 INT           NULL,
    [ReExamNoticeDocument]          VARCHAR (15)  NULL,
    [UseNF10]                       BIT           CONSTRAINT [DF_tblIMEData_UseNF10] DEFAULT ((0)) NOT NULL,
    [ShowCaseNotification]          BIT           CONSTRAINT [DF_tblIMEData_ShowCaseNotification] DEFAULT ((0)) NOT NULL,
    [UseICDRequest]                 BIT           CONSTRAINT [DF_tblIMEData_UseICDRequest] DEFAULT ((0)) NOT NULL,
    [UsePeerBill]                   BIT           CONSTRAINT [DF_tblIMEData_UsePeerBill] DEFAULT ((0)) NOT NULL,
    [ExamineeReimbDefProdCode]      INT           NULL,
    [AcctDocFolderID]               INT           NULL,
    [CaseDocFolderID]               INT           NULL,
    [FeeScheduleSetting]            INT           CONSTRAINT [DF_tblIMEData_FeeScheduleSetting] DEFAULT ((1)) NOT NULL,
    [FeeCalcMethod]                 INT           NULL,
	[PrmptForClientChngAssocCases]	BIT			  CONSTRAINT [DF_tblIMEData_PrmptForClientChngAssocCases] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_tblIMEData] PRIMARY KEY CLUSTERED ([IMECode] ASC)
);



