CREATE TABLE [dbo].[tblServiceWorkflowQueueDocument] (
    [ServiceWorkflowQueueDocumentID] INT          IDENTITY (1, 1) NOT NULL,
    [ServiceWorkflowQueueID]         INT          NOT NULL,
    [DateAdded]               DATETIME     NULL,
    [UserIDAdded]             VARCHAR (15) NULL,
    [DateEdited]              DATETIME     NULL,
    [UserIDEdited]            VARCHAR (15) NULL,
    [Document]                VARCHAR (15) NOT NULL,
    [Attachment]              VARCHAR (15) NULL,
    [ProcessOrder]            INT          NULL,
    [PrintCopies]             INT          CONSTRAINT [DF_tblServiceWorkflowQueueDocument_PrintCopies] DEFAULT ((0)) NULL,
    [EmailDoctor]             BIT          NULL,
    [EmailAttorney]           BIT          NULL,
    [EmailClient]             BIT          NULL,
    [FaxDoctor]               BIT          NULL,
    [FaxAttorney]             BIT          NULL,
    [FaxClient]               BIT          NULL,
    [PublishOnWeb]            BIT          CONSTRAINT [DF_tblServiceWorkflowQueueDocument_PublishOnWeb] DEFAULT ((0)) NULL,
    [PublishedTo]             VARCHAR (50) NULL,
    [EnvelopeAOrder]          INT          NULL, 
    [EnvelopeBOrder]          INT          NULL, 
    [EnvelopeCOrder]          INT          NULL, 
    [EnvelopeDOrder]          INT          NULL, 
	[CombineDocs]             BIT          CONSTRAINT [DF_tblServiceWorkflowQueueDocument_CombineDocs] DEFAULT ((0)) NOT NULL, 
    CONSTRAINT [PK_tblServiceWorkflowQueueDocument] PRIMARY KEY CLUSTERED ([ServiceWorkflowQueueDocumentID] ASC)
);

