CREATE TABLE [dbo].[tblWebQRRequest] (
    [QRRequestID]                INT            IDENTITY (1, 1) NOT NULL,
    [ReqService]                 VARCHAR (40)   NULL,
    [ReqType]                    VARCHAR (40)   NULL,
    [RefCompanyName]             VARCHAR (30)   NULL,
    [RefCompanyAddress1]         VARCHAR (30)   NULL,
    [RefCompanyAddress2]         VARCHAR (30)   NULL,
    [RefCompanyCity]             VARCHAR (30)   NULL,
    [RefCompanyProvince]         VARCHAR (25)   NULL,
    [RefCompanyPostalCode]       VARCHAR (15)   NULL,
    [RefPersonFirstName]         VARCHAR (30)   NULL,
    [RefPersonLastName]          VARCHAR (30)   NULL,
    [RefPersonOffice]            VARCHAR (50)   NULL,
    [RefPersonPhone]             VARCHAR (30)   NULL,
    [RefPersonFax]               VARCHAR (30)   NULL,
    [RefPersonEmail]             VARCHAR (255)  NULL,
    [ExamineeFileNum]            VARCHAR (50)   NULL,
    [ExamineeDOI]                SMALLDATETIME  NULL,
    [ExamineeDOB]                SMALLDATETIME  NULL,
    [ExamineePrefix]             VARCHAR (15)   NULL,
    [ExamineeFirstName]          VARCHAR (30)   NULL,
    [ExamineeLastName]           VARCHAR (30)   NULL,
    [ExamineeAddress1]           VARCHAR (30)   NULL,
    [ExamineeAddress2]           VARCHAR (30)   NULL,
    [ExamineeCity]               VARCHAR (30)   NULL,
    [ExamineeProvince]           VARCHAR (25)   NULL,
    [ExamineePostalCode]         VARCHAR (15)   NULL,
    [ExamineePhone]              VARCHAR (30)   NULL,
    [ExamineeFax]                VARCHAR (30)   NULL,
    [ExamineeEmail]              VARCHAR (255)  NULL,
    [ExamineeSSN]                VARCHAR (15)   NULL,
    [ExamineeGender]             VARCHAR (10)   NULL,
    [Transportation]             VARCHAR (10)   NULL,
    [Interpretation]             VARCHAR (10)   NULL,
    [Language]                   VARCHAR (50)   NULL,
    [AdditionalTransInterpNeeds] VARCHAR (2000) NULL,
    [CorrespFirstName]           VARCHAR (30)   NULL,
    [CorrespLastName]            VARCHAR (30)   NULL,
    [CorrespEmail]               VARCHAR (255)  NULL,
    [ReqPhysicianFirstName]      VARCHAR (30)   NULL,
    [ReqPhysicianLastName]       VARCHAR (30)   NULL,
    [ReqSpecialties]             VARCHAR (4000) NULL,
    [SubspecialtyExpertise]      VARCHAR (4000) NULL,
    [PhysSpecInstructions]       VARCHAR (4000) NULL,
    [PreferredTimeline]          VARCHAR (4000) NULL,
    [DiagInjDescMedBrief]        VARCHAR (4000) NULL,
    [DateAdded]                  SMALLDATETIME  NULL,
    [IPAddress]                  VARCHAR (50)   NULL,
    [EWFacilityID]               INT            NULL,
    CONSTRAINT [PK_tblWebQRRequest] PRIMARY KEY CLUSTERED ([QRRequestID] ASC)
);

