CREATE TABLE [dbo].[SedgwickPaymentDetails] (
    [Id]                   INT             IDENTITY (1, 1) NOT NULL,
    [PaymentType]          VARCHAR (8)     NULL,
    [BillStatus]           VARCHAR (32)    NULL,
    [ICN]                  VARCHAR (32)    NULL,
    [DetailSeq]            INT             NULL,
    [CMSClaimNumber]       VARCHAR (32)    NULL,
    [ShortVendorId]        VARCHAR (8)     NULL,
    [Office]               VARCHAR (8)     NULL,
    [ClientNumber]         VARCHAR (8)     NULL,
    [BankAccount]          VARCHAR (16)    NULL,
    [TaxId]                VARCHAR (16)    NULL,
    [DocType]              VARCHAR (4)     NULL,
    [Filler]               VARCHAR (8)     NULL,
    [SSN]                  VARCHAR (16)    NULL,
    [ClaimantClientUEN]    VARCHAR (32)    NULL,
    [ClaimantStateEEID]    VARCHAR (32)    NULL,
    [ClaimantLastName]     VARCHAR (32)    NULL,
    [ClaimantFirstName]    VARCHAR (32)    NULL,
    [StateOfJurisdiction]  CHAR (2)        NULL,
    [DateOfInjury]         VARCHAR (8)     NULL,
    [BillReceived]         VARCHAR (8)     NULL,
    [ScheduledPrintDate]   VARCHAR (8)     NULL,
    [PaymentPrinted]       VARCHAR (8)     NULL,
    [TotalPayment]         NUMERIC (18, 2) NULL,
    [AmountOfPaymentType]  NUMERIC (18, 2) NULL,
    [EditMessage]          VARCHAR (65)    NULL,
    [UserId]               VARCHAR (8)     NULL,
    [ProcedureCode]        VARCHAR (16)    NULL,
    [ProcedureModifier]    VARCHAR (8)     NULL,
    [ProviderPayStatus]    VARCHAR (32)    NULL,
    [ReturnPendingReason]  VARCHAR (256)   NULL,
    [ReturnReasonNote]     VARCHAR (256)   NULL,
    [InvoiceNumber]        VARCHAR (32)    NULL,
    [VoidDate]             VARCHAR (8)     NULL,
    [PayCode]              VARCHAR (4)     NULL,
    [EORMailedDate]        VARCHAR (8)     NULL,
    [ReviewOnly]           CHAR (1)        NULL,
    [ExaminerContactName]  VARCHAR (32)    NULL,
    [ExaminerContactEmail] VARCHAR (32)    NULL,
    [eBill]                VARCHAR (4)     NULL,
    [VDReturnField]        VARCHAR (4)     NULL,
    [Shell]                VARCHAR (4)     NULL,
    [ElectronicPayment]    VARCHAR (4)     NULL,
    [ReceivedBySedgwick]   VARCHAR (8)     NULL,
    [DateProcessed]        VARCHAR (8)     NULL,
    [ResubmitFlag]         CHAR (1)        NULL,
    [CheckNumberEFTRef]    VARCHAR (16)    NULL,
    [PaymentHeaderId]      INT             NULL,
    CONSTRAINT [PK_SedgwickPaymentDetails] PRIMARY KEY CLUSTERED ([Id] ASC)
);

