CREATE VIEW vwPDFInvDetData2
AS
	SELECT	
			AD7.LineNbr AS InvLineNbr7 ,
	        AD7.Date AS InvServiceDate7 ,
			B.BlankValue AS InvServiceDate7MM,
			B.BlankValue AS InvServiceDate7DD,
			B.BlankValue AS InvServiceDate7YY,
			ISNULL(AD7.ToDate, AD7.Date) AS InvServiceDateTo7,
			B.BlankValue AS InvServiceDateTo7MM,
			B.BlankValue AS InvServiceDateTo7DD,
			B.BlankValue AS InvServiceDateTo7YY,
	        AD7.CPTCode AS InvCPT7,
	        AD7.Modifier AS InvModifier7,
	        AD7.Modifier2 AS InvModifier7b ,
	        AD7.Modifier3 AS InvModifier7c ,
	        AD7.Modifier4 AS InvModifier7d ,
			B.BlankValue AS InvICD7,
			B.BlankValue AS InvDiagnosisPointer7,
	        AD7.Location AS InvPlaceOfService7,
			'2' AS InvTypeOfService7,
	        AD7.SuppInfo AS SupplementalInfo7,
	        AD7.Unit AS InvUnit7,
	        AD7.ExtendedAmount AS InvDetAmt7,
			AD7.RetailAmount AS InvRetailAmt7,
	        B.BlankValue AS InvDetAmt7Dollars,
			B.BlankValue AS InvDetAmt7Cents,
	        B.BlankValue AS InvDetAmt7bDollars,
			B.BlankValue AS InvDetAmt7bCents,
			AD7.DrOpCode AS DrOpCode7,
			DR7.NPINbr AS DoctorNPINbr7,

			AD8.LineNbr AS InvLineNbr8 ,
	        AD8.Date AS InvServiceDate8 ,
			B.BlankValue AS InvServiceDate8MM,
			B.BlankValue AS InvServiceDate8DD,
			B.BlankValue AS InvServiceDate8YY,
			ISNULL(AD8.ToDate, AD8.Date) AS InvServiceDateTo8,
			B.BlankValue AS InvServiceDateTo8MM,
			B.BlankValue AS InvServiceDateTo8DD,
			B.BlankValue AS InvServiceDateTo8YY,
	        AD8.CPTCode AS InvCPT8,
	        AD8.Modifier AS InvModifier8,
	        AD8.Modifier2 AS InvModifier8b ,
	        AD8.Modifier3 AS InvModifier8c ,
	        AD8.Modifier4 AS InvModifier8d ,
			B.BlankValue AS InvICD8,
			B.BlankValue AS InvDiagnosisPointer8,
	        AD8.Location AS InvPlaceOfService8,
			'2' AS InvTypeOfService8,
	        AD8.SuppInfo AS SupplementalInfo8,
	        AD8.Unit AS InvUnit8,
	        AD8.ExtendedAmount AS InvDetAmt8,
			AD8.RetailAmount AS InvRetailAmt8,
	        B.BlankValue AS InvDetAmt8Dollars,
			B.BlankValue AS InvDetAmt8Cents,
	        B.BlankValue AS InvDetAmt8bDollars,
			B.BlankValue AS InvDetAmt8bCents,
			AD8.DrOpCode AS DrOpCode8,
			DR8.NPINbr AS DoctorNPINbr8,

			AD9.LineNbr AS InvLineNbr9 ,
	        AD9.Date AS InvServiceDate9 ,
			B.BlankValue AS InvServiceDate9MM,
			B.BlankValue AS InvServiceDate9DD,
			B.BlankValue AS InvServiceDate9YY,
			ISNULL(AD9.ToDate, AD9.Date) AS InvServiceDateTo9,
			B.BlankValue AS InvServiceDateTo9MM,
			B.BlankValue AS InvServiceDateTo9DD,
			B.BlankValue AS InvServiceDateTo9YY,
	        AD9.CPTCode AS InvCPT9,
	        AD9.Modifier AS InvModifier9,
	        AD9.Modifier2 AS InvModifier9b ,
	        AD9.Modifier3 AS InvModifier9c ,
	        AD9.Modifier4 AS InvModifier9d ,
			B.BlankValue AS InvICD9,
			B.BlankValue AS InvDiagnosisPointer9,
	        AD9.Location AS InvPlaceOfService9,
			'2' AS InvTypeOfService9,
	        AD9.SuppInfo AS SupplementalInfo9,
	        AD9.Unit AS InvUnit9,
	        AD9.ExtendedAmount AS InvDetAmt9,
			AD9.RetailAmount AS InvRetailAmt9,
	        B.BlankValue AS InvDetAmt9Dollars,
			B.BlankValue AS InvDetAmt9Cents,
	        B.BlankValue AS InvDetAmt9bDollars,
			B.BlankValue AS InvDetAmt9bCents,
			AD9.DrOpCode AS DrOpCode9,
			DR9.NPINbr AS DoctorNPINbr9,

			AD10.LineNbr AS InvLineNbr10 ,
	        AD10.Date AS InvServiceDate10 ,
			B.BlankValue AS InvServiceDate10MM,
			B.BlankValue AS InvServiceDate10DD,
			B.BlankValue AS InvServiceDate10YY,
			ISNULL(AD10.ToDate, AD10.Date) AS InvServiceDateTo10,
			B.BlankValue AS InvServiceDateTo10MM,
			B.BlankValue AS InvServiceDateTo10DD,
			B.BlankValue AS InvServiceDateTo10YY,
	        AD10.CPTCode AS InvCPT10,
	        AD10.Modifier AS InvModifier10,
	        AD10.Modifier2 AS InvModifier10b ,
	        AD10.Modifier3 AS InvModifier10c ,
	        AD10.Modifier4 AS InvModifier10d ,
			B.BlankValue AS InvICD10,
			B.BlankValue AS InvDiagnosisPointer10,
	        AD10.Location AS InvPlaceOfService10,
			'2' AS InvTypeOfService10,
	        AD10.SuppInfo AS SupplementalInfo10,
	        AD10.Unit AS InvUnit10,
	        AD10.ExtendedAmount AS InvDetAmt10,
			AD10.RetailAmount AS InvRetailAmt10,
	        B.BlankValue AS InvDetAmt10Dollars,
			B.BlankValue AS InvDetAmt10Cents,
	        B.BlankValue AS InvDetAmt10bDollars,
			B.BlankValue AS InvDetAmt10bCents,
			AD10.DrOpCode AS DrOpCode10,
			DR10.NPINbr AS DoctorNPINbr10,

			AD11.LineNbr AS InvLineNbr11 ,
	        AD11.Date AS InvServiceDate11 ,
			B.BlankValue AS InvServiceDate11MM,
			B.BlankValue AS InvServiceDate11DD,
			B.BlankValue AS InvServiceDate11YY,
			ISNULL(AD11.ToDate, AD11.Date) AS InvServiceDateTo11,
			B.BlankValue AS InvServiceDateTo11MM,
			B.BlankValue AS InvServiceDateTo11DD,
			B.BlankValue AS InvServiceDateTo11YY,
	        AD11.CPTCode AS InvCPT11,
	        AD11.Modifier AS InvModifier11,
	        AD11.Modifier2 AS InvModifier11b ,
	        AD11.Modifier3 AS InvModifier11c ,
	        AD11.Modifier4 AS InvModifier11d ,
			B.BlankValue AS InvICD11,
			B.BlankValue AS InvDiagnosisPointer11,
	        AD11.Location AS InvPlaceOfService11,
			'2' AS InvTypeOfService11,
	        AD11.SuppInfo AS SupplementalInfo11,
	        AD11.Unit AS InvUnit11,
	        AD11.ExtendedAmount AS InvDetAmt11,
			AD11.RetailAmount AS InvRetailAmt11,
	        B.BlankValue AS InvDetAmt11Dollars,
			B.BlankValue AS InvDetAmt11Cents,
	        B.BlankValue AS InvDetAmt11bDollars,
			B.BlankValue AS InvDetAmt11bCents,
			AD11.DrOpCode AS DrOpCode11,
			DR11.NPINbr AS DoctorNPINbr11,

			AD12.LineNbr AS InvLineNbr12 ,
	        AD12.Date AS InvServiceDate12 ,
			B.BlankValue AS InvServiceDate12MM,
			B.BlankValue AS InvServiceDate12DD,
			B.BlankValue AS InvServiceDate12YY,
			ISNULL(AD12.ToDate, AD12.Date) AS InvServiceDateTo12,
			B.BlankValue AS InvServiceDateTo12MM,
			B.BlankValue AS InvServiceDateTo12DD,
			B.BlankValue AS InvServiceDateTo12YY,
	        AD12.CPTCode AS InvCPT12,
	        AD12.Modifier AS InvModifier12,
	        AD12.Modifier2 AS InvModifier12b ,
	        AD12.Modifier3 AS InvModifier12c ,
	        AD12.Modifier4 AS InvModifier12d ,
			B.BlankValue AS InvICD12,
			B.BlankValue AS InvDiagnosisPointer12,
	        AD12.Location AS InvPlaceOfService12,
			'2' AS InvTypeOfService12,
	        AD12.SuppInfo AS SupplementalInfo12,
	        AD12.Unit AS InvUnit12,
	        AD12.ExtendedAmount AS InvDetAmt12,
			AD12.RetailAmount AS InvRetailAmt12,
	        B.BlankValue AS InvDetAmt12Dollars,
			B.BlankValue AS InvDetAmt12Cents,
	        B.BlankValue AS InvDetAmt12bDollars,
			B.BlankValue AS InvDetAmt12bCents,
			AD12.DrOpCode AS DrOpCode12,
			DR12.NPINbr AS DoctorNPINbr12,

			AD1.HeaderID AS InvDetHeaderID

	FROM	tblAcctDetail AS AD1
	LEFT OUTER JOIN tblAcctDetail AS AD7 ON AD7.HeaderID = AD1.HeaderID AND AD7.LineNbr=7
	LEFT OUTER JOIN tblAcctDetail AS AD8 ON AD8.HeaderID = AD1.HeaderID AND AD8.LineNbr=8
	LEFT OUTER JOIN tblAcctDetail AS AD9 ON AD9.HeaderID = AD1.HeaderID AND AD9.LineNbr=9
	LEFT OUTER JOIN tblAcctDetail AS AD10 ON AD10.HeaderID = AD1.HeaderID AND AD10.LineNbr=10
	LEFT OUTER JOIN tblAcctDetail AS AD11 ON AD11.HeaderID = AD1.HeaderID AND AD11.LineNbr=11
	LEFT OUTER JOIN tblAcctDetail AS AD12 ON AD12.HeaderID = AD1.HeaderID AND AD12.LineNbr=12
	LEFT OUTER JOIN tblDoctor AS DR7 ON AD7.DrOpCode=DR7.DoctorCode
	LEFT OUTER JOIN tblDoctor AS DR8 ON AD8.DrOpCode=DR8.DoctorCode
	LEFT OUTER JOIN tblDoctor AS DR9 ON AD9.DrOpCode=DR9.DoctorCode
	LEFT OUTER JOIN tblDoctor AS DR10 ON AD10.DrOpCode=DR10.DoctorCode
	LEFT OUTER JOIN tblDoctor AS DR11 ON AD11.DrOpCode=DR11.DoctorCode
	LEFT OUTER JOIN tblDoctor AS DR12 ON AD12.DrOpCode=DR12.DoctorCode
	LEFT OUTER JOIN tblBlank AS B ON 1=1
	WHERE AD1.LineNbr=1
