CREATE VIEW vwRegisterTotal
AS
    SELECT  Casenbr ,
            HeaderID ,
            documenttype ,
            documentnbr ,
            ExamineeName ,
            DoctorName ,
            ClientCode ,
            CompanyCode ,
            ClientName ,
            CompanyName ,
            InvClientCode ,
            InvCompanyCode ,
            InvClientName ,
            InvCompanyName ,
            priority ,
            DateAdded ,
            Claimnbr ,
            DoctorLocation ,
            ApptTime ,
            DateEdited ,
            useridEdited ,
            adjusteremail ,
            adjusterFax ,
            marketerCode ,
            useridAdded ,
            documentDate ,
            INBatchSelect ,
            VOBatchSelect ,
            taxCode ,
            taxtotal ,
            documenttotal ,
            documentstatus ,
            batchnbr ,
            serviceCode ,
            officeCode ,
            DoctorCode ,
            apptDate ,
            Casetype , 
			ExtCaseNbr 
    FROM    vwAcctDocuments
