CREATE VIEW [dbo].[vwtblExaminee]
	AS 
	
	SELECT 
		ChartNbr                     	,
		OldChartNbr                  	,
		LastName                     	,
		FirstName                    	,
		MiddleInitial                	,
		Addr1                        	,
		Addr2                        	,
		City                         	,
		State                        	,
		Zip                          	,
		Phone1                       	,
		Phone2                       	,
		ISNULL(CONVERT(VARCHAR(15), DECRYPTBYKEYAUTOCERT(CERT_ID('IMEC_CLE_Certificate'), NULL, SSN_Encrypted)), 
		       SSN) AS SSN              ,
		Sex                          	,
		ISNULL(CONVERT(DATETIME, (CONVERT(VARCHAR, DECRYPTBYKEYAUTOCERT(CERT_ID('IMEC_CLE_Certificate'), NULL, DOB_Encrypted)))),
		       DOB) AS DOB              ,
		DateAdded                    	,
		DateEdited                   	,
		UserIDAdded                  	,
		UserIDEdited                 	,
		Note                         	,
		County                       	,
		Prefix                       	,
		USDVarchar1                  	,
		USDVarchar2                  	,
		USDDate1                     	,
		USDDate2                     	,
		USDText1                     	,
		USDText2                     	,
		USDInt1                      	,
		USDInt2                      	,
		USDMoney1                    	,
		USDMoney2                    	,
		Fax                          	,
		Email,
		Insured                      	,
		Employer                     	,
		TreatingPhysician            	,
		InsuredAddr1                 	,
		InsuredCity                  	,
		InsuredState                 	,
		InsuredZip                   	,
		InsuredSex                   	,
		InsuredRelationship          	,
		InsuredPhone                 	,
		InsuredPhoneExt              	,
		InsuredFax                   	,
		InsuredEmail                 	,
		ExamineeStatus               	,
		TreatingPhysicianAddr1       	,
		TreatingPhysicianCity        	,
		TreatingPhysicianState       	,
		TreatingPhysicianZip         	,
		TreatingPhysicianPhone       	,
		TreatingPhysicianPhoneExt    	,
		TreatingPhysicianFax         	,
		TreatingPhysicianEmail       	,
		EmployerAddr1                	,
		EmployerCity                 	,
		EmployerState                	,
		EmployerZip                  	,
		EmployerPhone                	,
		EmployerPhoneExt             	,
		EmployerFax                  	,
		EmployerEmail                	,
		Country                      	,
		PolicyNumber                 	,
		EmployerContactFirstName     	,
		EmployerContactLastName      	,
		TreatingPhysicianLicenseNbr  	,
		TreatingPhysicianTaxID       	,
		TreatingPhysicianCredentials 	,
		TreatingPhysicianDiagnosis   	,
		MobilePhone	                    ,
		TreatingPhysicianNPINbr       	,
		WorkPhone	
	FROM tblExaminee
