CREATE TABLE [dbo].[tblCaseDocumentsDicom] (
    [CaseDocDicomID]        INT           IDENTITY (1, 1) NOT NULL,
    [CaseNbr]               INT           NOT NULL,
    [CaseDocID]             INT           NOT NULL,
    [MediaType]             VARCHAR (100) NULL,
    [DiscID]                VARCHAR (100) NULL,
    [PatientName]           VARCHAR (200) NULL,
    [PatientId]             VARCHAR (200) NULL,
    [PatientBirthDate]      VARCHAR (50)  NULL,
    [PatientSex]            VARCHAR (50)  NULL,
    [StudyDate]             VARCHAR (50)  NULL,
    [StudyTime]             VARCHAR (50)  NULL,
    [StudyDescription]      VARCHAR (500) NULL,
    [StudyUID]              VARCHAR (200) NULL,
    [StudyID]               VARCHAR (200) NULL,
    [StudyDirRecType]       VARCHAR (100) NULL,
    [Modality]              VARCHAR (50)  NULL,
    [InstitutionName]       VARCHAR (200) NULL,
    [IsValidatedFileExists] BIT           CONSTRAINT [DF_tblCaseDocumentsDicom_IsValidatedFileExists] DEFAULT ((0)) NOT NULL,
    [IsValidatedBinary]     BIT           CONSTRAINT [DF_tblCaseDocumentsDicom_IsValidatedBinary] DEFAULT ((0)) NOT NULL,
    [FlagForUse]            BIT           CONSTRAINT [DF_tblCaseDocumentsDicom_FlagForUse] DEFAULT ((0)) NOT NULL,
    [ImportedOn]            DATETIME      NULL,
    [ImportedBy]            VARCHAR (50)  NULL,
    [Images]                INT           CONSTRAINT [DF_tblCaseDocumentsDicom_Images] DEFAULT ((0)) NOT NULL,
    [ImagesValidated]       INT           CONSTRAINT [DF_tblCaseDocumentsDicom_ImagesValidated] DEFAULT ((0)) NOT NULL,
    [ImagesExist]           INT           CONSTRAINT [DF_tblCaseDocumentsDicom_ImagesExist] DEFAULT ((0)) NOT NULL,
    [StorageID]             INT           NULL,
    CONSTRAINT [PK_tblCaseDocumentsDicom] PRIMARY KEY CLUSTERED ([CaseDocDicomID] ASC)
);

