CREATE TABLE [dbo].[tblDoctorScheduleSummary] (
    [Username]  NVARCHAR (20) NULL,
    [RecID]     INT           IDENTITY (1, 1) NOT NULL,
    [Weekof]    DATETIME      NULL,
    [RowNbr]    INT           NULL,
    [MonDate]   DATETIME      NULL,
    [MonDoc]    NVARCHAR (25) NULL,
    [MonSched]  INT           NULL,
    [MonFull]   INT           NULL,
    [TueDate]   DATETIME      NULL,
    [TueDoc]    NVARCHAR (25) NULL,
    [TueSched]  INT           NULL,
    [TueFull]   INT           NULL,
    [WedDate]   DATETIME      NULL,
    [WedDoc]    NVARCHAR (25) NULL,
    [WedSched]  INT           NULL,
    [WedFull]   INT           NULL,
    [ThuDate]   DATETIME      NULL,
    [ThuDoc]    NVARCHAR (25) NULL,
    [ThuSched]  INT           NULL,
    [ThuFull]   INT           NULL,
    [FriDate]   DATETIME      NULL,
    [FriDoc]    NVARCHAR (25) NULL,
    [FriSched]  INT           NULL,
    [FriFull]   INT           NULL,
    [SatDate]   DATETIME      NULL,
    [SatDoc]    NVARCHAR (25) NULL,
    [SatSched]  INT           NULL,
    [SatFull]   INT           NULL,
    [WeekSched] INT           NULL,
    [WeekFull]  INT           NULL,
    CONSTRAINT [PK_tblDoctorScheduleSummary] PRIMARY KEY CLUSTERED ([RecID] ASC)
);

