CREATE TABLE [dbo].[tblEWClient] (
    [EWClientID]               INT          NOT NULL,
    [EWCompanyID]              INT          NOT NULL,
    [LastName]                 VARCHAR (50) NULL,
    [FirstName]                VARCHAR (50) NULL,
    [Title]                    VARCHAR (50) NULL,
    [Prefix]                   VARCHAR (10) NULL,
    [Suffix]                   VARCHAR (50) NULL,
    [Addr1]                    VARCHAR (50) NULL,
    [Addr2]                    VARCHAR (50) NULL,
    [City]                     VARCHAR (50) NULL,
    [State]                    VARCHAR (2)  NULL,
    [Zip]                      VARCHAR (10) NULL,
    [Country]                  VARCHAR (50) NULL,
    [Phone1]                   VARCHAR (15) NULL,
    [Phone1Ext]                VARCHAR (15) NULL,
    [Phone2]                   VARCHAR (15) NULL,
    [Phone2Ext]                VARCHAR (15) NULL,
    [Fax]                      VARCHAR (15) NULL,
    [Email]                    VARCHAR (70) NULL,
    [Status]                   VARCHAR (10) NULL,
    [TypeCode]                 INT          NULL,
    [DateAdded]                DATETIME     NULL,
    [UserIDAdded]              VARCHAR (15) NULL,
    [DateEdited]               DATETIME     NULL,
    [UserIDEdited]             VARCHAR (15) NULL,
    [BillAddr1]                VARCHAR (50) NULL,
    [BillAddr2]                VARCHAR (50) NULL,
    [BillCity]                 VARCHAR (50) NULL,
    [BillState]                VARCHAR (2)  NULL,
    [BillZip]                  VARCHAR (10) NULL,
    [BillAttn]                 VARCHAR (70) NULL,
    [IsUnknown]                BIT          CONSTRAINT [DF_tblEWClient_IsUnknown] DEFAULT ((0)) NOT NULL,
    [UseNotificationOverrides] BIT          NULL,
    CONSTRAINT [PK_tblEWClient] PRIMARY KEY CLUSTERED ([EWClientID] ASC)
);

