CREATE TABLE [dbo].[tblWebReferral](
	[WebReferralID] [int] IDENTITY(1,1) NOT NULL,
	[CaseNbr] [int] NULL,
	[ClaimNbr] [varchar](50) NULL,
	[ClaimNbrExt] [varchar](50) NULL,
	[ClientCode] [int] NULL,
	[ClientName] [varchar](100) NULL,
	[ServiceType] [int] NULL,
	[ServiceDesc] [varchar](max) NULL,
	[CaseType] [int] NULL,
	[CaseTypeDesc] [varchar](max) NULL,
	[Jurisdiction] [varchar](5) NULL,
	[RequestedVenue] [varchar](50) NULL,
	[DateOfInjury1] [datetime] NULL,
	[DateOfInjury2] [datetime] NULL,
	[DateOfInjury3] [datetime] NULL,
	[DateOfInjury4] [datetime] NULL,
	[WCBNbr] [varchar](50) NULL,
	[IMETimeframeReq] [varchar](30) NULL,
	[HearingDeadlineDate] [datetime] NULL,
	[AmendedRequest] [bit] NOT NULL,
	[ContactAttorney] [bit] NOT NULL,
	[ContactClaimant] [bit] NOT NULL,
	[ClaimantLocations] [varchar](500) NULL,
	[ExamineePrefix] [varchar](10) NULL,
	[ExamineeFirstName] [varchar](50) NULL,
	[ExamineeLastName] [varchar](50) NULL,
	[ExamineeDOB] [datetime] NULL,
	[ExamineeAddress1] [varchar](50) NULL,
	[ExamineeAddress2] [varchar](50) NULL,
	[ExamineeCity] [varchar](70) NULL,
	[ExamineeState] [varchar](5) NULL,
	[ExamineeZip] [varchar](10) NULL,
	[ExamineePhone1] [varchar](15) NULL,
	[ExamineePhone2] [varchar](15) NULL,
	[ExamineeMobilePhone] [varchar](15) NULL,
	[ExamineeFax] [varchar](15) NULL,
	[ExamineeEmail] [varchar](100) NULL,
	[ExamineeSSN] [varchar](15) NULL,
	[ExamineeGender] [varchar](10) NULL,
	[TreatingPhysicianName] [varchar](100) NULL,
	[TreatingPhysicianAddress1] [varchar](80) NULL,
	[TreatingPhysicianCity] [varchar](70) NULL,
	[TreatingPhysicianState] [varchar](5) NULL,
	[TreatingPhysicianZip] [varchar](10) NULL,
	[TreatingPhysicianPhone1] [varchar](15) NULL,
	[TreatingPhysicianPhone2] [varchar](15) NULL,
	[TreatingPhysicianFax] [varchar](15) NULL,
	[TreatingPhysicianEmail] [varchar](100) NULL,
	[ProviderName] [varchar](100) NULL,
	[MedicalRecordStatus] [varchar](30) NULL,
	[InterpreterRequired] [bit] NOT NULL,
	[LanguageRequired] [bit] NOT NULL,
	[Language] [varchar](50) NULL,
	[TransportationRequired] [bit] NOT NULL,
	[SendBillToContactName] [varchar](100) NULL,
	[SendBillToCompanyName] [varchar](100) NULL,
	[Issues] [varchar](max) NULL,
	[IssueDescriptions] [varchar](max) NULL,
	[Problems] [varchar](max) NULL,
	[ProblemDescriptions] [varchar](max) NULL,
	[Specialties] [varchar](max) NULL,
	[Degrees] [varchar](max) NULL,
	[DegreeDescriptions] [varchar](max) NULL,
	[SpecialInstructions] [varchar](max) NULL,
	[OtherComments] [varchar](max) NULL,
	[PlaintiffAttorneyPrefix] [varchar](10) NULL,
	[PlaintiffAttorneyFirstName] [varchar](50) NULL,
	[PlaintiffAttorneyLastName] [varchar](50) NULL,
	[PlaintiffAttorneyCompany] [varchar](100) NULL,
	[PlaintiffAttorneyAddress1] [varchar](50) NULL,
	[PlaintiffAttorneyAddress2] [varchar](50) NULL,
	[PlaintiffAttorneyCity] [varchar](70) NULL,
	[PlaintiffAttorneyState] [varchar](5) NULL,
	[PlaintiffAttorneyZip] [varchar](10) NULL,
	[PlaintiffAttorneyPhone1] [varchar](15) NULL,
	[PlaintiffAttorneyPhone2] [varchar](15) NULL,
	[PlaintiffAttorneyFax] [varchar](15) NULL,
	[PlaintiffAttorneyEmail] [varchar](100) NULL,
	[DefenseAttorneyPrefix] [varchar](10) NULL,
	[DefenseAttorneyFirstName] [varchar](50) NULL,
	[DefenseAttorneyLastName] [varchar](50) NULL,
	[DefenseAttorneyCompany] [varchar](100) NULL,
	[DefenseAttorneyAddress1] [varchar](50) NULL,
	[DefenseAttorneyAddress2] [varchar](50) NULL,
	[DefenseAttorneyCity] [varchar](70) NULL,
	[DefenseAttorneyState] [varchar](5) NULL,
	[DefenseAttorneyZip] [varchar](10) NULL,
	[DefenseAttorneyPhone1] [varchar](15) NULL,
	[DefenseAttorneyPhone2] [varchar](15) NULL,
	[DefenseAttorneyFax] [varchar](15) NULL,
	[DefenseAttorneyEmail] [varchar](100) NULL,
	[CaseManagerPrefix] [varchar](10) NULL,
	[CaseManagerFirstName] [varchar](50) NULL,
	[CaseManagerLastName] [varchar](50) NULL,
	[CaseManagerCompany] [varchar](100) NULL,
	[CaseManagerAddress1] [varchar](50) NULL,
	[CaseManagerAddress2] [varchar](50) NULL,
	[CaseManagerCity] [varchar](70) NULL,
	[CaseManagerState] [varchar](5) NULL,
	[CaseManagerZip] [varchar](10) NULL,
	[CaseManagerPhone1] [varchar](15) NULL,
	[CaseManagerPhone2] [varchar](15) NULL,
	[CaseManagerFax] [varchar](15) NULL,
	[CaseManagerEmail] [varchar](100) NULL,
	[ClaimantEmployerCompany] [varchar](100) NULL,
	[ClaimantEmployerFirstName] [varchar](50) NULL,
	[ClaimantEmployerLastName] [varchar](50) NULL,
	[ClaimantEmployerAddress1] [varchar](50) NULL,
	[ClaimantEmployerCity] [varchar](70) NULL,
	[ClaimantEmployerState] [varchar](5) NULL,
	[ClaimantEmployerZip] [varchar](10) NULL,
	[ClaimantEmployerPhone1] [varchar](15) NULL,
	[ClaimantEmployerPhone2] [varchar](15) NULL,
	[ClaimantEmployerFax] [varchar](15) NULL,
	[ClaimantEmployerEmail] [varchar](100) NULL,
	[InsuringCompany] [varchar](50) NULL,
	[InsuredName] [varchar](100) NULL,
	[InsuredAddress1] [varchar](50) NULL,
	[InsuredCity] [varchar](70) NULL,
	[InsuredState] [varchar](5) NULL,
	[InsuredZip] [varchar](10) NULL,
	[InsuredPhone1] [varchar](15) NULL,
	[InsuredPhone2] [varchar](15) NULL,
	[InsuredFax] [varchar](15) NULL,
	[InsuredEmail] [varchar](100) NULL,
	[InsuredPolicyNumber] [varchar](50) NULL,
	[ThirdPartyBillingPrefix] [varchar](10) NULL,
	[ThirdPartyBillingFirstName] [varchar](50) NULL,
	[ThirdPartyBillingLastName] [varchar](50) NULL,
	[ThirdPartyBillingCompany] [varchar](100) NULL,
	[ThirdPartyBillingAddress1] [varchar](50) NULL,
	[ThirdPartyBillingAddress2] [varchar](50) NULL,
	[ThirdPartyBillingCity] [varchar](70) NULL,
	[ThirdPartyBillingState] [varchar](5) NULL,
	[ThirdPartyBillingZip] [varchar](10) NULL,
	[ThirdPartyBillingPhone1] [varchar](15) NULL,
	[ThirdPartyBillingPhone2] [varchar](15) NULL,
	[ThirdPartyBillingFax] [varchar](15) NULL,
	[ThirdPartyBillingEmail] [varchar](100) NULL,
	[OtherPartyAddressType] [varchar](50) NULL,
	[OtherPartyCompanyName] [varchar](100) NULL,
	[OtherPartyFirstName] [varchar](50) NULL,
	[OtherPartyLastName] [varchar](50) NULL,
	[OtherPartyAddress1] [varchar](50) NULL,
	[OtherPartyAddress2] [varchar](50) NULL,
	[OtherPartyCity] [varchar](70) NULL,
	[OtherPartyState] [varchar](5) NULL,
	[OtherPartyZip] [varchar](10) NULL,
	[OtherPartyPhone1] [varchar](15) NULL,
	[OtherPartyPhone2] [varchar](15) NULL,
	[OtherPartyFax] [varchar](15) NULL,
	[OtherPartyEmail] [varchar](100) NULL,
	[SendToOtherParty] [varchar](max) NULL,
	[ICDCode1] [varchar](70) NULL,
	[ICDStatus1] [varchar](20) NULL,
	[ICDBodySide1] [varchar](20) NULL,
	[ICDDescription1] [varchar](100) NULL,
	[ICDCode2] [varchar](70) NULL,
	[ICDStatus2] [varchar](20) NULL,
	[ICDBodySide2] [varchar](20) NULL,
	[ICDDescription2] [varchar](100) NULL,
	[ICDCode3] [varchar](70) NULL,
	[ICDStatus3] [varchar](20) NULL,
	[ICDBodySide3] [varchar](20) NULL,
	[ICDDescription3] [varchar](100) NULL,
	[ICDCode4] [varchar](70) NULL,
	[ICDStatus4] [varchar](20) NULL,
	[ICDBodySide4] [varchar](20) NULL,
	[ICDDescription4] [varchar](100) NULL,
	[PreviousClaimsClaimNbr1] [varchar](50) NULL,
	[PreviousClaimsPPDAward1] [varchar](30) NULL,
	[PreviousClaimsMajorBodyPart1] [varchar](50) NULL,
	[PreviousClaimsMinorBodyPart1] [varchar](50) NULL,
	[PreviousClaimsBodySide1] [varchar](50) NULL,
	[Notes] [varchar](max) NULL,
	[AttorneyNote] [varchar](max) NULL,
	[ScheduleNotes] [varchar](max) NULL,
	[BillingNote] [varchar](max) NULL,
	[OfficeCode] [int] NULL,
	[OfficeDesc] [varchar](100) NULL,
	[RecCode] [int] NULL,
	[RecDesc] [varchar](100) NULL,
	[QARep] [varchar](50) NULL,
	[Status] [int] NULL,
	[StatusDesc] [varchar](100) NULL,
	[SchedCode] [int] NULL,
	[ReportVerbal] [bit] NOT NULL,
	[PhotoRqd] [bit] NOT NULL,
	[CertifiedMail] [bit] NOT NULL,
	[HearingDate] [datetime] NULL,
	[ApptDate] [datetime] NULL,
	[ApptTime] [datetime] NULL,
	[ApptMadeDate] [datetime] NULL,
	[ApptStatusId] [int] NULL,
	[CaseApptId] [int] NULL,
	[CommitDate] [datetime] NULL,
	[DateReceived] [datetime] NULL,
	[DateAcknowledged] [datetime] NULL,
	[DateAdded] [datetime] NULL,
	[UserIdAdded] [varchar](50) NULL,
	[DateEdited] [datetime] NULL,
	[UserIdEdited] [varchar](50) NULL,
	[MedicalRecordStatusDesc] [varchar](100) NULL,
	[WebReferralFormName] VARCHAR(255) NULL, 
    CONSTRAINT [PK_tblWebReferral] PRIMARY KEY CLUSTERED 
(
	[WebReferralID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[tblWebReferral] ADD  CONSTRAINT [DF_tblWebReferral_AmendedRequest]  DEFAULT ((0)) FOR [AmendedRequest]
GO

ALTER TABLE [dbo].[tblWebReferral] ADD  CONSTRAINT [DF_tblWebReferral_ContactAttorney]  DEFAULT ((0)) FOR [ContactAttorney]
GO

ALTER TABLE [dbo].[tblWebReferral] ADD  CONSTRAINT [DF_tblWebReferral_ContactClaimant]  DEFAULT ((0)) FOR [ContactClaimant]
GO

ALTER TABLE [dbo].[tblWebReferral] ADD  CONSTRAINT [DF_tblWebReferral_InterpreterNeeded]  DEFAULT ((0)) FOR [InterpreterRequired]
GO

ALTER TABLE [dbo].[tblWebReferral] ADD  CONSTRAINT [DF_tblWebReferral_InterpreterNeeded1]  DEFAULT ((0)) FOR [LanguageRequired]
GO

ALTER TABLE [dbo].[tblWebReferral] ADD  CONSTRAINT [DF_tblWebReferral_TransportationNeeded]  DEFAULT ((0)) FOR [TransportationRequired]
GO

ALTER TABLE [dbo].[tblWebReferral] ADD  CONSTRAINT [DF_tblWebReferral_ReportVerbal]  DEFAULT ((0)) FOR [ReportVerbal]
GO

ALTER TABLE [dbo].[tblWebReferral] ADD  CONSTRAINT [DF_tblWebReferral_PhotoRqd]  DEFAULT ((0)) FOR [PhotoRqd]
GO

ALTER TABLE [dbo].[tblWebReferral] ADD  CONSTRAINT [DF_tblWebReferral_CertifiedMail]  DEFAULT ((0)) FOR [CertifiedMail]
GO

