CREATE VIEW vwPDFInvDetData3
AS
	SELECT	

			AD13.LineNbr AS InvLineNbr13 ,
	        AD13.Date AS InvServiceDate13 ,
			B.BlankValue AS InvServiceDate13MM,
			B.BlankValue AS InvServiceDate13DD,
			B.BlankValue AS InvServiceDate13YY,
			B.BlankValue AS InvServiceDateTo13MM,
			B.BlankValue AS InvServiceDateTo13DD,
			B.BlankValue AS InvServiceDateTo13YY,
	        AD13.CPTCode AS InvCPT13,
	        AD13.Modifier AS InvModifier13,
	        AD13.Modifier2 AS InvModifier13b ,
	        AD13.Modifier3 AS InvModifier13c ,
	        AD13.Modifier4 AS InvModifier13d ,
			B.BlankValue AS InvICD13,
			B.BlankValue AS InvDiagnosisPointer13,
	        AD13.Location AS InvPlaceOfService13,
			'2' AS InvTypeOfService13,
	        AD13.SuppInfo AS SupplementalInfo13,
	        AD13.Unit AS InvUnit13,
	        AD13.ExtendedAmount AS InvDetAmt13,
			AD13.RetailAmount AS InvRetailAmt13,
	        B.BlankValue AS InvDetAmt13Dollars,
			B.BlankValue AS InvDetAmt13Cents,
	        B.BlankValue AS InvDetAmt13bDollars,
			B.BlankValue AS InvDetAmt13bCents,
			AD13.DrOpCode AS DrOpCode13,
			DR13.NPINbr AS DoctorNPINbr13,


			AD14.LineNbr AS InvLineNbr14 ,
	        AD14.Date AS InvServiceDate14 ,
			B.BlankValue AS InvServiceDate14MM,
			B.BlankValue AS InvServiceDate14DD,
			B.BlankValue AS InvServiceDate14YY,
			B.BlankValue AS InvServiceDateTo14MM,
			B.BlankValue AS InvServiceDateTo14DD,
			B.BlankValue AS InvServiceDateTo14YY,
	        AD14.CPTCode AS InvCPT14,
	        AD14.Modifier AS InvModifier14,
	        AD14.Modifier2 AS InvModifier14b ,
	        AD14.Modifier3 AS InvModifier14c ,
	        AD14.Modifier4 AS InvModifier14d ,
			B.BlankValue AS InvICD14,
			B.BlankValue AS InvDiagnosisPointer14,
	        AD14.Location AS InvPlaceOfService14,
			'2' AS InvTypeOfService14,
	        AD14.SuppInfo AS SupplementalInfo14,
	        AD14.Unit AS InvUnit14,
	        AD14.ExtendedAmount AS InvDetAmt14,
			AD14.RetailAmount AS InvRetailAmt14,
	        B.BlankValue AS InvDetAmt14Dollars,
			B.BlankValue AS InvDetAmt14Cents,
	        B.BlankValue AS InvDetAmt14bDollars,
			B.BlankValue AS InvDetAmt14bCents,
			AD14.DrOpCode AS DrOpCode14,
			DR14.NPINbr AS DoctorNPINbr14,


			AD15.LineNbr AS InvLineNbr15 ,
	        AD15.Date AS InvServiceDate15 ,
			B.BlankValue AS InvServiceDate15MM,
			B.BlankValue AS InvServiceDate15DD,
			B.BlankValue AS InvServiceDate15YY,
			B.BlankValue AS InvServiceDateTo15MM,
			B.BlankValue AS InvServiceDateTo15DD,
			B.BlankValue AS InvServiceDateTo15YY,
	        AD15.CPTCode AS InvCPT15,
	        AD15.Modifier AS InvModifier15,
	        AD15.Modifier2 AS InvModifier15b ,
	        AD15.Modifier3 AS InvModifier15c ,
	        AD15.Modifier4 AS InvModifier15d ,
			B.BlankValue AS InvICD15,
			B.BlankValue AS InvDiagnosisPointer15,
	        AD15.Location AS InvPlaceOfService15,
			'2' AS InvTypeOfService15,
	        AD15.SuppInfo AS SupplementalInfo15,
	        AD15.Unit AS InvUnit15,
	        AD15.ExtendedAmount AS InvDetAmt15,
			AD15.RetailAmount AS InvRetailAmt15,
	        B.BlankValue AS InvDetAmt15Dollars,
			B.BlankValue AS InvDetAmt15Cents,
	        B.BlankValue AS InvDetAmt15bDollars,
			B.BlankValue AS InvDetAmt15bCents,
			AD15.DrOpCode AS DrOpCode15,
			DR15.NPINbr AS DoctorNPINbr15,


			AD16.LineNbr AS InvLineNbr16 ,
	        AD16.Date AS InvServiceDate16 ,
			B.BlankValue AS InvServiceDate16MM,
			B.BlankValue AS InvServiceDate16DD,
			B.BlankValue AS InvServiceDate16YY,
			B.BlankValue AS InvServiceDateTo16MM,
			B.BlankValue AS InvServiceDateTo16DD,
			B.BlankValue AS InvServiceDateTo16YY,
	        AD16.CPTCode AS InvCPT16,
	        AD16.Modifier AS InvModifier16,
	        AD16.Modifier2 AS InvModifier16b ,
	        AD16.Modifier3 AS InvModifier16c ,
	        AD16.Modifier4 AS InvModifier16d ,
			B.BlankValue AS InvICD16,
			B.BlankValue AS InvDiagnosisPointer16,
	        AD16.Location AS InvPlaceOfService16,
			'2' AS InvTypeOfService16,
	        AD16.SuppInfo AS SupplementalInfo16,
	        AD16.Unit AS InvUnit16,
	        AD16.ExtendedAmount AS InvDetAmt16,
			AD16.RetailAmount AS InvRetailAmt16,
	        B.BlankValue AS InvDetAmt16Dollars,
			B.BlankValue AS InvDetAmt16Cents,
	        B.BlankValue AS InvDetAmt16bDollars,
			B.BlankValue AS InvDetAmt16bCents,
			AD16.DrOpCode AS DrOpCode16,
			DR16.NPINbr AS DoctorNPINbr16,


			AD17.LineNbr AS InvLineNbr17 ,
	        AD17.Date AS InvServiceDate17 ,
			B.BlankValue AS InvServiceDate17MM,
			B.BlankValue AS InvServiceDate17DD,
			B.BlankValue AS InvServiceDate17YY,
			B.BlankValue AS InvServiceDateTo17MM,
			B.BlankValue AS InvServiceDateTo17DD,
			B.BlankValue AS InvServiceDateTo17YY,
	        AD17.CPTCode AS InvCPT17,
	        AD17.Modifier AS InvModifier17,
	        AD17.Modifier2 AS InvModifier17b ,
	        AD17.Modifier3 AS InvModifier17c ,
	        AD17.Modifier4 AS InvModifier17d ,
			B.BlankValue AS InvICD17,
			B.BlankValue AS InvDiagnosisPointer17,
	        AD17.Location AS InvPlaceOfService17,
			'2' AS InvTypeOfService17,
	        AD17.SuppInfo AS SupplementalInfo17,
	        AD17.Unit AS InvUnit17,
	        AD17.ExtendedAmount AS InvDetAmt17,
			AD17.RetailAmount AS InvRetailAmt17,
	        B.BlankValue AS InvDetAmt17Dollars,
			B.BlankValue AS InvDetAmt17Cents,
	        B.BlankValue AS InvDetAmt17bDollars,
			B.BlankValue AS InvDetAmt17bCents,
			AD17.DrOpCode AS DrOpCode17,
			DR17.NPINbr AS DoctorNPINbr17,


			AD18.LineNbr AS InvLineNbr18 ,
	        AD18.Date AS InvServiceDate18 ,
			B.BlankValue AS InvServiceDate18MM,
			B.BlankValue AS InvServiceDate18DD,
			B.BlankValue AS InvServiceDate18YY,
			B.BlankValue AS InvServiceDateTo18MM,
			B.BlankValue AS InvServiceDateTo18DD,
			B.BlankValue AS InvServiceDateTo18YY,
	        AD18.CPTCode AS InvCPT18,
	        AD18.Modifier AS InvModifier18,
	        AD18.Modifier2 AS InvModifier18b ,
	        AD18.Modifier3 AS InvModifier18c ,
	        AD18.Modifier4 AS InvModifier18d ,
			B.BlankValue AS InvICD18,
			B.BlankValue AS InvDiagnosisPointer18,
	        AD18.Location AS InvPlaceOfService18,
			'2' AS InvTypeOfService18,
	        AD18.SuppInfo AS SupplementalInfo18,
	        AD18.Unit AS InvUnit18,
	        AD18.ExtendedAmount AS InvDetAmt18,
			AD18.RetailAmount AS InvRetailAmt18,
	        B.BlankValue AS InvDetAmt18Dollars,
			B.BlankValue AS InvDetAmt18Cents,
	        B.BlankValue AS InvDetAmt18bDollars,
			B.BlankValue AS InvDetAmt18bCents,
			AD18.DrOpCode AS DrOpCode18,
			DR18.NPINbr AS DoctorNPINbr18,

			B.BlankValue AS InvICDDiagnosisPointer,
			AD1.HeaderID AS InvDetHeaderID


	FROM	tblAcctDetail AS AD1
	LEFT OUTER JOIN tblAcctDetail AS AD13 ON AD13.HeaderID = AD1.HeaderID AND AD13.LineNbr=13
	LEFT OUTER JOIN tblAcctDetail AS AD14 ON AD14.HeaderID = AD1.HeaderID AND AD14.LineNbr=14
	LEFT OUTER JOIN tblAcctDetail AS AD15 ON AD15.HeaderID = AD1.HeaderID AND AD15.LineNbr=15
	LEFT OUTER JOIN tblAcctDetail AS AD16 ON AD16.HeaderID = AD1.HeaderID AND AD16.LineNbr=16
	LEFT OUTER JOIN tblAcctDetail AS AD17 ON AD17.HeaderID = AD1.HeaderID AND AD17.LineNbr=17
	LEFT OUTER JOIN tblAcctDetail AS AD18 ON AD18.HeaderID = AD1.HeaderID AND AD18.LineNbr=18
	LEFT OUTER JOIN tblDoctor AS DR13 ON AD13.DrOpCode=DR13.DoctorCode
	LEFT OUTER JOIN tblDoctor AS DR14 ON AD14.DrOpCode=DR14.DoctorCode
	LEFT OUTER JOIN tblDoctor AS DR15 ON AD15.DrOpCode=DR15.DoctorCode
	LEFT OUTER JOIN tblDoctor AS DR16 ON AD16.DrOpCode=DR16.DoctorCode
	LEFT OUTER JOIN tblDoctor AS DR17 ON AD17.DrOpCode=DR17.DoctorCode
	LEFT OUTER JOIN tblDoctor AS DR18 ON AD18.DrOpCode=DR18.DoctorCode
	LEFT OUTER JOIN tblBlank AS B ON 1=1
	WHERE AD1.LineNbr=1