CREATE TABLE [dbo].[tblControl] (
    [InstallID]                INT              NOT NULL,
    [PGMVersion]               VARCHAR (15)     NULL,
    [DateAdded]                DATETIME         NULL,
    [UserIDAdded]              VARCHAR (30)     NULL,
    [DateEdited]               DATETIME         NULL,
    [UserIDEdited]             VARCHAR (30)     NULL,
    [PanelNbr]                 INT              NULL,
    [UseSecureDocs]            BIT              NULL,
    [SecureDocsGUID]           VARCHAR (70)     NULL,
    [SecureDocsURL]            VARCHAR (100)    NULL,
    [SecureDocsPrompt]         BIT              NULL,
    [SecureDocsRetention]      INT              CONSTRAINT [DF_tblControl_SecureDocsRetention] DEFAULT (28) NULL,
    [SecureDocsNotify]         BIT              CONSTRAINT [DF_tblControl_SecureDocsNotify] DEFAULT ((-1)) NULL,
    [UseWebPortal]             BIT              NULL,
    [WebGUID]                  UNIQUEIDENTIFIER NULL,
    [Custom]                   VARCHAR (50)     NULL,
    [FacilityID]               VARCHAR (20)     NULL,
    [IsTestSystem]             BIT              CONSTRAINT [DF_tblControl_IsTestSystem] DEFAULT ((0)) NULL,
    [AppTitle]                 VARCHAR (40)     NULL,
    [DBVersion]                VARCHAR (15)     NULL,
    [UseScheduleViewer]        BIT              CONSTRAINT [DF_tblControl_UseScheduleViewer] DEFAULT ((0)) NULL,
    [EWServiceAddress]         VARCHAR (50)     NULL,
    [EWServiceBinding]         VARCHAR (30)     NULL,
    [DBID]                     INT              NULL,
    [OffsetHours]              INT              NULL,
    [NDB]                      BIT              NULL,
    [DistributeRptBCC]         VARCHAR (70)     NULL,
    [PortalMasterDBID]         INT              NULL,
    [GPDBID]                   INT              NULL,
    [MaintenanceMode]          BIT              CONSTRAINT [DF_tblControl_MaintenanceMode] DEFAULT ((0)) NOT NULL,
    [EmailCapability]          BIT              NULL,
    [FaxCapability]            BIT              NULL,
    [FaxServerType]            VARCHAR (10)     NULL,
    [LabelCapability]          BIT              NULL,
    [TranscriptionCapability]  BIT              NULL,
    [CountryID]                INT              NULL,
    [BRqInternalCaseNbr]       BIT              CONSTRAINT [DF_tblControl_BRqInternalCaseNbr] DEFAULT ((0)) NULL,
    [CreateVouchers]           BIT              NULL,
    [CalcTaxOnVouchers]        BIT              NULL,
    [RequirePDF]               BIT              NULL,
    [AllowICD10]               BIT              NULL,
    [DefaultICDFormat]         INT              NULL,
    [UseHCAIInterface]         BIT              CONSTRAINT [DF_tblControl_UseHCAIInterface] DEFAULT ((0)) NOT NULL,
    [blnUseSubCases]           BIT              NULL,
    [NextInvoiceNbr]           INT              NULL,
    [NextVoucherNbr]           INT              NULL,
    [NextBatchNbr]             INT              NULL,
    [NextEDIBatchNbr]          INT              NULL,
    [ATSecurityProfileID]      INT              NULL,
    [CLSecurityProfileID]      INT              NULL,
    [DRSecurityProfileID]      INT              NULL,
    [OPSecurityProfileID]      INT              NULL,
    [TRSecurityProfileID]      INT              NULL,
    [ApptDuration]             INT              NULL,
    [MultiPortal]              BIT              NULL,
    [IncludeSubCaseOnMaster]   BIT              CONSTRAINT [DF_tblControl_IncludeSubCaseOnMaster] DEFAULT ((0)) NOT NULL,
    [WorkHourStart]            INT              NULL,
    [WorkHourEnd]              INT              NULL,
    [DrDocFolderID]            INT              NULL,
    [DirWebQuickReferralFiles] VARCHAR (70)     NULL,
    [DirTemplate]              VARCHAR (70)     NULL,
    [DirDirections]            VARCHAR (70)     NULL,
    [SourceDirectory]          VARCHAR (70)     NULL,
    [DirVoicePlayer]           VARCHAR (70)     NULL,
    [DirIMECentricHelper]      VARCHAR (70)     NULL,
    [CbxWaitInterval]          INT              NULL,
    [XMediusFaxPrefix]         VARCHAR (10)     NULL,
    [UseUDF]                   BIT              CONSTRAINT [DF_tblControl_UseUDF] DEFAULT ((0)) NOT NULL,
    [NewReferralStatusCode]    INT              CONSTRAINT [DF_tblControl_NewReferralStatusCode] DEFAULT ((10)) NOT NULL,
    [EWTimeZoneID]             INT              NULL,
    [MaintenanceAccessLevel]   INT              CONSTRAINT [DF_tblControl_MaintenanceAccessLevel] DEFAULT ((0)) NOT NULL,
    [SysTimerInterval]         INT              CONSTRAINT [DF_tblControl_SysTimerInterval] DEFAULT ((0)) NOT NULL,
    [ExitWaitInterval]         INT              CONSTRAINT [DF_tblControl_ExitWaitInterval] DEFAULT ((0)) NOT NULL,
    [SearchResultLimit]        INT              CONSTRAINT [DF_tblControl_SearchResultLimit] DEFAULT ((0)) NOT NULL,
    [UseNP]                    BIT              CONSTRAINT [DF_tblControl_UseNP] DEFAULT ((0)) NOT NULL,
    [AllowMigratingClaim]      BIT              CONSTRAINT [DF_tblControl_AllowMigratingClaim] DEFAULT ((0)) NOT NULL,
    [VendorGPEntityPrefix]     VARCHAR (3)      NULL,
    [DbTimeoutSec]             INT              CONSTRAINT [DF_tblControl_DbTimeoutSec] DEFAULT ((60)) NOT NULL,
    [CompanyNameStandard]      INT              NULL,
    [NextConfirmationBatchNbr] INT              NULL,
    [DPSUserID]                VARCHAR (50)     NULL,
    [DPSPassword]              VARCHAR (50)     NULL,
    [DPSFolderID]              INT              NULL,
    [DPSServiceAddress]        VARCHAR (100)    NULL,
    [LockTimeoutSec]           INT              NULL,
    [SettingCacheMin]          INT              NULL, 
    [UserCacheMin]             INT              NULL, 
    [SettingVersion]           INT              CONSTRAINT [DF_tblControl_SettingVersion] DEFAULT ((1)) NOT NULL, 
	[DASecurityProfileID]      INT              NULL,

    CONSTRAINT [PK_tblControl] PRIMARY KEY CLUSTERED ([InstallID] ASC)
);







