CREATE TABLE [dbo].[tblDocument] (
    [Document]                      VARCHAR (15)    NOT NULL,
    [Type]                          VARCHAR (10)    NOT NULL,
    [SubType]                       VARCHAR (50)    NULL,
    [Description]                   VARCHAR (50)    NULL,
    [sFilename]                     VARCHAR (50)    NULL,
    [EmailSubject]                  VARCHAR (120)   NULL,
    [EmailBody]                     TEXT            NULL,
    [FaxCover]                      VARCHAR (50)    NULL,
    [DocumentName]                  VARCHAR (10)    NULL,
    [DateAdded]                     DATETIME        NULL,
    [UserIDAdded]                   VARCHAR (20)    NULL,
    [DateEdited]                    DATETIME        NULL,
    [UserIDEdited]                  VARCHAR (20)    NULL,
    [Retention]                     INT             NULL,
    [CreateHistory]                 BIT             NULL,
    [AddressedTo]                   VARCHAR (20)    NULL,
    [NeverEmail]                    BIT             NULL,
    [NeverFax]                      BIT             NULL,
    [DefaultPrinter]                VARCHAR (50)    NULL,
    [DocumentDateFlag]              VARCHAR (1)     NULL,
    [PublishOnWeb]                  BIT             CONSTRAINT [DF_tblDocument_publishonweb] DEFAULT (0) NULL,
    [PublishAsPDF]                  BIT             CONSTRAINT [DF_tblDocument_PublishAsPDF] DEFAULT (0) NULL,
    [PublishedTo]                   VARCHAR (50)    NULL,
    [SeqNo]                         INT             IDENTITY (1, 1) NOT NULL,
    [blnAlwaysCreateAsPDF]          BIT             CONSTRAINT [DF_tblDocument_blnAlwaysCreateAsPDF] DEFAULT (0) NULL,
    [blnPDFWhenDistribute]          BIT             CONSTRAINT [DF_tblDocument_blnPDFWhenDistribute] DEFAULT (0) NULL,
    [blnWarnIfNoICDCodesEntered]    BIT             CONSTRAINT [DF_tblDocument_blnWarnIfNoICDCodesEntered] DEFAULT (0) NULL,
    [TemplateFormat]                VARCHAR (10)    NULL,
    [HideFormGraphics]              BIT             CONSTRAINT [DF_tblDocument_HideFormGraphics] DEFAULT ((0)) NULL,
    [OffsetX]                       FLOAT (53)      NULL,
    [OffsetY]                       FLOAT (53)      NULL,
    [FlattenFormFields]             BIT             NULL,
    [UsePDFReaderToPrint]           BIT             NULL,
    [OldKey]                        VARCHAR (15)    NULL,
    [FaxCoverDemographics]          INT             NULL,
    [FaxCoverPageID]                INT             NULL,
    [FaxEWFacilityID]               INT             NULL,
    [CMSDiscountPercentage]         NUMERIC (10, 2) NULL,
    [CMSPayor]                      VARCHAR (150)   NULL,
    [CMSBox10aYes]                  VARCHAR (30)    NULL,
    [CMSBox17]                      VARCHAR (30)    NULL,
    [CMSBox17a]                     VARCHAR (30)    NULL,
    [CMSBox17b]                     VARCHAR (30)    NULL,
    [CMSBox19]                      VARCHAR (50)    NULL,
    [CMSBox24JNonNPINbr]            VARCHAR (50)    NULL,
    [CMSBox24JNPINbr]               VARCHAR (30)    NULL,
    [CMSBox25]                      VARCHAR (20)    NULL,
    [CMSBox27Yes]                   VARCHAR (30)    NULL,
    [CMSBox31Line1]                 VARCHAR (100)   NULL,
    [CMSBox31Line2]                 VARCHAR (50)    NULL,
    [CMSBox32a]                     VARCHAR (30)    NULL,
    [CMSBox32b]                     VARCHAR (50)    NULL,
    [CMSBox33Line1]                 VARCHAR (45)    NULL,
    [CMSBox33Line2]                 VARCHAR (45)    NULL,
    [CMSBox33Line3]                 VARCHAR (45)    NULL,
    [CMSBox33AreaCode]              VARCHAR (30)    NULL,
    [CMSBox33PhoneNumber]           VARCHAR (30)    NULL,
    [CMSBox33a]                     VARCHAR (30)    NULL,
    [CMSBox33b]                     VARCHAR (30)    NULL,
    [CMSBox1a]                      VARCHAR (30)    NULL,
    [CMSBox4]                       VARCHAR (30)    NULL,
    [CMSBox7Address]                VARCHAR (30)    NULL,
    [CMSBox7City]                   VARCHAR (30)    NULL,
    [CMSBox7State]                  VARCHAR (30)    NULL,
    [CMSBox7Zip]                    VARCHAR (30)    NULL,
    [CMSBox7AreaCode]               VARCHAR (30)    NULL,
    [CMSBox7PhoneNumber]            VARCHAR (30)    NULL,
    [CMSBox10bNo]                   VARCHAR (30)    NULL,
    [CMSBox10bState]                VARCHAR (30)    NULL,
    [CMSBox10cNo]                   VARCHAR (30)    NULL,
    [CMSBox17aQual]                 VARCHAR (30)    NULL,
    [CMSBox24JNonNPIQual]           VARCHAR (30)    NULL,
    [PageScaling]                   INT             NULL,
    [Status]                        VARCHAR (10)    NULL,
    [CMSBox11]                      VARCHAR(30)     NULL, 
    [CMSBox9A]                      VARCHAR(30)     NULL, 
    [CMSBox23]                      VARCHAR(30)     NULL, 
	[CMSBox17Qual]				    VARCHAR(5)	    NULL,
    [UseMultipleExamineeAddressess] BIT             CONSTRAINT [DF_tblDocument_UseMultipleExamineeAddressess] DEFAULT (0) NULL, 
    [IsEnvelopeReady]               BIT             CONSTRAINT [DF_tblDocument_IsEnvelopeReady] DEFAULT ((0)) NOT NULL,
    [NotifyTo]						VARCHAR(50)		NULL, 
    [ExcludeFromPortalWidget]		VARCHAR(50)		NULL, 
	[EmailDocAsLink]                BIT             CONSTRAINT [DF_tblDocument_EmailDocAsLink] DEFAULT ((0)) NOT NULL,
	[DaysEmailLinkValid]            INT             NULL,
	[FunctionCode]                  VARCHAR(30)     NULL,
    [CMSBox12]                      VARCHAR(30)     NULL, 
    [CMSBox12Date]                  VARCHAR(30)     NULL, 
    [CMSBox13]                      VARCHAR(30)     NULL, 
    [CMSBox14Qual]                  VARCHAR(30)     NULL, 
    [CMSBox26]                      VARCHAR(30)     NULL, 
    [CMSLineItemAmtType]            VARCHAR(30)     NULL, 
	[CMSBox6Other]                  VARCHAR(30)     NULL, 
	[ShowProductDescOnClaimForm]	INT				CONSTRAINT [DF_tblDocument_ShowProductDescOnClaimForm] DEFAULT ((0)) NOT NULL,
    [ElecTransferFolderID]          INT             NULL,
	[ElecTransferOutputFile]        VARCHAR(128)    NULL,
	[ElecTransferDupFileHandling]   INT             NULL,
	CONSTRAINT [PK_tbldocument] PRIMARY KEY CLUSTERED ([SeqNo] ASC) WITH (FILLFACTOR = 90)
);

GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_U_tblDocument_Document]
    ON [dbo].[tblDocument]([Document] ASC);

