ALTER TABLE tblEWDrDocType
 ADD AllowPublishOnWeb BIT
GO


--Patch Data
UPDATE tblDoctor SET AddExceptionTriggered=1
GO
UPDATE tblcase SET RptFinalizedDate=DATEADD(dd, 0, DATEDIFF(dd, 0, RptFinalizedDate))
 WHERE RptFinalizedDate IS NOT NULL
UPDATE tblcase SET RptInitialDraftDate=DATEADD(dd, 0, DATEDIFF(dd, 0, RptInitialDraftDate))
 WHERE RptInitialDraftDate IS NOT NULL
UPDATE tblcase SET RptSentDate=DATEADD(dd, 0, DATEDIFF(dd, 0, RptSentDate))
 WHERE RptSentDate IS NOT NULL
GO

UPDATE tblCaseAppt SET DateReceived=DR
FROM tblCaseAppt INNER JOIN
(
SELECT CA.CaseApptID,
 CASE ROW_NUMBER() OVER (PARTITION BY CA.CaseNbr ORDER BY CA.CaseApptID)
  WHEN 1 THEN C.DateReceived
  ELSE CA.DateAdded
 END AS DR
 FROM tblCaseAppt AS CA
 INNER JOIN tblCase AS C ON CA.CaseNbr = C.CaseNbr
) AS appt ON tblCaseAppt.CaseApptID = appt.CaseApptID
GO
UPDATE tblCaseAppt SET DateReceived=DATEADD(dd, 0, DATEDIFF(dd, 0, DateReceived))
GO



--Update views for new fields

DROP VIEW vwCaseAppt
GO
CREATE VIEW vwCaseAppt
AS
WITH allDoctors AS (
		SELECT  
			CA.CaseApptID ,
			ISNULL(CA.DoctorCode, CAP.DoctorCode) AS DoctorCode,
			CASE WHEN CA.DoctorCode IS NULL THEN
			LTRIM(RTRIM(ISNULL(DP.FirstName,'')+' '+ISNULL(DP.LastName,'')+' '+ISNULL(DP.Credentials,'')))
			ELSE
			LTRIM(RTRIM(ISNULL(D.FirstName,'')+' '+ISNULL(D.LastName,'')+' '+ISNULL(D.Credentials,'')))
			END AS DoctorName,
			ISNULL(CA.SpecialtyCode, CAP.SpecialtyCode) AS SpecialtyCode
		 FROM tblCaseAppt AS CA
		 LEFT OUTER JOIN tblDoctor AS D ON CA.DoctorCode=D.DoctorCode
		 LEFT OUTER JOIN tblCaseApptPanel AS CAP ON CA.CaseApptID=CAP.CaseApptID
		 LEFT OUTER JOIN tblDoctor AS DP ON CAP.DoctorCode=DP.DoctorCode
)
SELECT  DISTINCT
		CA.CaseApptID ,
        CA.CaseNbr ,
        CA.ApptStatusID ,
        S.Name AS ApptStatus,

        CA.ApptTime ,
        CA.LocationCode ,
        L.Location,

        CA.CanceledByID ,
        CB.Name AS CanceledBy ,
        CA.Reason ,
        
        CA.DateAdded ,
        CA.UserIDAdded ,
        CA.DateEdited ,
        CA.UserIDEdited ,
        CA.LastStatusChg ,
        CAST(CASE WHEN CA.DoctorCode IS NULL THEN 1 ELSE 0 END AS BIT) AS IsPanel,
        (STUFF((
        SELECT '\'+ CAST(DoctorCode AS VARCHAR) FROM allDoctors WHERE AllDoctors.CaseApptID=CA.CaseApptID
		FOR XML PATH(''), TYPE, ROOT).value('root[1]', 'varchar(100)'),1,1,'')) AS DoctorCodes,
        (STUFF((
        SELECT '\'+DoctorName FROM allDoctors WHERE AllDoctors.CaseApptID=CA.CaseApptID
		FOR XML PATH(''), TYPE, ROOT).value('root[1]', 'varchar(300)'),1,1,'')) AS DoctorNames,
        (STUFF((
        SELECT '\'+ SpecialtyCode FROM allDoctors WHERE AllDoctors.CaseApptID=CA.CaseApptID
		FOR XML PATH(''), TYPE, ROOT).value('root[1]', 'varchar(300)'),1,1,'')) AS Specialties,
		CA.DateReceived
     FROM tblCaseAppt AS CA
     INNER JOIN tblApptStatus AS S ON CA.ApptStatusID = S.ApptStatusID
     LEFT OUTER JOIN tblCanceledBy AS CB ON CA.CanceledByID=CB.CanceledByID
     LEFT OUTER JOIN tblLocation AS L ON CA.LocationCode=L.LocationCode
GO


DROP VIEW vwDocument
GO
CREATE VIEW vwDocument
AS
    SELECT  tblCase.casenbr ,
            tblCase.claimnbr ,
            tblExaminee.addr1 AS examineeaddr1 ,
            tblExaminee.addr2 AS examineeaddr2 ,
            tblExaminee.city + ', ' + tblExaminee.state + '  '
            + tblExaminee.zip AS examineecitystatezip ,
            tblExaminee.SSN ,
            tblClient.firstname + ' ' + tblClient.lastname AS clientname ,
            tblCompany.extname AS company ,
            tblClient.phone1 + ' ' + ISNULL(tblClient.phone1ext, ' ') AS clientphone ,
            tblClient.phone2 + ' ' + ISNULL(tblClient.phone2ext, ' ') AS clientphone2 ,
            tblLocation.addr1 AS doctoraddr1 ,
            tblLocation.addr2 AS doctoraddr2 ,
            tblLocation.city + ', ' + tblLocation.state + '  '
            + tblLocation.zip AS doctorcitystatezip ,
            tblCase.ApptDate ,
            tblCase.Appttime ,
            tblExaminee.firstname + ' ' + tblExaminee.lastname AS examineename ,
            tblExaminee.phone1 AS examineephone ,
            tblExaminee.sex ,
            tblExaminee.DOB ,
            tblLocation.Phone AS doctorphone ,
            tblClient.addr1 AS clientaddr1 ,
            tblClient.addr2 AS clientaddr2 ,
            tblClient.city + ', ' + tblClient.state + '  ' + tblClient.zip AS clientcitystatezip ,
            tblClient.fax AS clientfax ,
            tblClient.email AS clientemail ,
            ISNULL(tblUser.lastname, '')
            + CASE WHEN ISNULL(tblUser.LastName, '') = ''
                        OR ISNULL(tblUser.FirstName, '') = '' THEN ''
                   ELSE ', '
              END + ISNULL(tblUser.firstname, '') AS scheduler ,
            tblCase.marketercode AS marketer ,
            tblCase.dateadded AS datecalledin ,
            tblCase.dateofinjury AS DOI ,
            tblCase.allegation ,
            tblCase.notes ,
            tblCase.casetype ,
            'Dear ' + tblExaminee.firstname + ' ' + tblExaminee.lastname AS examineesalutation ,
            tblCase.status ,
            tblCase.calledinby ,
            tblCase.chartnbr ,
            'Dear ' + tblClient.firstname + ' ' + tblClient.lastname AS clientsalutation ,
            'Dear ' + tblDoctor.firstname + ' ' + tblDoctor.lastname + ', '
            + ISNULL(tblDoctor.credentials, '') AS doctorsalutation ,
            tblLocation.insidedr ,
            tblLocation.email AS doctoremail ,
            tblLocation.fax AS doctorfax ,
            tblLocation.faxdrschedule ,
            tblLocation.medrcdletter ,
            tblLocation.drletter ,
            tblCase.reportverbal ,
            tblCase.datemedsrecd AS medsrecd ,
            tblCCAddress_2.firstname + ' ' + tblCCAddress_2.lastname AS Pattorneyname ,
            'Dear ' + ISNULL(tblCCAddress_2.firstname, '') + ' '
            + ISNULL(tblCCAddress_2.lastname, '') AS Pattorneysalutation ,
            tblCCAddress_2.company AS Pattorneycompany ,
            tblCCAddress_2.address1 AS Pattorneyaddr1 ,
            tblCCAddress_2.address2 AS Pattorneyaddr2 ,
            tblCCAddress_2.city + ', ' + tblCCAddress_2.state + '  '
            + tblCCAddress_2.zip AS Pattorneycitystatezip ,
            tblCCAddress_2.phone + ISNULL(tblCCAddress_2.phoneextension, '') AS Pattorneyphone ,
            tblCCAddress_2.fax AS Pattorneyfax ,
            tblCCAddress_2.email AS Pattorneyemail ,
            tblCCAddress_1.firstname + ' ' + tblCCAddress_1.lastname AS Dattorneyname ,
            'Dear ' + ISNULL(tblCCAddress_1.firstname, '') + ' '
            + ISNULL(tblCCAddress_1.lastname, '') AS Dattorneysalutation ,
            tblCCAddress_1.company AS Dattorneycompany ,
            tblCCAddress_1.address1 AS Dattorneyaddr1 ,
            tblCCAddress_1.address2 AS Dattorneyaddr2 ,
            tblCCAddress_1.city + ', ' + tblCCAddress_1.state + '  '
            + tblCCAddress_1.zip AS Dattorneycitystatezip ,
            tblCCAddress_1.phone + ' ' + ISNULL(tblCCAddress_1.phoneextension,
                                                '') AS Dattorneyphone ,
            tblCCAddress_1.fax AS Dattorneyfax ,
            tblCCAddress_1.email AS Dattorneyemail ,
            tblCCAddress_1.fax ,
            tblCCAddress_3.firstname + ' ' + tblCCAddress_3.lastname AS DParaLegalname ,
            'Dear ' + ISNULL(tblCCAddress_3.firstname, '') + ' '
            + ISNULL(tblCCAddress_3.lastname, '') AS DParaLegalsalutation ,
            tblCCAddress_3.company AS DParaLegalcompany ,
            tblCCAddress_3.address1 AS DParaLegaladdr1 ,
            tblCCAddress_3.address2 AS DParaLegaladdr2 ,
            tblCCAddress_3.city + ', ' + tblCCAddress_3.state + '  '
            + tblCCAddress_3.zip AS DParaLegalcitystatezip ,
            tblCCAddress_3.phone + ' ' + ISNULL(tblCCAddress_3.phoneextension,
                                                '') AS DParaLegalphone ,
            tblCCAddress_3.email AS DParaLegalemail ,
            tblCCAddress_3.fax AS DParaLegalfax ,
            tblCase.typemedsrecd ,
            tblCase.plaintiffattorneycode ,
            tblCase.defenseattorneycode ,
            tblCase.servicecode ,
            tblCase.faxPattny ,
            tblCase.faxdoctor ,
            tblCase.faxclient ,
            tblCase.emailclient ,
            tblCase.emaildoctor ,
            tblCase.emailPattny ,
            tblCase.invoicedate ,
            tblCase.invoiceamt ,
            tblCase.commitdate ,
            tblCase.WCBNbr ,
            tblCase.specialinstructions ,
            tblCase.priority ,
            tblServices.description AS servicedesc ,
            tblCase.usdvarchar1 AS caseusdvarchar1 ,
            tblCase.usdvarchar2 AS caseusdvarchar2 ,
            tblCase.usddate1 AS caseusddate1 ,
            tblCase.usddate2 AS caseusddate2 ,
            tblCase.usdtext1 AS caseusdtext1 ,
            tblCase.usdtext2 AS caseusdtext2 ,
            tblCase.usdint1 AS caseusdint1 ,
            tblCase.usdint2 AS caseusdint2 ,
            tblCase.usdmoney1 AS caseusdmoney1 ,
            tblCase.usdmoney2 AS caseusdmoney2 ,
            tblClient.title AS clienttitle ,
            tblClient.prefix AS clientprefix ,
            tblClient.suffix AS clientsuffix ,
            tblClient.usdvarchar1 AS clientusdvarchar1 ,
            tblClient.usdvarchar2 AS clientusdvarchar2 ,
            tblClient.usddate1 AS clientusddate1 ,
            tblClient.usddate2 AS clientusddate2 ,
            tblClient.usdtext1 AS clientusdtext1 ,
            tblClient.usdtext2 AS clientusdtext2 ,
            tblClient.usdint1 AS clientusdint1 ,
            tblClient.usdint2 AS clientusdint2 ,
            tblClient.usdmoney1 AS clientusdmoney1 ,
            tblClient.usdmoney2 AS clientusdmoney2 ,
            tblDoctor.notes AS doctornotes ,
            tblDoctor.prefix AS doctorprefix ,
            tblDoctor.addr1 AS doctorcorrespaddr1 ,
            tblDoctor.addr2 AS doctorcorrespaddr2 ,
            tblDoctor.city + ', ' + tblDoctor.state + '  ' + tblDoctor.zip AS doctorcorrespcitystatezip ,
            tblDoctor.phone + ' ' + ISNULL(tblDoctor.phoneExt, ' ') AS doctorcorrespphone ,
            tblDoctor.faxNbr AS doctorcorrespfax ,
            tblDoctor.emailAddr AS doctorcorrespemail ,
            tblDoctor.qualifications ,
            tblDoctor.prepaid ,
            tblDoctor.county AS doctorcorrespcounty ,
            tblLocation.county AS doctorcounty ,
            tblLocation.vicinity AS doctorvicinity ,
            tblExaminee.county AS examineecounty ,
            tblExaminee.prefix AS examineeprefix ,
            tblExaminee.usdvarchar1 AS examineeusdvarchar1 ,
            tblExaminee.usdvarchar2 AS examineeusdvarchar2 ,
            tblExaminee.usddate1 AS examineeusddate1 ,
            tblExaminee.usddate2 AS examineeusddate2 ,
            tblExaminee.usdtext1 AS examineeusdtext1 ,
            tblExaminee.usdtext2 AS examineeusdtext2 ,
            tblExaminee.usdint1 AS examineeusdint1 ,
            tblExaminee.usdint2 AS examineeusdint2 ,
            tblExaminee.usdmoney1 AS examineeusdmoney1 ,
            tblExaminee.usdmoney2 AS examineeusdmoney2 ,
            tblDoctor.usdvarchar1 AS doctorusdvarchar1 ,
            tblDoctor.usdvarchar2 AS doctorusdvarchar2 ,
            tblDoctor.usddate1 AS doctorusddate1 ,
            tblDoctor.usddate2 AS doctorusddate2 ,
            tblDoctor.usdtext1 AS doctorusdtext1 ,
            tblDoctor.usdtext2 AS doctorusdtext2 ,
            tblDoctor.usdint1 AS doctorusdint1 ,
            tblDoctor.usdint2 AS doctorusdint2 ,
            tblDoctor.usdmoney1 AS doctorusdmoney1 ,
            tblDoctor.usdmoney2 AS doctorusdmoney2 ,
            tblCase.schedulenotes ,
            tblCase.requesteddoc ,
            tblCompany.usdvarchar1 AS companyusdvarchar1 ,
            tblCompany.usdvarchar2 AS companyusdvarchar2 ,
            tblCompany.usddate1 AS companyusddate1 ,
            tblCompany.usddate2 AS companyusddate2 ,
            tblCompany.usdtext1 AS companyusdtext1 ,
            tblCompany.usdtext2 AS companyusdtext2 ,
            tblCompany.usdint1 AS companyusdint1 ,
            tblCompany.usdint2 AS companyusdint2 ,
            tblCompany.usdmoney1 AS companyusdmoney1 ,
            tblCompany.usdmoney2 AS companyusdmoney2 ,
            tblDoctor.WCNbr AS doctorwcnbr ,
            tblCaseType.description AS casetypedesc ,
            tblLocation.location ,
            tblCase.doctorlocation ,
            tblCase.sinternalcasenbr AS internalcasenbr ,
            tblDoctor.credentials AS doctordegree ,
            tblSpecialty.description AS specialtydesc ,
            tblExaminee.note AS chartnotes ,
            tblExaminee.fax AS examineefax ,
            tblExaminee.email AS examineeemail ,
            tblExaminee.insured AS examineeinsured ,
            tblCase.clientcode ,
            tblCase.doctorcode ,
            tblCase.feecode ,
            tblClient.companycode ,
            tblClient.notes AS clientnotes ,
            tblCompany.notes AS companynotes ,
            tblClient.billaddr1 ,
            tblClient.billaddr2 ,
            tblClient.billcity ,
            tblClient.billstate ,
            tblClient.billzip ,
            tblClient.billattn ,
            tblClient.ARKey ,
            tblCase.icd9code ,
            tblDoctor.remitattn ,
            tblDoctor.remitaddr1 ,
            tblDoctor.remitaddr2 ,
            tblDoctor.remitcity ,
            tblDoctor.remitstate ,
            tblDoctor.remitzip ,
            tblCase.doctorspecialty ,
            tblServices.shortdesc ,
            tblDoctor.licensenbr AS doctorlicense ,
            tblLocation.notes AS doctorlocationnotes ,
            tblLocation.contactfirst + ' ' + tblLocation.contactlast AS doctorlocationcontact ,
            'Dear ' + tblLocation.contactfirst + ' ' + tblLocation.contactlast AS doctorlocationcontactsalutation ,
            tblRecordStatus.description AS medsstatus ,
            tblExaminee.employer ,
            tblExaminee.treatingphysician ,
            tblExaminee.city AS examineecity ,
            tblExaminee.state AS examineestate ,
            tblExaminee.zip AS examineezip ,
            tblDoctor.SSNTaxID AS DoctorTaxID ,
            tblCase.billclientcode AS casebillclientcode ,
            tblSpecialty.specialtycode ,
            tblDoctorLocation.correspondence AS doctorcorrespondence ,
            tblExaminee.lastname AS examineelastname ,
            tblExaminee.firstname AS examineefirstname ,
            tblClient.billfax AS clientbillfax ,
            tblCase.officecode ,
            tblDoctor.lastname AS doctorlastname ,
            tblDoctor.firstname AS doctorfirstname ,
            tblDoctor.middleinitial AS doctormiddleinitial ,
            ISNULL(LEFT(tblDoctor.firstname, 1), '')
            + ISNULL(LEFT(tblDoctor.middleinitial, 1), '')
            + ISNULL(LEFT(tblDoctor.lastname, 1), '') AS doctorinitials ,
            tblCase.QARep ,
            tblClient.lastname AS clientlastname ,
            tblClient.firstname AS clientfirstname ,
            tblCCAddress_1.prefix AS dattorneyprefix ,
            tblCCAddress_1.lastname AS dattorneylastname ,
            tblCCAddress_1.firstname AS dattorneyfirstname ,
            tblCCAddress_2.prefix AS pattorneyprefix ,
            tblCCAddress_2.lastname AS pattorneylastname ,
            tblCCAddress_2.firstname AS pattorneyfirstname ,
            tblLocation.contactprefix AS doctorlocationcontactprefix ,
            tblLocation.contactfirst AS doctorlocationcontactfirstname ,
            tblLocation.contactlast AS doctorlocationcontactlastname ,
            tblExaminee.middleinitial AS examineemiddleinitial ,
            tblCase.ICD9Code2 ,
            tblCase.ICD9Code3 ,
            tblCase.ICD9Code4 ,
            tblExaminee.InsuredAddr1 ,
            tblExaminee.InsuredCity ,
            tblExaminee.InsuredState ,
            tblExaminee.InsuredZip ,
            tblExaminee.InsuredSex ,
            tblExaminee.InsuredRelationship ,
            tblExaminee.InsuredPhone ,
            tblExaminee.InsuredPhoneExt ,
            tblExaminee.InsuredFax ,
            tblExaminee.InsuredEmail ,
            tblExaminee.ExamineeStatus ,
            tblExaminee.TreatingPhysicianAddr1 ,
            tblExaminee.TreatingPhysicianCity ,
            tblExaminee.TreatingPhysicianState ,
            tblExaminee.TreatingPhysicianZip ,
            tblExaminee.TreatingPhysicianPhone ,
            tblExaminee.TreatingPhysicianPhoneExt ,
            tblExaminee.TreatingPhysicianFax ,
            tblExaminee.TreatingPhysicianEmail ,
            tblExaminee.TreatingPhysicianLicenseNbr ,
            tblExaminee.EmployerAddr1 ,
            tblExaminee.EmployerCity ,
            tblExaminee.EmployerState ,
            tblExaminee.EmployerZip ,
            tblExaminee.EmployerPhone ,
            tblExaminee.EmployerPhoneExt ,
            tblExaminee.EmployerFax ,
            tblExaminee.EmployerEmail ,
            tblExaminee.TreatingPhysicianTaxID ,
            tblExaminee.Country ,
            tblDoctor.UPIN ,
            tblDoctor.schedulepriority ,
            tblDoctor.feecode AS drfeecode ,
            tblCase.PanelNbr ,
            tblState.StateName AS Jurisdiction ,
            tblCase.photoRqd ,
            tblCase.CertMailNbr ,
            tblCase.HearingDate ,
            tblCase.DoctorName ,
            tblCase.DefParaLegal ,
            tblLocation.state AS doctorstate ,
            tblClient.state AS clientstate ,
            tblDoctor.state AS doctorcorrespstate ,
            tblCCAddress_1.state AS dattorneystate ,
            tblCCAddress_2.state AS pattorneystate ,
            tblCase.prevappt ,
            tblCase.mastersubcase ,
            tblCase.mastercasenbr ,
            tblLocation.city AS doctorcity ,
            tblLocation.zip AS doctorzip ,
            tblClient.city AS clientcity ,
            tblClient.zip AS clientzip ,
            tblExaminee.policynumber ,
            tblCCAddress_2.city AS pattorneycity ,
            tblCCAddress_2.zip AS pattorneyzip ,
            tblDoctorSchedule.duration AS ApptDuration ,
            tblDoctor.companyname AS PracticeName ,
            tblCase.AssessmentToAddress ,
            tblCase.OCF25Date ,
            tblCase.AssessingFacility ,
            tblCase.DateForminDispute ,
            tblExaminee.EmployerContactLastName ,
            tblExaminee.EmployerContactFirstName ,
            tblDoctor.NPINbr AS DoctorNPINbr ,
            tblCase.PublishOnWeb ,
            tblProviderType.description AS DoctorProviderType ,
            tblDoctor.ProvTypeCode ,
            tblCase.Jurisdiction AS JurisdictionCode ,
            tblCase.LegalEvent ,
            tblCase.PILegalEvent ,
            tblCase.Transcode ,
            tblTranscription.transcompany ,
            tblCase.DateReceived ,
            tblCase.usddate3 AS caseusddate3 ,
            tblCase.usddate4 AS caseusddate4 ,
            tblCase.UsdBit1 AS caseusdboolean1 ,
            tblCase.UsdBit2 AS caseusdboolean2 ,
            tblCase.usddate5 AS caseusddate5 ,
            tblDoctor.usddate3 AS doctorusddate3 ,
            tblDoctor.usddate4 AS doctorusddate4 ,
            tblDoctor.usdvarchar3 AS doctorusdvarchar3 ,
            tblDoctor.usddate5 AS doctorusddate5 ,
            tblDoctor.usddate6 AS doctorusddate6 ,
            tblDoctor.usddate7 AS doctorusddate7 ,
            tblCase.ClaimNbrExt ,
            tblCase.sreqspecialty AS RequestedSpecialty ,
            tblQueues.statusdesc ,
            tblCase.AttorneyNote ,
            tblCaseType.ShortDesc AS CaseTypeShortDesc ,
            tblCase.ExternalDueDate ,
            tblCase.InternalDueDate ,
            tblLocation.ExtName AS LocationExtName ,
            tblVenue.County AS Venue ,
            tblOffice.description AS office ,
            tblOffice.usdvarchar1 AS OfficeUSDVarChar1 ,
            tblOffice.usdvarchar2 AS OfficeUSDVarChar2 ,
            tblCase.TransportationRequired ,
            tblCase.InterpreterRequired ,
            tblLanguage.Description AS LANGUAGE ,
            tblCase.ForecastDate ,
            tblCase.EWReferralType ,
            tblCase.EWReferralEWFacilityID ,
            tblDoctor.PrintOnCheckAs ,
            tblExaminee.TreatingPhysicianCredentials AS TreatingPhysicianDegree ,
            tblCase.CaseApptID ,
            tblCase.ApptStatusID ,
            tblApptStatus.Name AS ApptStatus ,
            tblCase.RptFinalizedDate
    FROM    tblCase
            INNER JOIN tblExaminee ON tblExaminee.chartnbr = tblCase.chartnbr
            INNER JOIN tblOffice ON tblOffice.officecode = tblCase.officecode
            INNER JOIN tblClient ON tblCase.clientcode = tblClient.clientcode
            INNER JOIN tblCompany ON tblClient.companycode = tblCompany.companycode
            INNER JOIN tblCaseType ON tblCase.casetype = tblCaseType.code
            INNER JOIN tblQueues ON tblCase.status = tblQueues.statuscode
            LEFT OUTER JOIN tblApptStatus ON tblCase.ApptStatusID = tblApptStatus.ApptStatusID
            LEFT OUTER JOIN tblDoctor ON tblCase.doctorcode = tblDoctor.doctorcode
            LEFT OUTER JOIN tblProviderType ON tblDoctor.ProvTypeCode = tblProviderType.ProvTypeCode
            LEFT OUTER JOIN tblLocation ON tblCase.doctorlocation = tblLocation.locationcode
            LEFT OUTER JOIN tblDoctorLocation ON tblCase.doctorlocation = tblDoctorLocation.locationcode
                                                 AND tblCase.doctorcode = tblDoctorLocation.doctorcode
            LEFT OUTER JOIN tblVenue ON tblCase.VenueID = tblVenue.VenueID
            LEFT OUTER JOIN tblTranscription ON tblCase.Transcode = tblTranscription.Transcode
            LEFT OUTER JOIN tblDoctorSchedule ON tblCase.schedcode = tblDoctorSchedule.schedcode
            LEFT OUTER JOIN tblState ON tblCase.Jurisdiction = tblState.Statecode
            LEFT OUTER JOIN tblRecordStatus ON tblCase.reccode = tblRecordStatus.reccode
            LEFT OUTER JOIN tblUser ON tblCase.schedulercode = tblUser.userid
            LEFT OUTER JOIN tblSpecialty ON tblCase.doctorspecialty = tblSpecialty.specialtycode
            LEFT OUTER JOIN tblServices ON tblCase.servicecode = tblServices.servicecode
            LEFT OUTER JOIN tblCCAddress AS tblCCAddress_1 ON tblCase.defenseattorneycode = tblCCAddress_1.cccode
            LEFT OUTER JOIN tblCCAddress AS tblCCAddress_2 ON tblCase.plaintiffattorneycode = tblCCAddress_2.cccode
            LEFT OUTER JOIN tblCCAddress AS tblCCAddress_3 ON tblCCAddress_3.cccode = tblCase.DefParaLegal
            LEFT OUTER JOIN tblLanguage ON tblLanguage.LanguageID = tblCase.LanguageID
GO

DROP VIEW vwDocumentAccting
GO
CREATE VIEW vwDocumentAccting
AS
    SELECT  tblCase.casenbr ,
            tblCase.claimnbr ,
            tblExaminee.addr1 AS examineeaddr1 ,
            tblExaminee.addr2 AS examineeaddr2 ,
            tblExaminee.city + ', ' + tblExaminee.state + '  '
            + tblExaminee.zip AS examineecitystatezip ,
            tblExaminee.SSN ,
            tblClient.firstname + ' ' + tblClient.lastname AS clientname ,
            tblCompany.extname AS company ,
            tblClient.phone1 + ' ' + ISNULL(tblClient.phone1ext, ' ') AS clientphone ,
            tblClient.phone2 + ' ' + ISNULL(tblClient.phone2ext, ' ') AS clientphone2 ,
            tblLocation.addr1 AS doctoraddr1 ,
            tblLocation.addr2 AS doctoraddr2 ,
            tblLocation.city + ', ' + tblLocation.state + '  '
            + tblLocation.zip AS doctorcitystatezip ,
            tblExaminee.firstname + ' ' + tblExaminee.lastname AS examineename ,
            tblExaminee.phone1 AS examineephone ,
            tblExaminee.sex ,
            tblExaminee.DOB ,
            tblLocation.Phone AS doctorphone ,
            tblClient.addr1 AS clientaddr1 ,
            tblClient.addr2 AS clientaddr2 ,
            tblClient.city + ', ' + tblClient.state + '  '
            + tblClient.zip AS clientcitystatezip ,
            tblClient.fax AS clientfax ,
            tblClient.email AS clientemail ,
            ISNULL(tblUser.lastname, '')
            + CASE WHEN ISNULL(tblUser.LastName, '') = ''
                        OR ISNULL(tblUser.FirstName, '') = '' THEN ''
                   ELSE ', '
              END + ISNULL(tblUser.firstname, '') AS scheduler ,
            tblCase.marketercode AS marketer ,
            tblCase.dateadded AS datecalledin ,
            tblCase.dateofinjury AS DOI ,
            tblCase.allegation ,
            tblCase.notes ,
            tblCase.casetype ,
            'Dear ' + tblExaminee.firstname + ' '
            + tblExaminee.lastname AS examineesalutation ,
            tblCase.status ,
            tblCase.calledinby ,
            tblCase.chartnbr ,
            'Dear ' + tblClient.firstname + ' ' + tblClient.lastname AS clientsalutation ,
            'Dear ' + tblDoctor.firstname + ' ' + tblDoctor.lastname
            + ', ' + ISNULL(tblDoctor.credentials, '') AS doctorsalutation ,
            tblLocation.insidedr ,
            tblLocation.email AS doctoremail ,
            tblLocation.fax AS doctorfax ,
            tblLocation.faxdrschedule ,
            tblLocation.medrcdletter ,
            tblLocation.drletter ,
            tblCase.reportverbal ,
            tblCase.datemedsrecd AS medsrecd ,
            tblCCAddress_2.firstname + ' ' + tblCCAddress_2.lastname AS Pattorneyname ,
            'Dear ' + ISNULL(tblCCAddress_2.firstname, '') + ' '
            + ISNULL(tblCCAddress_2.lastname, '') AS Pattorneysalutation ,
            tblCCAddress_2.company AS Pattorneycompany ,
            tblCCAddress_2.address1 AS Pattorneyaddr1 ,
            tblCCAddress_2.address2 AS Pattorneyaddr2 ,
            tblCCAddress_2.city + ', ' + tblCCAddress_2.state + '  '
            + tblCCAddress_2.zip AS Pattorneycitystatezip ,
            tblCCAddress_2.phone + ISNULL(tblCCAddress_2.phoneextension, '') AS Pattorneyphone ,
            tblCCAddress_2.fax AS Pattorneyfax ,
            tblCCAddress_2.email AS Pattorneyemail ,
            tblCCAddress_1.firstname + ' ' + tblCCAddress_1.lastname AS Dattorneyname ,
            'Dear ' + ISNULL(tblCCAddress_1.firstname, '') + ' '
            + ISNULL(tblCCAddress_1.lastname, '') AS Dattorneysalutation ,
            tblCCAddress_1.company AS Dattorneycompany ,
            tblCCAddress_1.address1 AS Dattorneyaddr1 ,
            tblCCAddress_1.address2 AS Dattorneyaddr2 ,
            tblCCAddress_1.city + ', ' + tblCCAddress_1.state + '  '
            + tblCCAddress_1.zip AS Dattorneycitystatezip ,
            tblCCAddress_1.phone + ' ' + ISNULL(tblCCAddress_1.phoneextension,
                                                '') AS Dattorneyphone ,
            tblCCAddress_1.fax AS Dattorneyfax ,
            tblCCAddress_1.email AS Dattorneyemail ,
            tblCCAddress_1.fax ,
            tblCase.typemedsrecd ,
            tblCase.plaintiffattorneycode ,
            tblCase.defenseattorneycode ,
            tblCase.servicecode ,
            tblCase.faxPattny ,
            tblCase.faxdoctor ,
            tblCase.faxclient ,
            tblCase.emailclient ,
            tblCase.emaildoctor ,
            tblCase.emailPattny ,
            tblCase.invoicedate ,
            tblCase.invoiceamt ,
            tblCase.commitdate ,
            tblCase.WCBNbr ,
            tblCase.specialinstructions ,
            tblCase.priority ,
            tblServices.description AS servicedesc ,
            tblCase.usdvarchar1 AS caseusdvarchar1 ,
            tblCase.usdvarchar2 AS caseusdvarchar2 ,
            tblCase.usddate1 AS caseusddate1 ,
            tblCase.usddate2 AS caseusddate2 ,
            tblCase.usdtext1 AS caseusdtext1 ,
            tblCase.usdtext2 AS caseusdtext2 ,
            tblCase.usdint1 AS caseusdint1 ,
            tblCase.usdint2 AS caseusdint2 ,
            tblCase.usdmoney1 AS caseusdmoney1 ,
            tblCase.usdmoney2 AS caseusdmoney2 ,
            tblClient.title AS clienttitle ,
            tblClient.prefix AS clientprefix ,
            tblClient.suffix AS clientsuffix ,
            tblClient.usdvarchar1 AS clientusdvarchar1 ,
            tblClient.usdvarchar2 AS clientusdvarchar2 ,
            tblClient.usddate1 AS clientusddate1 ,
            tblClient.usddate2 AS clientusddate2 ,
            tblClient.usdtext1 AS clientusdtext1 ,
            tblClient.usdtext2 AS clientusdtext2 ,
            tblClient.usdint1 AS clientusdint1 ,
            tblClient.usdint2 AS clientusdint2 ,
            tblClient.usdmoney1 AS clientusdmoney1 ,
            tblClient.usdmoney2 AS clientusdmoney2 ,
            tblDoctor.notes AS doctornotes ,
            tblDoctor.prefix AS doctorprefix ,
            tblDoctor.addr1 AS doctorcorrespaddr1 ,
            tblDoctor.addr2 AS doctorcorrespaddr2 ,
            tblDoctor.city + ', ' + tblDoctor.state + '  '
            + tblDoctor.zip AS doctorcorrespcitystatezip ,
            tblDoctor.phone + ' ' + ISNULL(tblDoctor.phoneExt, ' ') AS doctorcorrespphone ,
            tblDoctor.faxNbr AS doctorcorrespfax ,
            tblDoctor.emailAddr AS doctorcorrespemail ,
            tblDoctor.qualifications ,
            tblDoctor.prepaid ,
            tblDoctor.county AS doctorcorrespcounty ,
            tblLocation.county AS doctorcounty ,
            tblLocation.vicinity AS doctorvicinity ,
            tblExaminee.county AS examineecounty ,
            tblExaminee.prefix AS examineeprefix ,
            tblExaminee.usdvarchar1 AS examineeusdvarchar1 ,
            tblExaminee.usdvarchar2 AS examineeusdvarchar2 ,
            tblExaminee.usddate1 AS examineeusddate1 ,
            tblExaminee.usddate2 AS examineeusddate2 ,
            tblExaminee.usdtext1 AS examineeusdtext1 ,
            tblExaminee.usdtext2 AS examineeusdtext2 ,
            tblExaminee.usdint1 AS examineeusdint1 ,
            tblExaminee.usdint2 AS examineeusdint2 ,
            tblExaminee.usdmoney1 AS examineeusdmoney1 ,
            tblExaminee.usdmoney2 AS examineeusdmoney2 ,
            tblDoctor.usdvarchar1 AS doctorusdvarchar1 ,
            tblDoctor.usdvarchar2 AS doctorusdvarchar2 ,
            tblDoctor.usddate1 AS doctorusddate1 ,
            tblDoctor.usddate2 AS doctorusddate2 ,
            tblDoctor.usdtext1 AS doctorusdtext1 ,
            tblDoctor.usdtext2 AS doctorusdtext2 ,
            tblDoctor.usdint1 AS doctorusdint1 ,
            tblDoctor.usdint2 AS doctorusdint2 ,
            tblDoctor.usdmoney1 AS doctorusdmoney1 ,
            tblDoctor.usdmoney2 AS doctorusdmoney2 ,
            tblCase.schedulenotes ,
            tblCase.requesteddoc ,
            tblCompany.usdvarchar1 AS companyusdvarchar1 ,
            tblCompany.usdvarchar2 AS companyusdvarchar2 ,
            tblCompany.usddate1 AS companyusddate1 ,
            tblCompany.usddate2 AS companyusddate2 ,
            tblCompany.usdtext1 AS companyusdtext1 ,
            tblCompany.usdtext2 AS companyusdtext2 ,
            tblCompany.usdint1 AS companyusdint1 ,
            tblCompany.usdint2 AS companyusdint2 ,
            tblCompany.usdmoney1 AS companyusdmoney1 ,
            tblCompany.usdmoney2 AS companyusdmoney2 ,
            tblDoctor.WCNbr AS doctorwcnbr ,
            tblCaseType.description AS casetypedesc ,
            tblLocation.location ,
            tblCase.sinternalcasenbr AS internalcasenbr ,
            tblDoctor.credentials AS doctordegree ,
            tblSpecialty.description AS specialtydesc ,
            tblExaminee.note AS chartnotes ,
            tblExaminee.fax AS examineefax ,
            tblExaminee.email AS examineeemail ,
            tblExaminee.insured AS examineeinsured ,
            tblCase.clientcode ,
            tblCase.feecode ,
            tblClient.companycode ,
            tblClient.notes AS clientnotes ,
            tblCompany.notes AS companynotes ,
            tblClient.billaddr1 ,
            tblClient.billaddr2 ,
            tblClient.billcity ,
            tblClient.billstate ,
            tblClient.billzip ,
            tblClient.billattn ,
            tblClient.ARKey ,
            tblCase.icd9code ,
            tblDoctor.remitattn ,
            tblDoctor.remitaddr1 ,
            tblDoctor.remitaddr2 ,
            tblDoctor.remitcity ,
            tblDoctor.remitstate ,
            tblDoctor.remitzip ,
            tblCase.doctorspecialty ,
            tblServices.shortdesc ,
            tblDoctor.licensenbr AS doctorlicense ,
            tblLocation.notes AS doctorlocationnotes ,
            tblLocation.contactfirst + ' ' + tblLocation.contactlast AS doctorlocationcontact ,
            'Dear ' + tblLocation.contactfirst + ' '
            + tblLocation.contactlast AS doctorlocationcontactsalutation ,
            tblRecordStatus.description AS medsstatus ,
            tblExaminee.employer ,
            tblExaminee.treatingphysician ,
            tblExaminee.city AS examineecity ,
            tblExaminee.state AS examineestate ,
            tblExaminee.zip AS examineezip ,
            tblDoctor.SSNTaxID AS DoctorTaxID ,
            tblCase.billclientcode AS casebillclientcode ,
            tblSpecialty.specialtycode ,
            tblDoctorLocation.correspondence AS doctorcorrespondence ,
            tblExaminee.lastname AS examineelastname ,
            tblExaminee.firstname AS examineefirstname ,
            tblClient.billfax AS clientbillfax ,
            tblCase.officecode ,
            tblDoctor.lastname AS doctorlastname ,
            tblDoctor.firstname AS doctorfirstname ,
            tblDoctor.middleinitial AS doctormiddleinitial ,
            ISNULL(LEFT(tblDoctor.firstname, 1), '')
            + ISNULL(LEFT(tblDoctor.middleinitial, 1), '')
            + ISNULL(LEFT(tblDoctor.lastname, 1), '') AS doctorinitials ,
            tblCase.QARep ,
            tblClient.lastname AS clientlastname ,
            tblClient.firstname AS clientfirstname ,
            tblCCAddress_1.prefix AS dattorneyprefix ,
            tblCCAddress_1.lastname AS dattorneylastname ,
            tblCCAddress_1.firstname AS dattorneyfirstname ,
            tblCCAddress_2.prefix AS pattorneyprefix ,
            tblCCAddress_2.lastname AS pattorneylastname ,
            tblCCAddress_2.firstname AS pattorneyfirstname ,
            tblLocation.contactprefix AS doctorlocationcontactprefix ,
            tblLocation.contactfirst AS doctorlocationcontactfirstname ,
            tblLocation.contactlast AS doctorlocationcontactlastname ,
            tblExaminee.middleinitial AS examineemiddleinitial ,
            tblCase.ICD9Code2 ,
            tblCase.ICD9Code3 ,
            tblCase.ICD9Code4 ,
            tblExaminee.InsuredAddr1 ,
            tblExaminee.InsuredCity ,
            tblExaminee.InsuredState ,
            tblExaminee.InsuredZip ,
            tblExaminee.InsuredSex ,
            tblExaminee.InsuredRelationship ,
            tblExaminee.InsuredPhone ,
            tblExaminee.InsuredPhoneExt ,
            tblExaminee.InsuredFax ,
            tblExaminee.InsuredEmail ,
            tblExaminee.ExamineeStatus ,
            tblExaminee.TreatingPhysicianAddr1 ,
            tblExaminee.TreatingPhysicianCity ,
            tblExaminee.TreatingPhysicianState ,
            tblExaminee.TreatingPhysicianZip ,
            tblExaminee.TreatingPhysicianPhone ,
            tblExaminee.TreatingPhysicianPhoneExt ,
            tblExaminee.TreatingPhysicianFax ,
            tblExaminee.TreatingPhysicianEmail ,
            tblExaminee.TreatingPhysicianLicenseNbr ,
            tblExaminee.TreatingPhysicianTaxID ,
            tblExaminee.EmployerAddr1 ,
            tblExaminee.EmployerCity ,
            tblExaminee.EmployerState ,
            tblExaminee.EmployerZip ,
            tblExaminee.EmployerPhone ,
            tblExaminee.EmployerPhoneExt ,
            tblExaminee.EmployerFax ,
            tblExaminee.EmployerEmail ,
            tblExaminee.Country ,
            tblDoctor.UPIN ,
            tblDoctor.schedulepriority ,
            tblDoctor.feecode AS drfeecode ,
            tblCase.PanelNbr ,
            tblState.StateName AS Jurisdiction ,
            tblCase.photoRqd ,
            tblCase.CertMailNbr ,
            tblCase.HearingDate ,
            tblCase.DoctorName ,
            tblLocation.state AS doctorstate ,
            tblClient.state AS clientstate ,
            tblDoctor.state AS doctorcorrespstate ,
            tblCCAddress_1.state AS dattorneystate ,
            tblCCAddress_2.state AS pattorneystate ,
            tblAcctingTrans.apptdate ,
            CASE WHEN EWReferralType = 2 THEN tblCase.doctorcode
                 ELSE tblAcctingTrans.DrOpCode
            END AS doctorCode ,
            CASE WHEN EWReferralType = 2 THEN tblCase.doctorlocation
                 ELSE tblAcctingTrans.doctorlocation
            END AS doctorLocation ,
            tblAcctingTrans.documentnbr ,
            tblAcctingTrans.type AS documenttype ,
            tblAcctingTrans.appttime ,
            tblCase.prevappt ,
            tblLocation.state ,
            tblClient.state AS Expr1 ,
            tblDoctor.state AS Expr2 ,
            tblCCAddress_1.state AS Expr3 ,
            tblCCAddress_2.state AS Expr4 ,
            tblLocation.city AS doctorcity ,
            tblLocation.zip AS doctorzip ,
            tblClient.city AS clientcity ,
            tblClient.zip AS clientzip ,
            tblExaminee.policynumber ,
            tblCCAddress_2.city AS pattorneycity ,
            tblCCAddress_2.zip AS pattorneyzip ,
            tblCase.mastercasenbr ,
            tblDoctorSchedule.duration AS ApptDuration ,
            tblDoctor.companyname AS PracticeName ,
            tblCase.AssessmentToAddress ,
            tblCase.OCF25Date ,
            tblCase.AssessingFacility ,
            tblCase.DateForminDispute ,
            tblExaminee.EmployerContactFirstName ,
            tblExaminee.EmployerContactLastName ,
            tblDoctor.NPINbr AS DoctorNPINbr ,
            tblProviderType.description AS DoctorProviderType ,
            tblDoctor.ProvTypeCode ,
            tblCase.DateReceived ,
            tblCase.usddate3 AS caseusddate3 ,
            tblCase.usddate4 AS caseusddate4 ,
            tblCase.usddate5 AS caseusddate5 ,
            tblCase.UsdBit1 AS caseusdboolean1 ,
            tblCase.UsdBit2 AS caseusdboolean2 ,
            tblDoctor.usdvarchar3 AS doctorusdvarchar3 ,
            tblDoctor.usddate5 AS doctorusddate5 ,
            tblDoctor.usddate6 AS doctorusddate6 ,
            tblDoctor.usddate7 AS doctorusddate7 ,
            tblDoctor.usddate3 AS doctorusddate3 ,
            tblDoctor.usddate4 AS doctorusddate4 ,
            tblAcctingTrans.SeqNO ,
            tblOffice.usdvarchar1 AS officeusdvarchar1 ,
            tblOffice.usdvarchar2 AS officeusdvarchar2 ,
            tblCase.ClaimNbrExt ,
            tblCase.sreqspecialty AS RequestedSpecialty ,
            tblCCAddress_3.firstname + ' ' + tblCCAddress_3.lastname AS DParaLegalname ,
            'Dear ' + ISNULL(tblCCAddress_3.firstname, '') + ' '
            + ISNULL(tblCCAddress_3.lastname, '') AS DParaLegalsalutation ,
            tblCCAddress_3.company AS DParaLegalcompany ,
            tblCCAddress_3.address1 AS DParaLegaladdr1 ,
            tblCCAddress_3.address2 AS DParaLegaladdr2 ,
            tblCCAddress_3.city + ', ' + tblCCAddress_3.state + '  '
            + tblCCAddress_3.zip AS DParaLegalcitystatezip ,
            tblCCAddress_3.phone + ' ' + ISNULL(tblCCAddress_3.phoneextension,
                                                '') AS DParaLegalphone ,
            tblCCAddress_3.email AS DParaLegalemail ,
            tblCCAddress_3.fax AS DParaLegalfax ,
            tblCase.AttorneyNote ,
            tblCaseType.ShortDesc AS CaseTypeShortDesc ,
            tblCase.ExternalDueDate ,
            tblCase.InternalDueDate ,
            tblLocation.ExtName AS LocationExtName ,
            tblVenue.County AS Venue ,
            tblOffice.description AS Office ,
            tblCase.ForecastDate ,
            tblDoctor.PrintOnCheckAs ,
            tblExaminee.TreatingPhysicianCredentials AS TreatingPhysicianDegree,
            tblAcctingTrans.CaseApptID
    FROM    tblCase
            INNER JOIN tblExaminee ON tblExaminee.chartnbr = tblCase.chartnbr
            INNER JOIN tblClient ON tblCase.clientcode = tblClient.clientcode
            INNER JOIN tblCompany ON tblClient.companycode = tblCompany.companycode
            INNER JOIN tblCaseType ON tblCase.casetype = tblCaseType.code
            INNER JOIN tblAcctingTrans ON tblCase.casenbr = tblAcctingTrans.casenbr
            INNER JOIN tblOffice ON tblCase.officecode = tblOffice.officecode
            LEFT OUTER JOIN tblVenue ON tblCase.VenueID = tblVenue.VenueID
            LEFT OUTER JOIN tblCCAddress AS tblCCAddress_3 ON tblCase.DefParaLegal = tblCCAddress_3.cccode
            LEFT OUTER JOIN tblDoctorSchedule ON tblCase.schedcode = tblDoctorSchedule.schedcode
            LEFT OUTER JOIN tblDoctor ON CASE WHEN EWReferralType = 2
                                                  THEN tblCase.doctorcode
                                                  ELSE tblAcctingTrans.DrOpCode
                                             END = tblDoctor.doctorcode
            LEFT OUTER JOIN tblLocation ON CASE WHEN EWReferralType = 2
                                                    THEN tblCase.doctorlocation
                                                    ELSE tblAcctingTrans.doctorlocation
                                               END = tblLocation.locationcode
            LEFT OUTER JOIN tblDoctorLocation ON tblCase.doctorlocation = tblDoctorLocation.locationcode
                                                     AND tblCase.doctorcode = tblDoctorLocation.doctorcode
            LEFT OUTER JOIN tblSpecialty ON tblCase.doctorspecialty = tblSpecialty.specialtycode
            LEFT OUTER JOIN tblProviderType ON tblDoctor.ProvTypeCode = tblProviderType.ProvTypeCode
            LEFT OUTER JOIN tblState ON tblCase.Jurisdiction = tblState.Statecode
            LEFT OUTER JOIN tblRecordStatus ON tblCase.reccode = tblRecordStatus.reccode
            LEFT OUTER JOIN tblUser ON tblCase.schedulercode = tblUser.userid
            LEFT OUTER JOIN tblServices ON tblCase.servicecode = tblServices.servicecode
            LEFT OUTER JOIN tblCCAddress AS tblCCAddress_1 ON tblCase.defenseattorneycode = tblCCAddress_1.cccode
            LEFT OUTER JOIN tblCCAddress AS tblCCAddress_2 ON tblCase.plaintiffattorneycode = tblCCAddress_2.cccode
GO




--Changes by Gary
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[proc_IMECase_Update]') AND OBJECTPROPERTY(id,N'IsProcedure') = 1)
    DROP PROCEDURE [proc_IMECase_Update];
GO

CREATE PROCEDURE [proc_IMECase_Update]
(
	@casenbr int,
	@chartnbr int = NULL,
	@doctorlocation varchar(10) = NULL,
	@clientcode int = NULL,
	@marketercode varchar(15) = NULL,
	@schedulercode varchar(15) = NULL,
	@priority varchar(15) = NULL,
	@status int = NULL,
	@casetype int = NULL,
	@dateadded datetime = NULL,
	@dateedited datetime = NULL,
	@useridadded varchar(15) = NULL,
	@useridedited varchar(15) = NULL,
	@schedcode int = NULL,
	@ApptDate datetime = NULL,
	@Appttime datetime = NULL,
	@ApptMadeDate datetime = NULL,
	@claimnbr varchar(50) = NULL,
	@dateofinjury datetime = NULL,
	@allegation text = NULL,
	@calledinby varchar(50) = NULL,
	@notes text = NULL,
	@schedulenotes text = NULL,
	@requesteddoc varchar(50) = NULL,
	@datemedsrecd datetime = NULL,
	@typemedsrecd varchar(50) = NULL,
	@transreceived datetime = NULL,
	@shownoshow int = NULL,
	@rptstatus varchar(50) = NULL,
	@reportverbal bit = NULL,
	@emailclient bit = NULL,
	@emaildoctor bit = NULL,
	@emailPattny bit = NULL,
	@faxclient bit = NULL,
	@faxdoctor bit = NULL,
	@faxPattny bit = NULL,
	@apptrptsselect bit = NULL,
	@chartprepselect bit = NULL,
	@apptselect bit = NULL,
	@awaittransselect bit = NULL,
	@intransselect bit = NULL,
	@inqaselect bit = NULL,
	@drchartselect bit = NULL,
	@datedrchart datetime = NULL,
	@billedselect bit = NULL,
	@miscselect bit = NULL,
	@invoicedate datetime = NULL,
	@invoiceamt money = NULL,
	@plaintiffattorneycode int = NULL,
	@defenseattorneycode int = NULL,
	@commitdate datetime = NULL,
	@servicecode int = NULL,
	@issuecode int = NULL,
	@doctorcode int = NULL,
	@WCBNbr varchar(50) = NULL,
	@specialinstructions text = NULL,
	@usdvarchar1 varchar(50) = NULL,
	@usdvarchar2 varchar(50) = NULL,
	@usddate1 datetime = NULL,
	@usddate2 datetime = NULL,
	@usdtext1 text = NULL,
	@usdtext2 text = NULL,
	@usdint1 int = NULL,
	@usdint2 int = NULL,
	@usdmoney1 money = NULL,
	@usdmoney2 money = NULL,
	@bComplete bit = NULL,
	@bhanddelivery bit = NULL,
	@sinternalcasenbr varchar(70) = NULL,
	@sreqspecialty varchar(50) = NULL,
	@doctorspecialty varchar(50) = NULL,
	@feecode int = NULL,
	@voucherselect bit = NULL,
	@voucheramt money = NULL,
	@voucherdate datetime = NULL,
	@icd9code varchar(70) = NULL,
	@reccode int = NULL,
	@billclientcode int = NULL,
	@officecode int = NULL,
	@QARep varchar(15) = NULL,
	@photoRqd bit = NULL,
	@CertifiedMail bit = NULL,
	@ICD9Code2 varchar(70) = NULL,
	@ICD9Code3 varchar(70) = NULL,
	@ICD9Code4 varchar(70) = NULL,
	@PanelNbr int = NULL,
	@DoctorName varchar(100) = NULL,
	@HearingDate smalldatetime = NULL,
	@CertMailNbr varchar(30) = NULL,
	@laststatuschg datetime = NULL,
	@Jurisdiction varchar(5) = NULL,
	@prevappt datetime = NULL,
	@mastersubcase varchar(1) = NULL,
	@mastercasenbr int = NULL,
	@PublishOnWeb bit = NULL,
	@WebNotifyEmail varchar(200) = NULL,
	@AssessmentToAddress varchar(50) = NULL,
	@OCF25Date smalldatetime = NULL,
	@DateForminDispute smalldatetime = NULL,
	@AssessingFacility varchar(100) = NULL,
	@referralmethod int = NULL,
	@referraltype int = NULL,
	@CSR1 varchar(15) = NULL,
	@CSR2 varchar(15) = NULL,
	@LegalEvent bit = NULL,
	@PILegalEvent bit = NULL,
	@Transcode int = NULL,
	@PublishDocuments bit = NULL,
	@DateReceived datetime = NULL,
	@usddate3 datetime = NULL,
	@usddate4 datetime = NULL,
	@usddate5 datetime = NULL,
	@UsdBit1 bit = NULL,
	@UsdBit2 bit = NULL,
	@ClaimNbrExt varchar(50) = NULL,
	@DefParaLegal int = NULL,
	@AttorneyNote text = NULL,
	@BillingNote text = NULL,
	@InterpreterRequired bit = NULL,
	@TransportationRequired bit = NULL,
	@LanguageID int = NULL,
	@InputSourceID int = NULL,
	@ReqEWAccreditationID int = NULL,
	@RptInitialDraftDate datetime = NULL,
	@RptSentDate datetime = NULL,
	@ApptStatusId int = NULL,
	@CaseApptId int = NULL,
	@MMIReached bit = NULL,
	@MMITreatmentWeeks int = NULL
)
AS
BEGIN

	SET NOCOUNT OFF
	DECLARE @Err int

	UPDATE [tblCase]
	SET
		[chartnbr] = @chartnbr,
		[doctorlocation] = @doctorlocation,
		[clientcode] = @clientcode,
		[marketercode] = @marketercode,
		[schedulercode] = @schedulercode,
		[priority] = @priority,
		[status] = @status,
		[casetype] = @casetype,
		[dateadded] = @dateadded,
		[dateedited] = @dateedited,
		[useridadded] = @useridadded,
		[useridedited] = @useridedited,
		[schedcode] = @schedcode,
		[ApptDate] = @ApptDate,
		[Appttime] = @Appttime,
		[ApptMadeDate] = @ApptMadeDate,
		[claimnbr] = @claimnbr,
		[dateofinjury] = @dateofinjury,
		[allegation] = @allegation,
		[calledinby] = @calledinby,
		[notes] = @notes,
		[schedulenotes] = @schedulenotes,
		[requesteddoc] = @requesteddoc,
		[datemedsrecd] = @datemedsrecd,
		[typemedsrecd] = @typemedsrecd,
		[transreceived] = @transreceived,
		[shownoshow] = @shownoshow,
		[rptstatus] = @rptstatus,
		[reportverbal] = @reportverbal,
		[emailclient] = @emailclient,
		[emaildoctor] = @emaildoctor,
		[emailPattny] = @emailPattny,
		[faxclient] = @faxclient,
		[faxdoctor] = @faxdoctor,
		[faxPattny] = @faxPattny,
		[apptrptsselect] = @apptrptsselect,
		[chartprepselect] = @chartprepselect,
		[apptselect] = @apptselect,
		[awaittransselect] = @awaittransselect,
		[intransselect] = @intransselect,
		[inqaselect] = @inqaselect,
		[drchartselect] = @drchartselect,
		[datedrchart] = @datedrchart,
		[billedselect] = @billedselect,
		[miscselect] = @miscselect,
		[invoicedate] = @invoicedate,
		[invoiceamt] = @invoiceamt,
		[plaintiffattorneycode] = @plaintiffattorneycode,
		[defenseattorneycode] = @defenseattorneycode,
		[commitdate] = @commitdate,
		[servicecode] = @servicecode,
		[issuecode] = @issuecode,
		[doctorcode] = @doctorcode,
		[WCBNbr] = @WCBNbr,
		[specialinstructions] = @specialinstructions,
		[usdvarchar1] = @usdvarchar1,
		[usdvarchar2] = @usdvarchar2,
		[usddate1] = @usddate1,
		[usddate2] = @usddate2,
		[usdtext1] = @usdtext1,
		[usdtext2] = @usdtext2,
		[usdint1] = @usdint1,
		[usdint2] = @usdint2,
		[usdmoney1] = @usdmoney1,
		[usdmoney2] = @usdmoney2,
		[bComplete] = @bComplete,
		[bhanddelivery] = @bhanddelivery,
		[sinternalcasenbr] = @sinternalcasenbr,
		[sreqspecialty] = @sreqspecialty,
		[doctorspecialty] = @doctorspecialty,
		[feecode] = @feecode,
		[voucherselect] = @voucherselect,
		[voucheramt] = @voucheramt,
		[voucherdate] = @voucherdate,
		[icd9code] = @icd9code,
		[reccode] = @reccode,
		[billclientcode] = @billclientcode,
		[officecode] = @officecode,
		[QARep] = @QARep,
		[photoRqd] = @photoRqd,
		[CertifiedMail] = @CertifiedMail,
		[ICD9Code2] = @ICD9Code2,
		[ICD9Code3] = @ICD9Code3,
		[ICD9Code4] = @ICD9Code4,
		[PanelNbr] = @PanelNbr,
		[DoctorName] = @DoctorName,
		[HearingDate] = @HearingDate,
		[CertMailNbr] = @CertMailNbr,
		[laststatuschg] = @laststatuschg,
		[Jurisdiction] = @Jurisdiction,
		[prevappt] = @prevappt,
		[mastersubcase] = @mastersubcase,
		[mastercasenbr] = @mastercasenbr,
		[PublishOnWeb] = @PublishOnWeb,
		[WebNotifyEmail] = @WebNotifyEmail,
		[AssessmentToAddress] = @AssessmentToAddress,
		[OCF25Date] = @OCF25Date,
		[DateForminDispute] = @DateForminDispute,
		[AssessingFacility] = @AssessingFacility,
		[referralmethod] = @referralmethod,
		[referraltype] = @referraltype,
		[CSR1] = @CSR1,
		[CSR2] = @CSR2,
		[LegalEvent] = @LegalEvent,
		[PILegalEvent] = @PILegalEvent,
		[Transcode] = @Transcode,
		[PublishDocuments] = @PublishDocuments,
		[DateReceived] = @DateReceived,
		[usddate3] = @usddate3,
		[usddate4] = @usddate4,
		[usddate5] = @usddate5,
		[UsdBit1] = @UsdBit1,
		[UsdBit2] = @UsdBit2,
		[ClaimNbrExt] = @ClaimNbrExt,
		[DefParaLegal] = @DefParaLegal,
		[AttorneyNote] = @AttorneyNote,
		[BillingNote] = @BillingNote,
		[InterpreterRequired] = @InterpreterRequired,
		[TransportationRequired] = @TransportationRequired,
		[LanguageID] = @LanguageID,
		[InputSourceID] = @InputSourceID,
		[ReqEWAccreditationID] = @ReqEWAccreditationID,
		[RptInitialDraftDate] =	@RptInitialDraftDate,
		[RptSentDate] =	@RptSentDate,		
		[ApptStatusId] = @ApptStatusId,	
		[CaseApptId] = @CaseApptId,
		[MMIReached] = @MMIReached,
		[MMITreatmentWeeks] = @MMITreatmentWeeks
	WHERE
		[casenbr] = @casenbr


	SET @Err = @@Error


	RETURN @Err
END
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[proc_IMECase_Insert]') AND OBJECTPROPERTY(id,N'IsProcedure') = 1)
    DROP PROCEDURE [proc_IMECase_Insert];
GO

CREATE PROCEDURE [proc_IMECase_Insert]
(
	@casenbr int = NULL output,
	@chartnbr int = NULL,
	@doctorlocation varchar(10) = NULL,
	@clientcode int = NULL,
	@marketercode varchar(15) = NULL,
	@schedulercode varchar(15) = NULL,
	@priority varchar(15) = NULL,
	@status int = NULL,
	@casetype int = NULL,
	@dateadded datetime = NULL,
	@dateedited datetime = NULL,
	@useridadded varchar(15) = NULL,
	@useridedited varchar(15) = NULL,
	@schedcode int = NULL,
	@ApptDate datetime = NULL,
	@Appttime datetime = NULL,
	@ApptMadeDate datetime = NULL,
	@claimnbr varchar(50) = NULL,
	@dateofinjury datetime = NULL,
	@allegation text = NULL,
	@calledinby varchar(50) = NULL,
	@notes text = NULL,
	@schedulenotes text = NULL,
	@requesteddoc varchar(50) = NULL,
	@datemedsrecd datetime = NULL,
	@typemedsrecd varchar(50) = NULL,
	@transreceived datetime = NULL,
	@shownoshow int = NULL,
	@rptstatus varchar(50) = NULL,
	@reportverbal bit = NULL,
	@emailclient bit = NULL,
	@emaildoctor bit = NULL,
	@emailPattny bit = NULL,
	@faxclient bit = NULL,
	@faxdoctor bit = NULL,
	@faxPattny bit = NULL,
	@apptrptsselect bit = NULL,
	@chartprepselect bit = NULL,
	@apptselect bit = NULL,
	@awaittransselect bit = NULL,
	@intransselect bit = NULL,
	@inqaselect bit = NULL,
	@drchartselect bit = NULL,
	@datedrchart datetime = NULL,
	@billedselect bit = NULL,
	@miscselect bit = NULL,
	@invoicedate datetime = NULL,
	@invoiceamt money = NULL,
	@plaintiffattorneycode int = NULL,
	@defenseattorneycode int = NULL,
	@commitdate datetime = NULL,
	@servicecode int = NULL,
	@issuecode int = NULL,
	@doctorcode int = NULL,
	@WCBNbr varchar(50) = NULL,
	@specialinstructions text = NULL,
	@usdvarchar1 varchar(50) = NULL,
	@usdvarchar2 varchar(50) = NULL,
	@usddate1 datetime = NULL,
	@usddate2 datetime = NULL,
	@usdtext1 text = NULL,
	@usdtext2 text = NULL,
	@usdint1 int = NULL,
	@usdint2 int = NULL,
	@usdmoney1 money = NULL,
	@usdmoney2 money = NULL,
	@bComplete bit = NULL,
	@bhanddelivery bit = NULL,
	@sinternalcasenbr varchar(70) = NULL,
	@sreqspecialty varchar(50) = NULL,
	@doctorspecialty varchar(50) = NULL,
	@feecode int = NULL,
	@voucherselect bit = NULL,
	@voucheramt money = NULL,
	@voucherdate datetime = NULL,
	@icd9code varchar(70) = NULL,
	@reccode int = NULL,
	@billclientcode int = NULL,
	@officecode int = NULL,
	@QARep varchar(15) = NULL,
	@photoRqd bit = NULL,
	@CertifiedMail bit = NULL,
	@ICD9Code2 varchar(70) = NULL,
	@ICD9Code3 varchar(70) = NULL,
	@ICD9Code4 varchar(70) = NULL,
	@PanelNbr int = NULL,
	@DoctorName varchar(100) = NULL,
	@HearingDate smalldatetime = NULL,
	@CertMailNbr varchar(30) = NULL,
	@laststatuschg datetime = NULL,
	@Jurisdiction varchar(5) = NULL,
	@prevappt datetime = NULL,
	@mastersubcase varchar(1) = NULL,
	@mastercasenbr int = NULL,
	@PublishOnWeb bit = NULL,
	@WebNotifyEmail varchar(200) = NULL,
	@AssessmentToAddress varchar(50) = NULL,
	@OCF25Date smalldatetime = NULL,
	@DateForminDispute smalldatetime = NULL,
	@AssessingFacility varchar(100) = NULL,
	@referralmethod int = NULL,
	@referraltype int = NULL,
	@CSR1 varchar(15) = NULL,
	@CSR2 varchar(15) = NULL,
	@LegalEvent bit = NULL,
	@PILegalEvent bit = NULL,
	@Transcode int = NULL,
	@PublishDocuments bit = NULL,
	@DateReceived datetime = NULL,
	@usddate3 datetime = NULL,
	@usddate4 datetime = NULL,
	@usddate5 datetime = NULL,
	@UsdBit1 bit = NULL,
	@UsdBit2 bit = NULL,
	@ClaimNbrExt varchar(50) = NULL,
	@DefParaLegal int = NULL,
	@AttorneyNote text = NULL,
	@BillingNote text = NULL,
	@InterpreterRequired bit = NULL,
	@TransportationRequired bit = NULL,
	@LanguageID int = NULL,
	@InputSourceID int = NULL,
	@ReqEWAccreditationID int = NULL,
	@RptInitialDraftDate datetime = NULL,
	@RptSentDate datetime = NULL,
	@ApptStatusId int = NULL,
	@CaseApptId int = NULL,
	@MMIReached bit = NULL,
	@MMITreatmentWeeks int = NULL
	)
AS
BEGIN

	SET NOCOUNT OFF
	DECLARE @Err int

	INSERT
	INTO [tblCase]
	(
		[chartnbr],
		[doctorlocation],
		[clientcode],
		[marketercode],
		[schedulercode],
		[priority],
		[status],
		[casetype],
		[dateadded],
		[dateedited],
		[useridadded],
		[useridedited],
		[schedcode],
		[ApptDate],
		[Appttime],
		[ApptMadeDate],
		[claimnbr],
		[dateofinjury],
		[allegation],
		[calledinby],
		[notes],
		[schedulenotes],
		[requesteddoc],
		[datemedsrecd],
		[typemedsrecd],
		[transreceived],
		[shownoshow],
		[rptstatus],
		[reportverbal],
		[emailclient],
		[emaildoctor],
		[emailPattny],
		[faxclient],
		[faxdoctor],
		[faxPattny],
		[apptrptsselect],
		[chartprepselect],
		[apptselect],
		[awaittransselect],
		[intransselect],
		[inqaselect],
		[drchartselect],
		[datedrchart],
		[billedselect],
		[miscselect],
		[invoicedate],
		[invoiceamt],
		[plaintiffattorneycode],
		[defenseattorneycode],
		[commitdate],
		[servicecode],
		[issuecode],
		[doctorcode],
		[WCBNbr],
		[specialinstructions],
		[usdvarchar1],
		[usdvarchar2],
		[usddate1],
		[usddate2],
		[usdtext1],
		[usdtext2],
		[usdint1],
		[usdint2],
		[usdmoney1],
		[usdmoney2],
		[bComplete],
		[bhanddelivery],
		[sinternalcasenbr],
		[sreqspecialty],
		[doctorspecialty],
		[feecode],
		[voucherselect],
		[voucheramt],
		[voucherdate],
		[icd9code],
		[reccode],
		[billclientcode],
		[officecode],
		[QARep],
		[photoRqd],
		[CertifiedMail],
		[ICD9Code2],
		[ICD9Code3],
		[ICD9Code4],
		[PanelNbr],
		[DoctorName],
		[HearingDate],
		[CertMailNbr],
		[laststatuschg],
		[Jurisdiction],
		[prevappt],
		[mastersubcase],
		[mastercasenbr],
		[PublishOnWeb],
		[WebNotifyEmail],
		[AssessmentToAddress],
		[OCF25Date],
		[DateForminDispute],
		[AssessingFacility],
		[referralmethod],
		[referraltype],
		[CSR1],
		[CSR2],
		[LegalEvent],
		[PILegalEvent],
		[Transcode],
		[PublishDocuments],
		[DateReceived],
		[usddate3],
		[usddate4],
		[usddate5],
		[UsdBit1],
		[UsdBit2],
		[ClaimNbrExt],
		[DefParaLegal],
		[AttorneyNote],
		[BillingNote],
		[InterpreterRequired],
		[TransportationRequired],
		[LanguageID],
		[InputSourceID],
		[ReqEWAccreditationID],
		[RptInitialDraftDate],
		[RptSentDate],
		[ApptStatusId],
		[CaseApptId],
		[MMIReached],
		[MMITreatmentWeeks]					
	)
	VALUES
	(
		@chartnbr,
		@doctorlocation,
		@clientcode,
		@marketercode,
		@schedulercode,
		@priority,
		@status,
		@casetype,
		@dateadded,
		@dateedited,
		@useridadded,
		@useridedited,
		@schedcode,
		@ApptDate,
		@Appttime,
		@ApptMadeDate,
		@claimnbr,
		@dateofinjury,
		@allegation,
		@calledinby,
		@notes,
		@schedulenotes,
		@requesteddoc,
		@datemedsrecd,
		@typemedsrecd,
		@transreceived,
		@shownoshow,
		@rptstatus,
		@reportverbal,
		@emailclient,
		@emaildoctor,
		@emailPattny,
		@faxclient,
		@faxdoctor,
		@faxPattny,
		@apptrptsselect,
		@chartprepselect,
		@apptselect,
		@awaittransselect,
		@intransselect,
		@inqaselect,
		@drchartselect,
		@datedrchart,
		@billedselect,
		@miscselect,
		@invoicedate,
		@invoiceamt,
		@plaintiffattorneycode,
		@defenseattorneycode,
		@commitdate,
		@servicecode,
		@issuecode,
		@doctorcode,
		@WCBNbr,
		@specialinstructions,
		@usdvarchar1,
		@usdvarchar2,
		@usddate1,
		@usddate2,
		@usdtext1,
		@usdtext2,
		@usdint1,
		@usdint2,
		@usdmoney1,
		@usdmoney2,
		@bComplete,
		@bhanddelivery,
		@sinternalcasenbr,
		@sreqspecialty,
		@doctorspecialty,
		@feecode,
		@voucherselect,
		@voucheramt,
		@voucherdate,
		@icd9code,
		@reccode,
		@billclientcode,
		@officecode,
		@QARep,
		@photoRqd,
		@CertifiedMail,
		@ICD9Code2,
		@ICD9Code3,
		@ICD9Code4,
		@PanelNbr,
		@DoctorName,
		@HearingDate,
		@CertMailNbr,
		@laststatuschg,
		@Jurisdiction,
		@prevappt,
		@mastersubcase,
		@mastercasenbr,
		@PublishOnWeb,
		@WebNotifyEmail,
		@AssessmentToAddress,
		@OCF25Date,
		@DateForminDispute,
		@AssessingFacility,
		@referralmethod,
		@referraltype,
		@CSR1,
		@CSR2,
		@LegalEvent,
		@PILegalEvent,
		@Transcode,
		@PublishDocuments,
		@DateReceived,
		@usddate3,
		@usddate4,
		@usddate5,
		@UsdBit1,
		@UsdBit2,
		@ClaimNbrExt,
		@DefParaLegal,
		@AttorneyNote,
		@BillingNote,
		@InterpreterRequired,
		@TransportationRequired,
		@LanguageID,
		@InputSourceID,		
		@ReqEWAccreditationID,
		@RptInitialDraftDate,
		@RptSentDate,
		@ApptStatusId,
		@CaseApptId,
		@MMIReached,
		@MMITreatmentWeeks				
	)

	SET @Err = @@Error

	SELECT @casenbr = SCOPE_IDENTITY()

	RETURN @Err
END
GO


--Remove unused stored proc or view
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[vwDupTest]') AND OBJECTPROPERTY(id,N'IsView') = 1)
    DROP VIEW vwDupTest
GO
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[vwExportMAS90]') AND OBJECTPROPERTY(id,N'IsView') = 1)
    DROP VIEW vwExportMAS90
GO
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[vwExportQBAcct]') AND OBJECTPROPERTY(id,N'IsView') = 1)
    DROP VIEW vwExportQBAcct
GO
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[vwExportQBClient]') AND OBJECTPROPERTY(id,N'IsView') = 1)
    DROP VIEW vwExportQBClient
GO
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[vwQBKey]') AND OBJECTPROPERTY(id,N'IsView') = 1)
    DROP VIEW vwQBKey
GO
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[vwCompany]') AND OBJECTPROPERTY(id,N'IsView') = 1)
    DROP VIEW vwCompany
GO
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[vwInvoiceTax]') AND OBJECTPROPERTY(id,N'IsView') = 1)
    DROP VIEW vwInvoiceTax
GO
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[vwlatecancel]') AND OBJECTPROPERTY(id,N'IsView') = 1)
    DROP VIEW vwlatecancel
GO
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[vwexportacct]') AND OBJECTPROPERTY(id,N'IsView') = 1)
    DROP VIEW vwexportacct
GO
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[spDoctors]') AND OBJECTPROPERTY(id,N'IsProcedure') = 1)
    DROP PROCEDURE spDoctors
GO






--Remove unused billing client fields from tblCase
ALTER TABLE tblCase
 DROP COLUMN BillCompany
GO
ALTER TABLE tblCase
 DROP COLUMN BillContact
GO
ALTER TABLE tblCase
 DROP COLUMN BillAddr1
GO
ALTER TABLE tblCase
 DROP COLUMN BillAddr2
GO
ALTER TABLE tblCase
 DROP COLUMN BillCity
GO
ALTER TABLE tblCase
 DROP COLUMN BillState
GO
ALTER TABLE tblCase
 DROP COLUMN BillZip
GO
ALTER TABLE tblCase
 DROP COLUMN BillFax
GO
ALTER TABLE tblCase
 DROP COLUMN BillARKey
GO





UPDATE tblControl SET DBVersion='2.07'
GO
