CREATE TABLE [dbo].[tblWebDictationStatus] (
    [DictationStatusID]     INT           IDENTITY (1, 1) NOT NULL,
    [CaseNbr]               INT           NULL,
    [DoctorCode]            INT           NULL,
    [DictationFileName]     VARCHAR (255) NULL,
    [DictationFileSize]     BIGINT        NULL,
    [DictationStatus]       VARCHAR (50)  NULL,
    [UserIDAdded]           VARCHAR (50)  NULL,
    [DateAdded]             SMALLDATETIME NULL,
    [UserIDEdited]          VARCHAR (50)  NULL,
    [DateEdited]            SMALLDATETIME NULL,
    [DictationCompleteDate] SMALLDATETIME NULL,
    CONSTRAINT [PK_tblDictationStatus] PRIMARY KEY CLUSTERED ([DictationStatusID] ASC) ON [PRIMARY]
) ON [PRIMARY];


GO

DROP TABLE [dbo].[tblWebReferral]
GO
CREATE TABLE [dbo].[tblWebReferral] (
    [WebReferralID]                INT           IDENTITY (1, 1) NOT NULL,
    [CaseNbr]                      INT           NULL,
    [ClaimNbr]                     VARCHAR (50)  NULL,
    [ClaimNbrExt]                  VARCHAR (50)  NULL,
    [ClientCode]                   INT           NULL,
    [ClientName]                   VARCHAR (100) NULL,
    [ServiceType]                  INT           NULL,
    [ServiceDesc]                  VARCHAR (MAX) NULL,
    [CaseType]                     INT           NULL,
    [CaseTypeDesc]                 VARCHAR (MAX) NULL,
    [Jurisdiction]                 VARCHAR (5)   NULL,
    [RequestedVenue]               VARCHAR (50)  NULL,
    [DateOfInjury1]                DATETIME      NULL,
    [DateOfInjury2]                DATETIME      NULL,
    [DateOfInjury3]                DATETIME      NULL,
    [DateOfInjury4]                DATETIME      NULL,
    [WCBNbr]                       VARCHAR (50)  NULL,
    [IMETimeframeReq]              VARCHAR (30)  NULL,
    [HearingDeadlineDate]          DATETIME      NULL,
    [AmendedRequest]               BIT           CONSTRAINT [DF_tblWebReferral_AmendedRequest] DEFAULT ((0)) NOT NULL,
    [ContactAttorney]              BIT           CONSTRAINT [DF_tblWebReferral_ContactAttorney] DEFAULT ((0)) NOT NULL,
    [ContactClaimant]              BIT           CONSTRAINT [DF_tblWebReferral_ContactClaimant] DEFAULT ((0)) NOT NULL,
    [ClaimantLocations]            VARCHAR (500) NULL,
    [ExamineePrefix]               VARCHAR (10)  NULL,
    [ExamineeFirstName]            VARCHAR (50)  NULL,
    [ExamineeLastName]             VARCHAR (50)  NULL,
    [ExamineeDOB]                  DATETIME      NULL,
    [ExamineeAddress1]             VARCHAR (50)  NULL,
    [ExamineeAddress2]             VARCHAR (50)  NULL,
    [ExamineeCity]                 VARCHAR (70)  NULL,
    [ExamineeState]                VARCHAR (5)   NULL,
    [ExamineeZip]                  VARCHAR (10)  NULL,
    [ExamineePhone1]               VARCHAR (15)  NULL,
    [ExamineePhone2]               VARCHAR (15)  NULL,
    [ExamineeMobilePhone]          VARCHAR (15)  NULL,
    [ExamineeFax]                  VARCHAR (15)  NULL,
    [ExamineeEmail]                VARCHAR (100) NULL,
    [ExamineeSSN]                  VARCHAR (15)  NULL,
    [ExamineeGender]               VARCHAR (10)  NULL,
    [TreatingPhysicianName]        VARCHAR (100) NULL,
    [TreatingPhysicianAddress1]    VARCHAR (80)  NULL,
    [TreatingPhysicianCity]        VARCHAR (70)  NULL,
    [TreatingPhysicianState]       VARCHAR (5)   NULL,
    [TreatingPhysicianZip]         VARCHAR (10)  NULL,
    [TreatingPhysicianPhone1]      VARCHAR (15)  NULL,
    [TreatingPhysicianPhone2]      VARCHAR (15)  NULL,
    [TreatingPhysicianFax]         VARCHAR (15)  NULL,
    [TreatingPhysicianEmail]       VARCHAR (100) NULL,
    [ProviderName]                 VARCHAR (100) NULL,
    [MedicalRecordStatus]          VARCHAR (30)  NULL,
    [InterpreterRequired]          BIT           CONSTRAINT [DF_tblWebReferral_InterpreterNeeded] DEFAULT ((0)) NOT NULL,
    [LanguageRequired]             BIT           CONSTRAINT [DF_tblWebReferral_InterpreterNeeded1] DEFAULT ((0)) NOT NULL,
    [Language]                     VARCHAR (50)  NULL,
    [TransportationRequired]       BIT           CONSTRAINT [DF_tblWebReferral_TransportationNeeded] DEFAULT ((0)) NOT NULL,
    [SendBillToContactName]        VARCHAR (100) NULL,
    [SendBillToCompanyName]        VARCHAR (100) NULL,
    [Issues]                       VARCHAR (MAX) NULL,
    [IssueDescriptions]            VARCHAR (MAX) NULL,
    [Problems]                     VARCHAR (MAX) NULL,
    [ProblemDescriptions]          VARCHAR (MAX) NULL,
    [Specialties]                  VARCHAR (MAX) NULL,
    [Degrees]                      VARCHAR (MAX) NULL,
    [DegreeDescriptions]           VARCHAR (MAX) NULL,
    [SpecialInstructions]          VARCHAR (MAX) NULL,
    [OtherComments]                VARCHAR (MAX) NULL,
    [PlaintiffAttorneyPrefix]      VARCHAR (10)  NULL,
    [PlaintiffAttorneyFirstName]   VARCHAR (50)  NULL,
    [PlaintiffAttorneyLastName]    VARCHAR (50)  NULL,
    [PlaintiffAttorneyCompany]     VARCHAR (100) NULL,
    [PlaintiffAttorneyAddress1]    VARCHAR (50)  NULL,
    [PlaintiffAttorneyAddress2]    VARCHAR (50)  NULL,
    [PlaintiffAttorneyCity]        VARCHAR (70)  NULL,
    [PlaintiffAttorneyState]       VARCHAR (5)   NULL,
    [PlaintiffAttorneyZip]         VARCHAR (10)  NULL,
    [PlaintiffAttorneyPhone1]      VARCHAR (15)  NULL,
    [PlaintiffAttorneyPhone2]      VARCHAR (15)  NULL,
    [PlaintiffAttorneyFax]         VARCHAR (15)  NULL,
    [PlaintiffAttorneyEmail]       VARCHAR (100) NULL,
    [DefenseAttorneyPrefix]        VARCHAR (10)  NULL,
    [DefenseAttorneyFirstName]     VARCHAR (50)  NULL,
    [DefenseAttorneyLastName]      VARCHAR (50)  NULL,
    [DefenseAttorneyCompany]       VARCHAR (100) NULL,
    [DefenseAttorneyAddress1]      VARCHAR (50)  NULL,
    [DefenseAttorneyAddress2]      VARCHAR (50)  NULL,
    [DefenseAttorneyCity]          VARCHAR (70)  NULL,
    [DefenseAttorneyState]         VARCHAR (5)   NULL,
    [DefenseAttorneyZip]           VARCHAR (10)  NULL,
    [DefenseAttorneyPhone1]        VARCHAR (15)  NULL,
    [DefenseAttorneyPhone2]        VARCHAR (15)  NULL,
    [DefenseAttorneyFax]           VARCHAR (15)  NULL,
    [DefenseAttorneyEmail]         VARCHAR (100) NULL,
    [CaseManagerPrefix]            VARCHAR (10)  NULL,
    [CaseManagerFirstName]         VARCHAR (50)  NULL,
    [CaseManagerLastName]          VARCHAR (50)  NULL,
    [CaseManagerCompany]           VARCHAR (100) NULL,
    [CaseManagerAddress1]          VARCHAR (50)  NULL,
    [CaseManagerAddress2]          VARCHAR (50)  NULL,
    [CaseManagerCity]              VARCHAR (70)  NULL,
    [CaseManagerState]             VARCHAR (5)   NULL,
    [CaseManagerZip]               VARCHAR (10)  NULL,
    [CaseManagerPhone1]            VARCHAR (15)  NULL,
    [CaseManagerPhone2]            VARCHAR (15)  NULL,
    [CaseManagerFax]               VARCHAR (15)  NULL,
    [CaseManagerEmail]             VARCHAR (100) NULL,
    [ClaimantEmployerCompany]      VARCHAR (100) NULL,
    [ClaimantEmployerFirstName]    VARCHAR (50)  NULL,
    [ClaimantEmployerLastName]     VARCHAR (50)  NULL,
    [ClaimantEmployerAddress1]     VARCHAR (50)  NULL,
    [ClaimantEmployerCity]         VARCHAR (70)  NULL,
    [ClaimantEmployerState]        VARCHAR (5)   NULL,
    [ClaimantEmployerZip]          VARCHAR (10)  NULL,
    [ClaimantEmployerPhone1]       VARCHAR (15)  NULL,
    [ClaimantEmployerPhone2]       VARCHAR (15)  NULL,
    [ClaimantEmployerFax]          VARCHAR (15)  NULL,
    [ClaimantEmployerEmail]        VARCHAR (100) NULL,
    [InsuringCompany]              VARCHAR (50)  NULL,
    [InsuredName]                  VARCHAR (100) NULL,
    [InsuredAddress1]              VARCHAR (50)  NULL,
    [InsuredCity]                  VARCHAR (70)  NULL,
    [InsuredState]                 VARCHAR (5)   NULL,
    [InsuredZip]                   VARCHAR (10)  NULL,
    [InsuredPhone1]                VARCHAR (15)  NULL,
    [InsuredPhone2]                VARCHAR (15)  NULL,
    [InsuredFax]                   VARCHAR (15)  NULL,
    [InsuredEmail]                 VARCHAR (100) NULL,
    [InsuredPolicyNumber]          VARCHAR (50)  NULL,
    [ThirdPartyBillingPrefix]      VARCHAR (10)  NULL,
    [ThirdPartyBillingFirstName]   VARCHAR (50)  NULL,
    [ThirdPartyBillingLastName]    VARCHAR (50)  NULL,
    [ThirdPartyBillingCompany]     VARCHAR (100) NULL,
    [ThirdPartyBillingAddress1]    VARCHAR (50)  NULL,
    [ThirdPartyBillingAddress2]    VARCHAR (50)  NULL,
    [ThirdPartyBillingCity]        VARCHAR (70)  NULL,
    [ThirdPartyBillingState]       VARCHAR (5)   NULL,
    [ThirdPartyBillingZip]         VARCHAR (10)  NULL,
    [ThirdPartyBillingPhone1]      VARCHAR (15)  NULL,
    [ThirdPartyBillingPhone2]      VARCHAR (15)  NULL,
    [ThirdPartyBillingFax]         VARCHAR (15)  NULL,
    [ThirdPartyBillingEmail]       VARCHAR (100) NULL,
    [OtherPartyAddressType]        VARCHAR (50)  NULL,
    [OtherPartyCompanyName]        VARCHAR (100) NULL,
    [OtherPartyFirstName]          VARCHAR (50)  NULL,
    [OtherPartyLastName]           VARCHAR (50)  NULL,
    [OtherPartyAddress1]           VARCHAR (50)  NULL,
    [OtherPartyAddress2]           VARCHAR (50)  NULL,
    [OtherPartyCity]               VARCHAR (70)  NULL,
    [OtherPartyState]              VARCHAR (5)   NULL,
    [OtherPartyZip]                VARCHAR (10)  NULL,
    [OtherPartyPhone1]             VARCHAR (15)  NULL,
    [OtherPartyPhone2]             VARCHAR (15)  NULL,
    [OtherPartyFax]                VARCHAR (15)  NULL,
    [OtherPartyEmail]              VARCHAR (100) NULL,
    [SendToOtherParty]             VARCHAR (MAX) NULL,
    [ICDCode1]                     VARCHAR (70)  NULL,
    [ICDStatus1]                   VARCHAR (20)  NULL,
    [ICDBodySide1]                 VARCHAR (20)  NULL,
    [ICDDescription1]              VARCHAR (100) NULL,
    [ICDCode2]                     VARCHAR (70)  NULL,
    [ICDStatus2]                   VARCHAR (20)  NULL,
    [ICDBodySide2]                 VARCHAR (20)  NULL,
    [ICDDescription2]              VARCHAR (100) NULL,
    [ICDCode3]                     VARCHAR (70)  NULL,
    [ICDStatus3]                   VARCHAR (20)  NULL,
    [ICDBodySide3]                 VARCHAR (20)  NULL,
    [ICDDescription3]              VARCHAR (100) NULL,
    [ICDCode4]                     VARCHAR (70)  NULL,
    [ICDStatus4]                   VARCHAR (20)  NULL,
    [ICDBodySide4]                 VARCHAR (20)  NULL,
    [ICDDescription4]              VARCHAR (100) NULL,
    [PreviousClaimsClaimNbr1]      VARCHAR (50)  NULL,
    [PreviousClaimsPPDAward1]      VARCHAR (30)  NULL,
    [PreviousClaimsMajorBodyPart1] VARCHAR (50)  NULL,
    [PreviousClaimsMinorBodyPart1] VARCHAR (50)  NULL,
    [PreviousClaimsBodySide1]      VARCHAR (50)  NULL,
    [Notes]                        VARCHAR (MAX) NULL,
    [AttorneyNote]                 VARCHAR (MAX) NULL,
    [ScheduleNotes]                VARCHAR (MAX) NULL,
    [BillingNote]                  VARCHAR (MAX) NULL,
    [OfficeCode]                   INT           NULL,
    [OfficeDesc]                   VARCHAR (100) NULL,
    [RecCode]                      INT           NULL,
    [RecDesc]                      VARCHAR (100) NULL,
    [QARep]                        VARCHAR (50)  NULL,
    [Status]                       INT           NULL,
    [StatusDesc]                   VARCHAR (100) NULL,
    [SchedCode]                    INT           NULL,
    [ReportVerbal]                 BIT           CONSTRAINT [DF_tblWebReferral_ReportVerbal] DEFAULT ((0)) NOT NULL,
    [PhotoRqd]                     BIT           CONSTRAINT [DF_tblWebReferral_PhotoRqd] DEFAULT ((0)) NOT NULL,
    [CertifiedMail]                BIT           CONSTRAINT [DF_tblWebReferral_CertifiedMail] DEFAULT ((0)) NOT NULL,
    [HearingDate]                  DATETIME      NULL,
    [ApptDate]                     DATETIME      NULL,
    [ApptTime]                     DATETIME      NULL,
    [ApptMadeDate]                 DATETIME      NULL,
    [ApptStatusId]                 INT           NULL,
    [CaseApptId]                   INT           NULL,
    [CommitDate]                   DATETIME      NULL,
    [DateReceived]                 DATETIME      NULL,
    [DateAcknowledged]             DATETIME      NULL,
    [DateAdded]                    DATETIME      NULL,
    [UserIdAdded]                  VARCHAR (50)  NULL,
    [DateEdited]                   DATETIME      NULL,
    [UserIdEdited]                 VARCHAR (50)  NULL,
    CONSTRAINT [PK_tblWebReferral] PRIMARY KEY CLUSTERED ([WebReferralID] ASC) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY];
GO


UPDATE tblControl SET DBVersion='3.25'
GO