/*
Deployment script for sTargetDB

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
/*
:setvar DatabaseName "sTargetDB"
:setvar DefaultFilePrefix "sTargetDB"
:setvar DefaultDataPath ""
:setvar DefaultLogPath ""
*/

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO

IF (SELECT OBJECT_ID('tempdb..#tmpErrors')) IS NOT NULL DROP TABLE #tmpErrors
GO
CREATE TABLE #tmpErrors (Error int)
GO
SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
GO
BEGIN TRANSACTION
GO
PRINT N'Dropping [dbo].[DF_tblBusinessRule_AllowOverride]...';


GO
ALTER TABLE [dbo].[tblBusinessRule] DROP CONSTRAINT [DF_tblBusinessRule_AllowOverride];


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Dropping [dbo].[DF_tblBusinessRule_IsActive]...';


GO
ALTER TABLE [dbo].[tblBusinessRule] DROP CONSTRAINT [DF_tblBusinessRule_IsActive];


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Dropping [dbo].[DF_tblExceptionList_Status]...';


GO
ALTER TABLE [dbo].[tblExceptionList] DROP CONSTRAINT [DF_tblExceptionList_Status];


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Altering [dbo].[tblAcctHeader]...';


GO
ALTER TABLE [dbo].[tblAcctHeader]
    ADD [BulkBillingID] INT NULL;


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Starting rebuilding table [dbo].[tblBusinessRule]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_tblBusinessRule] (
    [BusinessRuleID]   INT           NOT NULL,
    [Name]             VARCHAR (35)  NULL,
    [Category]         VARCHAR (20)  NULL,
    [Descrip]          VARCHAR (150) NULL,
    [IsActive]         BIT           CONSTRAINT [DF_tblBusinessRule_IsActive] DEFAULT ((1)) NOT NULL,
    [EventID]          INT           NULL,
    [AllowOverride]    BIT           CONSTRAINT [DF_tblBusinessRule_AllowOverride] DEFAULT ((0)) NOT NULL,
    [Param1Desc]       VARCHAR (20)  NULL,
    [Param2Desc]       VARCHAR (20)  NULL,
    [Param3Desc]       VARCHAR (20)  NULL,
    [Param4Desc]       VARCHAR (20)  NULL,
    [Param5Desc]       VARCHAR (20)  NULL,
    [BrokenRuleAction] INT           NOT NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_tblBusinessRule1] PRIMARY KEY CLUSTERED ([BusinessRuleID] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[tblBusinessRule])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_tblBusinessRule] ([BusinessRuleID], [Name], [Category], [Descrip], [IsActive], [EventID], [AllowOverride], [Param1Desc], [Param2Desc], [Param3Desc], [Param4Desc], [Param5Desc], [BrokenRuleAction])
        SELECT   [BusinessRuleID],
                 [Name],
                 [Category],
                 [Descrip],
                 [IsActive],
                 [EventID],
                 [AllowOverride],
                 [Param1Desc],
                 [Param2Desc],
                 [Param3Desc],
                 [Param4Desc],
                 [Param5Desc],
                 [BrokenRuleAction]
        FROM     [dbo].[tblBusinessRule]
        ORDER BY [BusinessRuleID] ASC;
    END

DROP TABLE [dbo].[tblBusinessRule];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_tblBusinessRule]', N'tblBusinessRule';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_tblBusinessRule1]', N'PK_tblBusinessRule', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Altering [dbo].[tblCaseContactRequest]...';


GO
ALTER TABLE [dbo].[tblCaseContactRequest]
    ADD [DateNotificationSent] SMALLDATETIME NULL,
        [DateAdded]            SMALLDATETIME NULL,
        [UserIDAdded]          VARCHAR (50)  NULL;


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Altering [dbo].[tblCaseDocumentsDicom]...';


GO
ALTER TABLE [dbo].[tblCaseDocumentsDicom] DROP COLUMN [AcquisitionDate], COLUMN [AcquisitionTime], COLUMN [ContentDate], COLUMN [ContentTime], COLUMN [Filename], COLUMN [Filesize], COLUMN [InstanceDirRecType], COLUMN [InstanceNumber], COLUMN [InstanceUID], COLUMN [InstitutionAddress], COLUMN [InstitutionalDepartmentName], COLUMN [MediaStorageSopInstanceUid], COLUMN [Notes], COLUMN [PerformedProcedureStepDescription], COLUMN [ProtocolName], COLUMN [ReferenceFileID], COLUMN [ReferringPhysiciansName], COLUMN [RequestedProcedureDescription], COLUMN [SeriesDate], COLUMN [SeriesDescription], COLUMN [SeriesDirRecType], COLUMN [SeriesModality], COLUMN [SeriesNumber], COLUMN [SeriesTime], COLUMN [SeriesUID], COLUMN [SopClass];


GO
ALTER TABLE [dbo].[tblCaseDocumentsDicom] ALTER COLUMN [MediaType] VARCHAR (100) NULL;


GO
ALTER TABLE [dbo].[tblCaseDocumentsDicom]
    ADD [Images]          INT CONSTRAINT [DF_tblCaseDocumentsDicom_Images] DEFAULT ((0)) NOT NULL,
        [ImagesValidated] INT CONSTRAINT [DF_tblCaseDocumentsDicom_ImagesValidated] DEFAULT ((0)) NOT NULL,
        [ImagesExist]     INT CONSTRAINT [DF_tblCaseDocumentsDicom_ImagesExist] DEFAULT ((0)) NOT NULL,
        [StorageID]       INT NULL;


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Altering [dbo].[tblCaseHistory]...';


GO
ALTER TABLE [dbo].[tblCaseHistory]
    ADD [AlertType] INT CONSTRAINT [DF_tblCaseHistory_AlertType] DEFAULT ((0)) NOT NULL;


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Altering [dbo].[tblCaseSLARuleDetail]...';


GO
ALTER TABLE [dbo].[tblCaseSLARuleDetail]
    ADD [SysExceptionFired] BIT NULL;


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Altering [dbo].[tblDoctor]...';


GO
ALTER TABLE [dbo].[tblDoctor]
    ADD [EWParentDocID] INT NULL;


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Altering [dbo].[tblDocument]...';


GO
ALTER TABLE [dbo].[tblDocument]
    ADD [FunctionCode]               VARCHAR (30) NULL,
        [CMSBox12]                   VARCHAR (30) NULL,
        [CMSBox12Date]               VARCHAR (30) NULL,
        [CMSBox13]                   VARCHAR (30) NULL,
        [CMSBox14Qual]               VARCHAR (30) NULL,
        [CMSBox26]                   VARCHAR (30) NULL,
        [CMSLineItemAmtType]         VARCHAR (30) NULL,
        [ShowProductDescOnClaimForm] INT          CONSTRAINT [DF_tblDocument_ShowProductDescOnClaimForm] DEFAULT ((0)) NOT NULL;


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Altering [dbo].[tblExceptionDefinition]...';


GO
ALTER TABLE [dbo].[tblExceptionDefinition]
    ADD [AllSLARuleDetail] BIT CONSTRAINT [DF_tblExceptionDefinition_SLARuleDetail] DEFAULT ((1)) NOT NULL;


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Starting rebuilding table [dbo].[tblExceptionList]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_tblExceptionList] (
    [ExceptionID]  INT           NOT NULL,
    [Description]  VARCHAR (100) NOT NULL,
    [Status]       VARCHAR (10)  CONSTRAINT [DF_tblExceptionList_Status] DEFAULT ('Active') NULL,
    [DateAdded]    DATETIME      NULL,
    [UserIDAdded]  VARCHAR (50)  NULL,
    [DateEdited]   DATETIME      NULL,
    [UserIDEdited] VARCHAR (50)  NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_tblExceptionList1] PRIMARY KEY CLUSTERED ([ExceptionID] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[tblExceptionList])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_tblExceptionList] ([ExceptionID], [Description], [Status], [DateAdded], [UserIDAdded], [DateEdited], [UserIDEdited])
        SELECT   [ExceptionID],
                 [Description],
                 [Status],
                 [DateAdded],
                 [UserIDAdded],
                 [DateEdited],
                 [UserIDEdited]
        FROM     [dbo].[tblExceptionList]
        ORDER BY [ExceptionID] ASC;
    END

DROP TABLE [dbo].[tblExceptionList];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_tblExceptionList]', N'tblExceptionList';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_tblExceptionList1]', N'PK_tblExceptionList', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Altering [dbo].[tblPOPBVoucher]...';


GO
ALTER TABLE [dbo].[tblPOPBVoucher]
    ADD [CaseDoctorCode] INT NULL;


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Altering [dbo].[tblSLARuleDetail]...';


GO
ALTER TABLE [dbo].[tblSLARuleDetail]
    ADD [ExceptionDefIDTmp] INT NULL;


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[tblConfiguration]...';


GO
CREATE TABLE [dbo].[tblConfiguration] (
    [ConfigurationID]   INT           NOT NULL,
    [Name]              VARCHAR (30)  NULL,
    [Active]            BIT           NOT NULL,
    [ConfigurationType] VARCHAR (15)  NULL,
    [DateEdited]        DATETIME      NOT NULL,
    [UserIDEdited]      VARCHAR (15)  NULL,
    [Param]             VARCHAR (MAX) NULL,
    CONSTRAINT [PK_tblConfiguration] PRIMARY KEY CLUSTERED ([ConfigurationID] ASC)
);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[tblExceptionDefSLARuleDetail]...';


GO
CREATE TABLE [dbo].[tblExceptionDefSLARuleDetail] (
    [ExceptionDefID]  INT NOT NULL,
    [SLARuleDetailID] INT NOT NULL,
    CONSTRAINT [PK_tblExceptionDefSLARuleDetail] PRIMARY KEY CLUSTERED ([ExceptionDefID] ASC, [SLARuleDetailID] ASC)
);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[tblStorage]...';


GO
CREATE TABLE [dbo].[tblStorage] (
    [StorageID]     INT           IDENTITY (1, 1) NOT NULL,
    [StorageTypeID] INT           NOT NULL,
    [ExtStorageKey] VARCHAR (30)  NULL,
    [DateAdded]     DATETIME      NOT NULL,
    [UserIDAdded]   VARCHAR (15)  NULL,
    [IsDeleted]     BIT           NOT NULL,
    [Param]         VARCHAR (100) NULL,
    CONSTRAINT [PK_tblStorage] PRIMARY KEY CLUSTERED ([StorageID] ASC)
);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[DF_tblConfiguration_Active]...';


GO
ALTER TABLE [dbo].[tblConfiguration]
    ADD CONSTRAINT [DF_tblConfiguration_Active] DEFAULT ((1)) FOR [Active];


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[DF_tblConfiguration_DateEdited]...';


GO
ALTER TABLE [dbo].[tblConfiguration]
    ADD CONSTRAINT [DF_tblConfiguration_DateEdited] DEFAULT (getdate()) FOR [DateEdited];


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[DF_tblStorage_IsDeleted]...';


GO
ALTER TABLE [dbo].[tblStorage]
    ADD CONSTRAINT [DF_tblStorage_IsDeleted] DEFAULT ((0)) FOR [IsDeleted];


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Altering [dbo].[vwEDIExportSummary]...';


GO
ALTER VIEW vwEDIExportSummary
AS
    SELECT  tblCase.CaseNbr ,
			tblAcctingTrans.SeqNO ,
			tblAcctHeader.HeaderID ,
            tblAcctHeader.DocumentType ,
            tblAcctHeader.DocumentNbr ,
            tblAcctingTrans.StatusCode ,
            tblAcctHeader.EDIBatchNbr ,
            tblAcctHeader.EDIStatus ,
            tblAcctHeader.EDILastStatusChg ,
            tblAcctHeader.EDIRejectedMsg ,
            tblQueues.StatusDesc ,
            tblExaminee.LastName + ', ' + tblExaminee.FirstName AS ExamineeName ,
            tblAcctingTrans.DrOpType ,
            CASE ISNULL(tblCase.PanelNbr, 0)
              WHEN 0
              THEN CASE tblAcctingTrans.DrOpType
                     WHEN 'DR'
                     THEN ISNULL(tblDoctor.LastName, '') + ', '
                          + ISNULL(tblDoctor.FirstName, '')
                     WHEN ''
                     THEN ISNULL(tblDoctor.LastName, '') + ', '
                          + ISNULL(tblDoctor.FirstName, '')
                     WHEN '' THEN ISNULL(tblCase.DoctorName, '')
                     WHEN 'OP' THEN tblDoctor.CompanyName
                   END
              ELSE CASE tblAcctingTrans.DrOpType
                     WHEN 'DR' THEN ISNULL(tblCase.DoctorName, '')
                     WHEN '' THEN ISNULL(tblCase.DoctorName, '')
                     WHEN 'OP' THEN tblDoctor.CompanyName
                   END
            END AS DoctorName ,
            tblClient.LastName + ', ' + tblClient.FirstName AS ClientName ,
            tblCompany.IntName AS CompanyName ,
            tblCase.Priority ,
            tblCase.ApptDate ,
            tblCase.DateAdded ,
            tblCase.ClaimNbr ,
            tblCase.DoctorLocation ,
            tblCase.ApptTime ,
            tblCase.DateEdited ,
            tblCase.UserIDEdited ,
            tblClient.Email AS AdjusterEmail ,
            tblClient.Fax AS AdjusterFax ,
            tblCase.MarketerCode ,
            tblCase.UserIDAdded ,
            tblAcctHeader.DocumentDate ,
            tblAcctHeader.INBatchSelect ,
            tblAcctHeader.VOBatchSelect ,
            tblAcctHeader.TaxCode ,
            tblAcctHeader.TaxTotal ,
            tblAcctHeader.DocumentTotal ,
            tblAcctHeader.DocumentStatus ,
            tblCase.ClientCode ,
            tblCase.DoctorCode ,
            tblAcctHeader.BatchNbr ,
            tblCase.OfficeCode ,
            tblCase.SchedulerCode ,
            tblClient.CompanyCode ,
            tblCase.QARep ,
            tblCase.PanelNbr ,
            DATEDIFF(DAY, tblAcctingTrans.LastStatusChg, GETDATE()) AS IQ ,
            tblCase.MasterSubCase ,
            tblqueues_1.StatusDesc AS CaseStatus ,
            tblQueues.FunctionCode ,
            tblServices.ShortDesc AS Service ,
            tblCase.ServiceCode ,
            tblCase.CaseType ,
            tblCase.InputSourceID ,
            -- tblCompany.BulkBillingID ,
			ISNULL(tblAcctHeader.BulkBillingID, tblCompany.BulkBillingID) AS BulkBillingID,
            tblAcctHeader.EDISubmissionCount ,
            tblAcctHeader.EDISubmissionDateTime , 
			tblCase.ExtCaseNbr, 
			tblCompany.ParentCompanyID 
    FROM    tblAcctHeader
            INNER JOIN tblAcctingTrans ON tblAcctHeader.SeqNo = tblAcctingTrans.SeqNO
            INNER JOIN tblCase ON tblAcctHeader.CaseNbr = tblCase.CaseNbr
            LEFT OUTER JOIN tblCompany ON tblAcctHeader.CompanyCode = tblCompany.CompanyCode
            LEFT OUTER JOIN tblClient ON tblAcctHeader.ClientCode = tblClient.ClientCode
            INNER JOIN tblQueues ON tblAcctingTrans.StatusCode = tblQueues.StatusCode
            INNER JOIN tblQueues tblqueues_1 ON tblCase.Status = tblqueues_1.StatusCode
            LEFT OUTER JOIN tblDoctor ON tblAcctHeader.DrOpCode = tblDoctor.DoctorCode
            LEFT OUTER JOIN tblExaminee ON tblCase.ChartNbr = tblExaminee.ChartNbr
            INNER JOIN tblServices ON tblServices.ServiceCode = tblCase.ServiceCode
    WHERE   ( tblAcctingTrans.StatusCode <> 20 )
            AND ( tblAcctHeader.DocumentStatus = 'Final' )
GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Altering [dbo].[vwDocument]...';


GO
ALTER VIEW vwDocument
AS
    SELECT  tblCase.CaseNbr ,
			tblCase.ExtCaseNbr,
            tblCase.ClaimNbr ,
			tblCase.AddlClaimNbrs, 

            tblApptStatus.Name AS ApptStatus ,

            tblCase.ApptDate ,
            tblCase.Appttime ,
            tblCase.CaseApptID ,
            tblCase.ApptStatusID ,

            tblCase.DoctorCode ,
            tblCase.DoctorLocation ,

			tblcase.EmployerID ,
			tblcase.EmployerAddressID ,

            tblExaminee.City AS ExamineeCity ,
            UPPER(tblExaminee.State) AS ExamineeState ,
            tblExaminee.Zip AS ExamineeZip ,
            tblExaminee.lastName AS ExamineelastName ,
            tblExaminee.firstName AS ExamineefirstName ,
            tblExaminee.Addr1 AS ExamineeAddr1 ,
            tblExaminee.Addr2 AS ExamineeAddr2 ,
            tblExaminee.City + ', ' + UPPER(tblExaminee.State) + '  ' + tblExaminee.Zip AS ExamineeCityStateZip ,
            tblExaminee.Country ,
            tblExaminee.PolicyNumber ,
            tblExaminee.SSN ,
            tblExaminee.firstName + ' ' + tblExaminee.lastName AS ExamineeName ,
            tblExaminee.Phone1 AS ExamineePhone ,
			tblExaminee.WorkPhone AS ExamineeWorkPhone,
            tblExaminee.sex ,
            tblExaminee.DOB ,
            tblExaminee.county AS Examineecounty ,
            tblExaminee.Prefix AS ExamineePrefix ,

            tblExaminee.USDvarchar1 AS ExamineeUSDvarchar1 ,
            tblExaminee.USDvarchar2 AS ExamineeUSDvarchar2 ,
            tblExaminee.USDDate1 AS ExamineeUSDDate1 ,
            tblExaminee.USDDate2 AS ExamineeUSDDate2 ,
            tblExaminee.USDtext1 AS ExamineeUSDtext1 ,
            tblExaminee.USDtext2 AS ExamineeUSDtext2 ,
            tblExaminee.USDint1 AS ExamineeUSDint1 ,
            tblExaminee.USDint2 AS ExamineeUSDint2 ,
            tblExaminee.USDmoney1 AS ExamineeUSDmoney1 ,
            tblExaminee.USDmoney2 AS ExamineeUSDmoney2 ,

            tblExaminee.note AS ChartNotes ,
            tblExaminee.Fax AS ExamineeFax ,
            tblExaminee.Email AS ExamineeEmail ,
            tblExaminee.insured AS Examineeinsured ,
            tblExaminee.middleinitial AS Examineemiddleinitial ,
            tblExaminee.InsuredAddr1 ,
            tblExaminee.InsuredCity ,
            UPPER(tblExaminee.InsuredState) AS InsuredState ,
            tblExaminee.InsuredZip ,
            tblExaminee.InsuredSex ,
            tblExaminee.InsuredRelationship ,
            tblExaminee.InsuredPhone ,
            tblExaminee.InsuredPhoneExt ,
            tblExaminee.InsuredFax ,
            tblExaminee.InsuredEmail ,
            tblExaminee.ExamineeStatus ,

            tblExaminee.TreatingPhysician ,
            tblExaminee.TreatingPhysicianAddr1 ,
            tblExaminee.TreatingPhysicianCity ,
            UPPER(tblExaminee.TreatingPhysicianState) AS TreatingPhysicianState ,
            tblExaminee.TreatingPhysicianZip ,
            tblExaminee.TreatingPhysicianPhone ,
            tblExaminee.TreatingPhysicianPhoneExt ,
            tblExaminee.TreatingPhysicianFax ,
            tblExaminee.TreatingPhysicianEmail ,
            tblExaminee.TreatingPhysicianLicenseNbr ,
			tblExaminee.TreatingPhysicianTaxID ,
            tblExaminee.TreatingPhysicianCredentials AS TreatingPhysicianDegree ,
			tblExaminee.TreatingPhysicianNPINbr,

			(Case ISNULL(tblcase.EmployerID, 0)
              WHEN 0
              THEN tblExaminee.Employer  
			  ELSE tblEmployer.Name  
			  END) AS Employer,  

			(Case ISNULL(tblcase.EmployerID , 0)
              WHEN 0
              THEN tblExaminee.EmployerAddr1  
			  ELSE tblEmployerAddress.Address1 
			  END) AS EmployerAddr1,  

			(Case ISNULL(tblcase.EmployerID , 0)
              WHEN 0
              THEN tblExaminee.EmployerCity  
			  ELSE tblEmployerAddress.City  
			  END) AS EmployerCity,  

			(Case ISNULL(tblcase.EmployerID , 0)
              WHEN 0
              THEN UPPER(tblExaminee.EmployerState)  
			  ELSE UPPER(tblEmployerAddress.State)  
			  END) AS EmployerState,  

			(Case ISNULL(tblcase.EmployerID , 0)
              WHEN 0
              THEN tblExaminee.EmployerZip  
			  ELSE tblEmployerAddress.Zip  
			  END) AS EmployerZip,  

			(Case ISNULL(tblcase.EmployerID , 0)
              WHEN 0
              THEN tblExaminee.EmployerPhone  
			  ELSE tblEmployerAddress.Phone  
			  END) AS EmployerPhone,  

			(Case ISNULL(tblcase.EmployerID , 0)
              WHEN 0
              THEN tblExaminee.EmployerPhoneExt  
			  ELSE tblEmployerAddress.PhoneExt  
			  END) AS EmployerPhoneExt,  

			(Case ISNULL(tblcase.EmployerID , 0)
              WHEN 0
              THEN tblExaminee.EmployerFax  
			  ELSE tblEmployerAddress.Fax  
			  END) AS EmployerFax,  
            
			(Case ISNULL(tblcase.EmployerID , 0)
              WHEN 0
              THEN tblExaminee.EmployerEmail  
			  ELSE tblEmployerAddress.Email  
			  END) AS EmployerEmail,  
            
			(Case ISNULL(tblcase.EmployerID , 0)
              WHEN 0
              THEN tblExaminee.EmployerContactLastName  
			  ELSE tblEmployerAddress.ContactLast  
			  END) AS EmployerContactLastName,  
            
			(Case ISNULL(tblcase.EmployerID , 0)
              WHEN 0
              THEN tblExaminee.EmployerContactFirstName  
			  ELSE tblEmployerAddress.ContactFirst  
			  END) AS EmployerContactFirstName,  

            tblClient.firstName + ' ' + tblClient.lastName AS ClientName ,
            tblClient.Phone1 + ' ' + ISNULL(tblClient.Phone1ext, ' ') AS ClientPhone ,
            tblClient.Phone2 + ' ' + ISNULL(tblClient.Phone2ext, ' ') AS ClientPhone2 ,
            tblClient.Addr1 AS ClientAddr1 ,
            tblClient.Addr2 AS ClientAddr2 ,
            tblClient.City + ', ' + UPPER(tblClient.State) + '  ' + tblClient.Zip AS ClientCityStateZip ,
            tblClient.Fax AS ClientFax ,
            tblClient.Email AS ClientEmail ,
            'Dear ' + tblClient.firstName + ' ' + tblClient.lastName AS ClientSalutation ,
            tblClient.title AS Clienttitle ,
            tblClient.Prefix AS ClientPrefix ,
            tblClient.suffix AS Clientsuffix ,
            tblClient.USDvarchar1 AS ClientUSDvarchar1 ,
            tblClient.USDvarchar2 AS ClientUSDvarchar2 ,
            tblClient.USDDate1 AS ClientUSDDate1 ,
            tblClient.USDDate2 AS ClientUSDDate2 ,
            tblClient.USDtext1 AS ClientUSDtext1 ,
            tblClient.USDtext2 AS ClientUSDtext2 ,
            tblClient.USDint1 AS ClientUSDint1 ,
            tblClient.USDint2 AS ClientUSDint2 ,
            tblClient.USDmoney1 AS ClientUSDmoney1 ,
            tblClient.USDmoney2 AS ClientUSDmoney2 ,
            tblClient.CompanyCode ,
            tblClient.Notes AS ClientNotes ,
            tblClient.BillAddr1 ,
            tblClient.BillAddr2 ,
            tblClient.BillCity ,
            UPPER(tblClient.BillState) AS BillState ,
            tblClient.BillZip ,
            tblClient.Billattn ,
            tblClient.ARKey ,
            tblClient.BillFax AS ClientBillFax ,
            tblClient.lastName AS ClientlastName ,
            tblClient.firstName AS ClientfirstName ,
            UPPER(tblClient.State) AS ClientState ,
            tblClient.City AS ClientCity ,
            tblClient.Zip AS ClientZip ,

            tblCompany.extName AS Company ,
            tblCompany.USDvarchar1 AS CompanyUSDvarchar1 ,
            tblCompany.USDvarchar2 AS CompanyUSDvarchar2 ,
            tblCompany.USDDate1 AS CompanyUSDDate1 ,
            tblCompany.USDDate2 AS CompanyUSDDate2 ,
            tblCompany.USDtext1 AS CompanyUSDtext1 ,
            tblCompany.USDtext2 AS CompanyUSDtext2 ,
            tblCompany.USDint1 AS CompanyUSDint1 ,
            tblCompany.USDint2 AS CompanyUSDint2 ,
            tblCompany.USDmoney1 AS CompanyUSDmoney1 ,
            tblCompany.USDmoney2 AS CompanyUSDmoney2 ,
            tblCompany.Notes AS CompanyNotes ,

            tblCase.QARep ,
            tblCase.Doctorspecialty ,
            tblCase.BillClientCode AS CaseBillClientCode ,
            tblCase.officeCode ,
            tblCase.PanelNbr ,

            ISNULL(tblUser.lastName, '')
            + Case WHEN ISNULL(tblUser.LastName, '') = ''
                        OR ISNULL(tblUser.FirstName, '') = '' THEN ''
                   ELSE ', '
              END + ISNULL(tblUser.firstName, '') AS scheduler ,

            tblCase.marketerCode AS Marketer ,
            tblCase.Dateadded AS DateCalledIn ,
            tblCase.Dateofinjury AS DOI ,
            tblCase.Allegation ,
            tblCase.Notes ,
            tblCase.CaseType ,
            'Dear ' + tblExaminee.firstName + ' ' + tblExaminee.lastName AS Examineesalutation ,
            tblCase.status ,
            tblCase.calledInBy ,
            tblCase.chartnbr ,
            tblCase.reportverbal ,
            tblCase.Datemedsrecd AS medsrecd ,
            tblCase.typemedsrecd ,
            tblCase.plaintiffAttorneyCode ,
            tblCase.defenseAttorneyCode ,
            tblCase.serviceCode ,
            tblCase.FaxPattny ,
            tblCase.FaxDoctor ,
            tblCase.FaxClient ,
            tblCase.EmailClient ,
            tblCase.EmailDoctor ,
            tblCase.EmailPattny ,
            tblCase.invoiceDate ,
            tblCase.invoiceamt ,
            tblCase.commitDate ,
            tblCase.WCBNbr ,
            tblCase.specialinstructions ,
            tblCase.priority ,
            tblCase.scheduleNotes ,
            tblCase.requesteddoc ,

            tblCase.USDvarchar1 AS CaseUSDvarchar1 ,
            tblCase.USDvarchar2 AS CaseUSDvarchar2 ,
            tblCase.USDDate1 AS CaseUSDDate1 ,
            tblCase.USDDate2 AS CaseUSDDate2 ,
            tblCase.USDtext1 AS CaseUSDtext1 ,
            tblCase.USDtext2 AS CaseUSDtext2 ,
            tblCase.USDint1 AS CaseUSDint1 ,
            tblCase.USDint2 AS CaseUSDint2 ,
            tblCase.USDmoney1 AS CaseUSDmoney1 ,
            tblCase.USDmoney2 AS CaseUSDmoney2 ,
            tblCase.USDDate3 AS CaseUSDDate3 ,
            tblCase.USDDate4 AS CaseUSDDate4 ,
            tblCase.USDDate5 AS CaseUSDDate5 ,
            tblCase.USDBit1 AS CaseUSDboolean1 ,
            tblCase.USDBit2 AS CaseUSDboolean2 ,

            tblCase.sinternalCasenbr AS internalCasenbr ,
            tblDoctor.credentials AS Doctordegree ,
            tblCase.ClientCode ,
            tblCase.feeCode ,
            tblCase.photoRqd ,
            tblCase.CertMailNbr ,
            tblCase.CertMailNbr2 ,
            tblCase.HearingDate ,
            tblCase.DoctorName ,
            tblCase.masterCasenbr ,
            tblCase.prevappt ,
            tblCase.AssessmentToAddress ,
            tblCase.OCF25Date ,
            tblCase.AssessingFacility ,
            tblCase.DateForminDispute ,
            tblCase.DateReceived ,
            tblCase.ClaimNbrExt ,
            tblCase.sreqspecialty AS RequestedSpecialty ,
            tblCase.AttorneyNote ,
            tblCase.ExternalDueDate ,
            tblCase.InternalDueDate ,
            tblCase.ForecastDate ,
			tblCase.DoctorRptDueDate , 
			tblCase.DoctorReason ,
            tblCase.DefParaLegal ,

            tblCase.MasterSubCase ,
            tblCase.TransportationRequired ,
            tblCase.InterpreterRequired ,
            tblCase.EWReferralType ,
            tblCase.EWReferralEWFacilityID ,
            tblCase.PublishOnWeb ,
            tblCase.Jurisdiction AS JurisdictionCode ,
            tblCase.LegalEvent ,
            tblCase.PILegalEvent ,
            tblCase.TransCode ,
            tblCase.RptFinalizedDate ,

			tblCase.ICDCodeA ,
			tblCase.ICDCodeB ,
			tblCase.ICDCodeC ,
			tblCase.ICDCodeD ,
			tblCase.ICDCodeE ,
			tblCase.ICDCodeF ,
			tblCase.ICDCodeG ,
			tblCase.ICDCodeH ,
			tblCase.ICDCodeI ,
			tblCase.ICDCodeJ ,
			tblCase.ICDCodeK ,
			tblCase.ICDCodeL ,

            'Dear ' + tblDoctor.firstName + ' ' + tblDoctor.lastName + ', ' + ISNULL(tblDoctor.credentials, '') AS DoctorSalutation ,
            tblDoctor.Notes AS DoctorNotes ,
            tblDoctor.Prefix AS DoctorPrefix ,
            tblDoctor.Addr1 AS DoctorcorrespAddr1 ,
            tblDoctor.Addr2 AS DoctorcorrespAddr2 ,
            tblDoctor.City + ', ' + UPPER(tblDoctor.State) + '  ' + tblDoctor.Zip AS DoctorcorrespCityStateZip ,
            tblDoctor.Phone + ' ' + ISNULL(tblDoctor.PhoneExt, ' ') AS DoctorcorrespPhone ,
            tblDoctor.FaxNbr AS DoctorcorrespFax ,
            tblDoctor.EmailAddr AS DoctorcorrespEmail ,
            tblDoctor.Qualifications ,
            tblDoctor.Prepaid ,
            tblDoctor.county AS DoctorCorrespCounty ,

            tblDoctor.USDvarchar1 AS DoctorUSDvarchar1 ,
            tblDoctor.USDvarchar2 AS DoctorUSDvarchar2 ,
            tblDoctor.USDvarchar3 AS DoctorUSDvarchar3 ,
            tblDoctor.USDDate1 AS DoctorUSDDate1 ,
            tblDoctor.USDDate2 AS DoctorUSDDate2 ,
            tblDoctor.USDDate3 AS DoctorUSDDate3 ,
            tblDoctor.USDDate4 AS DoctorUSDDate4 ,
            tblDoctor.USDDate5 AS DoctorUSDDate5 ,
            tblDoctor.USDDate6 AS DoctorUSDDate6 ,
            tblDoctor.USDDate7 AS DoctorUSDDate7 ,
            tblDoctor.USDtext1 AS DoctorUSDtext1 ,
            tblDoctor.USDtext2 AS DoctorUSDtext2 ,
            tblDoctor.USDint1 AS DoctorUSDint1 ,
            tblDoctor.USDint2 AS DoctorUSDint2 ,
            tblDoctor.USDmoney1 AS DoctorUSDmoney1 ,
            tblDoctor.USDmoney2 AS DoctorUSDmoney2 ,
			tblDoctor.DrMedRecsInDays AS DrMedRecsInDays ,
			tblDoctor.ExpectedVisitDuration As ExpectedVisitDuration,

            tblDoctor.WCNbr AS Doctorwcnbr ,
            tblDoctor.remitattn ,
            tblDoctor.remitAddr1 ,
            tblDoctor.remitAddr2 ,
            tblDoctor.remitCity ,
            UPPER(tblDoctor.remitState) AS remitState ,
            tblDoctor.remitZip ,
            tblDoctor.UPIN ,
            tblDoctor.schedulepriority ,
            tblDoctor.feeCode AS drfeeCode ,
            tblDoctor.licensenbr AS Doctorlicense ,
            tblDoctor.SSNTaxID AS DoctorTaxID ,
            tblDoctor.lastName AS DoctorlastName ,
            tblDoctor.firstName AS DoctorfirstName ,
            tblDoctor.middleinitial AS Doctormiddleinitial ,
            ISNULL(LEFT(tblDoctor.firstName, 1), '')
            + ISNULL(LEFT(tblDoctor.middleinitial, 1), '')
            + ISNULL(LEFT(tblDoctor.lastName, 1), '') AS Doctorinitials ,
            UPPER(tblDoctor.State) AS DoctorcorrespState ,
            tblDoctor.CompanyName AS PracticeName ,
            tblDoctor.NPINbr AS DoctorNPINbr ,
            tblDoctor.ProvTypeCode ,
            tblDoctor.PrintOnCheckAs ,

            tblLocation.ExtName AS LocationExtName ,
            tblLocation.Location ,
            tblLocation.Addr1 AS DoctorAddr1 ,
            tblLocation.Addr2 AS DoctorAddr2 ,
			tblLocation.AddressInstructions,
            tblLocation.City + ', ' + UPPER(tblLocation.State) + '  ' + tblLocation.Zip AS DoctorCityStateZip ,
            tblLocation.Phone AS DoctorPhone ,
            tblLocation.insidedr ,
            tblLocation.Email AS DoctorEmail ,
            tblLocation.Fax AS DoctorFax ,
            tblLocation.Faxdrschedule ,
            tblLocation.medrcdletter ,
            tblLocation.drletter ,
            tblLocation.county AS Doctorcounty ,
            tblLocation.vicinity AS Doctorvicinity ,
            tblLocation.contactPrefix AS DoctorLocationcontactPrefix ,
            tblLocation.contactfirst AS DoctorLocationcontactfirstName ,
            tblLocation.contactlast AS DoctorLocationcontactlastName ,
            tblLocation.Notes AS DoctorLocationNotes ,
            tblLocation.contactfirst + ' ' + tblLocation.contactlast AS DoctorLocationcontact ,
            'Dear ' + tblLocation.contactfirst + ' ' + tblLocation.contactlast AS DoctorLocationcontactsalutation ,
            UPPER(tblLocation.State) AS DoctorState ,
            tblLocation.City AS DoctorCity ,
            tblLocation.Zip AS DoctorZip ,
            UPPER(tblLocation.State) AS State ,

            RTRIM(LTRIM(ISNULL(tblCCAddress_2.firstName,'') + ' ' + ISNULL(tblCCAddress_2.lastName,''))) AS PAttorneyName ,
            'Dear ' + ISNULL(tblCCAddress_2.firstName, '') + ' ' + ISNULL(tblCCAddress_2.lastName, '') AS PAttorneysalutation ,
            tblCCAddress_2.Company AS PAttorneyCompany ,
            tblCCAddress_2.Address1 AS PAttorneyAddr1 ,
            tblCCAddress_2.Address2 AS PAttorneyAddr2 ,
            tblCCAddress_2.City + ', ' + UPPER(tblCCAddress_2.State) + '  ' + tblCCAddress_2.Zip AS PAttorneyCityStateZip ,
            tblCCAddress_2.Phone + ISNULL(tblCCAddress_2.PhoneExtension, '') AS PAttorneyPhone ,
            tblCCAddress_2.Fax AS PAttorneyFax ,
            tblCCAddress_2.Email AS PAttorneyEmail ,
            tblCCAddress_2.Prefix AS pAttorneyPrefix ,
            tblCCAddress_2.lastName AS pAttorneylastName ,
            tblCCAddress_2.firstName AS pAttorneyfirstName ,
            UPPER(tblCCAddress_2.State) AS pAttorneyState ,
            tblCCAddress_2.City AS pAttorneyCity ,
            tblCCAddress_2.Zip AS pAttorneyZip ,

            RTRIM(LTRIM(ISNULL(tblCCAddress_1.firstName,'') + ' ' + ISNULL(tblCCAddress_1.lastName,''))) AS DAttorneyName ,
            'Dear ' + ISNULL(tblCCAddress_1.firstName, '') + ' ' + ISNULL(tblCCAddress_1.lastName, '') AS DAttorneysalutation ,
            tblCCAddress_1.Company AS DAttorneyCompany ,
            tblCCAddress_1.Address1 AS DAttorneyAddr1 ,
            tblCCAddress_1.Address2 AS DAttorneyAddr2 ,
            tblCCAddress_1.City + ', ' + UPPER(tblCCAddress_1.State) + '  ' + tblCCAddress_1.Zip AS DAttorneyCityStateZip ,
            tblCCAddress_1.Phone + ' ' + ISNULL(tblCCAddress_1.PhoneExtension, '') AS DattorneyPhone ,
            tblCCAddress_1.Prefix AS dAttorneyPrefix ,
            tblCCAddress_1.lastName AS dAttorneylastName ,
            tblCCAddress_1.firstName AS dAttorneyfirstName ,
            tblCCAddress_1.Fax AS DAttorneyFax ,
            tblCCAddress_1.Email AS DAttorneyEmail ,
            tblCCAddress_1.Fax ,
            UPPER(tblCCAddress_1.State) AS dAttorneyState ,

            RTRIM(LTRIM(ISNULL(tblCCAddress_3.firstName,'') + ' ' + ISNULL(tblCCAddress_3.lastName,''))) AS DParaLegalName ,
            'Dear ' + ISNULL(tblCCAddress_3.firstName, '') + ' ' + ISNULL(tblCCAddress_3.lastName, '') AS DParaLegalsalutation ,
            tblCCAddress_3.Company AS DParaLegalCompany ,
            tblCCAddress_3.Address1 AS DParaLegalAddr1 ,
            tblCCAddress_3.Address2 AS DParaLegalAddr2 ,
            tblCCAddress_3.City + ', ' + UPPER(tblCCAddress_3.State) + '  ' + tblCCAddress_3.Zip AS DParaLegalCityStateZip ,
            tblCCAddress_3.Phone + ' ' + ISNULL(tblCCAddress_3.PhoneExtension,'') AS DParaLegalPhone ,
            tblCCAddress_3.Email AS DParaLegalEmail ,
            tblCCAddress_3.Fax AS DParaLegalFax ,


            tblServices.description AS ServiceDesc ,
            tblServices.ShortDesc ,

            tblCaseType.ShortDesc AS CaseTypeShortDesc ,
			tblCaseType.ExternalDesc AS CaseTypeDesc ,
            --tblCaseType.description AS CaseTypeDesc ,  -- Issue 5985 - stop usign description and use ExternalDesc

            tblQueues.StatusDesc ,

            tblSpecialty.specialtyCode ,
            tblSpecialty.description AS specialtydesc ,

            tblRecordStatus.description AS medsstatus ,

            tblDoctorLocation.correspondence AS Doctorcorrespondence ,

            tblState.StateName AS Jurisdiction ,

            tblDoctorSchedule.duration AS ApptDuration ,

            tblProviderType.description AS DoctorProviderType ,

            tblVenue.County AS Venue ,

            tblOffice.description AS office ,
			tblOffice.ShortDesc AS OfficeShortDesc ,
            tblOffice.USDvarchar1 AS OfficeUSDVarChar1 ,
            tblOffice.USDvarchar2 AS OfficeUSDVarChar2 ,
			tblOffice.NYWCCompanyName ,

            tblLanguage.Description AS Language ,

            tblTranscription.TransCompany,                          
			
			tblCase.DateOfInjury2 AS DOI2, 
			tblCase.DateOfInjury3 AS DOI3, 
			tblCase.DateOfInjury4 AS DOI4,
			tblCase.InsuringCompany as InsuringCompany,
			tblCase.CaseCaption, 
			tblCase.LitigationNotes, 
			tblCase.BillClientCode

    FROM    tblCase
            INNER JOIN tblExaminee ON tblExaminee.chartnbr = tblCase.chartnbr
            INNER JOIN tblOffice ON tblOffice.officeCode = tblCase.officeCode
            INNER JOIN tblClient ON tblCase.ClientCode = tblClient.ClientCode
            INNER JOIN tblCompany ON tblClient.CompanyCode = tblCompany.CompanyCode
            INNER JOIN tblCaseType ON tblCase.Casetype = tblCaseType.Code
            INNER JOIN tblQueues ON tblCase.status = tblQueues.statusCode

            LEFT OUTER JOIN tblDoctor ON tblCase.DoctorCode = tblDoctor.DoctorCode
            LEFT OUTER JOIN tblLocation ON tblCase.DoctorLocation = tblLocation.LocationCode
            LEFT OUTER JOIN tblDoctorSchedule ON tblCase.schedCode = tblDoctorSchedule.schedCode
            LEFT OUTER JOIN tblDoctorLocation ON tblCase.DoctorLocation = tblDoctorLocation.LocationCode
                                                 AND tblCase.DoctorCode = tblDoctorLocation.DoctorCode

            LEFT OUTER JOIN tblSpecialty ON tblCase.Doctorspecialty = tblSpecialty.specialtyCode
            LEFT OUTER JOIN tblVenue ON tblCase.VenueID = tblVenue.VenueID
            LEFT OUTER JOIN tblProviderType ON tblDoctor.ProvTypeCode = tblProviderType.ProvTypeCode
            LEFT OUTER JOIN tblState ON tblCase.Jurisdiction = tblState.StateCode
            LEFT OUTER JOIN tblRecordStatus ON tblCase.recCode = tblRecordStatus.recCode
            LEFT OUTER JOIN tblUser ON tblCase.schedulerCode = tblUser.userid
            LEFT OUTER JOIN tblServices ON tblCase.serviceCode = tblServices.serviceCode
            LEFT OUTER JOIN tblCCAddress AS tblCCAddress_1 ON tblCase.defenseAttorneyCode = tblCCAddress_1.ccCode
            LEFT OUTER JOIN tblCCAddress AS tblCCAddress_2 ON tblCase.plaintiffAttorneyCode = tblCCAddress_2.ccCode
            LEFT OUTER JOIN tblCCAddress AS tblCCAddress_3 ON tblCCAddress_3.ccCode = tblCase.DefParaLegal
            LEFT OUTER JOIN tblLanguage ON tblLanguage.LanguageID = tblCase.LanguageID
            LEFT OUTER JOIN tblTranscription ON tblCase.TransCode = tblTranscription.TransCode
            LEFT OUTER JOIN tblApptStatus ON tblCase.ApptStatusID = tblApptStatus.ApptStatusID
            LEFT OUTER JOIN tblEmployer on tblcase.EmployerID = tblEmployer.EmployerID 
            LEFT OUTER JOIN tblEmployerAddress on tblcase.EmployerAddressID = tblEmployerAddress.EmployerAddressID
GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Altering [dbo].[vwPDFInvDetData]...';


GO
ALTER VIEW vwPDFInvDetData
AS
	SELECT	
			AD1.LineNbr AS InvLineNbr1 ,
	        AD1.Date AS InvServiceDate1 ,
			B.BlankValue AS InvServiceDate1MM,
			B.BlankValue AS InvServiceDate1DD,
			B.BlankValue AS InvServiceDate1YY,
			B.BlankValue AS InvServiceDateTo1MM,
			B.BlankValue AS InvServiceDateTo1DD,
			B.BlankValue AS InvServiceDateTo1YY,
	        AD1.CPTCode AS InvCPT1,
	        AD1.Modifier AS InvModifier1,
	        AD1.Modifier2 AS InvModifier1b ,
	        AD1.Modifier3 AS InvModifier1c ,
	        AD1.Modifier4 AS InvModifier1d ,
			B.BlankValue AS InvICD1,
			B.BlankValue AS InvDiagnosisPointer1,
	        AD1.Location AS InvPlaceOfService1,
			'2' AS InvTypeOfService1,
	        AD1.SuppInfo AS SupplementalInfo1,
	        AD1.Unit AS InvUnit1,
	        AD1.ExtendedAmount AS InvDetAmt1,
			AD1.RetailAmount AS InvRetailAmt1,
	        B.BlankValue AS InvDetAmt1Dollars,
			B.BlankValue AS InvDetAmt1Cents,
	        B.BlankValue AS InvDetAmt1bDollars,
			B.BlankValue AS InvDetAmt1bCents,
			AD1.DrOpCode AS DrOpCode1,
			DR1.NPINbr AS DoctorNPINbr1,


			AD2.LineNbr AS InvLineNbr2 ,
	        AD2.Date AS InvServiceDate2 ,
			B.BlankValue AS InvServiceDate2MM,
			B.BlankValue AS InvServiceDate2DD,
			B.BlankValue AS InvServiceDate2YY,
			B.BlankValue AS InvServiceDateTo2MM,
			B.BlankValue AS InvServiceDateTo2DD,
			B.BlankValue AS InvServiceDateTo2YY,
	        AD2.CPTCode AS InvCPT2,
	        AD2.Modifier AS InvModifier2,
	        AD2.Modifier2 AS InvModifier2b ,
	        AD2.Modifier3 AS InvModifier2c ,
	        AD2.Modifier4 AS InvModifier2d ,
			B.BlankValue AS InvICD2,
			B.BlankValue AS InvDiagnosisPointer2,
	        AD2.Location AS InvPlaceOfService2,
			'2' AS InvTypeOfService2,
	        AD2.SuppInfo AS SupplementalInfo2,
	        AD2.Unit AS InvUnit2,
	        AD2.ExtendedAmount AS InvDetAmt2,
			AD2.RetailAmount AS InvRetailAmt2,
	        B.BlankValue AS InvDetAmt2Dollars,
			B.BlankValue AS InvDetAmt2Cents,
	        B.BlankValue AS InvDetAmt2bDollars,
			B.BlankValue AS InvDetAmt2bCents,
			AD2.DrOpCode AS DrOpCode2,
			DR2.NPINbr AS DoctorNPINbr2,


			AD3.LineNbr AS InvLineNbr3 ,
	        AD3.Date AS InvServiceDate3 ,
			B.BlankValue AS InvServiceDate3MM,
			B.BlankValue AS InvServiceDate3DD,
			B.BlankValue AS InvServiceDate3YY,
			B.BlankValue AS InvServiceDateTo3MM,
			B.BlankValue AS InvServiceDateTo3DD,
			B.BlankValue AS InvServiceDateTo3YY,
	        AD3.CPTCode AS InvCPT3,
	        AD3.Modifier AS InvModifier3,
	        AD3.Modifier2 AS InvModifier3b ,
	        AD3.Modifier3 AS InvModifier3c ,
	        AD3.Modifier4 AS InvModifier3d ,
			B.BlankValue AS InvICD3,
			B.BlankValue AS InvDiagnosisPointer3,
	        AD3.Location AS InvPlaceOfService3,
			'2' AS InvTypeOfService3,
	        AD3.SuppInfo AS SupplementalInfo3,
	        AD3.Unit AS InvUnit3,
	        AD3.ExtendedAmount AS InvDetAmt3,
	        AD3.RetailAmount AS InvRetailAmt3,
			B.BlankValue AS InvDetAmt3Dollars,
			B.BlankValue AS InvDetAmt3Cents,
			B.BlankValue AS InvDetAmt3bDollars,
			B.BlankValue AS InvDetAmt3bCents,
			AD3.DrOpCode AS DrOpCode3,
			DR3.NPINbr AS DoctorNPINbr3,


			AD4.LineNbr AS InvLineNbr4 ,
	        AD4.Date AS InvServiceDate4 ,
			B.BlankValue AS InvServiceDate4MM,
			B.BlankValue AS InvServiceDate4DD,
			B.BlankValue AS InvServiceDate4YY,
			B.BlankValue AS InvServiceDateTo4MM,
			B.BlankValue AS InvServiceDateTo4DD,
			B.BlankValue AS InvServiceDateTo4YY,
	        AD4.CPTCode AS InvCPT4,
	        AD4.Modifier AS InvModifier4,
	        AD4.Modifier2 AS InvModifier4b ,
	        AD4.Modifier3 AS InvModifier4c ,
	        AD4.Modifier4 AS InvModifier4d ,
			B.BlankValue AS InvICD4,
			B.BlankValue AS InvDiagnosisPointer4,
	        AD4.Location AS InvPlaceOfService4,
			'2' AS InvTypeOfService4,
	        AD4.SuppInfo AS SupplementalInfo4,
	        AD4.Unit AS InvUnit4,
	        AD4.ExtendedAmount AS InvDetAmt4,
			AD4.RetailAmount AS InvRetailAmt4,
	        B.BlankValue AS InvDetAmt4Dollars,
			B.BlankValue AS InvDetAmt4Cents,
	        B.BlankValue AS InvDetAmt4bDollars,
			B.BlankValue AS InvDetAmt4bCents,
			AD4.DrOpCode AS DrOpCode4,
			DR4.NPINbr AS DoctorNPINbr4,


			AD5.LineNbr AS InvLineNbr5 ,
	        AD5.Date AS InvServiceDate5 ,
			B.BlankValue AS InvServiceDate5MM,
			B.BlankValue AS InvServiceDate5DD,
			B.BlankValue AS InvServiceDate5YY,
			B.BlankValue AS InvServiceDateTo5MM,
			B.BlankValue AS InvServiceDateTo5DD,
			B.BlankValue AS InvServiceDateTo5YY,
	        AD5.CPTCode AS InvCPT5,
	        AD5.Modifier AS InvModifier5,
	        AD5.Modifier2 AS InvModifier5b ,
	        AD5.Modifier3 AS InvModifier5c ,
	        AD5.Modifier4 AS InvModifier5d ,
			B.BlankValue AS InvICD5,
			B.BlankValue AS InvDiagnosisPointer5,
	        AD5.Location AS InvPlaceOfService5,
			'2' AS InvTypeOfService5,
	        AD5.SuppInfo AS SupplementalInfo5,
	        AD5.Unit AS InvUnit5,
	        AD5.ExtendedAmount AS InvDetAmt5,
			AD5.RetailAmount AS InvRetailAmt5,
	        B.BlankValue AS InvDetAmt5Dollars,
			B.BlankValue AS InvDetAmt5Cents,
	        B.BlankValue AS InvDetAmt5bDollars,
			B.BlankValue AS InvDetAmt5bCents,
			AD5.DrOpCode AS DrOpCode5,
			DR5.NPINbr AS DoctorNPINbr5,


			AD6.LineNbr AS InvLineNbr6 ,
	        AD6.Date AS InvServiceDate6 ,
			B.BlankValue AS InvServiceDate6MM,
			B.BlankValue AS InvServiceDate6DD,
			B.BlankValue AS InvServiceDate6YY,
			B.BlankValue AS InvServiceDateTo6MM,
			B.BlankValue AS InvServiceDateTo6DD,
			B.BlankValue AS InvServiceDateTo6YY,
	        AD6.CPTCode AS InvCPT6,
	        AD6.Modifier AS InvModifier6,
	        AD6.Modifier2 AS InvModifier6b ,
	        AD6.Modifier3 AS InvModifier6c ,
	        AD6.Modifier4 AS InvModifier6d ,
			B.BlankValue AS InvICD6,
			B.BlankValue AS InvDiagnosisPointer6,
	        AD6.Location AS InvPlaceOfService6,
			'2' AS InvTypeOfService6,
	        AD6.SuppInfo AS SupplementalInfo6,
	        AD6.Unit AS InvUnit6,
	        AD6.ExtendedAmount AS InvDetAmt6,
			AD6.RetailAmount AS InvRetailAmt6,
	        B.BlankValue AS InvDetAmt6Dollars,
			B.BlankValue AS InvDetAmt6Cents,
	        B.BlankValue AS InvDetAmt6bDollars,
			B.BlankValue AS InvDetAmt6bCents,
			AD6.DrOpCode AS DrOpCode6,
			DR6.NPINbr AS DoctorNPINbr6,

			B.BlankValue AS InvICDDiagnosisPointer,
			AD1.HeaderID AS InvDetHeaderID

	FROM	tblAcctDetail AS AD1
	LEFT OUTER JOIN tblAcctDetail AS AD2 ON AD2.HeaderID = AD1.HeaderID AND AD2.LineNbr=2
	LEFT OUTER JOIN tblAcctDetail AS AD3 ON AD3.HeaderID = AD1.HeaderID AND AD3.LineNbr=3
	LEFT OUTER JOIN tblAcctDetail AS AD4 ON AD4.HeaderID = AD1.HeaderID AND AD4.LineNbr=4
	LEFT OUTER JOIN tblAcctDetail AS AD5 ON AD5.HeaderID = AD1.HeaderID AND AD5.LineNbr=5
	LEFT OUTER JOIN tblAcctDetail AS AD6 ON AD6.HeaderID = AD1.HeaderID AND AD6.LineNbr=6
	LEFT OUTER JOIN tblDoctor AS DR1 ON AD1.DrOpCode=DR1.DoctorCode
	LEFT OUTER JOIN tblDoctor AS DR2 ON AD2.DrOpCode=DR2.DoctorCode
	LEFT OUTER JOIN tblDoctor AS DR3 ON AD3.DrOpCode=DR3.DoctorCode
	LEFT OUTER JOIN tblDoctor AS DR4 ON AD4.DrOpCode=DR4.DoctorCode
	LEFT OUTER JOIN tblDoctor AS DR5 ON AD5.DrOpCode=DR5.DoctorCode
	LEFT OUTER JOIN tblDoctor AS DR6 ON AD6.DrOpCode=DR6.DoctorCode
	LEFT OUTER JOIN tblBlank AS B ON 1=1
	WHERE AD1.LineNbr=1
GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Altering [dbo].[vwPDFOverride]...';


GO
ALTER VIEW vwPDFOverride
AS
	SELECT
			--These are bookmarks that need to be duplicated, so they can be placed on the form multiple times, but each one is independent from each other
			'%Company%' as Company2,
			'%ClientName%' AS ClientName2,
			'%ClientFullAddress%' AS ClientFullAddress2,
			'%ClientPhoneAreaCode%' AS ClientPhoneAreaCode2,
			'%ClientPhoneNumber%' AS ClientPhoneNumber2,
			'%ClientFaxAreaCode%' AS ClientFaxAreaCode2,
			'%ClientFaxNumber%' AS ClientFaxNumber2,

			--Simply alias name for the same data field
			'%DocumentDate%' AS InvoiceDate,

			-------------------------------
			--CMS1500 Related Old Bookmarks
			-------------------------------

			--For backward compatibility, bookmarks used on old CMS1500 forms
			'Signature on file' AS AuthorizedSignature ,
			'Signature on file'	AS AssignmentSignature ,

			'%CurrentDate%' AS AuthorizedSignatureDate ,
			'%CurrentDate%' AS DoctorSignatureDate ,

			'%Checked%' AS Box1Other,
			'%Checked%' AS ExamineeRelToInsOther,
			'%Checked%' AS BillingProviderEINCheck,

			'%ClaimNbr%' AS InsuredPolicyNbr,
			'%Employer%' AS InsuredEmployer,
			'%DocumentNbr%' AS ExamineeAccountNbr,
			'%Jurisdiction%' AS AutoAccidentState,

			--For backward compatibility, one of the old forms has these bookmars
			'%CMSBox24JNonNPILine1%' AS PrimaryDoctorNonNPINbr1,
			'%CMSBox24JNonNPILine2%' AS PrimaryDoctorNonNPINbr2,
			'%CMSBox24JNonNPILine3%' AS PrimaryDoctorNonNPINbr3,
			'%CMSBox24JNonNPILine4%' AS PrimaryDoctorNonNPINbr4,
			'%CMSBox24JNonNPILine5%' AS PrimaryDoctorNonNPINbr5,
			'%CMSBox24JNonNPILine6%' AS PrimaryDoctorNonNPINbr6,

			--For backward compatibility, these fields are renamed in tblClaimInfo
			'%CMSBox23%' AS PriorAuthNbr,
			'%CMSBox31Line1%' AS DoctorNameWithDegree,
			'%CMSBox31Line2%' AS DoctorSpecialty,
			'%CMSBox32b%' AS DoctorNonNPINbr,
			'%CMSBox33b%' AS BillingProviderNonNPINbr,

			-------------------------------
			--CMS1500 Related New Bookmarks
			-------------------------------

			B.BlankValueLong AS CMSPayor ,									--doc override

			B.BlankValue AS CMSBox1a ,										--doc override
			B.BlankValue AS CMSBox4 ,										--doc and inv override
			B.BlankValue AS CMSBox7Address ,								--doc override
			B.BlankValue AS CMSBox7City ,									--doc override
			B.BlankValue AS CMSBox7State ,									--doc override
			B.BlankValue AS CMSBox7Zip ,									--doc override
			B.BlankValue AS CMSBox7AreaCode ,								--doc override
			B.BlankValue AS CMSBox7PhoneNumber ,							--doc override
			B.Blankvalue AS OtherInsuredPolicyNbr,							--doc and inv override CMSBox9a
			B.BlankValue AS CMSBox10aYes ,									--doc override
			B.BlankValue AS CMSBox10bNo ,									--doc override
			B.BlankValue AS CMSBox10bState ,								--doc override
			B.BlankValue AS CMSBox10cNo ,									--doc override

			B.BlankValue AS CMSBox11,                                       --doc override
			B.BlankValue AS CMSBox12,                                       --doc override
			B.BlankValue AS CMSBox12Date,                                   --doc override
			B.BlankValue AS CMSBox13,                                       --doc override
			B.BlankValue AS CMSBox14Qual,									--doc override

			B.BlankValue AS CMSBox17Qual,									--doc override
			B.BlankValue AS CMSBox17 ,										--doc override
			B.BlankValue AS CMSBox17a ,										--doc override
			B.BlankValue AS CMSBox17aQual ,									--doc override
			B.BlankValue AS CMSBox17b ,										--doc override
			
			B.BlankValue AS CMSBox19 ,										--doc override	

			B.BlankValue AS CMSBox23 ,										--inv override
			B.BlankValue AS CMSBox24JNonNPINbr ,							--doc and inv override
			B.BlankValue AS CMSBox24JNonNPIQual ,							--doc override

			B.BlankValue AS CMSBox24JNonNPIQualLine1 ,						--doc override
			B.BlankValue AS CMSBox24JNonNPIQualLine2 ,						--doc override
			B.BlankValue AS CMSBox24JNonNPIQualLine3 ,						--doc override
			B.BlankValue AS CMSBox24JNonNPIQualLine4 ,						--doc override
			B.BlankValue AS CMSBox24JNonNPIQualLine5 ,						--doc override
			B.BlankValue AS CMSBox24JNonNPIQualLine6 ,						--doc override

			B.BlankValue AS CMSBox24JNonNPILine1 ,							--doc override
			B.BlankValue AS CMSBox24JNonNPILine2 ,							--doc override
			B.BlankValue AS CMSBox24JNonNPILine3 ,							--doc override
			B.BlankValue AS CMSBox24JNonNPILine4 ,							--doc override
			B.BlankValue AS CMSBox24JNonNPILine5 ,							--doc override
			B.BlankValue AS CMSBox24JNonNPILine6 ,							--doc override

			B.BlankValue AS CMSBox24JNPILine1 ,								--doc override
			B.BlankValue AS CMSBox24JNPILine2 ,								--doc override
			B.BlankValue AS CMSBox24JNPILine3 ,								--doc override
			B.BlankValue AS CMSBox24JNPILine4 ,								--doc override
			B.BlankValue AS CMSBox24JNPILine5 ,								--doc override
			B.BlankValue AS CMSBox24JNPILine6 ,								--doc override

			B.BlankValue AS CMSBox25,
			B.BlankValue AS CMSBox26,										--inv override
			B.BlankValue AS CMSBox27Yes ,									--doc override

			B.BlankValueLong AS CMSBox31Line1 ,								--doc and inv override
			B.BlankValue AS CMSBox31Line2 ,									--doc and inv override

			B.BlankValue AS CMSBox32a ,										--doc override
			B.BlankValue AS CMSBox32b ,										--doc and inv override

			B.BlankValue AS CMSBox33Line1 ,									--doc override
			B.BlankValue AS CMSBox33Line2 ,									--doc override
			B.BlankValue AS CMSBox33Line3 ,									--doc override
			B.BlankValue AS CMSBox33AreaCode,								--doc override
			B.BlankValue AS CMSBox33PhoneNumber,							--doc override
			B.BlankValue AS CMSBox33a,										--doc override
			B.BlankValue AS CMSBox33b 										--doc and inv override

	FROM	tblBlank AS B
GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Altering [dbo].[vwServiceWorkflow]...';


GO
ALTER VIEW [dbo].[vwServiceWorkflow]
AS
    SELECT
        WF.ServiceWorkflowID,
        WF.OfficeCode,
        WF.CaseType,
        WF.ServiceCode,
        WF.UserIDAdded,
        WF.DateAdded,
        WF.UserIDEdited,
        WF.DateEdited,
        WF.ExamineeAddrReqd,
        WF.ExamineeSSNReqd,
        WF.AttorneyReqd,
        WF.DOIRqd,
        WF.ClaimNbrRqd,
        WF.JurisdictionRqd,
        WF.EmployerRqd,
        WF.TreatingPhysicianRqd,
        WF.CalcFrom,
        WF.DaysToForecastDate,
        WF.DaysToInternalDueDate,
        WF.DaysToExternalDueDate,
		WF.DaysToDoctorRptDueDate,
		WF.InternalDueDateType,
		WF.ExternalDueDateType,
		WF.DoctorRptDueDateType,
		WF.ForecastDateType,
        WFQ.QueueCount,
        CT.Description AS CaseTypeDesc,
        CT.Status AS CaseTypeStatus,
        S.Description AS ServiceDesc,
        S.Status AS ServiceStatus,
        S.ApptBased,
        S.ShowLegalTabOnCase,
        O.Description AS OfficeDesc,
        O.Status AS OfficeStatus,
		WF.UsePeerBill,
		S.ProdCode, 
		CT.EWBusLineID, 
		S.EWServiceTypeID
    FROM
        tblServiceWorkflow AS WF
    INNER JOIN tblCaseType AS CT ON WF.CaseType=CT.Code
    INNER JOIN tblServices AS S ON S.ServiceCode=WF.ServiceCode
    INNER JOIN tblOffice AS O ON O.OfficeCode=WF.OfficeCode
    LEFT OUTER JOIN (
                     SELECT
                        ServiceWorkflowID,
                        COUNT(ServiceWorkflowQueueID) AS QueueCount
                     FROM
                        tblServiceWorkflowQueue
                     GROUP BY
                        ServiceWorkflowID
                    ) AS WFQ ON WFQ.ServiceWorkflowID=WF.ServiceWorkflowID
GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Altering [dbo].[proc_CaseHistory_LoadByWebUserIDAndLastLoginDate]...';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
ALTER PROCEDURE [dbo].[proc_CaseHistory_LoadByWebUserIDAndLastLoginDate]

@LastLoginDate datetime,
@UserCode int,
@UserType char(2)

AS

SELECT DISTINCT tblCaseHistory.*, claimnbr, tblExaminee.firstname + ' ' + tblExaminee.lastname AS examineename,
	tblCaseHistory.EventDesc AS EventName, tblCaseHistory.UserID AS ByUser
	FROM tblCaseHistory
	INNER JOIN tblCase ON tblCaseHistory.casenbr = tblCase.Casenbr
	INNER JOIN tblExaminee ON tblCase.chartnbr = tblExaminee.chartnbr
	INNER JOIN tblPublishOnWeb ON tblCaseHistory.id = tblPublishOnWeb.TableKey
		WHERE tblPublishOnWeb.TableType = 'tblCaseHistory'
		AND (tblPublishOnWeb.PublishOnWeb = 1)
		AND (tblPublishOnWeb.UserCode = @UserCode)
		AND (tblPublishOnWeb.UserType = @UserType)
		AND (tblPublishOnWeb.DateAdded > @LastLoginDate)
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Altering [dbo].[proc_CaseHistory_LoadByWebUserIDAndViewed]...';


GO
ALTER PROCEDURE [dbo].[proc_CaseHistory_LoadByWebUserIDAndViewed]

@LastLoginDate datetime,
@UserCode int,
@UserType char(2)

AS

SELECT DISTINCT tblCaseHistory.*, claimnbr, tblExaminee.firstname + ' ' + tblExaminee.lastname AS examineename, tblCase.DoctorName, tblCase.DoctorSpecialty
	FROM tblCaseHistory
	INNER JOIN tblCase ON tblCaseHistory.casenbr = tblCase.Casenbr
	INNER JOIN tblExaminee ON tblCase.chartnbr = tblExaminee.chartnbr
	INNER JOIN tblPublishOnWeb ON tblCaseHistory.id = tblPublishOnWeb.TableKey
		WHERE tblPublishOnWeb.TableType = 'tblCaseHistory'
		AND (tblPublishOnWeb.PublishOnWeb = 1)
		AND (tblPublishOnWeb.UserCode = @UserCode)
		AND (tblPublishOnWeb.UserType = @UserType)
		AND (ISNULL(tblPublishOnWeb.Viewed, 0) = 0)
GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Altering [dbo].[proc_CaseHistory_LoadByWebUserIDAndViewedCount]...';


GO
ALTER PROCEDURE [dbo].[proc_CaseHistory_LoadByWebUserIDAndViewedCount]

@LastLoginDate datetime,
@UserCode int,
@UserType char(2)

AS

SELECT DISTINCT COUNT(tblCaseHistory.id)
	FROM tblCaseHistory
	INNER JOIN tblCase ON tblCaseHistory.casenbr = tblCase.Casenbr
	INNER JOIN tblExaminee ON tblCase.chartnbr = tblExaminee.chartnbr
	INNER JOIN tblPublishOnWeb ON tblCaseHistory.id = tblPublishOnWeb.TableKey AND tblPublishOnWeb.TableType = 'tblCaseHistory'
		WHERE tblPublishOnWeb.TableType = 'tblCaseHistory'
		AND (tblPublishOnWeb.PublishOnWeb = 1)
		AND (tblPublishOnWeb.UserCode = @UserCode)
		AND (tblPublishOnWeb.UserType = @UserType)
		AND (ISNULL(tblPublishOnWeb.Viewed, 0) = 0)
GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Altering [dbo].[proc_IMEException]...';


GO
ALTER PROCEDURE proc_IMEException
    @ExceptionID INT ,
    @OfficeCode INT ,
    @CaseTypeCode INT ,
    @ServiceCode INT ,
    @StatusCode INT ,
    @EnterLeave INT ,
    @CaseNbr INT, 
	@SLARuleDetailID INT
AS
BEGIN

    SET NOCOUNT ON;
    DECLARE @Err INT;

    SELECT  ED.* ,
            ISNULL(C.CaseNbr, -1) AS CaseNbr ,
            CL.ClientCode ,
            CO.ParentCompanyID ,
            CL.CompanyCode ,
            C.DoctorCode ,
            C.PlaintiffAttorneyCode ,
            C.DefenseAttorneyCode ,
            C.DefParaLegal ,
            BCL.ClientCode AS BillClientCode ,
            BCO.ParentCompanyID AS BillParentCompanyID ,
            BCL.CompanyCode AS BillCompanyCode
    FROM    tblExceptionDefinition AS ED
            LEFT OUTER JOIN tblCase AS C ON C.CaseNbr = @CaseNbr
            LEFT OUTER JOIN tblClient AS CL ON CL.ClientCode = C.ClientCode
            LEFT OUTER JOIN tblCompany AS CO ON CL.CompanyCode = CO.CompanyCode
            LEFT OUTER JOIN tblClient AS BCL ON BCL.ClientCode = ISNULL(C.BillClientCode, C.ClientCode)
            LEFT OUTER JOIN tblCompany AS BCO ON BCO.CompanyCode = BCL.CompanyCode
			LEFT OUTER JOIN tblEmployer AS ER ON ER.EmployerID = C.EmployerID
			LEFT OUTER JOIN tblEWParentEmployer AS PE ON PE.EWParentEmployerID = ER.EWParentEmployerID
			LEFT OUTER JOIN tblSLARule AS  SLA ON SLA.SLARuleID = C.SLARuleID 
			LEFT OUTER JOIN tblSLARuleDetail AS SLADET ON SLADET.SLARuleID = SLA.SLARuleID 
    WHERE   ED.Status = 'Active' AND ED.ExceptionID = @ExceptionID
			AND
			( ED.Entity = 'CS'
                OR ( ED.Entity = 'PC'
                    AND ( CO.ParentCompanyID IN (SELECT IMECentricCode FROM tblExceptionDefEntity WHERE ExceptionDefID=ED.ExceptionDefID)
                            AND ISNULL(ED.UseBillingEntity, 0) = 0
                        
                    OR  BCO.ParentCompanyID IN (SELECT IMECentricCode FROM tblExceptionDefEntity WHERE ExceptionDefID=ED.ExceptionDefID)
                        AND ISNULL(ED.UseBillingEntity, 0) = 1
                        )
                    )
                OR ( ED.Entity = 'CO'
                    AND ( CL.CompanyCode IN (SELECT IMECentricCode FROM tblExceptionDefEntity WHERE ExceptionDefID=ED.ExceptionDefID)
                            AND ISNULL(ED.UseBillingEntity, 0) = 0
                        
                    OR  BCL.CompanyCode IN (SELECT IMECentricCode FROM tblExceptionDefEntity WHERE ExceptionDefID=ED.ExceptionDefID)
                        AND ISNULL(ED.UseBillingEntity, 0) = 1
                        )
                    )
                OR ( ED.Entity = 'CL'
                    AND ( CL.ClientCode IN (SELECT IMECentricCode FROM tblExceptionDefEntity WHERE ExceptionDefID=ED.ExceptionDefID)
                            AND ISNULL(ED.UseBillingEntity, 0) = 0
                       
                    OR  BCL.ClientCode IN (SELECT IMECentricCode FROM tblExceptionDefEntity WHERE ExceptionDefID=ED.ExceptionDefID)
                        AND ISNULL(ED.UseBillingEntity, 0) = 1
                        )
                    )
                OR ( ED.Entity = 'DR'
                    AND ( C.DoctorCode IN (SELECT IMECentricCode FROM tblExceptionDefEntity WHERE ExceptionDefID=ED.ExceptionDefID) )
                    )
                OR ( ED.Entity = 'AT'
                    AND ( C.PlaintiffAttorneyCode IN (SELECT IMECentricCode FROM tblExceptionDefEntity WHERE ExceptionDefID=ED.ExceptionDefID)
                    
					OR C.DefenseAttorneyCode IN (SELECT IMECentricCode FROM tblExceptionDefEntity WHERE ExceptionDefID=ED.ExceptionDefID)
                        )
                    )
                OR ( ED.Entity = 'PE'
                    AND ( ER.EWParentEmployerID IN (SELECT IMECentricCode FROM tblExceptionDefEntity WHERE ExceptionDefID=ED.ExceptionDefID) )
                    )
                OR ( ED.Entity = 'ER'
                    AND ( C.EmployerID IN (SELECT IMECentricCode FROM tblExceptionDefEntity WHERE ExceptionDefID=ED.ExceptionDefID) )
                    )
            )
            AND ( ED.AllOffice = 1
				    OR ED.ExceptionDefID IN (SELECT ExceptionDefID FROM tblExceptionDefOffice WHERE OfficeCode = C.OfficeCode )
				    OR ED.ExceptionDefID IN (SELECT ExceptionDefID FROM tblExceptionDefOffice WHERE OfficeCode = @OfficeCode )
                )
            AND ( ED.AllCaseType = 1
				    OR ED.ExceptionDefID IN (SELECT ExceptionDefID FROM tblExceptionDefCaseType WHERE CaseTypeCode = C.CaseType )
				    OR ED.ExceptionDefID IN (SELECT ExceptionDefID FROM tblExceptionDefCaseType WHERE CaseTypeCode = @CaseTypeCode )
                )
            AND 
				( ED.AllService = 1
					OR ED.ExceptionDefID IN (SELECT ExceptionDefID FROM tblExceptionDefService WHERE ServiceCode = C.ServiceCode )
					OR ED.ExceptionDefID IN (SELECT ExceptionDefID FROM tblExceptionDefService WHERE ServiceCode = @ServiceCode )
				)
			AND
				( ED.AllEWServiceType = 1
					OR ED.ExceptionDefID IN (SELECT ExceptionDefID FROM tblExceptionDefEWServiceType AS tEWS
										INNER JOIN tblServices AS tS ON tEWS.EWServiceTypeID = tS.EWServiceTypeID 
										WHERE tS.ServiceCode = C.ServiceCode )
					OR ED.ExceptionDefID IN (SELECT ExceptionDefID FROM tblExceptionDefEWServiceType AS tEWS
										INNER JOIN tblServices AS tS ON tEWS.EWServiceTypeID = tS.EWServiceTypeID 
										WHERE tS.ServiceCode = @ServiceCode )
				)
            AND ( ( ED.StatusCode = -1
                    AND ( ED.ExceptionID <> 18
                            OR ISNULL(ED.StatusCodeValue, 1) = @EnterLeave
                        )
                    )
                    OR ( ED.StatusCode = @StatusCode
                        AND ED.StatusCodeValue = @EnterLeave
                        )
                )
			AND 
				( ED.AllSLARuleDetail = 1
					OR SLADET.SLARuleDetailID IN (SELECT SLARuleDetailID 
					                                FROM tblExceptionDefSLARuleDetail 
												   WHERE SLARuleDetailID = @SLARuleDetailID 
												     AND ExceptionDefID = ED.ExceptionDefID)
				)

    SET @Err = @@Error;

    RETURN @Err;
END;
GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Altering [dbo].[proc_CaseDocuments_LoadByWebUserIDAndLastLoginDate]...';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
ALTER PROCEDURE [proc_CaseDocuments_LoadByWebUserIDAndLastLoginDate]

@LastLoginDate datetime,
@UserCode int,
@UserType char(2)

AS

SELECT DISTINCT tblCaseDocuments.*, claimnbr, tblExaminee.firstname + ' ' + tblExaminee.lastname AS examineename,
	tblPublishOnWeb.PublishasPDF, tblCaseDocType.Description AS doctypedesc, RTRIM(CAST(tblCase.ExtCaseNbr AS VARCHAR(20))) AS ExtCaseNbr, 
	tblExaminee.firstname + ' ' + tblExaminee.lastname AS examinee, tblCaseDocuments.sFileName FileName, RTRIM(CAST(tblCaseDocuments.DateAdded AS VARCHAR(20))) Date
	FROM tblCaseDocuments
		INNER JOIN tblCase ON tblCaseDocuments.casenbr = tblCase.Casenbr
		INNER JOIN tblExaminee ON tblCase.chartnbr = tblExaminee.chartnbr
		INNER JOIN tblPublishOnWeb ON tblCaseDocuments.seqno = tblPublishOnWeb.TableKey
		LEFT JOIN tblCaseDocType on tblCaseDocuments.CaseDocTypeID = tblCaseDocType.CaseDocTypeID
	WHERE (tblPublishOnWeb.TableType = 'tblCaseDocuments')
		AND (tblPublishOnWeb.PublishOnWeb = 1)
		AND (tblPublishOnWeb.UserCode = @UserCode)
		AND (tblPublishOnWeb.UserType = @UserType)
		AND (tblPublishOnWeb.DateAdded > @LastLoginDate)
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Altering [dbo].[proc_CaseDocuments_LoadByWebUserIDAndLastLoginDateCountProgressive]...';


GO
ALTER PROCEDURE [proc_CaseDocuments_LoadByWebUserIDAndLastLoginDateCountProgressive]

@LastLoginDate datetime,
@UserCode int,
@UserType char(2)

AS

SELECT DISTINCT COUNT(tblCaseDocuments.seqno)
	FROM tblCaseDocuments
	INNER JOIN tblCase ON tblCaseDocuments.casenbr = tblCase.Casenbr
	INNER JOIN tblExaminee ON tblCase.chartnbr = tblExaminee.chartnbr
	INNER JOIN tblPublishOnWeb ON tblCaseDocuments.seqno = tblPublishOnWeb.TableKey
		WHERE tblPublishOnWeb.TableType = 'tblCaseDocuments'
		AND (tblPublishOnWeb.PublishOnWeb = 1)
		AND (tblPublishOnWeb.UserCode = @UserCode)
		AND (tblPublishOnWeb.UserType = @UserType)
		AND (ISNULL(tblPublishOnWeb.Viewed, 0) = 0)
		AND (tblPublishOnWeb.UseWidget = 1)
GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Altering [dbo].[proc_CaseDocuments_LoadByWebUserIDAndLastLoginDateProgressive]...';


GO
ALTER PROCEDURE [proc_CaseDocuments_LoadByWebUserIDAndLastLoginDateProgressive]

@LastLoginDate datetime,
@UserCode int,
@UserType char(2)

AS

SELECT DISTINCT tblCaseDocuments.*, claimnbr, tblExaminee.firstname + ' ' + tblExaminee.lastname AS examineename,
	tblPublishOnWeb.PublishasPDF, tblCaseDocType.Description AS doctypedesc, tblCase.DoctorSpecialty, tblCase.DoctorName
	FROM tblCaseDocuments
		INNER JOIN tblCase ON tblCaseDocuments.casenbr = tblCase.Casenbr
		INNER JOIN tblExaminee ON tblCase.chartnbr = tblExaminee.chartnbr
		INNER JOIN tblPublishOnWeb ON tblCaseDocuments.seqno = tblPublishOnWeb.TableKey
		LEFT JOIN tblCaseDocType on tblCaseDocuments.CaseDocTypeID = tblCaseDocType.CaseDocTypeID
	WHERE (tblPublishOnWeb.TableType = 'tblCaseDocuments')
		AND (tblPublishOnWeb.PublishOnWeb = 1)
		AND (tblPublishOnWeb.UserCode = @UserCode)
		AND (tblPublishOnWeb.UserType = @UserType)
		AND (ISNULL(tblPublishOnWeb.Viewed, 0) = 0)
		AND (tblPublishOnWeb.UseWidget = 1)
GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Altering [dbo].[proc_GetReferralsByClaimantAndClaim]...';


GO
ALTER PROCEDURE [dbo].[proc_GetReferralsByClaimantAndClaim]

@WebUserID int,
@ClaimNbr varchar(50),
@Chartnbr int,
@CaseNbr int

AS
BEGIN

	SET NOCOUNT ON
	DECLARE @Err int

	SELECT DISTINCT TOP 100 PERCENT
		tblCase.casenbr,
		tblCase.ExtCaseNbr,
		tblCase.dateadded,
		tblExaminee.lastname +  ', ' + tblExaminee.firstname AS examineename,
		tblClient.lastname + ', ' + tblClient.firstname AS clientname,
		tblCompany.intname AS companyname,
		CONVERT(varchar(20), tblCase.ApptDate, 101) + ' ' + RIGHT(CONVERT(VARCHAR, tblCase.ApptTime),7)  ApptDate,
		tblCase.claimnbr,
		tblServices.description AS service,
		tblCase.DoctorName AS provider,
		tblWebQueues.description AS WebStatus,
		tblWebQueues.statuscode,
		ISNULL(NULLIF(tblCase.sinternalcasenbr,''),tblCase.casenbr) AS webcontrolnbr
		FROM tblCase
		INNER JOIN tblQueues ON tblCase.status = tblQueues.statuscode
		INNER JOIN tblServices ON tblCase.servicecode = tblServices.servicecode
		INNER JOIN tblWebQueues ON tblQueues.WebStatusCode = tblWebQueues.statuscode
		INNER JOIN tblClient ON tblCase.clientcode = tblClient.clientcode
		INNER JOIN tblCompany ON tblClient.companycode = tblCompany.companycode
		LEFT OUTER JOIN tblExaminee ON tblCase.chartnbr = tblExaminee.chartnbr
		INNER JOIN tblPublishOnWeb ON tblCase.casenbr = tblPublishOnWeb.tablekey
			AND tblPublishOnWeb.tabletype = 'tblCase'
			AND tblPublishOnWeb.PublishOnWeb = 1
		INNER JOIN tblWebUserAccount ON tblPublishOnWeb.UserCode = tblWebUserAccount.UserCode
			AND tblPublishOnWeb.UserType = tblWebUserAccount.UserType
			AND tblWebUserAccount.WebUserID = @WebUserID
		AND (tblCase.ClaimNbr = @ClaimNbr OR tblCase.ChartNbr = @ChartNbr)
		AND (tblCase.CaseNbr <> @CaseNbr)
		AND (ClaimNbr IS NOT NULL) 
		AND	(ClaimNbr <> '')


	SET @Err = @@Error

	RETURN @Err
END
GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Altering [dbo].[proc_GetReferralSearch]...';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
ALTER PROCEDURE [proc_GetReferralSearch]

@WebUserID int = 0

AS

SET NOCOUNT OFF
DECLARE @Err int

	SELECT DISTINCT
		tblWebQueues.statuscode,
		tblCase.casenbr,
		tblCase.ExtCaseNbr,
		ISNULL(tblCase.DoctorName,'') AS provider,
		ISNULL(CONVERT(varchar(20), tblCase.ApptDate, 101) + ' ' + RIGHT(CONVERT(VARCHAR, tblCase.ApptTime),7),'')  ApptDate,
		tblCase.chartnbr,
		ISNULL(tblCase.doctorspecialty,'') as Specialty,
		tblServices.shortdesc AS service,
		tblExaminee.lastname + ', ' + tblExaminee.firstname AS examineename,
		tblExaminee.lastname,
		tblExaminee.firstname,
		tblWebQueues.description AS WebStatus,
		tblQueues.WebStatusCode,
		tblWebQueues.statuscode,
		tblCase.claimnbr,
		tblWebUserAccount.WebUserID,
		ISNULL(NULLIF(tblCase.sinternalcasenbr,''),tblCase.casenbr) AS webcontrolnbr,
		ISNULL(tblEWTransDept.FolderPath,'') TransFolderPath
		FROM tblCase
		INNER JOIN tblOffice ON tblCase.OfficeCode = tblOffice.OfficeCode
		LEFT JOIN tblEWTransDept on tblOffice.EWTransDeptID = tblEWTransDept.EWTransDeptID
		INNER JOIN tblQueues ON tblCase.status = tblQueues.statuscode
		INNER JOIN tblServices ON tblCase.servicecode = tblServices.servicecode
		INNER JOIN tblWebQueues ON tblQueues.WebStatusCode = tblWebQueues.statuscode
		INNER JOIN tblExaminee ON tblCase.chartnbr = tblExaminee.chartnbr
		INNER JOIN tblclient on tblCase.clientcode = tblClient.clientcode
		INNER JOIN tblCompany ON tblCompany.companycode = tblClient.companycode
		INNER JOIN tblPublishOnWeb ON tblCase.casenbr = tblPublishOnWeb.tablekey
			AND tblPublishOnWeb.tabletype = 'tblCase'
			AND tblPublishOnWeb.PublishOnWeb = 1
		INNER JOIN tblWebUserAccount ON tblPublishOnWeb.UserCode = tblWebUserAccount.UserCode
			AND tblPublishOnWeb.UserType = tblWebUserAccount.UserType

	WHERE tblWebUserAccount.WebUserID = COALESCE(@WebUserID,tblWebUserAccount.WebUserID)

SET @Err = @@Error
RETURN @Err
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Altering [dbo].[proc_GetReferralSummarySinceLastLoginDate]...';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
ALTER PROCEDURE [dbo].[proc_GetReferralSummarySinceLastLoginDate]

@LastLoginDate datetime,
@UserCode int,
@UserType char(2)

AS
BEGIN

	SET NOCOUNT ON
	DECLARE @Err int


    SELECT DISTINCT TOP 100 PERCENT
		tblCase.casenbr,
		tblCase.ExtCaseNbr,
		tblCase.dateadded,
		tblExaminee.FirstName,
		tblExaminee.LastName,
		tblExaminee.lastname +  ', ' + tblExaminee.firstname AS examineename,
		CONVERT(varchar(20), tblCase.ApptDate, 101) + ' ' + RIGHT(CONVERT(VARCHAR, tblCase.ApptTime),7)  ApptDate,
		tblCase.claimnbr,
		tblServices.description AS Service,
		tblServices.description AS ServiceDesc,
		tblCase.DoctorName AS provider,
		tblCaseType.Description AS CaseType,
		tblWebQueuesV2.Description AS WebQueueStatusDesc,
		CAST(tblCase.DateAdded AS VARCHAR(20)) AS SavedDateTime,
		tblClient.LastName + ', ', tblClient.FirstName AS ClientName,
		ISNULL(NULLIF(tblCase.sinternalcasenbr,''),tblCase.casenbr) AS webcontrolnbr
			FROM tblCase
			INNER JOIN tblServices ON tblCase.servicecode = tblServices.servicecode
			INNER JOIN tblExaminee ON tblCase.chartnbr = tblExaminee.chartnbr
			INNER JOIN tblPublishOnWeb ON tblCase.casenbr = tblPublishOnWeb.tablekey
			INNER JOIN tblClient ON tblCase.ClientCode = tblClient.ClientCode
			INNER JOIN tblCaseType ON tblCase.CaseType = tblCaseType.Code
			INNER JOIN tblQueues ON tblCase.Status = tblQueues.StatusCode
			INNER JOIN tblWebQueuesV2 on tblQueues.WebStatusCodeV2 = tblWebQueuesV2.StatusCode
		WHERE tblPublishOnWeb.tabletype = 'tblCase'
			AND (tblPublishOnWeb.PublishOnWeb = 1)
			AND (tblPublishOnWeb.UserType = @UserType)
			AND (tblPublishOnWeb.UserCode = @UserCode)
			AND (tblPublishOnWeb.dateadded > @LastLoginDate)

	SET @Err = @@Error

	RETURN @Err
END
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[proc_GetClientsByCompany]...';


GO
CREATE PROCEDURE [proc_GetClientsByCompany]

@CompanyCode int

AS

SELECT DISTINCT lastname + ', ' + firstname + ' ' + tblCompany.intname name, clientcode FROM tblclient
	INNER JOIN tblCompany ON tblClient.CompanyCode = tblCompany.CompanyCode
	INNER JOIN tblWebUser ON tblClient.ClientCode = tblWebUser.IMECentricCode and tblWebUser.UserType = 'CL'
	WHERE tblClient.CompanyCode = @CompanyCode
		AND tblClient.Status = 'Active'
	ORDER BY name
GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO

IF EXISTS (SELECT * FROM #tmpErrors) ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT>0 BEGIN
PRINT N'The transacted portion of the database update succeeded.'
COMMIT TRANSACTION
END
ELSE PRINT N'The transacted portion of the database update failed.'
GO
DROP TABLE #tmpErrors
GO
PRINT N'Update complete.';


GO

-- -Issue 10022 - add new Exception trigger
INSERT INTO tblExceptionList (Description, Status, DateAdded, UserIDAdded, DateEdited, UserIDEdited)
VALUES('SLA Violation', 'Active', GETDATE(), 'Admin', GETDATE(), 'Admin')
GO

-- Issue 10048 - no longer using field ExceptionAlert.  Replacing with AlertType.  Set the values
-- For all Case History with Follow up date is not null AND the Office of the case is set to use 
--    ShowFollowUpOnCaseOpen (= true), KEEP the follow up date and set the AlertType=1
UPDATE H
   SET AlertType = 1
  FROM tblCaseHistory AS H
			INNER JOIN tblCase AS C ON H.CaseNbr = C.CaseNbr
			INNER JOIN tblOffice AS O ON C.OfficeCode = O.OfficeCode
 WHERE FollowUpDate IS NOT NULL 
   AND O.ShowFollowUpOnCaseOpen = 1
GO
-- For all Case History created by ERP (UserID = ERP) and the FollowUpDate is not null, Clear the follow up date and set AlertType=1
UPDATE tblCaseHistory 
   SET AlertType = 1, 
       FollowUpDate = NULL 
 WHERE UserID = 'ERP' 
   AND FollowUpDate IS NOT NULL
GO

-- Issue 10006 - new event ID and Business Rule to provide Bulk Billing Format override
INSERT INTO tblEvent(EventID, Descrip, Category)
VALUES(1811, 'Finalize Invoice', 'Accounting')
GO
INSERT INTO tblBusinessRule (BusinessRuleID, Name, Category, Descrip, IsActive, EventID, AllowOverride, Param1Desc, Param2Desc, Param3Desc, Param4Desc, Param5Desc, BrokenRuleAction)
VALUES(100, 'BulkBillingOverride', 'Accounting', 'Allow Bulk Billing Format Override based on case details', 1, 1811, 0, 'BulkBillingID', NULL, NULL, NULL, NULL, 0)
GO
-- Issue 10006 - patch tblAcctHeader.BulkBillingId column 
UPDATE ah 
   SET ah.BulkBillingID = co.bulkbillingid
  FROM tblAcctHeader ah
			INNER JOIN tblclient AS cl ON ah.clientcode = cl.ClientCode
			INNER JOIN tblCompany AS co ON cl.CompanyCode = co.CompanyCode
WHERE ah.DocumentType = 'IN'
GO 


--Issue 11044 (subtask of 11008) Zurich IMECentric and Bulk Billing Changes - data patch
 INSERT INTO tblCustomerData ([Version], TableType, TableKey, [Param], CustomerName)
  SELECT 
    1, 
	'tblCase', 
    C.CaseNbr, 
	CASE
	  WHEN CT.EWBusLineID = 3 AND S.EWServiceTypeID IN (2,3) THEN 'PayKind="37PCS";'
	  WHEN CT.EWBusLineID = 3 THEN 'PayKind="30IME";'
	  ELSE 'PayKind="37IME";'
	END AS [Param],
    'Zurich'
  FROM tblCase AS C
  INNER JOIN tblCaseType AS CT ON C.CaseType = CT.Code
  INNER JOIN tblServices AS S ON C.ServiceCode = S.ServiceCode
  INNER JOIN tblClient AS CL ON C.ClientCode = CL.ClientCode
  LEFT JOIN tblClient AS CLB ON C.BillClientCode = CLB.ClientCode
  INNER JOIN tblCompany AS CO ON CL.CompanyCode = CO.CompanyCode
  LEFT JOIN tblCompany AS CO2 ON CLB.CompanyCode = CO2.CompanyCode
  INNER JOIN tblEWParentCompany AS COP ON CO.ParentCompanyID = COP.ParentCompanyID
  LEFT JOIN tblEWParentCompany AS COP2 ON CO2.ParentCompanyID = COP2.ParentCompanyID
  WHERE 
    CO.ParentCompanyID = 60 
	OR CO2.ParentCompanyID = 60
    AND (C.Status NOT IN (8,9) 
	     OR (C.Status IN (8,9) 
		     AND ([DateCompleted] >= '2018-01-01' 
			      OR [DateCanceled] >= '2018-01-01')))
GO 

-- Issue 11046 - add new business rule to set visibility of amt fields for an invoice
INSERT INTO tblBusinessRule (BusinessRuleID, Name, Category, Descrip, IsActive, EventID, AllowOverride, Param1Desc, Param2Desc, Param3Desc, Param4Desc, Param5Desc, BrokenRuleAction)
VALUES(101, 'ShowInvoiceAmtFields', 'Accounting', 'Set Invoice Amt Field visibility', 1, 1801, 0, 'ShowRetailAmt', 'ShowDiscountAmt', NULL, NULL, NULL, 0)
GO 

-- Issue 11046 - add new business rule to calculate retail amount value
INSERT INTO tblBusinessRule (BusinessRuleID, Name, Category, Descrip, IsActive, EventID, AllowOverride, Param1Desc, Param2Desc, Param3Desc, Param4Desc, Param5Desc, BrokenRuleAction)
VALUES(102, 'CalcInvRetailAmt', 'Accounting', 'Caculate Retail Amount for Invoice Line Item', 1, 1801, 0, 'MarkupAmt', NULL, NULL, NULL, NULL, 0)
GO 



DELETE FROM tblCodes WHERE Category='WorkCompCaseType' AND SubCategory='CA'
GO
INSERT INTO tblCodes(Category, SubCategory, Value) VALUES 
('WorkCompCaseType', 'CA', 'AME'), 
('WorkCompCaseType', 'CA', 'AME-R'), 
('WorkCompCaseType', 'CA', 'AME-S'), 
('WorkCompCaseType', 'CA', 'A-QME'), 
('WorkCompCaseType', 'CA', 'CONSULT'), 
('WorkCompCaseType', 'CA', 'DCD'), 
('WorkCompCaseType', 'CA', 'D-QME'), 
('WorkCompCaseType', 'CA', 'FCE'), 
('WorkCompCaseType', 'CA', 'IME'), 
('WorkCompCaseType', 'CA', 'IME-S'), 
('WorkCompCaseType', 'CA', 'IME-ADR'), 
('WorkCompCaseType', 'CA', 'IME-LSH'), 
('WorkCompCaseType', 'CA', 'IME-SIBTF'), 
('WorkCompCaseType', 'CA', 'IME-SIBTF-S'), 
('WorkCompCaseType', 'CA', 'QME'), 
('WorkCompCaseType', 'CA', 'QME-R'), 
('WorkCompCaseType', 'CA', 'QME-S'), 
('WorkCompCaseType', 'CA', 'P/U-QME'), 
('WorkCompCaseType', 'CA', 'P/U-QME-R'), 
('WorkCompCaseType', 'CA', 'P/U-QME-S'), 
('WorkCompCaseType', 'CA', 'R-PQME'), 
('WorkCompCaseType', 'CA', 'R-PQME-R'), 
('WorkCompCaseType', 'CA', 'R-PQME-S'),
('WorkCompCaseType', 'CA', 'RR'), 
('WorkCompCaseType', 'CA', 'RR-S')
GO


-- Issue 11045 - business rules per comments on the issue.  ii will like Jose above, comment these out until ready
INSERT INTO tblBusinessRule (BusinessRuleID, Name, Category, Descrip, IsActive, EventID, AllowOverride, Param1Desc, Param2Desc, Param3Desc, Param4Desc, Param5Desc, BrokenRuleAction)
VALUES(120, 'DetermineInvFormat', 'Accounting', 'Zurich Bulk Billing Invoice Format', 1, 1806, 0, 'Invoice Format Key', NULL, NULL, NULL, NULL, 0)
GO
