/*
Deployment script for sTargetDB

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
/*
:setvar DatabaseName "sTargetDB"
:setvar DefaultFilePrefix "sTargetDB"
:setvar DefaultDataPath ""
:setvar DefaultLogPath ""
*/

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO

IF (SELECT OBJECT_ID('tempdb..#tmpErrors')) IS NOT NULL DROP TABLE #tmpErrors
GO
CREATE TABLE #tmpErrors (Error int)
GO
SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
GO
BEGIN TRANSACTION
GO
PRINT N'Altering [dbo].[tblCase]...';


GO
ALTER TABLE [dbo].[tblCase]
    ADD [DrMedRecsDueDate] DATETIME NULL;


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Altering [dbo].[tblDoctorRecommend]...';


GO
ALTER TABLE [dbo].[tblDoctorRecommend] ALTER COLUMN [FeedbackTo] VARCHAR (50) NULL;


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Altering [dbo].[tblWebNotification]...';


GO
ALTER TABLE [dbo].[tblWebNotification] ALTER COLUMN [NotificationSubject] VARCHAR (1000) NULL;


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[vwMedicalRecordsDue]...';


GO

CREATE VIEW [dbo].[vwMedicalRecordsDue]
AS
SELECT C.CaseNbr,
       C.ExtCaseNbr,
       CO.IntName AS CompanyName,
       ISNULL(EE.LastName, '') + ', ' + ISNULL(EE.FirstName, '') AS ExamineeName,
	   CASE WHEN ISNULL(DR.LastName,'') <> '' THEN DR.LastName + ', ' + ISNULL(DR.FirstName, '') ELSE '' END AS DoctorName,
	   LO.Location,
       C.DoctorLocation,
       C.MarketerCode,
       C.SchedulerCode,
       C.QARep,
       C.ApptDate,
	   SE.[Description] AS ServiceDesc,
       C.ClientCode,
       C.Status,
       C.DoctorCode,
       CL.CompanyCode,
       C.OfficeCode,
	   C.CaseType,
	   C.ServiceCode,
	   C.ExternalDueDate,
	   C.DateMedsRecd,
	   C.DrMedRecsDueDate,
	   C.InternalDueDate,
	   C.DrChartSelect,
	   C.DateDrChart,
	   C.DateEdited,
       C.UserIDEdited,
	   C.LastStatusChg,
       DATEDIFF(DAY, GETDATE(), C.DrMedRecsDueDate) AS DaysTillDue,
	   ISNULL(BillCompany.ParentCompanyID, CO.ParentCompanyID) AS ParentCompanyID,
	   Q.StatusDesc,
	   Q.FunctionCode
 FROM tblCase AS C
 INNER JOIN tblExaminee AS EE ON EE.ChartNbr = C.ChartNbr
 INNER JOIN tblClient AS CL ON CL.ClientCode = C.ClientCode
 INNER JOIN tblCompany AS CO ON CO.CompanyCode = CL.CompanyCode
 INNER JOIN tblServices AS SE ON SE.ServiceCode = C.ServiceCode
 INNER JOIN tblQueues AS Q ON Q.StatusCode=C.Status
 LEFT OUTER JOIN tblDoctor AS DR ON DR.DoctorCode = C.DoctorCode
 LEFT OUTER JOIN tblClient AS BillClient ON BillClient.ClientCode = C.BillClientCode
 LEFT OUTER JOIN tblCompany AS BillCompany ON BillCompany.CompanyCode = BillClient.CompanyCode
 LEFT OUTER JOIN tblLocation AS LO ON LO.LocationCode = C.DoctorLocation
GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Altering [dbo].[proc_WebNotification_Insert]...';


GO
ALTER PROCEDURE [proc_WebNotification_Insert]
(
	@WebNotificationID int = NULL output,
	@NotificationType varchar(30),
	@EntityId int = NULL,
	@EntityType varchar(50) = NULL,
	@ImeCentricCode int = NULL,
	@UserType char(2) = NULL,
	@WebUserId int = NULL,
	@WebUserCompanyName varchar(100) = NULL,
	@WebUserFirstName varchar(50) = NULL,
	@WebUserLastName varchar(50) = NULL,
	@WebUserEmailAddress varchar(200) = NULL,
	@ToEmailAddress varchar(200) = NULL,
	@FromEmailAddress varchar(200) = NULL,
	@NotificationSubject varchar(1000) = NULL,
	@NotificationDetail varchar(MAX) = NULL,
	@ErrorMessage varchar(500) = NULL,
	@DateAdded smalldatetime = NULL,
	@UserIDAdded varchar(100) = NULL,
	@NotificationSent bit = NULL,
	@NotificationSentDate smalldatetime = NULL
)

AS

BEGIN

	SET NOCOUNT OFF
	DECLARE @Err int

	INSERT
	INTO [tblWebNotification]
	(
		[NotificationType],
		[EntityId],
		[EntityType],
		[ImeCentricCode],
		[UserType],
		[WebUserId],
		[WebUserCompanyName],
		[WebUserFirstName],
		[WebUserLastName],
		[WebUserEmailAddress],
		[ToEmailAddress],
		[FromEmailAddress],
		[NotificationSubject],
		[NotificationDetail],
		[ErrorMessage],
		[DateAdded],
		[UserIDAdded],
		[NotificationSent],
		[NotificationSentDate]
	)
	VALUES
	(
		@NotificationType,
		@EntityId,
		@EntityType,
		@ImeCentricCode,
		@UserType,
		@WebUserId,
		@WebUserCompanyName,
		@WebUserFirstName,
		@WebUserLastName,
		@WebUserEmailAddress,
		@ToEmailAddress,
		@FromEmailAddress,
		@NotificationSubject,
		@NotificationDetail,
		@ErrorMessage,
		@DateAdded,
		@UserIDAdded,
		@NotificationSent,
		@NotificationSentDate
	)

	SET @Err = @@Error

	SELECT @WebNotificationID = SCOPE_IDENTITY()

	RETURN @Err
END
GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Altering [dbo].[proc_WebNotification_Update]...';


GO
ALTER PROCEDURE [proc_WebNotification_Update]
(
	@WebNotificationID int,
	@NotificationType varchar(30),
	@EntityId int = NULL,
	@EntityType varchar(50) = NULL,
	@ImeCentricCode int = NULL,
	@UserType char(2) = NULL,
	@WebUserId int = NULL,
	@WebUserCompanyName varchar(100) = NULL,
	@WebUserFirstName varchar(50) = NULL,
	@WebUserLastName varchar(50) = NULL,
	@WebUserEmailAddress varchar(200) = NULL,
	@ToEmailAddress varchar(200) = NULL,
	@FromEmailAddress varchar(200) = NULL,
	@NotificationSubject varchar(1000) = NULL,
	@NotificationDetail varchar(MAX) = NULL,
	@ErrorMessage varchar(500) = NULL,
	@DateAdded smalldatetime = NULL,
	@UserIDAdded varchar(100) = NULL,
	@NotificationSent bit = NULL,
	@NotificationSentDate smalldatetime = NULL
)
AS
BEGIN

	SET NOCOUNT OFF
	DECLARE @Err int

	UPDATE [tblWebNotification]
	SET
		[NotificationType] = @NotificationType,
		[EntityId] = @EntityId,
		[EntityType] = @EntityType,
		[ImeCentricCode] = @ImeCentricCode,
		[UserType] = @UserType,
		[WebUserId] = @WebUserId,
		[WebUserCompanyName] = @WebUserCompanyName,
		[WebUserFirstName] = @WebUserFirstName,
		[WebUserLastName] = @WebUserLastName,
		[WebUserEmailAddress] = @WebUserEmailAddress,
		[ToEmailAddress] = @ToEmailAddress,
		[FromEmailAddress] = @FromEmailAddress,
		[NotificationSubject] = @NotificationSubject,
		[NotificationDetail] = @NotificationDetail,
		[ErrorMessage] = @ErrorMessage,
		[DateAdded] = @DateAdded,
		[UserIDAdded] = @UserIDAdded,
		[NotificationSent] = @NotificationSent,
		[NotificationSentDate] = @NotificationSentDate
	WHERE
		[WebNotificationID] = @WebNotificationID

	SET @Err = @@Error

	RETURN @Err
END
GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO

IF EXISTS (SELECT * FROM #tmpErrors) ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT>0 BEGIN
PRINT N'The transacted portion of the database update succeeded.'
COMMIT TRANSACTION
END
ELSE PRINT N'The transacted portion of the database update failed.'
GO
DROP TABLE #tmpErrors
GO
PRINT N'Update complete.';


GO


-- Issue 11119 - add new item to tblExceptioList for Generate Quote Document
INSERT INTO tblExceptionList (ExceptionID, Description, Status, DateAdded, UserIDAdded, DateEdited, UserIDEdited)
VALUES(31, 'Generate Quote Document', 'Active', '2019-06-21 09:28:00.000', 'Admin', '2019-06-21 09:28:00.000', 'Admin')
GO 


-- Issue 11142 - Network Fee Schedule Calculation Method (switch between "new" and "old" fee schedule tables)
INSERT INTO tblSetting(Name, Value)
VALUES('NetworkFeeSchedCalcMethod', '1')
GO

-- Issue 10243 - add new status queue form to list of forms available for choosing
  INSERT INTO [tblQueueForms] ([FormName], [Description])
  VALUES ('frmStatusMedRecsDue', 'Form with Medical Records Due Date')


--*****  Issue 11152 - add business rules for MI Auto Authorization - add rules to the tables when ready to turn on

----  *******  Setting BusinessRuleID to 12 – if changed, need to change below
INSERT INTO tblBusinessRule (BusinessRuleID, Name, Category, Descrip, IsActive, EventID, AllowOverride, Param1Desc, Param2Desc, Param3Desc, Param4Desc, Param5Desc, BrokenRuleAction)
VALUES(12, 'ValidDrDocForSched', 'Appointment', 'Doctor must have the valid document on file when scheduling appointments', 1, 1101, 0, 'Document Type ID', NULL, NULL, NULL, NULL, 0)

















