/*
Deployment script for sTargetDB

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
/*
:setvar DatabaseName "sTargetDB"
:setvar DefaultFilePrefix "sTargetDB"
:setvar DefaultDataPath ""
:setvar DefaultLogPath ""
*/

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO

IF (SELECT OBJECT_ID('tempdb..#tmpErrors')) IS NOT NULL DROP TABLE #tmpErrors
GO
CREATE TABLE #tmpErrors (Error int)
GO
SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
GO
BEGIN TRANSACTION
GO
PRINT N'Altering [dbo].[tblAcctDetail]...';


GO
ALTER TABLE [dbo].[tblAcctDetail]
    ADD [FeeCodeSource] INT NULL;


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Altering [dbo].[tblAcctHeader]...';


GO
ALTER TABLE [dbo].[tblAcctHeader]
    ADD [FeeCodeSource] INT NULL;


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Altering [dbo].[tblAcctQuoteFee]...';


GO
ALTER TABLE [dbo].[tblAcctQuoteFee]
    ADD [QuoteFeeConfigID] INT NULL;


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Altering [dbo].[tblCaseTrans]...';


GO
ALTER TABLE [dbo].[tblCaseTrans]
    ADD [FeeCode]       INT NULL,
        [FeeCodeSource] INT NULL;


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Altering [dbo].[tblDoctorLocation]...';


GO
ALTER TABLE [dbo].[tblDoctorLocation]
    ADD [MaxSlotOnWeb] INT NULL;


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Altering [dbo].[tblDPSSortModel]...';


GO
ALTER TABLE [dbo].[tblDPSSortModel]
    ADD [DisplayOrder] INT NULL;


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Altering [dbo].[tblQuoteFeeConfig]...';


GO
ALTER TABLE [dbo].[tblQuoteFeeConfig]
    ADD [ProdCode] INT NULL;


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[tblCaseRecRetrieval]...';


GO
CREATE TABLE [dbo].[tblCaseRecRetrieval] (
    [RecRetrievalID]  INT           IDENTITY (1, 1) NOT NULL,
    [CaseNbr]         INT           NOT NULL,
    [RetrievalExtKey] VARCHAR (100) NULL,
    [DateAdded]       DATETIME      NULL,
    [UserIDAdded]     VARCHAR (15)  NULL,
    [DateEdited]      DATETIME      NULL,
    [UserIDEdited]    VARCHAR (15)  NULL,
    [ConfidenceValue] INT           NULL,
    [FirstName]       VARCHAR (50)  NULL,
    [LastName]        VARCHAR (50)  NULL,
    [FirmName]        VARCHAR (100) NULL,
    [ClaimNbr]        VARCHAR (50)  NULL,
    [DOB]             DATE          NULL,
    PRIMARY KEY CLUSTERED ([RecRetrievalID] ASC)
);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[tblCaseRecRetrievalDocument]...';


GO
CREATE TABLE [dbo].[tblCaseRecRetrievalDocument] (
    [RecRetrievalDocumentID] INT           IDENTITY (1, 1) NOT NULL,
    [CaseNbr]                INT           NOT NULL,
    [RetrievalDocExtKey]     VARCHAR (100) NULL,
    [DateAdded]              DATETIME      NULL,
    [UserIDAdded]            VARCHAR (15)  NULL,
    [DateEdited]             DATETIME      NULL,
    [UserIDEdited]           VARCHAR (15)  NULL,
    [RetrievalStart]         DATETIME      NULL,
    [RetrievalEnd]           DATETIME      NULL,
    [CaseDocID]              INT           NULL,
    [RetrievalStatusID]      INT           NOT NULL,
    PRIMARY KEY CLUSTERED ([RecRetrievalDocumentID] ASC)
);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[DF_tblCaseRecRetrievalDocument_RetrievalStatusID]...';


GO
ALTER TABLE [dbo].[tblCaseRecRetrievalDocument]
    ADD CONSTRAINT [DF_tblCaseRecRetrievalDocument_RetrievalStatusID] DEFAULT (0) FOR [RetrievalStatusID];


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Altering [dbo].[vwCaseTrans]...';


GO
ALTER VIEW vwCaseTrans
AS
    SELECT  tblCaseTrans.CaseNbr ,
            tblCaseTrans.LineNbr ,
            tblCaseTrans.Type ,
            tblCaseTrans.Date ,
            tblCaseTrans.ProdCode ,
            tblCaseTrans.CPTCode ,
            tblCaseTrans.LongDesc ,
            tblCaseTrans.unit ,
            tblCaseTrans.unitAmount ,
            tblCaseTrans.extendedAmount ,
            tblCaseTrans.Taxable ,
            tblCaseTrans.DateAdded ,
            tblCaseTrans.UserIDAdded ,
            tblCaseTrans.DateEdited ,
            tblCaseTrans.UserIDEdited ,
            tblCaseTrans.DrOPCode ,
            tblCaseTrans.DrOPType ,
            tblCaseTrans.SeqNo ,
            tblCaseTrans.LineItemType ,
            tblCaseTrans.Location ,
            tblCaseTrans.UnitOfMeasureCode,
			tblCaseTrans.CreateInvoiceVoucher,
			tblCaseTrans.FeeCode, 
			tblCaseTrans.FeeCodeSource
    FROM    tblCaseTrans
    WHERE   HeaderID IS NULL
GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Altering [dbo].[vwRptProgressiveUpcomingAppt]...';


GO

ALTER VIEW [dbo].[vwRptProgressiveUpcomingAppt]
AS
SELECT
 C.CaseNbr,
 CASE WHEN ISNULL(C.ClaimNbrExt,'') <> '' THEN C.ClaimNbr + '.' + C.ClaimNbrExt ELSE C.ClaimNbr END AS ClaimNumber,
 C.AddlClaimNbrs,
 Q.StatusDesc AS CaseStatus,
 S.Description AS Service,
 C.DateOfInjury AS DateOfLoss,

 ISNULL(EE.LastName,'') + ', ' + ISNULL(EE.FirstName,'') AS ClaimantName,
 ISNULL(CL.LastName,'') + ', ' + ISNULL(CL.FirstName,'') AS RepName,
 C.DoctorSpecialty,

 C.DateReceived,
 C.ApptDate,
 L.County AS ExamLocationCounty,
 (SELECT TOP 1 Description FROM tblCaseDocuments AS CD WHERE (CD.CaseNbr=C.CaseNbr OR (CD.MasterCaseNbr=C.MasterCaseNbr AND CD.SharedDoc=1)) AND Description LIKE '% EFF[ .]%' ORDER BY SeqNo DESC) AS LastEff,

 CL.CompanyCode,

 dbo.fnDateValue(C.ApptDate) AS FilterDate

 FROM tblCase AS C
 INNER JOIN tblExaminee AS EE ON EE.ChartNbr = C.ChartNbr
 INNER JOIN tblQueues AS Q ON C.Status = Q.StatusCode
 INNER JOIN tblServices AS S ON S.ServiceCode = C.ServiceCode
 INNER JOIN tblClient AS CL ON CL.ClientCode = C.ClientCode
 LEFT OUTER JOIN tblLocation AS L ON C.DoctorLocation = L.LocationCode
 WHERE 1=1
 AND S.EWServiceTypeID=1
GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Altering [dbo].[spFeeSched_SyncTableData_Detail]...';


GO
ALTER PROCEDURE [dbo].[spFeeSched_SyncTableData_Detail]
     @iHdrSetupID INTEGER,
	 @iHeaderID INTEGER 
AS
BEGIN
	
	DECLARE @iDtlSetupID INTEGER 
	DECLARE @iDetailID INTEGER 
	DECLARE @sBusLine VARCHAR(MAX)
	DECLARE @sFeeZone VARCHAR(MAX)
	DECLARE @sProduct VARCHAR(MAX)
	DECLARE @sSpecialty VARCHAR(MAX)
	DECLARE @sSvcType VARCHAR(MAX)
	DECLARE @sService VARCHAR(MAX)
	DECLARE @sDoctor VARCHAR(MAX)
	DECLARE @sExamLocation VARCHAR(MAX)
	
	-- DEV NOTE: this process will completely rebuild all items in FSDetailCondition for the Detail items
	--		that are present; therefore, before we do anything we are going dump all Condition items
	--		that are attached to the detail items for the Header we are processing.
	DELETE 
	  FROM tblFSDetailCondition 
	 WHERE FSDetailID IN (SELECT FSDetailID FROM tblFSDetail WHERE FSHeaderID = @iHeaderID)

	-- get a list of Detail Items that make up this Header and process them
	DECLARE curDetailSetup CURSOR FOR
		SELECT FSDetailSetupID, FSDetailID, 
			  BusLine,  ServiceType, Service, Product, FeeZone, Specialty, Doctor, ExamLocation
		  FROM tblFSDetailSetup 
		 WHERE FSHeaderSetupID = @iHdrSetupID
	OPEN curDetailSetup
	FETCH NEXT FROM curDetailSetup INTO @iDtlSetupID, @iDetailID, @sBusLine, @sSvcType, @sService, @sProduct, @sFeeZone, @sSpecialty, @sDoctor, @sExamLocation
	WHILE @@FETCH_STATUS = 0
	BEGIN 
		-- update or insert item? 
		IF @iDetailID IS NULL
		BEGIN 
			INSERT INTO tblFSDetail(FSHeaderID, ProcessOrder, FeeUnit, FeeAmt, NSFeeAmt1, NSFeeAmt2, NSFeeAmt3, LateCancelAmt, CancelDays, DateAdded, UserIDAdded)
				SELECT @iHeaderID, ProcessOrder, FeeUnit, ISNULL(FeeAmt, 0), NSFeeAmt1, NSFeeAmt2, NSFeeAmt3, LateCancelAmt, CancelDays, DateAdded, UserIDAdded
				  FROM tblFSDetailSetup
				 WHERE FSDetailSetupID = @iDtlSetupID
			SET @iDetailID = @@IDENTITY 
			IF @iDetailID IS NOT NULL AND @iDetailID > 0 
			BEGIN 
				UPDATE tblFSDetailSetup
				   SET FSDetailID = @iDetailID 
				 WHERE FSDetailSetupID = @iDtlSetupID
			END
			ELSE 
			BEGIN 
				-- no DetailID; unable to continue
				RAISERROR ('Unable to create new tblFSDetail entry (FSDetailID is not valid).', 16, 2);
				RETURN 
			END 
		END 
		ELSE 
		BEGIN 
			-- need to update existing tblFSDetail entry
			UPDATE calc
			   SET ProcessOrder = ui.ProcessOrder, 
				  FeeUnit = ui.FeeUnit,
				  FeeAmt = ISNULL(ui.FeeAmt, 0), 
				  NSFeeAmt1 = ui.NSFeeAmt1,
				  NSFeeAmt2 = ui.NSFeeAmt2, 
				  NSFeeAmt3 = ui.NSFeeAmt3, 
				  LateCancelAmt = ui.LateCancelAmt, 
				  CancelDays = ui.CancelDays, 
				  DateEdited = ui.DateEdited, 
				  UserIDEdited = ui.UserIDEdited
			  FROM tblFSDetail AS calc
					INNER JOIN tblFSDetailSetup AS ui ON ui.FSDetailID = calc.FSDetailID
			 WHERE calc.FSDetailID = @iDetailID
		END 

		-- process next row
		FETCH NEXT FROM curDetailSetup INTO @iDtlSetupID, @iDetailID, @sBusLine, @sSvcType, @sService, @sProduct, @sFeeZone, @sSpecialty, @sDoctor, @sExamLocation
	END
	CLOSE curDetailSetup
	DEALLOCATE curDetailSetup
	
	-- Process Detail Condition selections
	INSERT INTO tblFSDetailCondition(FSDetailID, ConditionTable, ConditionKey)
		SELECT  FSDetailID, 'tblEWBusLine', BL.value
		  FROM tblFSDetailSetup
					CROSS APPLY STRING_SPLIT(BusLine, ',') AS BL
		 WHERE FSHeaderSetupID = @iHdrSetupID
		   AND BL.value <> -1

		UNION 

		SELECT  FSDetailID, 'tblEWServiceType', ST.value
		  FROM tblFSDetailSetup
					CROSS APPLY STRING_SPLIT(ServiceType, ',') AS ST
		 WHERE FSHeaderSetupID = @iHdrSetupID
		   AND ST.value <> -1

		UNION 

		SELECT  FSDetailID, 'tblServices', S.value
		  FROM tblFSDetailSetup
					CROSS APPLY STRING_SPLIT(Service, ',') AS S
		 WHERE FSHeaderSetupID = @iHdrSetupID
		   AND S.value <> -1

		UNION 
		
		SELECT  FSDetailID, 'tblProduct', P.value
		  FROM tblFSDetailSetup
					CROSS APPLY STRING_SPLIT(Product, ',') AS P
		 WHERE FSHeaderSetupID = @iHdrSetupID
		   AND P.value <> -1

		UNION 

		SELECT  FSDetailID, 'tblEWFeeZone', FZ.value
		  FROM tblFSDetailSetup
					CROSS APPLY STRING_SPLIT(FeeZone, ',') AS FZ
		 WHERE FSHeaderSetupID = @iHdrSetupID
		   AND FZ.value <> -1

		UNION 

		SELECT  FSDetailID, 'tblSpecialty', SP.value
		  FROM tblFSDetailSetup
					CROSS APPLY STRING_SPLIT(Specialty, ',') AS SP
		 WHERE FSHeaderSetupID = @iHdrSetupID
		   AND SP.value <> -1

		UNION 

		SELECT  FSDetailID, 'tblDoctor', D.value
		  FROM tblFSDetailSetup
					CROSS APPLY STRING_SPLIT(Doctor, ',') AS D
		 WHERE FSHeaderSetupID = @iHdrSetupID
		   AND D.value <> -1

		UNION 

		SELECT  FSDetailID, 'tblLocation', L.value
		  FROM tblFSDetailSetup
					CROSS APPLY STRING_SPLIT(ExamLocation, ',') AS L
		 WHERE FSHeaderSetupID = @iHdrSetupID
		   AND L.value <> -1
	
	-- cleanup Detail table for items no longer part of setup table
	DELETE tblFSDetail
	  FROM tblfsDetail 
			LEFT OUTER JOIN tblFSDetailSetup ON tblFSDetailSetup.FSDetailID = tblFSDetail.FSDetailID
	 WHERE FSHeaderID = @iHeaderID 
	   AND tblFSDetailSetup.FSDetailID IS NULL
	
	RETURN

END
GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO

IF EXISTS (SELECT * FROM #tmpErrors) ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT>0 BEGIN
PRINT N'The transacted portion of the database update succeeded.'
COMMIT TRANSACTION
END
ELSE PRINT N'The transacted portion of the database update failed.'
GO
DROP TABLE #tmpErrors
GO
PRINT N'Update complete.';


GO
-- Issue 11654 - add new token for claim number extension only
INSERT INTO [dbo].[tblMessageToken] ([Name], [Description]) VALUES ('@ClaimNbrExt@ ', '')
GO


UPDATE U SET U.DisplayOrder=SM.RowNbr
FROM tblDPSSortModel AS U
INNER JOIN
(SELECT SortModelID, Description, ROW_NUMBER() OVER (ORDER BY Description) AS RowNbr
FROM tblDPSSortModel) AS SM ON U.SortModelID = SM.SortModelID
GO

-- Issue 11137 - data patch fot acctquotefee to link in prodcode
     UPDATE AQF
        SET AQF.QuoteFeeConfigID = QFC.QuoteFeeConfigID
     FROM tblAcctQuoteFee AS AQF
               INNER JOIN tblQuoteFeeConfig as QFC ON QFC.FeeValueName = AQF.FeeValueName
GO 

-- Issue 11137 - patch tblAcctDetail to set existing row to FeeCodeSource where FeeCode is present
UPDATE tblAcctDetail SET FeeCodeSource = 1 WHERE FeeCode IS NOT NULL AND FeeCodeSource IS NULL
GO 

-- Issue 11137 - patch tblAcctHeader to set existing rows to FeeCodeSource where FeeCode is present
UPDATE tblAcctHeader SET FeeCodeSource = 1 WHERE FeeCode IS NOT NULL AND FeeCodeSource IS NULL
GO 

-- Issue 11137 - patch tblAcctQuoteFee to set value for QuoteFeeConfigID
UPDATE AQ
   SET AQ.QuoteFeeConfigID = QF.QuoteFeeConfigID
FROM tblAcctQuoteFee AS AQ
          INNER JOIN tblQuoteFeeConfig AS QF ON QF.FeeValueName = AQ.FeeValueName
WHERE AQ.QuoteFeeConfigID IS NULL
GO

DELETE FROM [tblCaseApptRequestStatus]
INSERT INTO [dbo].[tblCaseApptRequestStatus] ([CaseApptRequestStatusID], [Name]) VALUES (0, 'Pending Acceptance')
INSERT INTO [dbo].[tblCaseApptRequestStatus] ([CaseApptRequestStatusID], [Name]) VALUES (1, 'Accepted')
INSERT INTO [dbo].[tblCaseApptRequestStatus] ([CaseApptRequestStatusID], [Name]) VALUES (2, 'Rejected')
GO
