/*
Deployment script for sTargetDB

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
/*
:setvar DatabaseName "sTargetDB"
:setvar DefaultFilePrefix "sTargetDB"
:setvar DefaultDataPath ""
:setvar DefaultLogPath ""
*/

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO

IF (SELECT OBJECT_ID('tempdb..#tmpErrors')) IS NOT NULL DROP TABLE #tmpErrors
GO
CREATE TABLE #tmpErrors (Error int)
GO
SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
GO
BEGIN TRANSACTION
GO
PRINT N'Dropping [dbo].[tblTempData].[IX_tblTempData_SessionIDModuleName]...';


GO
DROP INDEX [IX_tblTempData_SessionIDModuleName]
    ON [dbo].[tblTempData];


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Dropping [dbo].[tblCaseHistory].[IX_tblCaseHistory_CaseNbrEventDate]...';


GO
DROP INDEX [IX_tblCaseHistory_CaseNbrEventDate]
    ON [dbo].[tblCaseHistory];


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Dropping [dbo].[tblCaseHistory].[IX_tblCaseHistory_CaseNbrFollowUpDate]...';


GO
DROP INDEX [IX_tblCaseHistory_CaseNbrFollowUpDate]
    ON [dbo].[tblCaseHistory];


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Altering [dbo].[tblCaseRecRetrievalDocument]...';


GO
ALTER TABLE [dbo].[tblCaseRecRetrievalDocument]
    ADD [FileType]         VARCHAR (50)  NULL,
        [RetrievalGroupID] VARCHAR (100) NULL;


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Altering [dbo].[tblDocument]...';


GO
ALTER TABLE [dbo].[tblDocument]
    ADD [ElecTransferFolderID]        INT           NULL,
        [ElecTransferOutputFile]      VARCHAR (128) NULL,
        [ElecTransferDupFileHandling] INT           NULL;


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Altering [dbo].[tblOffice]...';


GO
ALTER TABLE [dbo].[tblOffice]
    ADD [RecRetrievalIncludeFileTypes] VARCHAR (150) NULL,
        [RecRetrievalExcludeFileTypes] VARCHAR (150) NULL,
        [RecRetrievalFileHandling]     INT           NULL,
        [RecRetrievalOrderStatus]      VARCHAR (150) NULL;


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Starting rebuilding table [dbo].[tblDoctorDocuments]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_tblDoctorDocuments] (
    [DoctorCode]         INT           NOT NULL,
    [RecID]              INT           IDENTITY (1, 1) NOT NULL,
    [Description]        VARCHAR (50)  NULL,
    [ExpireDate]         DATETIME      NULL,
    [PathFilename]       VARCHAR (120) NULL,
    [DateAdded]          DATETIME      NOT NULL,
    [UserIDAdded]        VARCHAR (20)  NULL,
    [PublishOnWeb]       BIT           NULL,
    [DateEdited]         DATETIME      NULL,
    [UserIDEdited]       VARCHAR (30)  NULL,
    [EWDoctorDocumentID] INT           NULL,
    [EWDoctorID]         INT           NULL,
    [EWDrDocTypeID]      INT           NULL,
    [SpecialtyCode]      VARCHAR (50)  NULL,
    [EWAccreditationID]  INT           NULL,
    [State]              VARCHAR (2)   NULL,
    [LicenseNbr]         VARCHAR (50)  NULL,
    [FileExists]         BIT           NULL,
    [Confidential]       BIT           NULL,
    [FolderID]           INT           NULL,
    [Notes]              TEXT          NULL,
    [AllowEdit]          BIT           NULL,
    [FileSize]           BIGINT        NULL,
    [OriginalFilePath]   VARCHAR (250) NULL,
    [ConvertStatus]      VARCHAR (25)  NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_tblDoctorDocuments1] PRIMARY KEY CLUSTERED ([RecID] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[tblDoctorDocuments])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_tblDoctorDocuments] ON;
        INSERT INTO [dbo].[tmp_ms_xx_tblDoctorDocuments] ([RecID], [DoctorCode], [Description], [ExpireDate], [PathFilename], [DateAdded], [UserIDAdded], [PublishOnWeb], [DateEdited], [UserIDEdited], [EWDoctorDocumentID], [EWDoctorID], [EWDrDocTypeID], [SpecialtyCode], [EWAccreditationID], [State], [LicenseNbr], [FileExists], [Confidential], [FolderID], [Notes], [AllowEdit], [FileSize], [OriginalFilePath], [ConvertStatus])
        SELECT   [RecID],
                 [DoctorCode],
                 [Description],
                 [ExpireDate],
                 [PathFilename],
                 [DateAdded],
                 [UserIDAdded],
                 [PublishOnWeb],
                 [DateEdited],
                 [UserIDEdited],
                 [EWDoctorDocumentID],
                 [EWDoctorID],
                 [EWDrDocTypeID],
                 [SpecialtyCode],
                 [EWAccreditationID],
                 [State],
                 [LicenseNbr],
                 [FileExists],
                 [Confidential],
                 [FolderID],
                 [Notes],
                 [AllowEdit],
                 [FileSize],
                 [OriginalFilePath],
                 [ConvertStatus]
        FROM     [dbo].[tblDoctorDocuments]
        ORDER BY [RecID] ASC;
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_tblDoctorDocuments] OFF;
    END

DROP TABLE [dbo].[tblDoctorDocuments];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_tblDoctorDocuments]', N'tblDoctorDocuments';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_tblDoctorDocuments1]', N'PK_tblDoctorDocuments', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[tblDoctorDocuments].[IX_tblDoctorDocuments_EWDoctorDocumentID]...';


GO
CREATE NONCLUSTERED INDEX [IX_tblDoctorDocuments_EWDoctorDocumentID]
    ON [dbo].[tblDoctorDocuments]([EWDoctorDocumentID] ASC);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[tblDoctorDocuments].[IX_U_tblDoctorDocuments_DoctorCodeRecID]...';


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_U_tblDoctorDocuments_DoctorCodeRecID]
    ON [dbo].[tblDoctorDocuments]([DoctorCode] ASC, [RecID] ASC);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[tblTempData].[IX_tblTempData_SessionIDModuleName]...';


GO
CREATE NONCLUSTERED INDEX [IX_tblTempData_SessionIDModuleName]
    ON [dbo].[tblTempData]([SessionID] ASC, [ModuleName] ASC)
    INCLUDE([IntValue1], [IntValue2], [VarCharValue1], [BitValue1], [BitValue2]);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[tblAcctHeader].[IX_tblAcctHeader_CaseDocID]...';


GO
CREATE NONCLUSTERED INDEX [IX_tblAcctHeader_CaseDocID]
    ON [dbo].[tblAcctHeader]([CaseDocID] ASC);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[tblAcctQuote].[IX_tblAcctQuote_CaseNbr]...';


GO
CREATE NONCLUSTERED INDEX [IX_tblAcctQuote_CaseNbr]
    ON [dbo].[tblAcctQuote]([CaseNbr] ASC);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[tblAcctQuoteFee].[IX_tblAcctQuoteFee_AcctQuoteID]...';


GO
CREATE NONCLUSTERED INDEX [IX_tblAcctQuoteFee_AcctQuoteID]
    ON [dbo].[tblAcctQuoteFee]([AcctQuoteID] ASC)
    INCLUDE([FeeValueName], [FeeAmount], [FeeUnit]);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[tblCaseEnvelope].[IX_tblCaseEnvelope_CaseNbrIsCertifiedMailDateAcknowledgedAddressedToEntityDateImported]...';


GO
CREATE NONCLUSTERED INDEX [IX_tblCaseEnvelope_CaseNbrIsCertifiedMailDateAcknowledgedAddressedToEntityDateImported]
    ON [dbo].[tblCaseEnvelope]([CaseNbr] ASC, [IsCertifiedMail] ASC, [DateAcknowledged] ASC, [AddressedToEntity] ASC, [DateImported] ASC);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[tblCaseHistory].[IX_tblCaseHistory_CaseNbr]...';


GO
CREATE NONCLUSTERED INDEX [IX_tblCaseHistory_CaseNbr]
    ON [dbo].[tblCaseHistory]([CaseNbr] ASC)
    INCLUDE([EventDate], [Eventdesc], [OtherInfo], [Duration], [Type], [Status], [PublishOnWeb], [UserIDEdited], [Highlight], [PublishedTo], [FollowUpDate], [AlertType], [UserID]);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[tblCasePeerBill].[IX_tblCasePeerBill_CaseNbr]...';


GO
CREATE NONCLUSTERED INDEX [IX_tblCasePeerBill_CaseNbr]
    ON [dbo].[tblCasePeerBill]([CaseNbr] ASC);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[tblDoctorCheckRequest].[IX_tblDoctorCheckRequest_CaseNbr]...';


GO
CREATE NONCLUSTERED INDEX [IX_tblDoctorCheckRequest_CaseNbr]
    ON [dbo].[tblDoctorCheckRequest]([CaseNbr] ASC);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[tblDPSBundle].[IX_tblDPSBundle_CombinedDPSBundleID]...';


GO
CREATE NONCLUSTERED INDEX [IX_tblDPSBundle_CombinedDPSBundleID]
    ON [dbo].[tblDPSBundle]([CombinedDPSBundleID] ASC)
    INCLUDE([DPSBundleID], [DPSBundleTypeID]);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[tblDPSBundle].[IX_tblDPSBundle_DPSStatusIDDateAcknowledged]...';


GO
CREATE NONCLUSTERED INDEX [IX_tblDPSBundle_DPSStatusIDDateAcknowledged]
    ON [dbo].[tblDPSBundle]([DPSStatusID] ASC, [DateAcknowledged] ASC)
    INCLUDE([CaseNbr]);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[tblExceptionDefEntity].[IX_tblExceptionDefEntity_IMECentricCode]...';


GO
CREATE NONCLUSTERED INDEX [IX_tblExceptionDefEntity_IMECentricCode]
    ON [dbo].[tblExceptionDefEntity]([IMECentricCode] ASC);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[tblOCRDocument].[IX_tblOCRDocument_OCRStatusID]...';


GO
CREATE NONCLUSTERED INDEX [IX_tblOCRDocument_OCRStatusID]
    ON [dbo].[tblOCRDocument]([OCRStatusID] ASC)
    INCLUDE([OCRSystemID], [CaseDocID], [ExtOCRDocumentID], [DateAdded], [UserIDAdded], [DateEdited], [UserIDEdited], [DateDue], [DateCompleted], [OriginalFileName], [OriginalFileDateUtc], [OriginalFileSizeKB], [OCRServer], [Priority], [Source], [DateReadyOCR], [DateSent], [DateReceived]);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[tblServiceWorkflowQueue].[IX_tblServiceWorkflowQueue_ServiceWorkflowIDStatusCodeNextStatus]...';


GO
CREATE NONCLUSTERED INDEX [IX_tblServiceWorkflowQueue_ServiceWorkflowIDStatusCodeNextStatus]
    ON [dbo].[tblServiceWorkflowQueue]([ServiceWorkflowID] ASC, [StatusCode] ASC, [NextStatus] ASC)
    INCLUDE([QueueOrder], [CreateInvoice], [CreateVoucher]);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[tblTranscriptionJobDictation].[IX_tblTranscriptionJobDictation_TranscriptionJobID]...';


GO
CREATE NONCLUSTERED INDEX [IX_tblTranscriptionJobDictation_TranscriptionJobID]
    ON [dbo].[tblTranscriptionJobDictation]([TranscriptionJobID] ASC);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[tblTranscriptionJobFile].[IX_tblTranscriptionJobFile_TranscriptionJobID]...';


GO
CREATE NONCLUSTERED INDEX [IX_tblTranscriptionJobFile_TranscriptionJobID]
    ON [dbo].[tblTranscriptionJobFile]([TranscriptionJobID] ASC);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Altering [dbo].[vwDoctorBlockTimeScheduleSummary]...';


GO
ALTER VIEW vwDoctorBlockTimeScheduleSummary
AS  
	
	-- DEV NOTE: the result set of this view needs to match (data type & column names) 
	--		vwDoctorScheduleSummary. These 2 views are conditionally used within the same IMEC code
	--		 and; therefore, need to be in "sync".
   
	-- This grabs all of the block time appts
	SELECT  
		Doc.LastName ,
		Doc.FirstName ,
		Loc.Location ,
		-- need to return date + "00:00" time
		DATEADD(d, DATEDIFF(d, 0, BTDay.ScheduleDate), 0) AS Date , 
          
		-- DEV NOTE: IMEC only looks for Scheduled/Hold value to count as Scheduled but only when CaseNbr is present; 
		--		"Reserved" is not considered scheduled. WHERE clause excludes late cancel/cancel appts.
		CASE BTSlot.DoctorBlockTimeSlotStatusID
			WHEN 22 THEN 'Hold'
			WHEN 30 THEN 'Scheduled' -- this will include your no shows
			ELSE 'Other'
		END AS Status, 
		
		Loc.InsideDr ,
		Doc.DoctorCode ,
		DocOff.OfficeCode ,
		BTDay.LocationCode , 
          
		-- DEV NOTE: Instead of using the Doctor.Booking value we will count the actual number
		--		slots that have been configured for each day, but only for the first slot of each day
		(SELECT IIF(MIN(sl.DoctorBlockTimeSlotID) = BTSlot.DoctorBlockTimeSlotID, COUNT(sl.DoctorBlockTimeSlotID), 0) 
		   FROM tblDoctorBlockTimeSlot AS sl 
		  WHERE sl.DoctorBlockTimeDayID = BTDay.DoctorBlockTimeDayID AND sl.StartTime = BTSlot.StartTime) AS Booking,
		
		-- DEV NOTE: we now a multiple rows to define each potential booking slot at the same date/time; therefore, 
		--		we only ever have CaseNbr1 to set/process but there may be multiple rows for the same time.
		CA.CaseNbr AS CaseNbr1 , 
		CAST(NULL AS INT) AS CaseNbr2 , 
		CAST(NULL AS INT) AS CaseNbr3 , 
		CAST(NULL AS INT) AS CaseNbr4 , 
		CAST(NULL AS INT) AS CaseNbr5 , 
		CAST(NULL AS INT) AS CaseNbr6 , 
		BTSlot.StartTime, 
		LocOff.OfficeCode as LocationOffice,
		
		-- new columns added to help debugging
		CA.CaseApptID AS CaseApptID, 
		NULL AS SchedCode, 
		BTDay.DoctorBlockTimeDayID AS DoctorBlockTimeDayID, 
		BTSlot.DoctorBlockTimeSlotID AS DoctorBlockTimeSlotID
	FROM
		tblDoctorBlockTimeDay AS BTDay
			INNER JOIN tblDoctorBlockTimeSlot AS BTSlot ON BTSlot.DoctorBlockTimeDayID = BTDay.DoctorBlockTimeDayID
			INNER JOIN tblDoctor AS Doc ON Doc.DoctorCode = BTDay.DoctorCode
			INNER JOIN tblLocation AS Loc ON Loc.LocationCode = BTDay.LocationCode
			INNER JOIN tblDoctorOffice AS DocOff ON DocOff.DoctorCode = Doc.DoctorCode 
			INNER JOIN tbllocationoffice AS LocOff ON (LocOff.OfficeCode = DocOff.OfficeCode AND LocOff.LocationCode = Loc.LocationCode) 
			LEFT OUTER JOIN tblCaseAppt AS CA ON CA.CaseApptID = BTSlot.CaseApptID AND (CA.ApptStatusID in (10, 100, 101, 102)) 
			LEFT OUTER JOIN tblCaseApptPanel AS CAP ON CAP.CaseApptID = CA.CaseApptID AND CAP.DoctorBlockTimeSlotID = BTSlot.DoctorBlockTimeSlotID
			LEFT OUTER JOIN tblCase AS C ON C.CaseNbr = CA.CaseNbr AND (C.Status <> 9) 
	WHERE   
		(BTDay.Active = 1) 

	UNION ALL

	-- Which we need to UNION with the non-block time appts (include panel exam items)
	SELECT 		
		Doc.LastName ,
		Doc.FirstName ,
		Loc.Location ,
		-- need to return date + "00:00" time
		DATEADD(d, DATEDIFF(d, 0, CA.ApptTime), 0) AS Date , 
		'Scheduled' as Status, 
		Loc.InsideDr ,
		Doc.DoctorCode ,
		DocOff.OfficeCode ,
		CA.LocationCode , 
		1 AS Booking, 
		CA.CaseNbr AS CaseNbr1 , 
		CAST(NULL AS INT) AS CaseNbr2 , 
		CAST(NULL AS INT) AS CaseNbr3 , 
		CAST(NULL AS INT) AS CaseNbr4 , 
		CAST(NULL AS INT) AS CaseNbr5 , 
		CAST(NULL AS INT) AS CaseNbr6 , 
		CA.ApptTime AS StartTime,
		LocOff.OfficeCode as LocationOffice,
		-- new columns added to help debugging
		CA.CaseApptID AS CaseApptID, 
		NULL AS SchedCode, 
		NULL AS DoctorBlockTimeDayID, 
		NULL AS DoctorBlockTimeSlotID
	FROM
		tblCaseAppt AS CA 
			LEFT OUTER JOIN tblCaseApptPanel AS CAP ON CAP.CaseApptID = CA.CaseApptID
			INNER JOIN tblDoctor AS Doc ON Doc.DoctorCode = IIF(CAP.CaseApptID IS NULL, CA.DoctorCode, CAP.DoctorCode)
			INNER JOIN tblLocation AS Loc ON Loc.LocationCode = CA.LocationCode
			INNER JOIN tblDoctorOffice AS DocOff ON DocOff.DoctorCode = Doc.DoctorCode
			INNER JOIN tbllocationoffice AS LocOff ON (LocOff.OfficeCode = DocOff.OfficeCode AND LocOff.LocationCode = Loc.LocationCode) 
			INNER JOIN tblCase AS C ON C.CaseNbr = CA.CaseNbr
	WHERE   
		 ((CA.DoctorBlockTimeSlotID IS NULL AND CA.DoctorCode IS NOT NULL) OR (CAP.DoctorBlockTimeSlotID IS NULL AND CAP.CaseApptID IS NOT NULL))
	 AND (CA.ApptStatusID IN (10, 100, 101, 102)) 
	 AND (C.Status <> 9)
GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO

IF EXISTS (SELECT * FROM #tmpErrors) ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT>0 BEGIN
PRINT N'The transacted portion of the database update succeeded.'
COMMIT TRANSACTION
END
ELSE PRINT N'The transacted portion of the database update failed.'
GO
DROP TABLE #tmpErrors
GO
PRINT N'Update complete.';


GO
