CREATE TABLE tblBlank
    (
      PrimaryKey INT NOT NULL IDENTITY(1, 1) ,
      BlankValue VARCHAR(75) NULL ,
      BlankValueLong VARCHAR(150) NULL
    )
GO
ALTER TABLE tblBlank ADD CONSTRAINT PK_tblBlank PRIMARY KEY CLUSTERED  (PrimaryKey)
GO

ALTER TABLE tblIMEData ADD
	AllowICD10 bit NULL,
	DefaultICDFormat int NULL
GO

ALTER TABLE tblICDCode ADD
	ICDFormat int NULL,
	CountryID int NULL
GO

ALTER TABLE tblDocument ADD
	CMSDiscountPercentage NUMERIC (10, 2) NULL,
	CMSPayor VARCHAR (150) NULL,
	CMSBox10aYes VARCHAR (20) NULL,
	CMSBox17 VARCHAR (30) NULL,
	CMSBox17a VARCHAR (30) NULL,
	CMSBox17b VARCHAR (30) NULL,
	CMSBox19 VARCHAR (50) NULL,
	CMSBox24JNonNPINbr VARCHAR (50) NULL,
	CMSBox24JNPINbr VARCHAR (20) NULL,
	CMSBox25 VARCHAR(20) NULL,
	CMSBox27Yes VARCHAR (20) NULL,
	CMSBox31Line1 VARCHAR (100) NULL,
	CMSBox31Line2 VARCHAR (50) NULL,
	CMSBox32a VARCHAR (20) NULL,
	CMSBox32b VARCHAR (50) NULL,
	CMSBox33Line1 VARCHAR (45) NULL,
	CMSBox33Line2 VARCHAR (45) NULL,
	CMSBox33Line3 VARCHAR (45) NULL,
	CMSBox33AreaCode VARCHAR (20) NULL,
	CMSBox33PhoneNumber VARCHAR (20) NULL,
	CMSBox33a VARCHAR (20) NULL,
	CMSBox33b VARCHAR (20) NULL
GO


ALTER TABLE tblClaimInfo
	ADD CMSBox24JNonNPINbr VARCHAR(50)
GO

INSERT  INTO tblBlank
        ( BlankValue )
VALUES  ( NULL )
GO


ALTER TABLE tblCase ADD
	ICDFormat INT NULL,
	ICDCodeE VARCHAR (10) NULL,
	ICDCodeF VARCHAR (10) NULL,
	ICDCodeG VARCHAR (10) NULL,
	ICDCodeH VARCHAR (10) NULL,
	ICDCodeI VARCHAR (10) NULL,
	ICDCodeJ VARCHAR (10) NULL,
	ICDCodeK VARCHAR (10) NULL,
	ICDCodeL VARCHAR (10) NULL
GO

ALTER TABLE tblExaminee ADD
	TreatingPhysicianDiagnosis varchar (70) NULL
GO


UPDATE tblControl SET DBVersion = '2.22'
GO
