CREATE TABLE [dbo].[tblCaseDocumentsDicom] (
    [CaseDocDicomID]                    INT				 NOT NULL IDENTITY (1,1),
    [CaseNbr]                           INT              NOT NULL,
    [CaseDocID]                         INT              NOT NULL,
    [MediaType]                         VARCHAR (100)    NOT NULL,
    [DiscID]                            VARCHAR (100)    NULL,
    [PatientName]                       VARCHAR (200)    NULL,
    [PatientId]                         VARCHAR (200)    NULL,
    [PatientBirthDate]                  VARCHAR (50)     NULL,
    [PatientSex]                        VARCHAR (50)     NULL,
    [StudyDate]                         VARCHAR (50)     NULL,
    [StudyTime]                         VARCHAR (50)     NULL,
    [StudyDescription]                  VARCHAR (500)    NULL,
    [StudyUID]                          VARCHAR (200)    NULL,
    [StudyID]                           VARCHAR (200)    NULL,
    [StudyDirRecType]                   VARCHAR (100)    NULL,
    [SeriesUID]                         VARCHAR (200)    NULL,
    [SeriesNumber]                      INT              NULL,
    [SeriesDate]                        VARCHAR (50)     NULL,
    [SeriesTime]                        VARCHAR (50)     NULL,
    [SeriesDescription]                 VARCHAR (500)    NULL,
    [SeriesModality]                    VARCHAR (50)     NULL,
    [SeriesDirRecType]                  VARCHAR (100)    NULL,
    [InstanceNumber]                    INT              NULL,
    [InstanceUID]                       VARCHAR (200)    NULL,
    [ReferenceFileID]                   VARCHAR (200)    NULL,
    [InstanceDirRecType]                VARCHAR (100)    NULL,
    [MediaStorageSopInstanceUid]        VARCHAR (200)    NULL,
    [SopClass]                          VARCHAR (200)    NULL,
    [Modality]                          VARCHAR (50)     NULL,
    [Filename]                          VARCHAR (500)    NULL,
    [Filesize]                          INT              NULL,
    [AcquisitionDate]                   VARCHAR (50)     NULL,
    [AcquisitionTime]                   VARCHAR (50)     NULL,
    [ContentDate]                       VARCHAR (10)     NULL,
    [ContentTime]                       VARCHAR (10)     NULL,
    [InstitutionName]                   VARCHAR (200)    NULL,
    [InstitutionAddress]                VARCHAR (500)    NULL,
    [InstitutionalDepartmentName]       VARCHAR (200)    NULL,
    [ReferringPhysiciansName]           VARCHAR (200)    NULL,
    [ProtocolName]                      VARCHAR (200)    NULL,
    [RequestedProcedureDescription]     VARCHAR (200)    NULL,
    [PerformedProcedureStepDescription] VARCHAR (200)    NULL,
    [IsValidatedFileExists]             BIT              CONSTRAINT [DF_tblCaseDocumentsDicom_IsValidatedFileExists] DEFAULT ((0)) NOT NULL,
    [IsValidatedBinary]                 BIT              CONSTRAINT [DF_tblCaseDocumentsDicom_IsValidatedBinary] DEFAULT ((0)) NOT NULL,
    [FlagForUse]                        BIT              CONSTRAINT [DF_tblCaseDocumentsDicom_FlagForUse] DEFAULT ((0)) NOT NULL,
    [Notes]                             VARCHAR (2000)   NULL,
    [ImportedOn]                        DATETIME         NULL,
    [ImportedBy]                        VARCHAR (50)     NULL,
    CONSTRAINT [PK_tblCaseDocumentsDicom] PRIMARY KEY CLUSTERED ([CaseDocDicomID] ASC)
);

