CREATE VIEW vwPDFInvDetData
AS
	SELECT	
			AD1.LineNbr AS InvLineNbr1 ,
	        AD1.Date AS InvServiceDate1 ,
			B.BlankValue AS InvServiceDate1MM,
			B.BlankValue AS InvServiceDate1DD,
			B.BlankValue AS InvServiceDate1YY,
			B.BlankValue AS InvServiceDateTo1MM,
			B.BlankValue AS InvServiceDateTo1DD,
			B.BlankValue AS InvServiceDateTo1YY,
	        AD1.CPTCode AS InvCPT1,
	        AD1.Modifier AS InvModifier1,
	        AD1.Modifier2 AS InvModifier1b ,
	        AD1.Modifier3 AS InvModifier1c ,
	        AD1.Modifier4 AS InvModifier1d ,
			B.BlankValue AS InvICD1,
			B.BlankValue AS InvDiagnosisPointer1,
	        AD1.Location AS InvPlaceOfService1,
			'2' AS InvTypeOfService1,
	        AD1.SuppInfo AS SupplementalInfo1,
	        AD1.Unit AS InvUnit1,
	        AD1.ExtendedAmount AS InvDetAmt1,
			AD1.RetailAmount AS InvRetailAmt1,
	        B.BlankValue AS InvDetAmt1Dollars,
			B.BlankValue AS InvDetAmt1Cents,
	        B.BlankValue AS InvDetAmt1bDollars,
			B.BlankValue AS InvDetAmt1bCents,
			AD1.DrOpCode AS DrOpCode1,
			DR1.NPINbr AS DoctorNPINbr1,


			AD2.LineNbr AS InvLineNbr2 ,
	        AD2.Date AS InvServiceDate2 ,
			B.BlankValue AS InvServiceDate2MM,
			B.BlankValue AS InvServiceDate2DD,
			B.BlankValue AS InvServiceDate2YY,
			B.BlankValue AS InvServiceDateTo2MM,
			B.BlankValue AS InvServiceDateTo2DD,
			B.BlankValue AS InvServiceDateTo2YY,
	        AD2.CPTCode AS InvCPT2,
	        AD2.Modifier AS InvModifier2,
	        AD2.Modifier2 AS InvModifier2b ,
	        AD2.Modifier3 AS InvModifier2c ,
	        AD2.Modifier4 AS InvModifier2d ,
			B.BlankValue AS InvICD2,
			B.BlankValue AS InvDiagnosisPointer2,
	        AD2.Location AS InvPlaceOfService2,
			'2' AS InvTypeOfService2,
	        AD2.SuppInfo AS SupplementalInfo2,
	        AD2.Unit AS InvUnit2,
	        AD2.ExtendedAmount AS InvDetAmt2,
			AD2.RetailAmount AS InvRetailAmt2,
	        B.BlankValue AS InvDetAmt2Dollars,
			B.BlankValue AS InvDetAmt2Cents,
	        B.BlankValue AS InvDetAmt2bDollars,
			B.BlankValue AS InvDetAmt2bCents,
			AD2.DrOpCode AS DrOpCode2,
			DR2.NPINbr AS DoctorNPINbr2,


			AD3.LineNbr AS InvLineNbr3 ,
	        AD3.Date AS InvServiceDate3 ,
			B.BlankValue AS InvServiceDate3MM,
			B.BlankValue AS InvServiceDate3DD,
			B.BlankValue AS InvServiceDate3YY,
			B.BlankValue AS InvServiceDateTo3MM,
			B.BlankValue AS InvServiceDateTo3DD,
			B.BlankValue AS InvServiceDateTo3YY,
	        AD3.CPTCode AS InvCPT3,
	        AD3.Modifier AS InvModifier3,
	        AD3.Modifier2 AS InvModifier3b ,
	        AD3.Modifier3 AS InvModifier3c ,
	        AD3.Modifier4 AS InvModifier3d ,
			B.BlankValue AS InvICD3,
			B.BlankValue AS InvDiagnosisPointer3,
	        AD3.Location AS InvPlaceOfService3,
			'2' AS InvTypeOfService3,
	        AD3.SuppInfo AS SupplementalInfo3,
	        AD3.Unit AS InvUnit3,
	        AD3.ExtendedAmount AS InvDetAmt3,
	        AD3.RetailAmount AS InvRetailAmt3,
			B.BlankValue AS InvDetAmt3Dollars,
			B.BlankValue AS InvDetAmt3Cents,
			B.BlankValue AS InvDetAmt3bDollars,
			B.BlankValue AS InvDetAmt3bCents,
			AD3.DrOpCode AS DrOpCode3,
			DR3.NPINbr AS DoctorNPINbr3,


			AD4.LineNbr AS InvLineNbr4 ,
	        AD4.Date AS InvServiceDate4 ,
			B.BlankValue AS InvServiceDate4MM,
			B.BlankValue AS InvServiceDate4DD,
			B.BlankValue AS InvServiceDate4YY,
			B.BlankValue AS InvServiceDateTo4MM,
			B.BlankValue AS InvServiceDateTo4DD,
			B.BlankValue AS InvServiceDateTo4YY,
	        AD4.CPTCode AS InvCPT4,
	        AD4.Modifier AS InvModifier4,
	        AD4.Modifier2 AS InvModifier4b ,
	        AD4.Modifier3 AS InvModifier4c ,
	        AD4.Modifier4 AS InvModifier4d ,
			B.BlankValue AS InvICD4,
			B.BlankValue AS InvDiagnosisPointer4,
	        AD4.Location AS InvPlaceOfService4,
			'2' AS InvTypeOfService4,
	        AD4.SuppInfo AS SupplementalInfo4,
	        AD4.Unit AS InvUnit4,
	        AD4.ExtendedAmount AS InvDetAmt4,
			AD4.RetailAmount AS InvRetailAmt4,
	        B.BlankValue AS InvDetAmt4Dollars,
			B.BlankValue AS InvDetAmt4Cents,
	        B.BlankValue AS InvDetAmt4bDollars,
			B.BlankValue AS InvDetAmt4bCents,
			AD4.DrOpCode AS DrOpCode4,
			DR4.NPINbr AS DoctorNPINbr4,


			AD5.LineNbr AS InvLineNbr5 ,
	        AD5.Date AS InvServiceDate5 ,
			B.BlankValue AS InvServiceDate5MM,
			B.BlankValue AS InvServiceDate5DD,
			B.BlankValue AS InvServiceDate5YY,
			B.BlankValue AS InvServiceDateTo5MM,
			B.BlankValue AS InvServiceDateTo5DD,
			B.BlankValue AS InvServiceDateTo5YY,
	        AD5.CPTCode AS InvCPT5,
	        AD5.Modifier AS InvModifier5,
	        AD5.Modifier2 AS InvModifier5b ,
	        AD5.Modifier3 AS InvModifier5c ,
	        AD5.Modifier4 AS InvModifier5d ,
			B.BlankValue AS InvICD5,
			B.BlankValue AS InvDiagnosisPointer5,
	        AD5.Location AS InvPlaceOfService5,
			'2' AS InvTypeOfService5,
	        AD5.SuppInfo AS SupplementalInfo5,
	        AD5.Unit AS InvUnit5,
	        AD5.ExtendedAmount AS InvDetAmt5,
			AD5.RetailAmount AS InvRetailAmt5,
	        B.BlankValue AS InvDetAmt5Dollars,
			B.BlankValue AS InvDetAmt5Cents,
	        B.BlankValue AS InvDetAmt5bDollars,
			B.BlankValue AS InvDetAmt5bCents,
			AD5.DrOpCode AS DrOpCode5,
			DR5.NPINbr AS DoctorNPINbr5,


			AD6.LineNbr AS InvLineNbr6 ,
	        AD6.Date AS InvServiceDate6 ,
			B.BlankValue AS InvServiceDate6MM,
			B.BlankValue AS InvServiceDate6DD,
			B.BlankValue AS InvServiceDate6YY,
			B.BlankValue AS InvServiceDateTo6MM,
			B.BlankValue AS InvServiceDateTo6DD,
			B.BlankValue AS InvServiceDateTo6YY,
	        AD6.CPTCode AS InvCPT6,
	        AD6.Modifier AS InvModifier6,
	        AD6.Modifier2 AS InvModifier6b ,
	        AD6.Modifier3 AS InvModifier6c ,
	        AD6.Modifier4 AS InvModifier6d ,
			B.BlankValue AS InvICD6,
			B.BlankValue AS InvDiagnosisPointer6,
	        AD6.Location AS InvPlaceOfService6,
			'2' AS InvTypeOfService6,
	        AD6.SuppInfo AS SupplementalInfo6,
	        AD6.Unit AS InvUnit6,
	        AD6.ExtendedAmount AS InvDetAmt6,
			AD6.RetailAmount AS InvRetailAmt6,
	        B.BlankValue AS InvDetAmt6Dollars,
			B.BlankValue AS InvDetAmt6Cents,
	        B.BlankValue AS InvDetAmt6bDollars,
			B.BlankValue AS InvDetAmt6bCents,
			AD6.DrOpCode AS DrOpCode6,
			DR6.NPINbr AS DoctorNPINbr6,


			AD7.LineNbr AS InvLineNbr7 ,
	        AD7.Date AS InvServiceDate7 ,
			B.BlankValue AS InvServiceDate7MM,
			B.BlankValue AS InvServiceDate7DD,
			B.BlankValue AS InvServiceDate7YY,
			B.BlankValue AS InvServiceDateTo7MM,
			B.BlankValue AS InvServiceDateTo7DD,
			B.BlankValue AS InvServiceDateTo7YY,
	        AD7.CPTCode AS InvCPT7,
	        AD7.Modifier AS InvModifier7,
	        AD7.Modifier2 AS InvModifier7b ,
	        AD7.Modifier3 AS InvModifier7c ,
	        AD7.Modifier4 AS InvModifier7d ,
			B.BlankValue AS InvICD7,
			B.BlankValue AS InvDiagnosisPointer7,
	        AD7.Location AS InvPlaceOfService7,
			'2' AS InvTypeOfService7,
	        AD7.SuppInfo AS SupplementalInfo7,
	        AD7.Unit AS InvUnit7,
	        AD7.ExtendedAmount AS InvDetAmt7,
			AD7.RetailAmount AS InvRetailAmt7,
	        B.BlankValue AS InvDetAmt7Dollars,
			B.BlankValue AS InvDetAmt7Cents,
	        B.BlankValue AS InvDetAmt7bDollars,
			B.BlankValue AS InvDetAmt7bCents,
			AD7.DrOpCode AS DrOpCode7,
			DR7.NPINbr AS DoctorNPINbr7,


			AD8.LineNbr AS InvLineNbr8 ,
	        AD8.Date AS InvServiceDate8 ,
			B.BlankValue AS InvServiceDate8MM,
			B.BlankValue AS InvServiceDate8DD,
			B.BlankValue AS InvServiceDate8YY,
			B.BlankValue AS InvServiceDateTo8MM,
			B.BlankValue AS InvServiceDateTo8DD,
			B.BlankValue AS InvServiceDateTo8YY,
	        AD8.CPTCode AS InvCPT8,
	        AD8.Modifier AS InvModifier8,
	        AD8.Modifier2 AS InvModifier8b ,
	        AD8.Modifier3 AS InvModifier8c ,
	        AD8.Modifier4 AS InvModifier8d ,
			B.BlankValue AS InvICD8,
			B.BlankValue AS InvDiagnosisPointer8,
	        AD8.Location AS InvPlaceOfService8,
			'2' AS InvTypeOfService8,
	        AD8.SuppInfo AS SupplementalInfo8,
	        AD8.Unit AS InvUnit8,
	        AD8.ExtendedAmount AS InvDetAmt8,
			AD8.RetailAmount AS InvRetailAmt8,
	        B.BlankValue AS InvDetAmt8Dollars,
			B.BlankValue AS InvDetAmt8Cents,
	        B.BlankValue AS InvDetAmt8bDollars,
			B.BlankValue AS InvDetAmt8bCents,
			AD8.DrOpCode AS DrOpCode8,
			DR8.NPINbr AS DoctorNPINbr8,


	        AD9.Date AS InvServiceDate9 ,
			B.BlankValue AS InvServiceDate9MM,
			B.BlankValue AS InvServiceDate9DD,
			B.BlankValue AS InvServiceDate9YY,
			AD9.LineNbr AS InvLineNbr9 ,
			B.BlankValue AS InvServiceDateTo9MM,
			B.BlankValue AS InvServiceDateTo9DD,
			B.BlankValue AS InvServiceDateTo9YY,
	        AD9.CPTCode AS InvCPT9,
	        AD9.Modifier AS InvModifier9,
	        AD9.Modifier2 AS InvModifier9b ,
	        AD9.Modifier3 AS InvModifier9c ,
	        AD9.Modifier4 AS InvModifier9d ,
			B.BlankValue AS InvICD9,
			B.BlankValue AS InvDiagnosisPointer9,
	        AD9.Location AS InvPlaceOfService9,
			'2' AS InvTypeOfService9,
	        AD9.SuppInfo AS SupplementalInfo9,
	        AD9.Unit AS InvUnit9,
	        AD9.ExtendedAmount AS InvDetAmt9,
			AD9.RetailAmount AS InvRetailAmt9,
	        B.BlankValue AS InvDetAmt9Dollars,
			B.BlankValue AS InvDetAmt9Cents,
	        B.BlankValue AS InvDetAmt9bDollars,
			B.BlankValue AS InvDetAmt9bCents,
			AD9.DrOpCode AS DrOpCode9,
			DR9.NPINbr AS DoctorNPINbr9,


			AD10.LineNbr AS InvLineNbr10 ,
	        AD10.Date AS InvServiceDate10 ,
			B.BlankValue AS InvServiceDate10MM,
			B.BlankValue AS InvServiceDate10DD,
			B.BlankValue AS InvServiceDate10YY,
			B.BlankValue AS InvServiceDateTo10MM,
			B.BlankValue AS InvServiceDateTo10DD,
			B.BlankValue AS InvServiceDateTo10YY,
	        AD10.CPTCode AS InvCPT10,
	        AD10.Modifier AS InvModifier10,
	        AD10.Modifier2 AS InvModifier10b ,
	        AD10.Modifier3 AS InvModifier10c ,
	        AD10.Modifier4 AS InvModifier10d ,
			B.BlankValue AS InvICD10,
			B.BlankValue AS InvDiagnosisPointer10,
	        AD10.Location AS InvPlaceOfService10,
			'2' AS InvTypeOfService10,
	        AD10.SuppInfo AS SupplementalInfo10,
	        AD10.Unit AS InvUnit10,
	        AD10.ExtendedAmount AS InvDetAmt10,
			AD10.RetailAmount AS InvRetailAmt10,
	        B.BlankValue AS InvDetAmt10Dollars,
			B.BlankValue AS InvDetAmt10Cents,
	        B.BlankValue AS InvDetAmt10bDollars,
			B.BlankValue AS InvDetAmt10bCents,
			AD10.DrOpCode AS DrOpCode10,
			DR10.NPINbr AS DoctorNPINbr10,


			AD11.LineNbr AS InvLineNbr11 ,
	        AD11.Date AS InvServiceDate11 ,
			B.BlankValue AS InvServiceDate11MM,
			B.BlankValue AS InvServiceDate11DD,
			B.BlankValue AS InvServiceDate11YY,
			B.BlankValue AS InvServiceDateTo11MM,
			B.BlankValue AS InvServiceDateTo11DD,
			B.BlankValue AS InvServiceDateTo11YY,
	        AD11.CPTCode AS InvCPT11,
	        AD11.Modifier AS InvModifier11,
	        AD11.Modifier2 AS InvModifier11b ,
	        AD11.Modifier3 AS InvModifier11c ,
	        AD11.Modifier4 AS InvModifier11d ,
			B.BlankValue AS InvICD11,
			B.BlankValue AS InvDiagnosisPointer11,
	        AD11.Location AS InvPlaceOfService11,
			'2' AS InvTypeOfService11,
	        AD11.SuppInfo AS SupplementalInfo11,
	        AD11.Unit AS InvUnit11,
	        AD11.ExtendedAmount AS InvDetAmt11,
			AD11.RetailAmount AS InvRetailAmt11,
	        B.BlankValue AS InvDetAmt11Dollars,
			B.BlankValue AS InvDetAmt11Cents,
	        B.BlankValue AS InvDetAmt11bDollars,
			B.BlankValue AS InvDetAmt11bCents,
			AD11.DrOpCode AS DrOpCode11,
			DR11.NPINbr AS DoctorNPINbr11,

			AD12.LineNbr AS InvLineNbr12 ,
	        AD12.Date AS InvServiceDate12 ,
			B.BlankValue AS InvServiceDate12MM,
			B.BlankValue AS InvServiceDate12DD,
			B.BlankValue AS InvServiceDate12YY,
			B.BlankValue AS InvServiceDateTo12MM,
			B.BlankValue AS InvServiceDateTo12DD,
			B.BlankValue AS InvServiceDateTo12YY,
	        AD12.CPTCode AS InvCPT12,
	        AD12.Modifier AS InvModifier12,
	        AD12.Modifier2 AS InvModifier12b ,
	        AD12.Modifier3 AS InvModifier12c ,
	        AD12.Modifier4 AS InvModifier12d ,
			B.BlankValue AS InvICD12,
			B.BlankValue AS InvDiagnosisPointer12,
	        AD12.Location AS InvPlaceOfService12,
			'2' AS InvTypeOfService12,
	        AD12.SuppInfo AS SupplementalInfo12,
	        AD12.Unit AS InvUnit12,
	        AD12.ExtendedAmount AS InvDetAmt12,
			AD12.RetailAmount AS InvRetailAmt12,
	        B.BlankValue AS InvDetAmt12Dollars,
			B.BlankValue AS InvDetAmt12Cents,
	        B.BlankValue AS InvDetAmt12bDollars,
			B.BlankValue AS InvDetAmt12bCents,
			AD12.DrOpCode AS DrOpCode12,
			DR12.NPINbr AS DoctorNPINbr12,


			AD13.LineNbr AS InvLineNbr13 ,
	        AD13.Date AS InvServiceDate13 ,
			B.BlankValue AS InvServiceDate13MM,
			B.BlankValue AS InvServiceDate13DD,
			B.BlankValue AS InvServiceDate13YY,
			B.BlankValue AS InvServiceDateTo13MM,
			B.BlankValue AS InvServiceDateTo13DD,
			B.BlankValue AS InvServiceDateTo13YY,
	        AD13.CPTCode AS InvCPT13,
	        AD13.Modifier AS InvModifier13,
	        AD13.Modifier2 AS InvModifier13b ,
	        AD13.Modifier3 AS InvModifier13c ,
	        AD13.Modifier4 AS InvModifier13d ,
			B.BlankValue AS InvICD13,
			B.BlankValue AS InvDiagnosisPointer13,
	        AD13.Location AS InvPlaceOfService13,
			'2' AS InvTypeOfService13,
	        AD13.SuppInfo AS SupplementalInfo13,
	        AD13.Unit AS InvUnit13,
	        AD13.ExtendedAmount AS InvDetAmt13,
			AD13.RetailAmount AS InvRetailAmt13,
	        B.BlankValue AS InvDetAmt13Dollars,
			B.BlankValue AS InvDetAmt13Cents,
	        B.BlankValue AS InvDetAmt13bDollars,
			B.BlankValue AS InvDetAmt13bCents,
			AD13.DrOpCode AS DrOpCode13,
			DR13.NPINbr AS DoctorNPINbr13,


			AD14.LineNbr AS InvLineNbr14 ,
	        AD14.Date AS InvServiceDate14 ,
			B.BlankValue AS InvServiceDate14MM,
			B.BlankValue AS InvServiceDate14DD,
			B.BlankValue AS InvServiceDate14YY,
			B.BlankValue AS InvServiceDateTo14MM,
			B.BlankValue AS InvServiceDateTo14DD,
			B.BlankValue AS InvServiceDateTo14YY,
	        AD14.CPTCode AS InvCPT14,
	        AD14.Modifier AS InvModifier14,
	        AD14.Modifier2 AS InvModifier14b ,
	        AD14.Modifier3 AS InvModifier14c ,
	        AD14.Modifier4 AS InvModifier14d ,
			B.BlankValue AS InvICD14,
			B.BlankValue AS InvDiagnosisPointer14,
	        AD14.Location AS InvPlaceOfService14,
			'2' AS InvTypeOfService14,
	        AD14.SuppInfo AS SupplementalInfo14,
	        AD14.Unit AS InvUnit14,
	        AD14.ExtendedAmount AS InvDetAmt14,
			AD14.RetailAmount AS InvRetailAmt14,
	        B.BlankValue AS InvDetAmt14Dollars,
			B.BlankValue AS InvDetAmt14Cents,
	        B.BlankValue AS InvDetAmt14bDollars,
			B.BlankValue AS InvDetAmt14bCents,
			AD14.DrOpCode AS DrOpCode14,
			DR14.NPINbr AS DoctorNPINbr14,


			AD15.LineNbr AS InvLineNbr15 ,
	        AD15.Date AS InvServiceDate15 ,
			B.BlankValue AS InvServiceDate15MM,
			B.BlankValue AS InvServiceDate15DD,
			B.BlankValue AS InvServiceDate15YY,
			B.BlankValue AS InvServiceDateTo15MM,
			B.BlankValue AS InvServiceDateTo15DD,
			B.BlankValue AS InvServiceDateTo15YY,
	        AD15.CPTCode AS InvCPT15,
	        AD15.Modifier AS InvModifier15,
	        AD15.Modifier2 AS InvModifier15b ,
	        AD15.Modifier3 AS InvModifier15c ,
	        AD15.Modifier4 AS InvModifier15d ,
			B.BlankValue AS InvICD15,
			B.BlankValue AS InvDiagnosisPointer15,
	        AD15.Location AS InvPlaceOfService15,
			'2' AS InvTypeOfService15,
	        AD15.SuppInfo AS SupplementalInfo15,
	        AD15.Unit AS InvUnit15,
	        AD15.ExtendedAmount AS InvDetAmt15,
			AD15.RetailAmount AS InvRetailAmt15,
	        B.BlankValue AS InvDetAmt15Dollars,
			B.BlankValue AS InvDetAmt15Cents,
	        B.BlankValue AS InvDetAmt15bDollars,
			B.BlankValue AS InvDetAmt15bCents,
			AD15.DrOpCode AS DrOpCode15,
			DR15.NPINbr AS DoctorNPINbr15,


			AD16.LineNbr AS InvLineNbr16 ,
	        AD16.Date AS InvServiceDate16 ,
			B.BlankValue AS InvServiceDate16MM,
			B.BlankValue AS InvServiceDate16DD,
			B.BlankValue AS InvServiceDate16YY,
			B.BlankValue AS InvServiceDateTo16MM,
			B.BlankValue AS InvServiceDateTo16DD,
			B.BlankValue AS InvServiceDateTo16YY,
	        AD16.CPTCode AS InvCPT16,
	        AD16.Modifier AS InvModifier16,
	        AD16.Modifier2 AS InvModifier16b ,
	        AD16.Modifier3 AS InvModifier16c ,
	        AD16.Modifier4 AS InvModifier16d ,
			B.BlankValue AS InvICD16,
			B.BlankValue AS InvDiagnosisPointer16,
	        AD16.Location AS InvPlaceOfService16,
			'2' AS InvTypeOfService16,
	        AD16.SuppInfo AS SupplementalInfo16,
	        AD16.Unit AS InvUnit16,
	        AD16.ExtendedAmount AS InvDetAmt16,
			AD16.RetailAmount AS InvRetailAmt16,
	        B.BlankValue AS InvDetAmt16Dollars,
			B.BlankValue AS InvDetAmt16Cents,
	        B.BlankValue AS InvDetAmt16bDollars,
			B.BlankValue AS InvDetAmt16bCents,
			AD16.DrOpCode AS DrOpCode16,
			DR16.NPINbr AS DoctorNPINbr16,


			AD17.LineNbr AS InvLineNbr17 ,
	        AD17.Date AS InvServiceDate17 ,
			B.BlankValue AS InvServiceDate17MM,
			B.BlankValue AS InvServiceDate17DD,
			B.BlankValue AS InvServiceDate17YY,
			B.BlankValue AS InvServiceDateTo17MM,
			B.BlankValue AS InvServiceDateTo17DD,
			B.BlankValue AS InvServiceDateTo17YY,
	        AD17.CPTCode AS InvCPT17,
	        AD17.Modifier AS InvModifier17,
	        AD17.Modifier2 AS InvModifier17b ,
	        AD17.Modifier3 AS InvModifier17c ,
	        AD17.Modifier4 AS InvModifier17d ,
			B.BlankValue AS InvICD17,
			B.BlankValue AS InvDiagnosisPointer17,
	        AD17.Location AS InvPlaceOfService17,
			'2' AS InvTypeOfService17,
	        AD17.SuppInfo AS SupplementalInfo17,
	        AD17.Unit AS InvUnit17,
	        AD17.ExtendedAmount AS InvDetAmt17,
			AD17.RetailAmount AS InvRetailAmt17,
	        B.BlankValue AS InvDetAmt17Dollars,
			B.BlankValue AS InvDetAmt17Cents,
	        B.BlankValue AS InvDetAmt17bDollars,
			B.BlankValue AS InvDetAmt17bCents,
			AD17.DrOpCode AS DrOpCode17,
			DR17.NPINbr AS DoctorNPINbr17,


			AD18.LineNbr AS InvLineNbr18 ,
	        AD18.Date AS InvServiceDate18 ,
			B.BlankValue AS InvServiceDate18MM,
			B.BlankValue AS InvServiceDate18DD,
			B.BlankValue AS InvServiceDate18YY,
			B.BlankValue AS InvServiceDateTo18MM,
			B.BlankValue AS InvServiceDateTo18DD,
			B.BlankValue AS InvServiceDateTo18YY,
	        AD18.CPTCode AS InvCPT18,
	        AD18.Modifier AS InvModifier18,
	        AD18.Modifier2 AS InvModifier18b ,
	        AD18.Modifier3 AS InvModifier18c ,
	        AD18.Modifier4 AS InvModifier18d ,
			B.BlankValue AS InvICD18,
			B.BlankValue AS InvDiagnosisPointer18,
	        AD18.Location AS InvPlaceOfService18,
			'2' AS InvTypeOfService18,
	        AD18.SuppInfo AS SupplementalInfo18,
	        AD18.Unit AS InvUnit18,
	        AD18.ExtendedAmount AS InvDetAmt18,
			AD18.RetailAmount AS InvRetailAmt18,
	        B.BlankValue AS InvDetAmt18Dollars,
			B.BlankValue AS InvDetAmt18Cents,
	        B.BlankValue AS InvDetAmt18bDollars,
			B.BlankValue AS InvDetAmt18bCents,
			AD18.DrOpCode AS DrOpCode18,
			DR18.NPINbr AS DoctorNPINbr18,

			B.BlankValue AS InvICDDiagnosisPointer,
			AD1.HeaderID AS InvDetHeaderID

	FROM	tblAcctDetail AS AD1
	LEFT OUTER JOIN tblAcctDetail AS AD2 ON AD2.HeaderID = AD1.HeaderID AND AD2.LineNbr=2
	LEFT OUTER JOIN tblAcctDetail AS AD3 ON AD3.HeaderID = AD1.HeaderID AND AD3.LineNbr=3
	LEFT OUTER JOIN tblAcctDetail AS AD4 ON AD4.HeaderID = AD1.HeaderID AND AD4.LineNbr=4
	LEFT OUTER JOIN tblAcctDetail AS AD5 ON AD5.HeaderID = AD1.HeaderID AND AD5.LineNbr=5
	LEFT OUTER JOIN tblAcctDetail AS AD6 ON AD6.HeaderID = AD1.HeaderID AND AD6.LineNbr=6
	LEFT OUTER JOIN tblAcctDetail AS AD7 ON AD7.HeaderID = AD1.HeaderID AND AD7.LineNbr=7
	LEFT OUTER JOIN tblAcctDetail AS AD8 ON AD8.HeaderID = AD1.HeaderID AND AD8.LineNbr=8
	LEFT OUTER JOIN tblAcctDetail AS AD9 ON AD9.HeaderID = AD1.HeaderID AND AD9.LineNbr=9
	LEFT OUTER JOIN tblAcctDetail AS AD10 ON AD10.HeaderID = AD1.HeaderID AND AD10.LineNbr=10
	LEFT OUTER JOIN tblAcctDetail AS AD11 ON AD11.HeaderID = AD1.HeaderID AND AD11.LineNbr=11
	LEFT OUTER JOIN tblAcctDetail AS AD12 ON AD12.HeaderID = AD1.HeaderID AND AD12.LineNbr=12
	LEFT OUTER JOIN tblAcctDetail AS AD13 ON AD13.HeaderID = AD1.HeaderID AND AD13.LineNbr=13
	LEFT OUTER JOIN tblAcctDetail AS AD14 ON AD14.HeaderID = AD1.HeaderID AND AD14.LineNbr=14
	LEFT OUTER JOIN tblAcctDetail AS AD15 ON AD15.HeaderID = AD1.HeaderID AND AD15.LineNbr=15
	LEFT OUTER JOIN tblAcctDetail AS AD16 ON AD16.HeaderID = AD1.HeaderID AND AD16.LineNbr=16
	LEFT OUTER JOIN tblAcctDetail AS AD17 ON AD17.HeaderID = AD1.HeaderID AND AD17.LineNbr=17
	LEFT OUTER JOIN tblAcctDetail AS AD18 ON AD18.HeaderID = AD1.HeaderID AND AD18.LineNbr=18
	LEFT OUTER JOIN tblDoctor AS DR1 ON AD1.DrOpCode=DR1.DoctorCode
	LEFT OUTER JOIN tblDoctor AS DR2 ON AD2.DrOpCode=DR2.DoctorCode
	LEFT OUTER JOIN tblDoctor AS DR3 ON AD3.DrOpCode=DR3.DoctorCode
	LEFT OUTER JOIN tblDoctor AS DR4 ON AD4.DrOpCode=DR4.DoctorCode
	LEFT OUTER JOIN tblDoctor AS DR5 ON AD5.DrOpCode=DR5.DoctorCode
	LEFT OUTER JOIN tblDoctor AS DR6 ON AD6.DrOpCode=DR6.DoctorCode
	LEFT OUTER JOIN tblDoctor AS DR7 ON AD7.DrOpCode=DR7.DoctorCode
	LEFT OUTER JOIN tblDoctor AS DR8 ON AD8.DrOpCode=DR8.DoctorCode
	LEFT OUTER JOIN tblDoctor AS DR9 ON AD9.DrOpCode=DR9.DoctorCode
	LEFT OUTER JOIN tblDoctor AS DR10 ON AD10.DrOpCode=DR10.DoctorCode
	LEFT OUTER JOIN tblDoctor AS DR11 ON AD11.DrOpCode=DR11.DoctorCode
	LEFT OUTER JOIN tblDoctor AS DR12 ON AD12.DrOpCode=DR12.DoctorCode
	LEFT OUTER JOIN tblDoctor AS DR13 ON AD13.DrOpCode=DR13.DoctorCode
	LEFT OUTER JOIN tblDoctor AS DR14 ON AD14.DrOpCode=DR14.DoctorCode
	LEFT OUTER JOIN tblDoctor AS DR15 ON AD15.DrOpCode=DR15.DoctorCode
	LEFT OUTER JOIN tblDoctor AS DR16 ON AD16.DrOpCode=DR16.DoctorCode
	LEFT OUTER JOIN tblDoctor AS DR17 ON AD17.DrOpCode=DR17.DoctorCode
	LEFT OUTER JOIN tblDoctor AS DR18 ON AD18.DrOpCode=DR18.DoctorCode
	LEFT OUTER JOIN tblBlank AS B ON 1=1
	WHERE AD1.LineNbr=1
