CREATE TABLE [dbo].[TempVendorVoucher] (
    [TempVendorVoucherID] INT             IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [SourceID]            INT             NULL,
    [VoucherNo]           VARCHAR (15)    NULL,
    [VoucherDate]         DATETIME        NULL,
    [ServiceDate]         DATETIME        NULL,
    [Comment]             VARCHAR (30)    NULL,
    [EWFacilityID]        INT             NULL,
    [EWLocationID]        INT             NULL,
    [ClaimNo]             VARCHAR (50)    NULL,
    [CaseNo]              VARCHAR (15)    NULL,
    [BatchNo]             INT             NULL,
    [TotalAmount]         MONEY           NULL,
    [MonetaryUnit]        INT             NULL,
    [ExchangeRate]        DECIMAL (15, 7) NULL,
    [TotalAmountUS]       MONEY           NULL,
    [User]                VARCHAR (25)    NULL,
    [Office]              VARCHAR (15)    NULL,
    [PayeeName]           VARCHAR (64)    NULL,
    [Address1]            VARCHAR (50)    NULL,
    [Address2]            VARCHAR (50)    NULL,
    [Address3]            VARCHAR (50)    NULL,
    [City]                VARCHAR (35)    NULL,
    [State]               VARCHAR (3)     NULL,
    [Zip]                 VARCHAR (10)    NULL,
    [County]              VARCHAR (50)    NULL,
    [Country]             VARCHAR (2)     NULL,
    [GLNaturalAccount]    VARCHAR (5)     NULL,
    [GPExportStatus]      INT             NULL,
    CONSTRAINT [PK_TempVendorVoucher] PRIMARY KEY CLUSTERED ([TempVendorVoucherID] ASC)
);

