CREATE TABLE [dbo].[GeicoScheduleExpert] (
    [Id]                        INT            IDENTITY (1, 1) NOT NULL,
    [UniqueRecordIDs]           VARCHAR (2048) NULL,
    [TrialDate]                 DATETIME       NULL,
    [ReviewType]                VARCHAR (30)   NULL,
    [InjuredPartyName]          VARCHAR (200)  NULL,
    [LegalActionNumber]         VARCHAR (20)   NULL,
    [ClaimNumber]               VARCHAR (40)   NULL,
    [InvoiceNumber]             VARCHAR (30)   NULL,
    [UserId]                    INT            NULL,
    [DateAssigned]              DATETIME       NULL,
    [RespondIsBooked]           BIT            NULL,
    [RespondIsOriginalDoctor]   BIT            NULL,
    [RespondReason]             VARCHAR (100)  NULL,
    [RespondSubstituteDoctorId] INT            NULL,
    [Notes]                     VARCHAR (2048) NULL,
    [DateReceived]              DATETIME       NULL,
    [DateCompleted]             DATETIME       NULL,
    [IsCanceled]                BIT            NULL,
    [Status]                    TINYINT        NULL,
    [CancelExpertId]            INT            NULL,
    [RequestContextId]          INT            NOT NULL,
    [BusUnitId]                 INT            NULL,
    [CustomerId]                INT            NOT NULL,
    [ExpertId]                  INT            NULL,
    [AlternateExpertId]         INT            NULL,
    [VenueCountyId]             INT            NULL,
    [CourtTypeId]               INT            NULL,
    CONSTRAINT [PK_GeicoScheduleExpert] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_GeicoScheduleExpert_GeicoCancelExpert] FOREIGN KEY ([CancelExpertId]) REFERENCES [dbo].[GeicoCancelExpert] ([Id]),
    CONSTRAINT [FK_GeicoScheduleExpert_GeicoCourtType] FOREIGN KEY ([CourtTypeId]) REFERENCES [dbo].[GeicoCourtType] ([Id]),
    CONSTRAINT [FK_GeicoScheduleExpert_GeicoCustomer] FOREIGN KEY ([CustomerId]) REFERENCES [dbo].[GeicoCustomer] ([Id]),
    CONSTRAINT [FK_GeicoScheduleExpert_GeicoExpert] FOREIGN KEY ([ExpertId]) REFERENCES [dbo].[GeicoExpert] ([Id]),
    CONSTRAINT [FK_GeicoScheduleExpert_GeicoExpert1] FOREIGN KEY ([AlternateExpertId]) REFERENCES [dbo].[GeicoExpert] ([Id]),
    CONSTRAINT [FK_GeicoScheduleExpert_GeicoExpert2] FOREIGN KEY ([RespondSubstituteDoctorId]) REFERENCES [dbo].[GeicoExpert] ([Id]),
    CONSTRAINT [FK_GeicoScheduleExpert_GeicoRequestContext] FOREIGN KEY ([RequestContextId]) REFERENCES [dbo].[GeicoRequestContext] ([Id]),
    CONSTRAINT [FK_GeicoScheduleExpert_GeicoUser] FOREIGN KEY ([UserId]) REFERENCES [dbo].[GeicoUser] ([Id]),
    CONSTRAINT [FK_GeicoScheduleExpert_GeicoVenueCounty] FOREIGN KEY ([VenueCountyId]) REFERENCES [dbo].[GeicoVenueCounty] ([Id])
);

