CREATE TABLE [dbo].[SedgwickIMEReferralRecord] (
    [Id]                    INT           IDENTITY (1, 1) NOT NULL,
    [RecordType]            VARCHAR (8)   NOT NULL,
    [ClientNumber]          INT           NOT NULL,
    [ClaimNumber]           VARCHAR (32)  NOT NULL,
    [ShortVendorId]         VARCHAR (8)   NOT NULL,
    [CMSProcessingOffice]   INT           NOT NULL,
    [ClaimUniqueId]         VARCHAR (32)  NOT NULL,
    [ClaimSystemId]         VARCHAR (32)  NOT NULL,
    [ReferralUniqueId]      VARCHAR (32)  NOT NULL,
    [IMEPayCode]            TINYINT       NULL,
    [IMEQuestion1]          BIT           NULL,
    [IMEQuestion2]          BIT           NULL,
    [IMEQuestion3]          BIT           NULL,
    [IMEQuestion4]          BIT           NULL,
    [IMEQuestion5]          BIT           NULL,
    [IMEQuestion6]          BIT           NULL,
    [IMEQuestion7]          BIT           NULL,
    [IMEQuestion8]          BIT           NULL,
    [IMEQuestion9]          BIT           NULL,
    [IMEQuestion10]         BIT           NULL,
    [IMEQuestion11]         BIT           NULL,
    [IMEQuestion12]         BIT           NULL,
    [IMEQuestion13]         BIT           NULL,
    [IMEQuestion14]         BIT           NULL,
    [IMEQuestion15]         BIT           NULL,
    [IMEQuestion16]         BIT           NULL,
    [IMEQuestion17]         BIT           NULL,
    [IMEProviderSpeciality] VARCHAR (8)   NULL,
    [ReferralId]            INT           NOT NULL,
    [SubType]               VARCHAR (8)   NULL,
    [Addendum]              BIT           NULL,
    [AddendumText]          VARCHAR (300) NULL,
    [AddendumQuestion]      VARCHAR (300) NULL,
    [RecordsReviewOnly]     BIT           NULL,
    [Transportation]        BIT           NULL,
    [Translation]           BIT           NULL,
    [Language]              VARCHAR (20)  NULL,
    CONSTRAINT [PK_SedgwickIMEReferralRecord] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_SedgwickIMEReferralRecord_SedgwickReferralRecord] FOREIGN KEY ([ReferralId]) REFERENCES [dbo].[SedgwickReferralRecord] ([Id])
);



