CREATE VIEW vwDoctorExport
AS
    SELECT  vwDoctorExportColumns.LastName ,
            vwDoctorExportColumns.FirstName ,
            vwDoctorExportColumns.middleinitial ,
            vwDoctorExportColumns.degree ,
            vwDoctorExportColumns.Prefix ,
            vwDoctorExportColumns.Status ,
            vwDoctorExportColumns.Address1 ,
            vwDoctorExportColumns.Address2 ,
            vwDoctorExportColumns.City ,
            vwDoctorExportColumns.State ,
            vwDoctorExportColumns.Zip ,
            vwDoctorExportColumns.Phone ,
            vwDoctorExportColumns.Extension ,
            vwDoctorExportColumns.Fax ,
            vwDoctorExportColumns.Email ,
            vwDoctorExportColumns.OPType ,
            vwDoctorExportColumns.Specialty ,
            vwDoctorExportColumns.Office ,
            vwDoctorExportColumns.OfficeCode ,
            vwDoctorExportColumns.DoctorCode ,
            vwDoctorExportColumns.ProviderType ,
            vwDoctorExportColumns.USDvarchar1 ,
            vwDoctorExportColumns.USDvarchar2 ,
            vwDoctorExportColumns.USDDate1 ,
            vwDoctorExportColumns.USDDate2 ,
            vwDoctorExportColumns.USDint1 ,
            vwDoctorExportColumns.USDint2 ,
            vwDoctorExportColumns.USDmoney1 ,
            vwDoctorExportColumns.USDmoney2 ,
            vwDoctorExportColumns.USDDate3 ,
            vwDoctorExportColumns.USDDate4 ,
            vwDoctorExportColumns.USDvarchar3 ,
            vwDoctorExportColumns.USDDate5 ,
            vwDoctorExportColumns.USDDate6 ,
            vwDoctorExportColumns.USDDate7 ,
            vwDoctorExportColumns.licenseNbr ,
            vwDoctorExportColumns.WCNbr ,
            tblDoctor.notes ,
            tblDoctor.usdtext1 ,
            tblDoctor.usdtext2
    FROM    vwDoctorExportColumns
            INNER JOIN tblDoctor ON vwDoctorExportColumns.doctorcode = tblDoctor.doctorcode
