CREATE VIEW vwRegister
AS
    SELECT  tblAcctDetail.extendedamount ,
            tblproduct.INglacct ,
            tblproduct.VOglacct ,
            tblAcctDetail.longdesc ,
			vwAcctDocuments.HeaderID ,
            vwAcctDocuments.Casenbr ,
            vwAcctDocuments.documenttype ,
            vwAcctDocuments.documentnbr ,
            vwAcctDocuments.ExamineeName ,
            vwAcctDocuments.DoctorName ,
            vwAcctDocuments.ClientCode ,
            vwAcctDocuments.CompanyCode ,
            vwAcctDocuments.ClientName ,
            vwAcctDocuments.CompanyName ,
            vwAcctDocuments.InvClientCode ,
            vwAcctDocuments.InvCompanyCode ,
            vwAcctDocuments.InvClientName ,
            vwAcctDocuments.InvCompanyName ,
            vwAcctDocuments.priority ,
            vwAcctDocuments.DateAdded ,
            vwAcctDocuments.Claimnbr ,
            vwAcctDocuments.DoctorLocation ,
            vwAcctDocuments.ApptTime ,
            vwAcctDocuments.DateEdited ,
            vwAcctDocuments.useridEdited ,
            vwAcctDocuments.adjusteremail ,
            vwAcctDocuments.adjusterFax ,
            vwAcctDocuments.marketerCode ,
            vwAcctDocuments.useridAdded ,
            vwAcctDocuments.documentDate ,
            vwAcctDocuments.INBatchSelect ,
            vwAcctDocuments.VOBatchSelect ,
            vwAcctDocuments.taxCode ,
            vwAcctDocuments.taxtotal ,
            vwAcctDocuments.documenttotal ,
            vwAcctDocuments.documentstatus ,
            vwAcctDocuments.batchnbr ,
            vwAcctDocuments.serviceCode ,
            vwAcctDocuments.officeCode ,
            vwAcctDocuments.DoctorCode ,
            vwAcctDocuments.apptDate ,
            vwAcctDocuments.Casetype
    FROM    tblAcctDetail
            INNER JOIN tblproduct ON tblAcctDetail.prodcode = tblproduct.prodcode
            INNER JOIN vwAcctDocuments ON tblAcctDetail.HeaderID = vwAcctDocuments.HeaderID
